gx.evt.autoSkip=!1;
gx.define("a101_wp01_login",!1,function(){this.ServerClass="a101_wp01_login";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110c2_client");this.SetStandaloneVars=function(){this.AV8C_SYSDATE=gx.fn.getDateValue("vC_SYSDATE");this.A209TAT01_INFO=gx.fn.getControlValue("TAT01_INFO")};this.Validv_D_tam07_user_id=function(){try{var a=gx.util.balloon.getNew("vD_TAM07_USER_ID");this.AnyError=0}catch(b){}try{return a==
null?true:a.show()}catch(c){}return true};this.s122_client=function(){};this.s132_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.s162_client=function(){gx.fn.setCtrlProperty("vD_TAM07_USER_ID","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("vD_TAM07_PWD","Backcolor",gx.color.rgb(255,255,255))};this.e110c2_client=function(){this.executeServerEvent("'BTN_LOGIN'",true)};this.e150c2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e160c2_client=function(a){this.executeServerEvent("CANCEL",
true,a)};var c=this.GXValidFnc=[];this.GXCtrlIds=[2,5,9,19,22,24,27,29,32,43,46,48,49,56,59,60];this.GXLastCtrlId=60;var b=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",40,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"a101_wp01_login",[],true,1,true,true,0,false,false,false,"",600,"px","\u884c\u8ffd\u52a0",false,false,false,null,null,false,"",false,[1,1,1,1]);b.startRow("","","","","","");b.startCell("","","","","","","","","","");b.startTable("Table5",43,"0px");b.addHtmlCode("<tbody>");
b.startRow("","","","","","");b.startCell("","","top","","","36px","110px","","","");b.addSingleLineEdit(207,46,"TAT01_DATE_START","","","TAT01_DATE_START","date",10,"chr",10,10,"right",null,[],207,"TAT01_DATE_START",true,0,false,false,"ReadonlyAttributeInfo",1,"");b.endCell();b.startCell("","","top","","","","","","","");b.startDiv("Section1","0px","400px");b.addSingleLineEdit("D_grd_tat01_info",49,"vD_GRD_TAT01_INFO","","","D_GRD_TAT01_INFO","svchar",80,"chr",2E3,80,"left",null,[],"D_grd_tat01_info",
"D_GRD_TAT01_INFO",true,0,false,false,"ReadonlyAttribute",1,"");b.endDiv();b.endCell();b.endRow();b.startRow("","","","","","");b.startCell("","","","","","10px","","2","","");b.endCell();b.endRow();b.addHtmlCode("</tbody>");b.endTable();b.endCell();b.endRow();this.setGrid(b);c[2]={fld:"TABLE1",grid:0};c[5]={fld:"TABLE2",grid:0};c[9]={fld:"TABLE3",grid:0};c[19]={fld:"TABLE4",grid:0};c[22]={fld:"TEXTBLOCK2",format:0,grid:0};c[24]={lvl:0,type:"svchar",len:128,dec:0,sign:false,ro:0,grid:0,gxgrid:null,
fnc:this.Validv_D_tam07_user_id,isvalid:null,rgrid:[],fld:"vD_TAM07_USER_ID",gxz:"ZV12D_TAM07_USER_ID",gxold:"OV12D_TAM07_USER_ID",gxvar:"AV12D_TAM07_USER_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12D_TAM07_USER_ID=a},v2z:function(a){gx.O.ZV12D_TAM07_USER_ID=a},v2c:function(){gx.fn.setControlValue("vD_TAM07_USER_ID",gx.O.AV12D_TAM07_USER_ID,0)},c2v:function(){gx.O.AV12D_TAM07_USER_ID=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM07_USER_ID")},nac:gx.falseFn};
c[27]={fld:"TEXTBLOCK3",format:0,grid:0};c[29]={lvl:0,type:"svchar",len:128,dec:0,sign:false,isPwd:true,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM07_PWD",gxz:"ZV11D_TAM07_PWD",gxold:"OV11D_TAM07_PWD",gxvar:"AV11D_TAM07_PWD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11D_TAM07_PWD=a},v2z:function(a){gx.O.ZV11D_TAM07_PWD=a},v2c:function(){gx.fn.setControlValue("vD_TAM07_PWD",gx.O.AV11D_TAM07_PWD,0)},c2v:function(){gx.O.AV11D_TAM07_PWD=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM07_PWD")},
nac:gx.falseFn};c[32]={fld:"TEXTBLOCK1",format:0,grid:0};c[43]={fld:"TABLE5",grid:40};c[46]={lvl:2,type:"date",len:10,dec:0,sign:false,ro:1,isacc:0,grid:40,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAT01_DATE_START",gxz:"Z207TAT01_DATE_START",gxold:"O207TAT01_DATE_START",gxvar:"A207TAT01_DATE_START",dp:{f:0,st:false,wn:false,mf:false,pic:"99/99/9999",dec:0},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A207TAT01_DATE_START=gx.fn.toDatetimeValue(a)},
v2z:function(a){gx.O.Z207TAT01_DATE_START=gx.fn.toDatetimeValue(a)},v2c:function(a){gx.fn.setGridControlValue("TAT01_DATE_START",a||gx.fn.currentGridRowImpl(40),gx.O.A207TAT01_DATE_START,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A207TAT01_DATE_START=gx.fn.toDatetimeValue(this.val())},val:function(a){return gx.fn.getGridControlValue("TAT01_DATE_START",a||gx.fn.currentGridRowImpl(40))},nac:gx.falseFn};c[48]={fld:"SECTION1",grid:40};c[49]={lvl:2,type:"svchar",len:2E3,
dec:0,sign:false,ro:1,isacc:0,grid:40,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_TAT01_INFO",gxz:"ZV10D_GRD_TAT01_INFO",gxold:"OV10D_GRD_TAT01_INFO",gxvar:"AV10D_GRD_TAT01_INFO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV10D_GRD_TAT01_INFO=a},v2z:function(a){gx.O.ZV10D_GRD_TAT01_INFO=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_TAT01_INFO",a||gx.fn.currentGridRowImpl(40),gx.O.AV10D_GRD_TAT01_INFO,1)},c2v:function(){gx.O.AV10D_GRD_TAT01_INFO=
this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_TAT01_INFO",a||gx.fn.currentGridRowImpl(40))},nac:gx.falseFn};c[56]={fld:"TBL_HIDDEN",grid:0};c[59]={fld:"TXT_JS_EVENT",format:1,grid:0};c[60]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV13H_INIT_FLG",gxold:"OV13H_INIT_FLG",gxvar:"AV13H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_INIT_FLG=a},v2z:function(a){gx.O.ZV13H_INIT_FLG=
a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV13H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV13H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(60,function(){});this.OV11D_TAM07_PWD=this.ZV11D_TAM07_PWD=this.AV11D_TAM07_PWD=this.OV12D_TAM07_USER_ID=this.ZV12D_TAM07_USER_ID=this.AV12D_TAM07_USER_ID="";this.Z207TAT01_DATE_START=gx.date.nullDate();this.O207TAT01_DATE_START=
gx.date.nullDate();this.A880TAT01_INFO_KBN=this.A209TAT01_INFO=this.A304TAT01_DEL_FLG=this.AV13H_INIT_FLG=this.AV11D_TAM07_PWD=this.AV12D_TAM07_USER_ID=this.OV13H_INIT_FLG=this.ZV13H_INIT_FLG=this.AV13H_INIT_FLG=this.OV10D_GRD_TAT01_INFO=this.ZV10D_GRD_TAT01_INFO="";this.A208TAT01_DATE_END=gx.date.nullDate();this.A207TAT01_DATE_START=gx.date.nullDate();this.A210TAM07_PWD=this.A214TAM07_DEL_FLG=this.A56TAM07_AUTH_CD=this.A313TAM07_USER_KANA_NM=this.A205TAM07_USER_NM=this.A55TAM07_USER_ID=this.AV10D_GRD_TAT01_INFO=
"";this.AV8C_SYSDATE=gx.date.nullDate();this.Events={e110c2_client:["'BTN_LOGIN'",true],e150c2_client:["ENTER",true],e160c2_client:["CANCEL",true]};this.setVCMap("AV8C_SYSDATE","vC_SYSDATE",0,"date");this.setVCMap("A209TAT01_INFO","TAT01_INFO",0,"svchar");this.setVCMap("AV8C_SYSDATE","vC_SYSDATE",0,"date");this.setVCMap("A209TAT01_INFO","TAT01_INFO",0,"svchar");b.addRefreshingVar({rfrVar:"AV8C_SYSDATE"});b.addRefreshingVar(this.GXValidFnc[60]);b.addRefreshingVar(this.GXValidFnc[24]);b.addRefreshingVar({rfrVar:"A209TAT01_INFO"});
this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0012",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0054",lvl:1})});gx.setParentObj(new a101_wp01_login);
