gx.evt.autoSkip=!1;
gx.define("a103_wp01_system_menu",!1,function(){this.ServerClass="a103_wp01_system_menu";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110f2_client");this.SetStandaloneVars=function(){this.AV42Pgmname=gx.fn.getControlValue("vPGMNAME");this.A1TAM01_SYS_ID=gx.fn.getControlValue("TAM01_SYS_ID");this.A2TAM02_MENU_ID_TREE_1=gx.fn.getControlValue("TAM02_MENU_ID_TREE_1");this.A3TAM02_MENU_ID_TREE_2=gx.fn.getControlValue("TAM02_MENU_ID_TREE_2");
this.A4TAM02_MENU_ID_TREE_3=gx.fn.getControlValue("TAM02_MENU_ID_TREE_3");this.A211TAM02_MENU_NM=gx.fn.getControlValue("TAM02_MENU_NM");this.A276TAM03_KIDO_PG=gx.fn.getControlValue("TAM03_KIDO_PG");this.A5TAM02_APP_ID=gx.fn.getControlValue("TAM02_APP_ID");this.AV32P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",")};this.Validv_H_tam01_sys_id=function(){try{var a=gx.util.balloon.getNew("vH_TAM01_SYS_ID");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Validv_H_01_tam02_menu_id_tree_1=
function(){try{var a=gx.util.balloon.getNew("vH_01_TAM02_MENU_ID_TREE_1");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Validv_H_02_tam02_menu_id_tree_1=function(){try{var a=gx.util.balloon.getNew("vH_02_TAM02_MENU_ID_TREE_1");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Validv_H_02_tam02_menu_id_tree_2=function(){try{var a=gx.util.balloon.getNew("vH_02_TAM02_MENU_ID_TREE_2");this.AnyError=0}catch(b){}try{return a==
null?true:a.show()}catch(c){}return true};this.s122_client=function(){};this.s142_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.e110f2_client=function(){this.executeServerEvent("'BTN_PASS_CHG'",true)};this.e150f2_client=function(a){this.executeServerEvent("VD_GRD1_TAM02_MENU_NM.CLICK",true,a)};this.e200f2_client=function(a){this.executeServerEvent("VD_GRD2_TAM02_MENU_NM.CLICK",true,a)};this.e180f2_client=function(a){this.executeServerEvent("VD_GRD3_TAM02_MENU_NM.CLICK",true,a)};this.e210f2_client=function(a){this.executeServerEvent("ENTER",
true,a)};this.e220f2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,18,21,24,27,30,33,39,40,41,44,47,50,53,59,60,61,64,67,70,73,79,80,81,82,86,89,92,95,101,103,106,107,108,109,110,111,112];this.GXLastCtrlId=112;var f=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",36,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"a103_wp01_system_menu",[],true,1,true,true,0,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",
false,false,false,null,null,false,"",false,[1,1,1,1]);f.startRow("","","","","","");f.startCell("","","","","","","180px","","","");f.addSingleLineEdit("H_grd1_tam01_sys_id",39,"vH_GRD1_TAM01_SYS_ID","","","H_GRD1_TAM01_SYS_ID","svchar",2,"chr",2,2,"left",null,[],"H_grd1_tam01_sys_id","H_GRD1_TAM01_SYS_ID",true,0,false,false,"Attribute",1,"");f.addSingleLineEdit("D_grd1_link_tam02_menu_nm",40,"vD_GRD1_LINK_TAM02_MENU_NM","","","D_GRD1_LINK_TAM02_MENU_NM","svchar",50,"chr",50,50,"left",null,[],"D_grd1_link_tam02_menu_nm",
"D_GRD1_LINK_TAM02_MENU_NM",true,0,false,false,"",1,"");f.addSingleLineEdit("D_grd1_tam02_menu_nm",41,"vD_GRD1_TAM02_MENU_NM","","","D_GRD1_TAM02_MENU_NM","svchar",50,"chr",50,50,"left","e150f2_client",[],"D_grd1_tam02_menu_nm","D_GRD1_TAM02_MENU_NM",true,0,false,false,"",1,"");f.endCell();f.endRow();this.setGrid(f);var d=this.Grid2Container=new gx.grid.grid(this,4,"WbpLvl4",56,"Grid2","Grid2","Grid2Container",this.CmpContext,this.IsMasterPage,"a103_wp01_system_menu",[],true,1,true,true,0,false,false,
false,"",0,"px","\u884c\u8ffd\u52a0",false,false,false,null,null,false,"",false,[1,1,1,1]);d.startRow("","","","","","");d.startCell("","","","","","","300px","","","");d.addSingleLineEdit("D_grd2_tam02_menu_nm",59,"vD_GRD2_TAM02_MENU_NM","","","D_GRD2_TAM02_MENU_NM","svchar",40,"chr",50,50,"left","e200f2_client",[],"D_grd2_tam02_menu_nm","D_GRD2_TAM02_MENU_NM",true,0,false,false,"",1,"");d.addSingleLineEdit("D_grd2_link_tam02_menu_nm",60,"vD_GRD2_LINK_TAM02_MENU_NM","","","D_GRD2_LINK_TAM02_MENU_NM",
"svchar",40,"chr",50,50,"left",null,[],"D_grd2_link_tam02_menu_nm","D_GRD2_LINK_TAM02_MENU_NM",true,0,false,false,"",1,"");d.addSingleLineEdit("H_grd2_tam02_menu_id_tree_1",61,"vH_GRD2_TAM02_MENU_ID_TREE_1","","","H_GRD2_TAM02_MENU_ID_TREE_1","svchar",2,"chr",2,2,"left",null,[],"H_grd2_tam02_menu_id_tree_1","H_GRD2_TAM02_MENU_ID_TREE_1",true,0,false,false,"Attribute",1,"");d.endCell();d.endRow();this.setGrid(d);var c=this.Grid3Container=new gx.grid.grid(this,7,"WbpLvl7",76,"Grid3","Grid3","Grid3Container",
this.CmpContext,this.IsMasterPage,"a103_wp01_system_menu",[],true,1,true,true,0,false,false,false,"",100,"%","\u884c\u8ffd\u52a0",false,false,false,null,null,false,"",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","","","","","","300px","","","");c.addSingleLineEdit("D_grd3_tam02_menu_nm",79,"vD_GRD3_TAM02_MENU_NM","","","D_GRD3_TAM02_MENU_NM","svchar",40,"chr",50,50,"left","e180f2_client",[],"D_grd3_tam02_menu_nm","D_GRD3_TAM02_MENU_NM",true,0,false,false,"",1,"");c.addSingleLineEdit("D_grd3_link_tam02_menu_nm",
80,"vD_GRD3_LINK_TAM02_MENU_NM","","","D_GRD3_LINK_TAM02_MENU_NM","svchar",40,"chr",50,50,"left",null,[],"D_grd3_link_tam02_menu_nm","D_GRD3_LINK_TAM02_MENU_NM",true,0,false,false,"",1,"");c.addSingleLineEdit("H_grd3_tam02_menu_id_tree_1",81,"vH_GRD3_TAM02_MENU_ID_TREE_1","","","H_GRD3_TAM02_MENU_ID_TREE_1","svchar",2,"chr",2,2,"left",null,[],"H_grd3_tam02_menu_id_tree_1","H_GRD3_TAM02_MENU_ID_TREE_1",true,0,false,false,"Attribute",1,"");c.addSingleLineEdit("H_grd3_tam02_menu_id_tree_2",82,"vH_GRD3_TAM02_MENU_ID_TREE_2",
"","","H_GRD3_TAM02_MENU_ID_TREE_2","svchar",2,"chr",2,2,"left",null,[],"H_grd3_tam02_menu_id_tree_2","H_GRD3_TAM02_MENU_ID_TREE_2",true,0,false,false,"Attribute",1,"");c.endCell();c.endRow();this.setGrid(c);var e=this.Grid4Container=new gx.grid.grid(this,10,"WbpLvl10",98,"Grid4","Grid4","Grid4Container",this.CmpContext,this.IsMasterPage,"a103_wp01_system_menu",[],true,1,true,true,0,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",false,false,false,null,null,false,"",false,[1,1,1,1]);e.startRow("",
"","","","","");e.startCell("","","","","","","300px","","","");e.addSingleLineEdit("D_grd4_tam02_menu_nm",101,"vD_GRD4_TAM02_MENU_NM","","","D_GRD4_TAM02_MENU_NM","svchar",40,"chr",50,50,"left",null,[],"D_grd4_tam02_menu_nm","D_GRD4_TAM02_MENU_NM",true,0,false,false,"ReadonlyAttributeMenuList",1,"");e.endCell();e.endRow();this.setGrid(e);b[2]={fld:"TABLE2",grid:0};b[6]={fld:"TABLE3",grid:0};b[12]={fld:"TABLE10",grid:0};b[15]={fld:"TXT_BTN_PASS_CHG",format:0,grid:0};b[18]={fld:"TABLE5",grid:0};b[21]=
{fld:"TABLE4",grid:0};b[24]={fld:"TABLE12",grid:0};b[27]={fld:"TABLE7",grid:0};b[30]={fld:"TEXTBLOCK1",format:0,grid:0};b[33]={fld:"TABLE1",grid:0};b[39]={lvl:2,type:"svchar",len:2,dec:0,sign:false,ro:0,isacc:0,grid:36,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vH_GRD1_TAM01_SYS_ID",gxz:"ZV22H_GRD1_TAM01_SYS_ID",gxold:"OV22H_GRD1_TAM01_SYS_ID",gxvar:"AV22H_GRD1_TAM01_SYS_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV22H_GRD1_TAM01_SYS_ID=
a},v2z:function(a){gx.O.ZV22H_GRD1_TAM01_SYS_ID=a},v2c:function(a){gx.fn.setGridControlValue("vH_GRD1_TAM01_SYS_ID",a||gx.fn.currentGridRowImpl(36),gx.O.AV22H_GRD1_TAM01_SYS_ID,0)},c2v:function(){gx.O.AV22H_GRD1_TAM01_SYS_ID=this.val()},val:function(a){return gx.fn.getGridControlValue("vH_GRD1_TAM01_SYS_ID",a||gx.fn.currentGridRowImpl(36))},nac:gx.falseFn};b[40]={lvl:2,type:"svchar",len:50,dec:0,sign:false,ro:0,isacc:0,grid:36,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD1_LINK_TAM02_MENU_NM",
gxz:"ZV8D_GRD1_LINK_TAM02_MENU_NM",gxold:"OV8D_GRD1_LINK_TAM02_MENU_NM",gxvar:"AV8D_GRD1_LINK_TAM02_MENU_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV8D_GRD1_LINK_TAM02_MENU_NM=a},v2z:function(a){gx.O.ZV8D_GRD1_LINK_TAM02_MENU_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD1_LINK_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(36),gx.O.AV8D_GRD1_LINK_TAM02_MENU_NM,0)},c2v:function(){gx.O.AV8D_GRD1_LINK_TAM02_MENU_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD1_LINK_TAM02_MENU_NM",
a||gx.fn.currentGridRowImpl(36))},nac:gx.falseFn};b[41]={lvl:2,type:"svchar",len:50,dec:0,sign:false,ro:0,isacc:0,grid:36,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD1_TAM02_MENU_NM",gxz:"ZV9D_GRD1_TAM02_MENU_NM",gxold:"OV9D_GRD1_TAM02_MENU_NM",gxvar:"AV9D_GRD1_TAM02_MENU_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV9D_GRD1_TAM02_MENU_NM=a},v2z:function(a){gx.O.ZV9D_GRD1_TAM02_MENU_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD1_TAM02_MENU_NM",
a||gx.fn.currentGridRowImpl(36),gx.O.AV9D_GRD1_TAM02_MENU_NM,0)},c2v:function(){gx.O.AV9D_GRD1_TAM02_MENU_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD1_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(36))},nac:gx.falseFn};b[44]={fld:"TBL1",grid:0};b[47]={fld:"TABLE16",grid:0};b[50]={fld:"TXT_TITLE1",format:0,grid:0};b[53]={fld:"TABLE6",grid:0};b[59]={lvl:4,type:"svchar",len:50,dec:0,sign:false,ro:0,isacc:0,grid:56,gxgrid:this.Grid2Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD2_TAM02_MENU_NM",
gxz:"ZV11D_GRD2_TAM02_MENU_NM",gxold:"OV11D_GRD2_TAM02_MENU_NM",gxvar:"AV11D_GRD2_TAM02_MENU_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV11D_GRD2_TAM02_MENU_NM=a},v2z:function(a){gx.O.ZV11D_GRD2_TAM02_MENU_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD2_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(56),gx.O.AV11D_GRD2_TAM02_MENU_NM,0)},c2v:function(){gx.O.AV11D_GRD2_TAM02_MENU_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD2_TAM02_MENU_NM",
a||gx.fn.currentGridRowImpl(56))},nac:gx.falseFn};b[60]={lvl:4,type:"svchar",len:50,dec:0,sign:false,ro:0,isacc:0,grid:56,gxgrid:this.Grid2Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD2_LINK_TAM02_MENU_NM",gxz:"ZV10D_GRD2_LINK_TAM02_MENU_NM",gxold:"OV10D_GRD2_LINK_TAM02_MENU_NM",gxvar:"AV10D_GRD2_LINK_TAM02_MENU_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV10D_GRD2_LINK_TAM02_MENU_NM=a},v2z:function(a){gx.O.ZV10D_GRD2_LINK_TAM02_MENU_NM=
a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD2_LINK_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(56),gx.O.AV10D_GRD2_LINK_TAM02_MENU_NM,0)},c2v:function(){gx.O.AV10D_GRD2_LINK_TAM02_MENU_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD2_LINK_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(56))},nac:gx.falseFn};b[61]={lvl:4,type:"svchar",len:2,dec:0,sign:false,ro:0,isacc:0,grid:56,gxgrid:this.Grid2Container,fnc:null,isvalid:null,rgrid:[],fld:"vH_GRD2_TAM02_MENU_ID_TREE_1",gxz:"ZV23H_GRD2_TAM02_MENU_ID_TREE_1",
gxold:"OV23H_GRD2_TAM02_MENU_ID_TREE_1",gxvar:"AV23H_GRD2_TAM02_MENU_ID_TREE_1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV23H_GRD2_TAM02_MENU_ID_TREE_1=a},v2z:function(a){gx.O.ZV23H_GRD2_TAM02_MENU_ID_TREE_1=a},v2c:function(a){gx.fn.setGridControlValue("vH_GRD2_TAM02_MENU_ID_TREE_1",a||gx.fn.currentGridRowImpl(56),gx.O.AV23H_GRD2_TAM02_MENU_ID_TREE_1,0)},c2v:function(){gx.O.AV23H_GRD2_TAM02_MENU_ID_TREE_1=this.val()},val:function(a){return gx.fn.getGridControlValue("vH_GRD2_TAM02_MENU_ID_TREE_1",
a||gx.fn.currentGridRowImpl(56))},nac:gx.falseFn};b[64]={fld:"TBL2",grid:0};b[67]={fld:"TABLE19",grid:0};b[70]={fld:"TXT_TITLE2",format:0,grid:0};b[73]={fld:"TABLE8",grid:0};b[79]={lvl:7,type:"svchar",len:50,dec:0,sign:false,ro:0,isacc:0,grid:76,gxgrid:this.Grid3Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD3_TAM02_MENU_NM",gxz:"ZV13D_GRD3_TAM02_MENU_NM",gxold:"OV13D_GRD3_TAM02_MENU_NM",gxvar:"AV13D_GRD3_TAM02_MENU_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",
v2v:function(a){gx.O.AV13D_GRD3_TAM02_MENU_NM=a},v2z:function(a){gx.O.ZV13D_GRD3_TAM02_MENU_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD3_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(76),gx.O.AV13D_GRD3_TAM02_MENU_NM,0)},c2v:function(){gx.O.AV13D_GRD3_TAM02_MENU_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD3_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(76))},nac:gx.falseFn};b[80]={lvl:7,type:"svchar",len:50,dec:0,sign:false,ro:0,isacc:0,grid:76,gxgrid:this.Grid3Container,
fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD3_LINK_TAM02_MENU_NM",gxz:"ZV12D_GRD3_LINK_TAM02_MENU_NM",gxold:"OV12D_GRD3_LINK_TAM02_MENU_NM",gxvar:"AV12D_GRD3_LINK_TAM02_MENU_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV12D_GRD3_LINK_TAM02_MENU_NM=a},v2z:function(a){gx.O.ZV12D_GRD3_LINK_TAM02_MENU_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD3_LINK_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(76),gx.O.AV12D_GRD3_LINK_TAM02_MENU_NM,0)},
c2v:function(){gx.O.AV12D_GRD3_LINK_TAM02_MENU_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD3_LINK_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(76))},nac:gx.falseFn};b[81]={lvl:7,type:"svchar",len:2,dec:0,sign:false,ro:0,isacc:0,grid:76,gxgrid:this.Grid3Container,fnc:null,isvalid:null,rgrid:[],fld:"vH_GRD3_TAM02_MENU_ID_TREE_1",gxz:"ZV26H_GRD3_TAM02_MENU_ID_TREE_1",gxold:"OV26H_GRD3_TAM02_MENU_ID_TREE_1",gxvar:"AV26H_GRD3_TAM02_MENU_ID_TREE_1",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV26H_GRD3_TAM02_MENU_ID_TREE_1=a},v2z:function(a){gx.O.ZV26H_GRD3_TAM02_MENU_ID_TREE_1=a},v2c:function(a){gx.fn.setGridControlValue("vH_GRD3_TAM02_MENU_ID_TREE_1",a||gx.fn.currentGridRowImpl(76),gx.O.AV26H_GRD3_TAM02_MENU_ID_TREE_1,0)},c2v:function(){gx.O.AV26H_GRD3_TAM02_MENU_ID_TREE_1=this.val()},val:function(a){return gx.fn.getGridControlValue("vH_GRD3_TAM02_MENU_ID_TREE_1",a||gx.fn.currentGridRowImpl(76))},nac:gx.falseFn};
b[82]={lvl:7,type:"svchar",len:2,dec:0,sign:false,ro:0,isacc:0,grid:76,gxgrid:this.Grid3Container,fnc:null,isvalid:null,rgrid:[],fld:"vH_GRD3_TAM02_MENU_ID_TREE_2",gxz:"ZV27H_GRD3_TAM02_MENU_ID_TREE_2",gxold:"OV27H_GRD3_TAM02_MENU_ID_TREE_2",gxvar:"AV27H_GRD3_TAM02_MENU_ID_TREE_2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV27H_GRD3_TAM02_MENU_ID_TREE_2=a},v2z:function(a){gx.O.ZV27H_GRD3_TAM02_MENU_ID_TREE_2=a},v2c:function(a){gx.fn.setGridControlValue("vH_GRD3_TAM02_MENU_ID_TREE_2",
a||gx.fn.currentGridRowImpl(76),gx.O.AV27H_GRD3_TAM02_MENU_ID_TREE_2,0)},c2v:function(){gx.O.AV27H_GRD3_TAM02_MENU_ID_TREE_2=this.val()},val:function(a){return gx.fn.getGridControlValue("vH_GRD3_TAM02_MENU_ID_TREE_2",a||gx.fn.currentGridRowImpl(76))},nac:gx.falseFn};b[86]={fld:"TBL3",grid:0};b[89]={fld:"TABLE22",grid:0};b[92]={fld:"TXT_TITLE3",format:0,grid:0};b[95]={fld:"TABLE9",grid:0};b[101]={lvl:10,type:"svchar",len:50,dec:0,sign:false,ro:1,isacc:0,grid:98,gxgrid:this.Grid4Container,fnc:null,
isvalid:null,rgrid:[],fld:"vD_GRD4_TAM02_MENU_NM",gxz:"ZV14D_GRD4_TAM02_MENU_NM",gxold:"OV14D_GRD4_TAM02_MENU_NM",gxvar:"AV14D_GRD4_TAM02_MENU_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV14D_GRD4_TAM02_MENU_NM=a},v2z:function(a){gx.O.ZV14D_GRD4_TAM02_MENU_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD4_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(98),gx.O.AV14D_GRD4_TAM02_MENU_NM,0)},c2v:function(){gx.O.AV14D_GRD4_TAM02_MENU_NM=this.val()},
val:function(a){return gx.fn.getGridControlValue("vD_GRD4_TAM02_MENU_NM",a||gx.fn.currentGridRowImpl(98))},nac:gx.falseFn};b[103]={fld:"TBL_HIDDEN",grid:0};b[106]={fld:"TXT_JS_EVENT",format:1,grid:0};b[107]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV29H_INIT_FLG",gxold:"OV29H_INIT_FLG",gxvar:"AV29H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV29H_INIT_FLG=a},v2z:function(a){gx.O.ZV29H_INIT_FLG=
a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV29H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV29H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(107,function(){});b[108]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_H_tam01_sys_id,isvalid:null,rgrid:[],fld:"vH_TAM01_SYS_ID",gxz:"ZV31H_TAM01_SYS_ID",gxold:"OV31H_TAM01_SYS_ID",
gxvar:"AV31H_TAM01_SYS_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV31H_TAM01_SYS_ID=a},v2z:function(a){gx.O.ZV31H_TAM01_SYS_ID=a},v2c:function(){gx.fn.setControlValue("vH_TAM01_SYS_ID",gx.O.AV31H_TAM01_SYS_ID,0)},c2v:function(){gx.O.AV31H_TAM01_SYS_ID=this.val()},val:function(){return gx.fn.getControlValue("vH_TAM01_SYS_ID")},nac:gx.falseFn};b[109]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_H_01_tam02_menu_id_tree_1,isvalid:null,
rgrid:[],fld:"vH_01_TAM02_MENU_ID_TREE_1",gxz:"ZV16H_01_TAM02_MENU_ID_TREE_1",gxold:"OV16H_01_TAM02_MENU_ID_TREE_1",gxvar:"AV16H_01_TAM02_MENU_ID_TREE_1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV16H_01_TAM02_MENU_ID_TREE_1=a},v2z:function(a){gx.O.ZV16H_01_TAM02_MENU_ID_TREE_1=a},v2c:function(){gx.fn.setControlValue("vH_01_TAM02_MENU_ID_TREE_1",gx.O.AV16H_01_TAM02_MENU_ID_TREE_1,0)},c2v:function(){gx.O.AV16H_01_TAM02_MENU_ID_TREE_1=this.val()},val:function(){return gx.fn.getControlValue("vH_01_TAM02_MENU_ID_TREE_1")},
nac:gx.falseFn};b[110]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_H_02_tam02_menu_id_tree_1,isvalid:null,rgrid:[],fld:"vH_02_TAM02_MENU_ID_TREE_1",gxz:"ZV19H_02_TAM02_MENU_ID_TREE_1",gxold:"OV19H_02_TAM02_MENU_ID_TREE_1",gxvar:"AV19H_02_TAM02_MENU_ID_TREE_1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV19H_02_TAM02_MENU_ID_TREE_1=a},v2z:function(a){gx.O.ZV19H_02_TAM02_MENU_ID_TREE_1=a},v2c:function(){gx.fn.setControlValue("vH_02_TAM02_MENU_ID_TREE_1",
gx.O.AV19H_02_TAM02_MENU_ID_TREE_1,0)},c2v:function(){gx.O.AV19H_02_TAM02_MENU_ID_TREE_1=this.val()},val:function(){return gx.fn.getControlValue("vH_02_TAM02_MENU_ID_TREE_1")},nac:gx.falseFn};b[111]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_H_02_tam02_menu_id_tree_2,isvalid:null,rgrid:[],fld:"vH_02_TAM02_MENU_ID_TREE_2",gxz:"ZV20H_02_TAM02_MENU_ID_TREE_2",gxold:"OV20H_02_TAM02_MENU_ID_TREE_2",gxvar:"AV20H_02_TAM02_MENU_ID_TREE_2",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",v2v:function(a){gx.O.AV20H_02_TAM02_MENU_ID_TREE_2=a},v2z:function(a){gx.O.ZV20H_02_TAM02_MENU_ID_TREE_2=a},v2c:function(){gx.fn.setControlValue("vH_02_TAM02_MENU_ID_TREE_2",gx.O.AV20H_02_TAM02_MENU_ID_TREE_2,0)},c2v:function(){gx.O.AV20H_02_TAM02_MENU_ID_TREE_2=this.val()},val:function(){return gx.fn.getControlValue("vH_02_TAM02_MENU_ID_TREE_2")},nac:gx.falseFn};b[112]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_NONE",
gxz:"ZV15D_NONE",gxold:"OV15D_NONE",gxvar:"AV15D_NONE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15D_NONE=a},v2z:function(a){gx.O.ZV15D_NONE=a},v2c:function(){gx.fn.setControlValue("vD_NONE",gx.O.AV15D_NONE,0)},c2v:function(){gx.O.AV15D_NONE=this.val()},val:function(){return gx.fn.getControlValue("vD_NONE")},nac:gx.falseFn};this.AV15D_NONE=this.AV20H_02_TAM02_MENU_ID_TREE_2=this.AV19H_02_TAM02_MENU_ID_TREE_1=this.AV16H_01_TAM02_MENU_ID_TREE_1=this.AV31H_TAM01_SYS_ID=this.AV29H_INIT_FLG=
this.OV15D_NONE=this.ZV15D_NONE=this.AV15D_NONE=this.OV20H_02_TAM02_MENU_ID_TREE_2=this.ZV20H_02_TAM02_MENU_ID_TREE_2=this.AV20H_02_TAM02_MENU_ID_TREE_2=this.OV19H_02_TAM02_MENU_ID_TREE_1=this.ZV19H_02_TAM02_MENU_ID_TREE_1=this.AV19H_02_TAM02_MENU_ID_TREE_1=this.OV16H_01_TAM02_MENU_ID_TREE_1=this.ZV16H_01_TAM02_MENU_ID_TREE_1=this.AV16H_01_TAM02_MENU_ID_TREE_1=this.OV31H_TAM01_SYS_ID=this.ZV31H_TAM01_SYS_ID=this.AV31H_TAM01_SYS_ID=this.OV29H_INIT_FLG=this.ZV29H_INIT_FLG=this.AV29H_INIT_FLG=this.OV14D_GRD4_TAM02_MENU_NM=
this.ZV14D_GRD4_TAM02_MENU_NM=this.OV27H_GRD3_TAM02_MENU_ID_TREE_2=this.ZV27H_GRD3_TAM02_MENU_ID_TREE_2=this.OV26H_GRD3_TAM02_MENU_ID_TREE_1=this.ZV26H_GRD3_TAM02_MENU_ID_TREE_1=this.OV12D_GRD3_LINK_TAM02_MENU_NM=this.ZV12D_GRD3_LINK_TAM02_MENU_NM=this.OV13D_GRD3_TAM02_MENU_NM=this.ZV13D_GRD3_TAM02_MENU_NM=this.OV23H_GRD2_TAM02_MENU_ID_TREE_1=this.ZV23H_GRD2_TAM02_MENU_ID_TREE_1=this.OV10D_GRD2_LINK_TAM02_MENU_NM=this.ZV10D_GRD2_LINK_TAM02_MENU_NM=this.OV11D_GRD2_TAM02_MENU_NM=this.ZV11D_GRD2_TAM02_MENU_NM=
this.OV9D_GRD1_TAM02_MENU_NM=this.ZV9D_GRD1_TAM02_MENU_NM=this.OV8D_GRD1_LINK_TAM02_MENU_NM=this.ZV8D_GRD1_LINK_TAM02_MENU_NM=this.OV22H_GRD1_TAM01_SYS_ID=this.ZV22H_GRD1_TAM01_SYS_ID="";this.AV32P_MOVE_KBN=0;this.AV42Pgmname=this.A13TAM04_AUTH_CD=this.A288TAM05_KNGN_FLG=this.A215TAM04_DEL_FLG=this.A12TAM03_APP_ID=this.A212TAM02_DEL_FLG=this.A276TAM03_KIDO_PG=this.A5TAM02_APP_ID=this.AV14D_GRD4_TAM02_MENU_NM=this.AV27H_GRD3_TAM02_MENU_ID_TREE_2=this.AV26H_GRD3_TAM02_MENU_ID_TREE_1=this.AV12D_GRD3_LINK_TAM02_MENU_NM=
this.AV13D_GRD3_TAM02_MENU_NM=this.AV23H_GRD2_TAM02_MENU_ID_TREE_1=this.AV10D_GRD2_LINK_TAM02_MENU_NM=this.AV11D_GRD2_TAM02_MENU_NM=this.A211TAM02_MENU_NM=this.A1TAM01_SYS_ID=this.A2TAM02_MENU_ID_TREE_1=this.A3TAM02_MENU_ID_TREE_2=this.A4TAM02_MENU_ID_TREE_3=this.AV9D_GRD1_TAM02_MENU_NM=this.AV8D_GRD1_LINK_TAM02_MENU_NM=this.AV22H_GRD1_TAM01_SYS_ID="";this.Events={e110f2_client:["'BTN_PASS_CHG'",true],e150f2_client:["VD_GRD1_TAM02_MENU_NM.CLICK",true],e200f2_client:["VD_GRD2_TAM02_MENU_NM.CLICK",
true],e180f2_client:["VD_GRD3_TAM02_MENU_NM.CLICK",true],e210f2_client:["ENTER",true],e220f2_client:["CANCEL",true]};this.setVCMap("AV42Pgmname","vPGMNAME",0,"char");this.setVCMap("A1TAM01_SYS_ID","TAM01_SYS_ID",0,"svchar");this.setVCMap("A2TAM02_MENU_ID_TREE_1","TAM02_MENU_ID_TREE_1",0,"svchar");this.setVCMap("A3TAM02_MENU_ID_TREE_2","TAM02_MENU_ID_TREE_2",0,"svchar");this.setVCMap("A4TAM02_MENU_ID_TREE_3","TAM02_MENU_ID_TREE_3",0,"svchar");this.setVCMap("A211TAM02_MENU_NM","TAM02_MENU_NM",0,"svchar");
this.setVCMap("A276TAM03_KIDO_PG","TAM03_KIDO_PG",0,"svchar");this.setVCMap("A5TAM02_APP_ID","TAM02_APP_ID",0,"svchar");this.setVCMap("AV32P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV42Pgmname","vPGMNAME",0,"char");this.setVCMap("A1TAM01_SYS_ID","TAM01_SYS_ID",0,"svchar");this.setVCMap("A2TAM02_MENU_ID_TREE_1","TAM02_MENU_ID_TREE_1",0,"svchar");this.setVCMap("A3TAM02_MENU_ID_TREE_2","TAM02_MENU_ID_TREE_2",0,"svchar");this.setVCMap("A4TAM02_MENU_ID_TREE_3","TAM02_MENU_ID_TREE_3",0,"svchar");
this.setVCMap("A211TAM02_MENU_NM","TAM02_MENU_NM",0,"svchar");this.setVCMap("A276TAM03_KIDO_PG","TAM03_KIDO_PG",0,"svchar");this.setVCMap("A5TAM02_APP_ID","TAM02_APP_ID",0,"svchar");f.addRefreshingVar(this.GXValidFnc[107]);f.addRefreshingVar({rfrVar:"AV42Pgmname"});f.addRefreshingVar({rfrVar:"A1TAM01_SYS_ID"});f.addRefreshingVar({rfrVar:"A2TAM02_MENU_ID_TREE_1"});f.addRefreshingVar({rfrVar:"A3TAM02_MENU_ID_TREE_2"});f.addRefreshingVar({rfrVar:"A4TAM02_MENU_ID_TREE_3"});f.addRefreshingVar({rfrVar:"A211TAM02_MENU_NM"});
f.addRefreshingVar(this.GXValidFnc[108]);f.addRefreshingVar(this.GXValidFnc[109]);f.addRefreshingVar(this.GXValidFnc[110]);f.addRefreshingVar(this.GXValidFnc[111]);f.addRefreshingVar({rfrVar:"A276TAM03_KIDO_PG"});f.addRefreshingVar({rfrVar:"A5TAM02_APP_ID"});d.addRefreshingVar(this.GXValidFnc[107]);d.addRefreshingVar({rfrVar:"AV42Pgmname"});d.addRefreshingVar({rfrVar:"A1TAM01_SYS_ID"});d.addRefreshingVar({rfrVar:"A2TAM02_MENU_ID_TREE_1"});d.addRefreshingVar({rfrVar:"A3TAM02_MENU_ID_TREE_2"});d.addRefreshingVar({rfrVar:"A4TAM02_MENU_ID_TREE_3"});
d.addRefreshingVar({rfrVar:"A211TAM02_MENU_NM"});d.addRefreshingVar(this.GXValidFnc[108]);d.addRefreshingVar(this.GXValidFnc[109]);d.addRefreshingVar(this.GXValidFnc[110]);d.addRefreshingVar(this.GXValidFnc[111]);d.addRefreshingVar({rfrVar:"A212TAM02_DEL_FLG"});d.addRefreshingVar({rfrVar:"A13TAM04_AUTH_CD"});d.addRefreshingVar({rfrVar:"AV33W_A_LOGIN_SDT"});d.addRefreshingVar({rfrVar:"A12TAM03_APP_ID"});d.addRefreshingVar({rfrVar:"A5TAM02_APP_ID"});d.addRefreshingVar({rfrVar:"A215TAM04_DEL_FLG"});
d.addRefreshingVar({rfrVar:"A276TAM03_KIDO_PG"});c.addRefreshingVar(this.GXValidFnc[107]);c.addRefreshingVar({rfrVar:"AV42Pgmname"});c.addRefreshingVar({rfrVar:"A1TAM01_SYS_ID"});c.addRefreshingVar({rfrVar:"A2TAM02_MENU_ID_TREE_1"});c.addRefreshingVar({rfrVar:"A3TAM02_MENU_ID_TREE_2"});c.addRefreshingVar({rfrVar:"A4TAM02_MENU_ID_TREE_3"});c.addRefreshingVar({rfrVar:"A211TAM02_MENU_NM"});c.addRefreshingVar(this.GXValidFnc[108]);c.addRefreshingVar(this.GXValidFnc[109]);c.addRefreshingVar(this.GXValidFnc[110]);
c.addRefreshingVar(this.GXValidFnc[111]);c.addRefreshingVar({rfrVar:"A212TAM02_DEL_FLG"});c.addRefreshingVar({rfrVar:"A13TAM04_AUTH_CD"});c.addRefreshingVar({rfrVar:"AV33W_A_LOGIN_SDT"});c.addRefreshingVar({rfrVar:"A12TAM03_APP_ID"});c.addRefreshingVar({rfrVar:"A5TAM02_APP_ID"});c.addRefreshingVar({rfrVar:"A215TAM04_DEL_FLG"});c.addRefreshingVar({rfrVar:"A276TAM03_KIDO_PG"});e.addRefreshingVar(this.GXValidFnc[107]);e.addRefreshingVar({rfrVar:"AV42Pgmname"});e.addRefreshingVar({rfrVar:"A1TAM01_SYS_ID"});
e.addRefreshingVar({rfrVar:"A2TAM02_MENU_ID_TREE_1"});e.addRefreshingVar({rfrVar:"A3TAM02_MENU_ID_TREE_2"});e.addRefreshingVar({rfrVar:"A4TAM02_MENU_ID_TREE_3"});e.addRefreshingVar({rfrVar:"A211TAM02_MENU_NM"});e.addRefreshingVar(this.GXValidFnc[108]);e.addRefreshingVar(this.GXValidFnc[109]);e.addRefreshingVar(this.GXValidFnc[110]);e.addRefreshingVar(this.GXValidFnc[111]);e.addRefreshingVar({rfrVar:"A212TAM02_DEL_FLG"});e.addRefreshingVar({rfrVar:"A13TAM04_AUTH_CD"});e.addRefreshingVar({rfrVar:"AV33W_A_LOGIN_SDT"});
e.addRefreshingVar({rfrVar:"A12TAM03_APP_ID"});e.addRefreshingVar({rfrVar:"A5TAM02_APP_ID"});e.addRefreshingVar({rfrVar:"A215TAM04_DEL_FLG"});e.addRefreshingVar({rfrVar:"A276TAM03_KIDO_PG"});this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0115",lvl:1})});gx.setParentObj(new a103_wp01_system_menu);
