gx.evt.autoSkip=!1;
gx.define("a203_wp01_kngn_mst",!1,function(){this.ServerClass="a203_wp01_kngn_mst";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110q2_client");this.addKeyListener("4","e120q2_client");this.addKeyListener("6","e130q2_client");this.addKeyListener("11","e140q2_client");this.SetStandaloneVars=function(){this.AV16P_TAM04_KNGN_PTN_KBN=gx.fn.getControlValue("vP_TAM04_KNGN_PTN_KBN")};this.s162_client=
function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");""!=this.AV24W_A821_JS&&gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV24W_A821_JS);""!=this.AV23W_A819_JS&&gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV23W_A819_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.s192_client=function(){gx.fn.setCtrlProperty("CTLTAM04_KNGN_PTN_KBN","Backcolor",gx.color.rgb(255,
255,255));gx.fn.setCtrlProperty("CTLTAM04_KNGN_PTN_NM","Backcolor",gx.color.rgb(255,255,255))};this.s202_client=function(){for(this.AV45GXV10=1;this.AV45GXV10<=this.AV18W_A_CHK_RESULT_SDT.length;){this.AV19W_A_CHK_RESULT_SDT_ITEM=this.AV18W_A_CHK_RESULT_SDT[this.AV45GXV10-1];this.s212_client();this.AV45GXV10=this.AV45GXV10+1}};this.s212_client=function(){if(this.AV19W_A_CHK_RESULT_SDT_ITEM.ID=="TAM04_KNGN_PTN_KBN"){gx.fn.setCtrlProperty("CTLTAM04_KNGN_PTN_KBN","Backcolor",gx.color.rgb(255,192,203));
this.AV19W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTAM04_KNGN_PTN_KBN")}else if(this.AV19W_A_CHK_RESULT_SDT_ITEM.ID=="TAM04_KNGN_PTN_NM"){gx.fn.setCtrlProperty("CTLTAM04_KNGN_PTN_NM","Backcolor",gx.color.rgb(255,192,203));this.AV19W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTAM04_KNGN_PTN_NM")}};this.e170q2_client=function(){this.executeServerEvent("CTLTAM04_KNGN_PTN_KBN.ISVALID",true)};this.e110q2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e180q2_client=
function(){this.executeServerEvent("'BTN_REG_EXEC'",true)};this.e120q2_client=function(){this.executeServerEvent("'BTN_UPD'",true)};this.e190q2_client=function(){this.executeServerEvent("'BTN_UPD_EXEC'",true)};this.e130q2_client=function(){this.executeServerEvent("'BTN_DLT'",true)};this.e200q2_client=function(){this.executeServerEvent("'BTN_DLT_EXEC'",true)};this.e140q2_client=function(){this.executeServerEvent("'BTN_CAN'",true)};this.e220q2_client=function(){this.executeServerEvent("ENTER",true)};
this.e230q2_client=function(){this.executeServerEvent("CANCEL",true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,18,19,22,25,28,31,37,42,44,46,48,52,55,61,64,68,71,75,78,79,82,83,84,85,86,87,88];this.GXLastCtrlId=88;b[2]={fld:"TABLE2",grid:0};b[6]={fld:"TABLE3",grid:0};b[12]={fld:"TBL_INS_BTNSET",grid:0};b[15]={fld:"TEXTBLOCK42",format:0,grid:0};b[18]={fld:"TEXTBLOCK43",format:0,grid:0};b[19]={fld:"TBL_UPD_BTNSET",grid:0};b[22]={fld:"TEXTBLOCK44",format:0,grid:0};b[25]={fld:"TEXTBLOCK45",
format:0,grid:0};b[28]={fld:"TEXTBLOCK46",format:0,grid:0};b[31]={fld:"TABLE5",grid:0};b[37]={fld:"TABLE4",grid:0};b[42]={fld:"IMAGE1",grid:0};b[44]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:"e170q2_client",rgrid:[],fld:"CTLTAM04_KNGN_PTN_KBN",gxz:"ZV31GXV1",gxold:"OV31GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=a},v2z:function(a){gx.O.ZV31GXV1=a},v2c:function(){gx.fn.setControlValue("CTLTAM04_KNGN_PTN_KBN",gx.O.GXV1,
0)},c2v:function(){gx.O.GXV1=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM04_KNGN_PTN_KBN")},nac:gx.falseFn};b[46]={fld:"IMAGE5",grid:0};b[48]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_KNGN_PTN_NM",gxz:"ZV32GXV2",gxold:"OV32GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV2=a},v2z:function(a){gx.O.ZV32GXV2=a},v2c:function(){gx.fn.setControlValue("CTLTAM04_KNGN_PTN_NM",gx.O.GXV2,
0)},c2v:function(){gx.O.GXV2=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM04_KNGN_PTN_NM")},nac:gx.falseFn};b[52]={lvl:0,type:"int",len:2,dec:0,sign:false,pic:"Z9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_AUTH_LVL",gxz:"ZV33GXV3",gxold:"OV33GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.GXV3=gx.num.intval(a)},v2z:function(a){gx.O.ZV33GXV3=gx.num.intval(a)},v2c:function(){gx.fn.setComboBoxValue("CTLTAM04_AUTH_LVL",
gx.O.GXV3)},c2v:function(){gx.O.GXV3=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLTAM04_AUTH_LVL",",")},nac:gx.falseFn};b[55]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_DEL_FLG",gxz:"ZV34GXV4",gxold:"OV34GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",v2v:function(a){gx.O.GXV4=a},v2z:function(a){gx.O.ZV34GXV4=a},v2c:function(){gx.fn.setRadioValue("CTLTAM04_DEL_FLG",gx.O.GXV4)},c2v:function(){gx.O.GXV4=
this.val()},val:function(){return gx.fn.getControlValue("CTLTAM04_DEL_FLG")},nac:gx.falseFn};b[61]={lvl:0,type:"dtime",len:10,dec:8,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_CRT_DATETIME",gxz:"ZV35GXV5",gxold:"OV35GXV5",gxvar:"GXV5",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV5=gx.fn.toDatetimeValue(a,"Y4MD")},v2z:function(a){gx.O.ZV35GXV5=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTAM04_CRT_DATETIME",
gx.O.GXV5,0)},c2v:function(){gx.O.GXV5=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTAM04_CRT_DATETIME")},nac:gx.falseFn};b[64]={lvl:0,type:"dtime",len:10,dec:8,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_UPD_DATETIME",gxz:"ZV36GXV6",gxold:"OV36GXV6",gxvar:"GXV6",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV6=gx.fn.toDatetimeValue(a,
"Y4MD")},v2z:function(a){gx.O.ZV36GXV6=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTAM04_UPD_DATETIME",gx.O.GXV6,0)},c2v:function(){gx.O.GXV6=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTAM04_UPD_DATETIME")},nac:gx.falseFn};b[68]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM04_CRT_USER_NM",gxz:"ZV11D_TAM04_CRT_USER_NM",gxold:"OV11D_TAM04_CRT_USER_NM",gxvar:"AV11D_TAM04_CRT_USER_NM",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11D_TAM04_CRT_USER_NM=a},v2z:function(a){gx.O.ZV11D_TAM04_CRT_USER_NM=a},v2c:function(){gx.fn.setControlValue("vD_TAM04_CRT_USER_NM",gx.O.AV11D_TAM04_CRT_USER_NM,1)},c2v:function(){gx.O.AV11D_TAM04_CRT_USER_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM04_CRT_USER_NM")},nac:gx.falseFn};b[71]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM04_UPD_USER_NM",
gxz:"ZV12D_TAM04_UPD_USER_NM",gxold:"OV12D_TAM04_UPD_USER_NM",gxvar:"AV12D_TAM04_UPD_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12D_TAM04_UPD_USER_NM=a},v2z:function(a){gx.O.ZV12D_TAM04_UPD_USER_NM=a},v2c:function(){gx.fn.setControlValue("vD_TAM04_UPD_USER_NM",gx.O.AV12D_TAM04_UPD_USER_NM,1)},c2v:function(){gx.O.AV12D_TAM04_UPD_USER_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM04_UPD_USER_NM")},nac:gx.falseFn};b[75]={lvl:0,type:"svchar",len:40,
dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_CRT_PG_NM",gxz:"ZV37GXV7",gxold:"OV37GXV7",gxvar:"GXV7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV7=a},v2z:function(a){gx.O.ZV37GXV7=a},v2c:function(){gx.fn.setControlValue("CTLTAM04_CRT_PG_NM",gx.O.GXV7,0)},c2v:function(){gx.O.GXV7=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM04_CRT_PG_NM")},nac:gx.falseFn};b[78]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,
gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_UPD_PG_NM",gxz:"ZV38GXV8",gxold:"OV38GXV8",gxvar:"GXV8",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV8=a},v2z:function(a){gx.O.ZV38GXV8=a},v2c:function(){gx.fn.setControlValue("CTLTAM04_UPD_PG_NM",gx.O.GXV8,0)},c2v:function(){gx.O.GXV8=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM04_UPD_PG_NM")},nac:gx.falseFn};b[79]={fld:"TBL_HIDDEN",grid:0};b[82]={fld:"TXT_JS_EVENT",format:1,grid:0};b[83]={fld:"BTN_UPD_EXEC",
format:0,grid:0};b[84]={fld:"BTN_DLT_EXEC",format:0,grid:0};b[85]={fld:"BTN_REG_EXEC",format:0,grid:0};b[86]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV13H_INIT_FLG",gxold:"OV13H_INIT_FLG",gxvar:"AV13H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_INIT_FLG=a},v2z:function(a){gx.O.ZV13H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV13H_INIT_FLG,0);typeof this.dom_hdl==
"function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV13H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(86,function(){});b[87]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_MODE",gxz:"ZV15H_MODE",gxold:"OV15H_MODE",gxvar:"AV15H_MODE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_MODE=a},v2z:function(a){gx.O.ZV15H_MODE=a},v2c:function(){gx.fn.setControlValue("vH_MODE",
gx.O.AV15H_MODE,0)},c2v:function(){gx.O.AV15H_MODE=this.val()},val:function(){return gx.fn.getControlValue("vH_MODE")},nac:gx.falseFn};b[88]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV14H_KNGN_FLG",gxold:"OV14H_KNGN_FLG",gxvar:"AV14H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV14H_KNGN_FLG=a},v2z:function(a){gx.O.ZV14H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV14H_KNGN_FLG,
0)},c2v:function(){gx.O.AV14H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};this.OV32GXV2=this.ZV32GXV2=this.GXV2=this.OV31GXV1=this.ZV31GXV1=this.GXV1="";this.OV33GXV3=this.ZV33GXV3=this.GXV3=0;this.OV34GXV4=this.ZV34GXV4=this.GXV4="";this.GXV5=gx.date.nullDate();this.ZV35GXV5=gx.date.nullDate();this.OV35GXV5=gx.date.nullDate();this.GXV6=gx.date.nullDate();this.ZV36GXV6=gx.date.nullDate();this.OV36GXV6=gx.date.nullDate();this.GXV2=this.GXV1=this.OV14H_KNGN_FLG=
this.ZV14H_KNGN_FLG=this.AV14H_KNGN_FLG=this.OV15H_MODE=this.ZV15H_MODE=this.AV15H_MODE=this.OV13H_INIT_FLG=this.ZV13H_INIT_FLG=this.AV13H_INIT_FLG=this.OV38GXV8=this.ZV38GXV8=this.GXV8=this.OV37GXV7=this.ZV37GXV7=this.GXV7=this.OV12D_TAM04_UPD_USER_NM=this.ZV12D_TAM04_UPD_USER_NM=this.AV12D_TAM04_UPD_USER_NM=this.OV11D_TAM04_CRT_USER_NM=this.ZV11D_TAM04_CRT_USER_NM=this.AV11D_TAM04_CRT_USER_NM="";this.GXV3=0;this.GXV4="";this.GXV5=gx.date.nullDate();this.GXV6=gx.date.nullDate();this.A13TAM04_AUTH_CD=
this.A205TAM07_USER_NM=this.A55TAM07_USER_ID=this.AV16P_TAM04_KNGN_PTN_KBN=this.AV14H_KNGN_FLG=this.AV15H_MODE=this.AV13H_INIT_FLG=this.GXV8=this.GXV7=this.AV12D_TAM04_UPD_USER_NM=this.AV11D_TAM04_CRT_USER_NM="";this.A235TAM04_UPD_DATETIME=gx.date.nullDate();this.A8TAS01_ITEM_CD=this.A9TAS01_ITEM_NM=this.A300TAS01_DEL_FLG=this.A7TAS01_DATA_KIND="";this.A335TAS01_SORT_NO=0;this.AV24W_A821_JS=this.AV23W_A819_JS="";this.AV19W_A_CHK_RESULT_SDT_ITEM={};this.AV18W_A_CHK_RESULT_SDT=[];this.AV45GXV10=0;this.Events=
{e170q2_client:["CTLTAM04_KNGN_PTN_KBN.ISVALID",true],e110q2_client:["'BTN_REG'",true],e180q2_client:["'BTN_REG_EXEC'",true],e120q2_client:["'BTN_UPD'",true],e190q2_client:["'BTN_UPD_EXEC'",true],e130q2_client:["'BTN_DLT'",true],e200q2_client:["'BTN_DLT_EXEC'",true],e140q2_client:["'BTN_CAN'",true],e220q2_client:["ENTER",true],e230q2_client:["CANCEL",true]};this.setVCMap("AV16P_TAM04_KNGN_PTN_KBN","vP_TAM04_KNGN_PTN_KBN",0,"svchar");this.addBCProperty("Bc_tam04_kngn",["TAM04_AUTH_CD"],this.GXValidFnc[44],
"AV6BC_TAM04_KNGN");this.addBCProperty("Bc_tam04_kngn",["TAM04_AUTH_NM"],this.GXValidFnc[48],"AV6BC_TAM04_KNGN");this.addBCProperty("Bc_tam04_kngn",["TAM04_AUTH_LVL"],this.GXValidFnc[52],"AV6BC_TAM04_KNGN");this.addBCProperty("Bc_tam04_kngn",["TAM04_DEL_FLG"],this.GXValidFnc[55],"AV6BC_TAM04_KNGN");this.addBCProperty("Bc_tam04_kngn",["TAM04_CRT_DATETIME"],this.GXValidFnc[61],"AV6BC_TAM04_KNGN");this.addBCProperty("Bc_tam04_kngn",["TAM04_UPD_DATETIME"],this.GXValidFnc[64],"AV6BC_TAM04_KNGN");this.addBCProperty("Bc_tam04_kngn",
["TAM04_CRT_PROG_NM"],this.GXValidFnc[75],"AV6BC_TAM04_KNGN");this.addBCProperty("Bc_tam04_kngn",["TAM04_UPD_PROG_NM"],this.GXValidFnc[78],"AV6BC_TAM04_KNGN");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0091",lvl:1})});gx.setParentObj(new a203_wp01_kngn_mst);
