gx.evt.autoSkip=!1;
gx.define("a211_wp01_import_cdisc_item",!1,function(){this.ServerClass="a211_wp01_import_cdisc_item";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e111x2_client");this.addKeyListener("11","e121x2_client");this.SetStandaloneVars=function(){this.AV15P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV14P_DOM_CD=gx.fn.getControlValue("vP_DOM_CD")};this.s122_client=function(){this.AV18W_A819_JS=this.AV19W_A821_JS=
""};this.s142_client=function(){};this.e111x2_client=function(){this.executeServerEvent("'BTN_UPLOAD'",true)};this.e151x2_client=function(){this.executeServerEvent("'BTN_UPLOAD_EXEC'",true)};this.e121x2_client=function(){this.executeServerEvent("'BTN_CAN'",true)};this.e171x2_client=function(){this.executeServerEvent("ENTER",true)};this.e181x2_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,17,20,23,26,28,31,33,34,39,42,44,48,51,53,54,62,
71,74,75,76,77,78];this.GXLastCtrlId=78;a[2]={fld:"TABLE1",grid:0};a[6]={fld:"TABLE2",grid:0};a[12]={fld:"TBL_UPD_BTNSET",grid:0};a[15]={fld:"TXT_BTN_UPLOAD",format:0,grid:0};a[17]={fld:"TXT_BTN_CAN",format:0,grid:0};a[20]={fld:"TABLE3",grid:0};a[23]={fld:"TABLE10",grid:0};a[26]={fld:"TEXTBLOCK16",format:0,grid:0};a[28]={lvl:0,type:"bitstr",len:1024,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_UPLOAD_FILE",gxz:"ZV11D_UPLOAD_FILE",gxold:"OV11D_UPLOAD_FILE",gxvar:"AV11D_UPLOAD_FILE",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11D_UPLOAD_FILE=a},v2z:function(a){gx.O.ZV11D_UPLOAD_FILE=a},v2c:function(){gx.fn.setBlobValue("vD_UPLOAD_FILE",gx.O.AV11D_UPLOAD_FILE)},c2v:function(){gx.O.AV11D_UPLOAD_FILE=this.val()},val:function(){return gx.fn.getBlobValue("vD_UPLOAD_FILE")},nac:gx.falseFn};a[31]={fld:"TEXTBLOCK17",format:0,grid:0};a[33]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_VERSION",gxz:"ZV38D_VERSION",
gxold:"OV38D_VERSION",gxvar:"AV38D_VERSION",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV38D_VERSION=a},v2z:function(a){gx.O.ZV38D_VERSION=a},v2c:function(){gx.fn.setControlValue("vD_VERSION",gx.O.AV38D_VERSION,0)},c2v:function(){gx.O.AV38D_VERSION=this.val()},val:function(){return gx.fn.getControlValue("vD_VERSION")},nac:gx.falseFn};a[34]={fld:"TABLE5",grid:0};a[39]={fld:"TEXTBLOCK1",format:0,grid:0};a[42]={fld:"TEXTBLOCK4",format:0,grid:0};a[44]={fld:"TEXTBLOCK7",format:0,
grid:0};a[48]={fld:"TEXTBLOCK8",format:0,grid:0};a[51]={fld:"TEXTBLOCK5",format:0,grid:0};a[53]={fld:"TEXTBLOCK2",format:0,grid:0};a[54]={lvl:0,type:"svchar",len:200,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_ORIGINAL_NAME",gxz:"ZV10D_ORIGINAL_NAME",gxold:"OV10D_ORIGINAL_NAME",gxvar:"AV10D_ORIGINAL_NAME",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10D_ORIGINAL_NAME=a},v2z:function(a){gx.O.ZV10D_ORIGINAL_NAME=a},v2c:function(){gx.fn.setControlValue("vD_ORIGINAL_NAME",
gx.O.AV10D_ORIGINAL_NAME,0)},c2v:function(){gx.O.AV10D_ORIGINAL_NAME=this.val()},val:function(){return gx.fn.getControlValue("vD_ORIGINAL_NAME")},nac:gx.falseFn};a[62]={fld:"TABLE4",grid:0};a[71]={fld:"TBL_HIDDEN",grid:0};a[74]={fld:"TXT_JS_EVENT",format:1,grid:0};a[75]={fld:"TEXT_ONCLICK",format:1,grid:0};a[76]={fld:"BTN_UPLOAD_EXEC",format:0,grid:0};a[77]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV12H_INIT_FLG",gxold:"OV12H_INIT_FLG",
gxvar:"AV12H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12H_INIT_FLG=a},v2z:function(a){gx.O.ZV12H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV12H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV12H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(77,function(){});a[78]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,
gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV13H_KNGN_FLG",gxold:"OV13H_KNGN_FLG",gxvar:"AV13H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_KNGN_FLG=a},v2z:function(a){gx.O.ZV13H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV13H_KNGN_FLG,0)},c2v:function(){gx.O.AV13H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};this.AV13H_KNGN_FLG=this.AV12H_INIT_FLG=this.AV10D_ORIGINAL_NAME=
this.AV38D_VERSION=this.AV11D_UPLOAD_FILE=this.OV13H_KNGN_FLG=this.ZV13H_KNGN_FLG=this.AV13H_KNGN_FLG=this.OV12H_INIT_FLG=this.ZV12H_INIT_FLG=this.AV12H_INIT_FLG=this.OV10D_ORIGINAL_NAME=this.ZV10D_ORIGINAL_NAME=this.AV10D_ORIGINAL_NAME=this.OV38D_VERSION=this.ZV38D_VERSION=this.AV38D_VERSION=this.OV11D_UPLOAD_FILE=this.ZV11D_UPLOAD_FILE=this.AV11D_UPLOAD_FILE="";this.AV15P_MOVE_KBN=0;this.AV19W_A821_JS=this.AV18W_A819_JS=this.AV14P_DOM_CD="";this.Events={e111x2_client:["'BTN_UPLOAD'",true],e151x2_client:["'BTN_UPLOAD_EXEC'",
true],e121x2_client:["'BTN_CAN'",true],e171x2_client:["ENTER",true],e181x2_client:["CANCEL",true]};this.setVCMap("AV15P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV14P_DOM_CD","vP_DOM_CD",0,"svchar");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0069",lvl:1})});gx.setParentObj(new a211_wp01_import_cdisc_item);
