gx.evt.autoSkip=!1;
gx.define("a212_wp01_cdisc_item_list",!1,function(){this.ServerClass="a212_wp01_cdisc_item_list";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e111w2_client");this.addKeyListener("4","e121w2_client");this.addKeyListener("5","e131w2_client");this.addKeyListener("6","e141w2_client");this.addKeyListener("7","e151w2_client");this.addKeyListener("8","e161w2_client");this.addKeyListener("9","e171w2_client");
this.SetStandaloneVars=function(){this.AV51Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV6C_TAM02_APP_ID=gx.fn.getControlValue("vC_TAM02_APP_ID");this.AV26P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV27P_MOVE_KBN_2=gx.fn.getIntegerValue("vP_MOVE_KBN_2",",");this.AV25P_DOM_CD=gx.fn.getControlValue("vP_DOM_CD");this.AV17H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.A49TBM02_DOM_CD=gx.fn.getControlValue("TBM02_DOM_CD");this.A611TBM02_DOM_JNM=gx.fn.getControlValue("TBM02_DOM_JNM");
this.AV30W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.AV44SD_A212_SD01_LIST_C=gx.fn.getControlValue("vSD_A212_SD01_LIST_C");this.AV34W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG");this.A60TBM03_DOM_VAR_NM=gx.fn.getControlValue("TBM03_DOM_VAR_NM");this.A932TBM03_VERSION=gx.fn.getControlValue("TBM03_VERSION");this.A59TBM03_DOM_CD=gx.fn.getControlValue("TBM03_DOM_CD");this.A61TBM03_ORDER=gx.fn.getIntegerValue("TBM03_ORDER",",");this.A346TBM03_VAR_DESC=gx.fn.getControlValue("TBM03_VAR_DESC");this.A359TBM03_DEL_FLG=
gx.fn.getControlValue("TBM03_DEL_FLG")};this.s292_client=function(){gx.fn.setCtrlProperty("vD_LINE","Backcolor",gx.color.rgb(255,255,255))};this.s232_client=function(){this.AV18H_DOM_CD=this.AV7D_DOM_CD;this.AV19H_DOM_VAR_NM=this.AV9D_DOM_VAR_NM;this.AV24H_VAR_DESC=this.AV16D_VAR_DESC;this.AV22H_SORT=this.AV15D_SORT};this.s182_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"function proc() {");if(""!=this.AV30W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV30W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.s222_client=function(){this.s292_client()};this.e111w2_client=function(){this.executeServerEvent("'BTN_REG'",
true)};this.e121w2_client=function(){this.executeServerEvent("'BTN_CSV'",true)};this.e131w2_client=function(){this.executeServerEvent("'BTN_SRCH'",true)};this.e141w2_client=function(){this.executeServerEvent("'BTN_CLER'",true)};this.e151w2_client=function(){this.executeServerEvent("'BTN_EDIT'",true)};this.e161w2_client=function(){this.executeServerEvent("'BTN_IMPORT_CDISC_ITEM'",true)};this.e171w2_client=function(){this.executeServerEvent("'BTN_DOMAIN'",true)};this.e351w2_client=function(a){this.executeServerEvent("'BTN_SEL'",
true,a)};this.e181w2_client=function(){this.executeServerEvent("'PAGE_FIRST'",true)};this.e191w2_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};this.e201w2_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e211w2_client=function(){this.executeServerEvent("'PAGE_NEXT'",true)};this.e221w2_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e231w2_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e241w2_client=function(){this.executeServerEvent("'PAGE03'",
true)};this.e251w2_client=function(){this.executeServerEvent("'PAGE04'",true)};this.e261w2_client=function(){this.executeServerEvent("'PAGE05'",true)};this.e271w2_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e281w2_client=function(){this.executeServerEvent("'PAGE07'",true)};this.e291w2_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e301w2_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e311w2_client=function(){this.executeServerEvent("'PAGE10'",
true)};this.e361w2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e371w2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,16,19,22,25,28,31,34,38,42,46,50,53,56,59,65,68,71,74,77,80,83,86,89,92,95,98,101,104,107,110,113,116,119,122,125,128,131,134,137,140,143,146,149,152,155,157,160,162,165,171,174,178,180,182,184,186,188,190,196,198,200,202,204,206,208,210,217,220,221,222,223,224,225,226,227,228,231,233];this.GXLastCtrlId=
233;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",193,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"a212_wp01_cdisc_item_list",[],true,1,true,true,10,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,"",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","center","","","","","45px","","","");c.addTextBlock("BTN_SEL","e351w2_client");c.endCell();c.startCell("","right","","","","","50px","","","");c.addSingleLineEdit("D_grd_line",
198,"vD_GRD_LINE","","","D_GRD_LINE","int",4,"chr",4,4,"right",null,[],"D_grd_line","D_GRD_LINE",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","center","","","","","85px","","","");c.addSingleLineEdit("D_grd_dom_cd",200,"vD_GRD_DOM_CD","","","D_GRD_DOM_CD","svchar",2,"chr",2,2,"left",null,[],"D_grd_dom_cd","D_GRD_DOM_CD",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","","","","","","150px","","","");c.addSingleLineEdit("D_grd_dom_var_nm",202,"vD_GRD_DOM_VAR_NM",
"","","D_GRD_DOM_VAR_NM","svchar",50,"chr",50,50,"left",null,[],"D_grd_dom_var_nm","D_GRD_DOM_VAR_NM",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","","","","","","300px","","","");c.addSingleLineEdit("D_grd_var_desc",204,"vD_GRD_VAR_DESC","","","D_GRD_VAR_DESC","svchar",80,"chr",100,80,"left",null,[],"D_grd_var_desc","D_GRD_VAR_DESC",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","right","","","","","50px","","","");c.addSingleLineEdit("D_grd_order",206,"vD_GRD_ORDER",
"","","D_GRD_ORDER","int",5,"chr",5,5,"right",null,[],"D_grd_order","D_GRD_ORDER",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","center","","","","","65px","","","");c.addSingleLineEdit("D_grd_version",208,"vD_GRD_VERSION","","","D_GRD_VERSION","svchar",20,"chr",20,20,"left",null,[],"D_grd_version","D_GRD_VERSION",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","center","","","","","100px","","","");c.addSingleLineEdit("D_grd_del",210,"vD_GRD_DEL","","","D_GRD_DEL",
"svchar",10,"chr",10,10,"left",null,[],"D_grd_del","D_GRD_DEL",true,0,false,false,"Attribute",1,"");c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[6]={fld:"TABLE2",grid:0};b[12]={fld:"TABLE8",grid:0};b[15]={fld:"TXT_BTN_REG",format:0,grid:0};b[16]={fld:"TXT_BTN_REG2",format:0,grid:0};b[19]={fld:"TEXTBLOCK43",format:0,grid:0};b[22]={fld:"TEXTBLOCK47",format:0,grid:0};b[25]={fld:"BTN_DOMAIN",format:0,grid:0};b[28]={fld:"TABLE3",grid:0};b[31]={fld:"TABLE4",grid:0};b[34]={fld:"TABLE5",
grid:0};b[38]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_DOM_CD",gxz:"ZV7D_DOM_CD",gxold:"OV7D_DOM_CD",gxvar:"AV7D_DOM_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV7D_DOM_CD=a},v2z:function(a){gx.O.ZV7D_DOM_CD=a},v2c:function(){gx.fn.setComboBoxValue("vD_DOM_CD",gx.O.AV7D_DOM_CD)},c2v:function(){gx.O.AV7D_DOM_CD=this.val()},val:function(){return gx.fn.getControlValue("vD_DOM_CD")},nac:gx.falseFn};b[42]={lvl:0,
type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_DOM_VAR_NM",gxz:"ZV9D_DOM_VAR_NM",gxold:"OV9D_DOM_VAR_NM",gxvar:"AV9D_DOM_VAR_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9D_DOM_VAR_NM=a},v2z:function(a){gx.O.ZV9D_DOM_VAR_NM=a},v2c:function(){gx.fn.setControlValue("vD_DOM_VAR_NM",gx.O.AV9D_DOM_VAR_NM,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV9D_DOM_VAR_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_DOM_VAR_NM")},
nac:gx.falseFn};this.declareDomainHdlr(42,function(){});b[46]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_VAR_DESC",gxz:"ZV16D_VAR_DESC",gxold:"OV16D_VAR_DESC",gxvar:"AV16D_VAR_DESC",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV16D_VAR_DESC=a},v2z:function(a){gx.O.ZV16D_VAR_DESC=a},v2c:function(){gx.fn.setControlValue("vD_VAR_DESC",gx.O.AV16D_VAR_DESC,0)},c2v:function(){gx.O.AV16D_VAR_DESC=this.val()},val:function(){return gx.fn.getControlValue("vD_VAR_DESC")},
nac:gx.falseFn};b[50]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_SORT",gxz:"ZV15D_SORT",gxold:"OV15D_SORT",gxvar:"AV15D_SORT",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV15D_SORT=a},v2z:function(a){gx.O.ZV15D_SORT=a},v2c:function(){gx.fn.setComboBoxValue("vD_SORT",gx.O.AV15D_SORT)},c2v:function(){gx.O.AV15D_SORT=this.val()},val:function(){return gx.fn.getControlValue("vD_SORT")},nac:gx.falseFn};b[53]={fld:"TABLE9",
grid:0};b[56]={fld:"TEXTBLOCK45",format:0,grid:0};b[59]={fld:"TEXTBLOCK44",format:0,grid:0};b[65]={fld:"TBL_PAGE_AREA",grid:0};b[68]={fld:"TXT_REC_CNT",format:0,grid:0};b[71]={fld:"TBL_PAGE",grid:0};b[74]={fld:"TBL_FIRST",grid:0};b[77]={fld:"TXT_FIRST",format:0,grid:0};b[80]={fld:"TBL_BACK",grid:0};b[83]={fld:"TXT_BACK",format:0,grid:0};b[86]={fld:"TBL_PAGE01",grid:0};b[89]={fld:"TXT_PAGE01",format:0,grid:0};b[92]={fld:"TBL_PAGE02",grid:0};b[95]={fld:"TXT_PAGE02",format:0,grid:0};b[98]={fld:"TBL_PAGE03",
grid:0};b[101]={fld:"TXT_PAGE03",format:0,grid:0};b[104]={fld:"TBL_PAGE04",grid:0};b[107]={fld:"TXT_PAGE04",format:0,grid:0};b[110]={fld:"TBL_PAGE05",grid:0};b[113]={fld:"TXT_PAGE05",format:0,grid:0};b[116]={fld:"TBL_PAGE06",grid:0};b[119]={fld:"TXT_PAGE06",format:0,grid:0};b[122]={fld:"TBL_PAGE07",grid:0};b[125]={fld:"TXT_PAGE07",format:0,grid:0};b[128]={fld:"TBL_PAGE08",grid:0};b[131]={fld:"TXT_PAGE08",format:0,grid:0};b[134]={fld:"TBL_PAGE09",grid:0};b[137]={fld:"TXT_PAGE09",format:0,grid:0};b[140]=
{fld:"TBL_PAGE10",grid:0};b[143]={fld:"TXT_PAGE10",format:0,grid:0};b[146]={fld:"TBL_NEXT",grid:0};b[149]={fld:"TXT_NEXT",format:0,grid:0};b[152]={fld:"TBL_LAST",grid:0};b[155]={fld:"TXT_LAST",format:0,grid:0};b[157]={fld:"TBL_EDIT",grid:0};b[160]={fld:"TEXTBLOCK29",format:0,grid:0};b[162]={lvl:0,type:"char",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_LINE",gxz:"ZV14D_LINE",gxold:"OV14D_LINE",gxvar:"AV14D_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",
v2v:function(a){gx.O.AV14D_LINE=a},v2z:function(a){gx.O.ZV14D_LINE=a},v2c:function(){gx.fn.setControlValue("vD_LINE",gx.O.AV14D_LINE,0)},c2v:function(){gx.O.AV14D_LINE=this.val()},val:function(){return gx.fn.getControlValue("vD_LINE")},nac:gx.falseFn};b[165]={fld:"TEXTBLOCK28",format:0,grid:0};b[171]={fld:"TBL_GRID_HEADER",grid:0};b[174]={fld:"TBL_IN_GRID_HEADER",grid:0};b[178]={fld:"TEXTBLOCK34",format:0,grid:0};b[180]={fld:"TEXTBLOCK30",format:0,grid:0};b[182]={fld:"TEXTBLOCK31",format:0,grid:0};
b[184]={fld:"TEXTBLOCK32",format:0,grid:0};b[186]={fld:"TEXTBLOCK35",format:0,grid:0};b[188]={fld:"TEXTBLOCK36",format:0,grid:0};b[190]={fld:"TEXTBLOCK33",format:0,grid:0};b[196]={fld:"BTN_SEL",format:0,grid:193};b[198]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,isacc:0,grid:193,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_LINE",gxz:"ZV11D_GRD_LINE",gxold:"OV11D_GRD_LINE",gxvar:"AV11D_GRD_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV11D_GRD_LINE=
gx.num.intval(a)},v2z:function(a){gx.O.ZV11D_GRD_LINE=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(193),gx.O.AV11D_GRD_LINE,0)},c2v:function(){gx.O.AV11D_GRD_LINE=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(193),",")},nac:gx.falseFn};b[200]={lvl:2,type:"svchar",len:2,dec:0,sign:false,ro:0,isacc:0,grid:193,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_DOM_CD",
gxz:"ZV39D_GRD_DOM_CD",gxold:"OV39D_GRD_DOM_CD",gxvar:"AV39D_GRD_DOM_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV39D_GRD_DOM_CD=a},v2z:function(a){gx.O.ZV39D_GRD_DOM_CD=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_DOM_CD",a||gx.fn.currentGridRowImpl(193),gx.O.AV39D_GRD_DOM_CD,0)},c2v:function(){gx.O.AV39D_GRD_DOM_CD=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_DOM_CD",a||gx.fn.currentGridRowImpl(193))},nac:gx.falseFn};
b[202]={lvl:2,type:"svchar",len:50,dec:0,sign:false,ro:0,isacc:0,grid:193,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_DOM_VAR_NM",gxz:"ZV40D_GRD_DOM_VAR_NM",gxold:"OV40D_GRD_DOM_VAR_NM",gxvar:"AV40D_GRD_DOM_VAR_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV40D_GRD_DOM_VAR_NM=a},v2z:function(a){gx.O.ZV40D_GRD_DOM_VAR_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_DOM_VAR_NM",a||gx.fn.currentGridRowImpl(193),
gx.O.AV40D_GRD_DOM_VAR_NM,0)},c2v:function(){gx.O.AV40D_GRD_DOM_VAR_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_DOM_VAR_NM",a||gx.fn.currentGridRowImpl(193))},nac:gx.falseFn};b[204]={lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:0,isacc:0,grid:193,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_VAR_DESC",gxz:"ZV41D_GRD_VAR_DESC",gxold:"OV41D_GRD_VAR_DESC",gxvar:"AV41D_GRD_VAR_DESC",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",
v2v:function(a){gx.O.AV41D_GRD_VAR_DESC=a},v2z:function(a){gx.O.ZV41D_GRD_VAR_DESC=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_VAR_DESC",a||gx.fn.currentGridRowImpl(193),gx.O.AV41D_GRD_VAR_DESC,0)},c2v:function(){gx.O.AV41D_GRD_VAR_DESC=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_VAR_DESC",a||gx.fn.currentGridRowImpl(193))},nac:gx.falseFn};b[206]={lvl:2,type:"int",len:5,dec:0,sign:false,pic:"ZZZZ9",ro:0,isacc:0,grid:193,gxgrid:this.Grid1Container,fnc:null,isvalid:null,
rgrid:[],fld:"vD_GRD_ORDER",gxz:"ZV42D_GRD_ORDER",gxold:"OV42D_GRD_ORDER",gxvar:"AV42D_GRD_ORDER",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV42D_GRD_ORDER=gx.num.intval(a)},v2z:function(a){gx.O.ZV42D_GRD_ORDER=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_ORDER",a||gx.fn.currentGridRowImpl(193),gx.O.AV42D_GRD_ORDER,0)},c2v:function(){gx.O.AV42D_GRD_ORDER=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("vD_GRD_ORDER",
a||gx.fn.currentGridRowImpl(193),",")},nac:gx.falseFn};b[208]={lvl:2,type:"svchar",len:20,dec:0,sign:false,ro:0,isacc:0,grid:193,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_VERSION",gxz:"ZV43D_GRD_VERSION",gxold:"OV43D_GRD_VERSION",gxvar:"AV43D_GRD_VERSION",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV43D_GRD_VERSION=a},v2z:function(a){gx.O.ZV43D_GRD_VERSION=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_VERSION",
a||gx.fn.currentGridRowImpl(193),gx.O.AV43D_GRD_VERSION,0)},c2v:function(){gx.O.AV43D_GRD_VERSION=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_VERSION",a||gx.fn.currentGridRowImpl(193))},nac:gx.falseFn};b[210]={lvl:2,type:"svchar",len:10,dec:0,sign:false,ro:0,isacc:0,grid:193,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_DEL",gxz:"ZV10D_GRD_DEL",gxold:"OV10D_GRD_DEL",gxvar:"AV10D_GRD_DEL",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",
autoCorrect:"1",v2v:function(a){gx.O.AV10D_GRD_DEL=a},v2z:function(a){gx.O.ZV10D_GRD_DEL=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_DEL",a||gx.fn.currentGridRowImpl(193),gx.O.AV10D_GRD_DEL,0)},c2v:function(){gx.O.AV10D_GRD_DEL=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_DEL",a||gx.fn.currentGridRowImpl(193))},nac:gx.falseFn};b[217]={fld:"TBL_HIDDEN",grid:0};b[220]={fld:"TXT_JS_EVENT",format:1,grid:0};b[221]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,
gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV20H_INIT_FLG",gxold:"OV20H_INIT_FLG",gxvar:"AV20H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV20H_INIT_FLG=a},v2z:function(a){gx.O.ZV20H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV20H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV20H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};
this.declareDomainHdlr(221,function(){});b[222]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_SRCH_FLG",gxz:"ZV23H_SRCH_FLG",gxold:"OV23H_SRCH_FLG",gxvar:"AV23H_SRCH_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV23H_SRCH_FLG=a},v2z:function(a){gx.O.ZV23H_SRCH_FLG=a},v2c:function(){gx.fn.setControlValue("vH_SRCH_FLG",gx.O.AV23H_SRCH_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV23H_SRCH_FLG=
this.val()},val:function(){return gx.fn.getControlValue("vH_SRCH_FLG")},nac:gx.falseFn};this.declareDomainHdlr(222,function(){});b[223]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV21H_KNGN_FLG",gxold:"OV21H_KNGN_FLG",gxvar:"AV21H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV21H_KNGN_FLG=a},v2z:function(a){gx.O.ZV21H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV21H_KNGN_FLG,
0)},c2v:function(){gx.O.AV21H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[224]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_DOM_CD",gxz:"ZV18H_DOM_CD",gxold:"OV18H_DOM_CD",gxvar:"AV18H_DOM_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV18H_DOM_CD=a},v2z:function(a){gx.O.ZV18H_DOM_CD=a},v2c:function(){gx.fn.setControlValue("vH_DOM_CD",gx.O.AV18H_DOM_CD,0)},c2v:function(){gx.O.AV18H_DOM_CD=
this.val()},val:function(){return gx.fn.getControlValue("vH_DOM_CD")},nac:gx.falseFn};b[225]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_DOM_VAR_NM",gxz:"ZV19H_DOM_VAR_NM",gxold:"OV19H_DOM_VAR_NM",gxvar:"AV19H_DOM_VAR_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV19H_DOM_VAR_NM=a},v2z:function(a){gx.O.ZV19H_DOM_VAR_NM=a},v2c:function(){gx.fn.setControlValue("vH_DOM_VAR_NM",gx.O.AV19H_DOM_VAR_NM,0)},c2v:function(){gx.O.AV19H_DOM_VAR_NM=
this.val()},val:function(){return gx.fn.getControlValue("vH_DOM_VAR_NM")},nac:gx.falseFn};b[226]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_VAR_DESC",gxz:"ZV24H_VAR_DESC",gxold:"OV24H_VAR_DESC",gxvar:"AV24H_VAR_DESC",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV24H_VAR_DESC=a},v2z:function(a){gx.O.ZV24H_VAR_DESC=a},v2c:function(){gx.fn.setControlValue("vH_VAR_DESC",gx.O.AV24H_VAR_DESC,0)},c2v:function(){gx.O.AV24H_VAR_DESC=
this.val()},val:function(){return gx.fn.getControlValue("vH_VAR_DESC")},nac:gx.falseFn};b[227]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_SORT",gxz:"ZV22H_SORT",gxold:"OV22H_SORT",gxvar:"AV22H_SORT",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV22H_SORT=a},v2z:function(a){gx.O.ZV22H_SORT=a},v2c:function(){gx.fn.setControlValue("vH_SORT",gx.O.AV22H_SORT,0)},c2v:function(){gx.O.AV22H_SORT=this.val()},val:function(){return gx.fn.getControlValue("vH_SORT")},
nac:gx.falseFn};b[228]={fld:"TABLE7",grid:0};b[231]={fld:"TEXTBLOCK1",format:0,grid:0};b[233]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLMAX_ROW",gxz:"ZV49GXV1",gxold:"OV49GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=gx.num.intval(a)},v2z:function(a){gx.O.ZV49GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLMAX_ROW",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},
val:function(){return gx.fn.getIntegerValue("CTLMAX_ROW",",")},nac:gx.falseFn};this.OV14D_LINE=this.ZV14D_LINE=this.AV14D_LINE=this.OV15D_SORT=this.ZV15D_SORT=this.AV15D_SORT=this.OV16D_VAR_DESC=this.ZV16D_VAR_DESC=this.AV16D_VAR_DESC=this.OV9D_DOM_VAR_NM=this.ZV9D_DOM_VAR_NM=this.AV9D_DOM_VAR_NM=this.OV7D_DOM_CD=this.ZV7D_DOM_CD=this.AV7D_DOM_CD="";this.OV11D_GRD_LINE=this.ZV11D_GRD_LINE=0;this.OV41D_GRD_VAR_DESC=this.ZV41D_GRD_VAR_DESC=this.OV40D_GRD_DOM_VAR_NM=this.ZV40D_GRD_DOM_VAR_NM=this.OV39D_GRD_DOM_CD=
this.ZV39D_GRD_DOM_CD="";this.OV42D_GRD_ORDER=this.ZV42D_GRD_ORDER=0;this.OV22H_SORT=this.ZV22H_SORT=this.AV22H_SORT=this.OV24H_VAR_DESC=this.ZV24H_VAR_DESC=this.AV24H_VAR_DESC=this.OV19H_DOM_VAR_NM=this.ZV19H_DOM_VAR_NM=this.AV19H_DOM_VAR_NM=this.OV18H_DOM_CD=this.ZV18H_DOM_CD=this.AV18H_DOM_CD=this.OV21H_KNGN_FLG=this.ZV21H_KNGN_FLG=this.AV21H_KNGN_FLG=this.OV23H_SRCH_FLG=this.ZV23H_SRCH_FLG=this.AV23H_SRCH_FLG=this.OV20H_INIT_FLG=this.ZV20H_INIT_FLG=this.AV20H_INIT_FLG=this.OV10D_GRD_DEL=this.ZV10D_GRD_DEL=
this.OV43D_GRD_VERSION=this.ZV43D_GRD_VERSION="";this.OV49GXV1=this.ZV49GXV1=this.GXV1=0;this.AV22H_SORT=this.AV24H_VAR_DESC=this.AV19H_DOM_VAR_NM=this.AV18H_DOM_CD=this.AV21H_KNGN_FLG=this.AV23H_SRCH_FLG=this.AV20H_INIT_FLG=this.AV14D_LINE=this.AV15D_SORT=this.AV16D_VAR_DESC=this.AV9D_DOM_VAR_NM=this.AV7D_DOM_CD="";this.AV27P_MOVE_KBN_2=this.AV26P_MOVE_KBN=this.GXV1=0;this.AV25P_DOM_CD="";this.AV11D_GRD_LINE=0;this.AV41D_GRD_VAR_DESC=this.AV40D_GRD_DOM_VAR_NM=this.AV39D_GRD_DOM_CD="";this.AV42D_GRD_ORDER=
0;this.A359TBM03_DEL_FLG=this.A59TBM03_DOM_CD=this.A60TBM03_DOM_VAR_NM=this.A346TBM03_VAR_DESC=this.AV10D_GRD_DEL=this.AV43D_GRD_VERSION="";this.A61TBM03_ORDER=0;this.AV6C_TAM02_APP_ID=this.AV51Pgmname=this.A49TBM02_DOM_CD=this.A611TBM02_DOM_JNM=this.A932TBM03_VERSION="";this.AV17H_A_PAGING_SDT={};this.AV30W_A821_JS="";this.AV44SD_A212_SD01_LIST_C=[];this.AV34W_ERRFLG=false;this.Events={e111w2_client:["'BTN_REG'",true],e121w2_client:["'BTN_CSV'",true],e131w2_client:["'BTN_SRCH'",true],e141w2_client:["'BTN_CLER'",
true],e151w2_client:["'BTN_EDIT'",true],e161w2_client:["'BTN_IMPORT_CDISC_ITEM'",true],e171w2_client:["'BTN_DOMAIN'",true],e351w2_client:["'BTN_SEL'",true],e181w2_client:["'PAGE_FIRST'",true],e191w2_client:["'PAGE_LAST'",true],e201w2_client:["'PAGE_BACK'",true],e211w2_client:["'PAGE_NEXT'",true],e221w2_client:["'PAGE01'",true],e231w2_client:["'PAGE02'",true],e241w2_client:["'PAGE03'",true],e251w2_client:["'PAGE04'",true],e261w2_client:["'PAGE05'",true],e271w2_client:["'PAGE06'",true],e281w2_client:["'PAGE07'",
true],e291w2_client:["'PAGE08'",true],e301w2_client:["'PAGE09'",true],e311w2_client:["'PAGE10'",true],e361w2_client:["ENTER",true],e371w2_client:["CANCEL",true]};this.setVCMap("AV51Pgmname","vPGMNAME",0,"char");this.setVCMap("AV6C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV26P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV27P_MOVE_KBN_2","vP_MOVE_KBN_2",0,"int");this.setVCMap("AV25P_DOM_CD","vP_DOM_CD",0,"svchar");this.setVCMap("AV17H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");
this.setVCMap("A49TBM02_DOM_CD","TBM02_DOM_CD",0,"svchar");this.setVCMap("A611TBM02_DOM_JNM","TBM02_DOM_JNM",0,"svchar");this.setVCMap("AV30W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV44SD_A212_SD01_LIST_C","vSD_A212_SD01_LIST_C",0,"CollA212_SD01_LIST.A212_SD01_LISTItem");this.setVCMap("AV34W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("A60TBM03_DOM_VAR_NM","TBM03_DOM_VAR_NM",0,"svchar");this.setVCMap("A932TBM03_VERSION","TBM03_VERSION",0,"svchar");this.setVCMap("A59TBM03_DOM_CD","TBM03_DOM_CD",
0,"svchar");this.setVCMap("A61TBM03_ORDER","TBM03_ORDER",0,"int");this.setVCMap("A346TBM03_VAR_DESC","TBM03_VAR_DESC",0,"svchar");this.setVCMap("A359TBM03_DEL_FLG","TBM03_DEL_FLG",0,"svchar");this.setVCMap("AV51Pgmname","vPGMNAME",0,"char");this.setVCMap("AV6C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV26P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV27P_MOVE_KBN_2","vP_MOVE_KBN_2",0,"int");this.setVCMap("AV25P_DOM_CD","vP_DOM_CD",0,"svchar");this.setVCMap("AV17H_A_PAGING_SDT",
"vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("A49TBM02_DOM_CD","TBM02_DOM_CD",0,"svchar");this.setVCMap("A611TBM02_DOM_JNM","TBM02_DOM_JNM",0,"svchar");this.setVCMap("AV30W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV44SD_A212_SD01_LIST_C","vSD_A212_SD01_LIST_C",0,"CollA212_SD01_LIST.A212_SD01_LISTItem");this.setVCMap("AV34W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("A60TBM03_DOM_VAR_NM","TBM03_DOM_VAR_NM",0,"svchar");this.setVCMap("A932TBM03_VERSION","TBM03_VERSION",0,"svchar");
this.setVCMap("A59TBM03_DOM_CD","TBM03_DOM_CD",0,"svchar");this.setVCMap("A61TBM03_ORDER","TBM03_ORDER",0,"int");this.setVCMap("A346TBM03_VAR_DESC","TBM03_VAR_DESC",0,"svchar");this.setVCMap("A359TBM03_DEL_FLG","TBM03_DEL_FLG",0,"svchar");c.addRefreshingVar(this.GXValidFnc[221]);c.addRefreshingVar({rfrVar:"AV51Pgmname"});c.addRefreshingVar({rfrVar:"AV6C_TAM02_APP_ID"});c.addRefreshingVar({rfrVar:"AV26P_MOVE_KBN"});c.addRefreshingVar(this.GXValidFnc[38]);c.addRefreshingVar({rfrVar:"AV27P_MOVE_KBN_2"});
c.addRefreshingVar(this.GXValidFnc[42]);c.addRefreshingVar({rfrVar:"AV25P_DOM_CD"});c.addRefreshingVar({rfrVar:"AV17H_A_PAGING_SDT"});c.addRefreshingVar({rfrVar:"A49TBM02_DOM_CD"});c.addRefreshingVar({rfrVar:"A611TBM02_DOM_JNM"});c.addRefreshingVar(this.GXValidFnc[223]);c.addRefreshingVar({rfrVar:"AV30W_A821_JS"});c.addRefreshingVar({rfrVar:"AV44SD_A212_SD01_LIST_C"});c.addRefreshingVar(this.GXValidFnc[222]);c.addRefreshingVar({rfrVar:"AV34W_ERRFLG"});c.addRefreshingVar(this.GXValidFnc[46]);c.addRefreshingVar(this.GXValidFnc[50]);
c.addRefreshingVar(this.GXValidFnc[224]);c.addRefreshingVar(this.GXValidFnc[225]);c.addRefreshingVar(this.GXValidFnc[226]);c.addRefreshingVar(this.GXValidFnc[227]);c.addRefreshingVar({rfrVar:"A60TBM03_DOM_VAR_NM"});c.addRefreshingVar({rfrVar:"A932TBM03_VERSION"});c.addRefreshingVar({rfrVar:"A59TBM03_DOM_CD"});c.addRefreshingVar({rfrVar:"A61TBM03_ORDER"});c.addRefreshingVar({rfrVar:"A346TBM03_VAR_DESC"});c.addRefreshingVar({rfrVar:"A359TBM03_DEL_FLG"});this.addBCProperty("H_a_paging_sdt",["MAX_ROW"],
this.GXValidFnc[233],"AV17H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0215",lvl:1})});gx.setParentObj(new a212_wp01_cdisc_item_list);
