gx.evt.autoSkip=!1;
gx.define("b402_wp01_study_list",!1,function(){this.ServerClass="b402_wp01_study_list";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110x2_client");this.addKeyListener("5","e120x2_client");this.addKeyListener("6","e130x2_client");this.SetStandaloneVars=function(){this.AV34Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV5C_APP_ID=gx.fn.getControlValue("vC_APP_ID");this.AV17P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",
",");this.AV10H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.AV24W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG")};this.s122_client=function(){this.AV8D_STATUS=this.AV9D_STUDY_NM="";this.AV7D_DEL_FLG="0";this.AV15H_STATUS=this.AV16H_STUDY_NM="";this.AV11H_DEL_FLG="0";this.AV10H_A_PAGING_SDT.PAGE_NO=1;this.AV14H_SRCH_FLG="0";this.AV19W_A819_JS=""};this.s202_client=function(){this.AV16H_STUDY_NM=this.AV9D_STUDY_NM;this.AV15H_STATUS=this.AV8D_STATUS;this.AV11H_DEL_FLG=this.AV7D_DEL_FLG};this.s172_client=
function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+
"<\/script>")};this.e110x2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e120x2_client=function(){this.executeServerEvent("'BTN_SRCH'",true)};this.e130x2_client=function(){this.executeServerEvent("'BTN_CLER'",true)};this.e300x2_client=function(a){this.executeServerEvent("'BTN_SEL'",true,a)};this.e140x2_client=function(){this.executeServerEvent("'PAGE_FIRST'",true)};this.e150x2_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};this.e160x2_client=function(){this.executeServerEvent("'PAGE_BACK'",
true)};this.e170x2_client=function(){this.executeServerEvent("'PAGE_NEXT'",true)};this.e180x2_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e190x2_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e200x2_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e210x2_client=function(){this.executeServerEvent("'PAGE04'",true)};this.e220x2_client=function(){this.executeServerEvent("'PAGE05'",true)};this.e230x2_client=function(){this.executeServerEvent("'PAGE06'",
true)};this.e240x2_client=function(){this.executeServerEvent("'PAGE07'",true)};this.e250x2_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e260x2_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e270x2_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e320x2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e330x2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,18,21,24,27,
29,31,33,35,37,40,43,46,52,55,58,61,64,67,70,73,76,79,82,85,88,91,94,97,100,103,106,109,112,115,118,121,124,127,130,133,136,139,142,145,151,155,157,159,165,168,170,171,172,174,176,181,184,185,186,187,188,189,190,191];this.GXLastCtrlId=191;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",162,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"b402_wp01_study_list",[],true,1,true,true,10,false,false,false,"",935,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,"",
false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","","","","","","","","","");c.startTable("Tbl_grid_header2",165,"935px");c.addHtmlCode("<tbody>");c.startRow("","","","","","");c.startCell("","center","","","","","45px","","","");c.addTextBlock("BTN_SEL","e300x2_client");c.endCell();c.startCell("","","","","","","","","","");c.addSingleLineEdit(63,170,"TBM21_STUDY_ID","","","TBM21_STUDY_ID","int",10,"chr",10,10,"right",null,[],63,"TBM21_STUDY_ID",true,0,false,false,"ReadonlyAttribute",
1,"");c.addSingleLineEdit("D_space",171,"vD_SPACE","","","D_SPACE","char",1,"chr",1,1,"left",null,[],"D_space","D_SPACE",true,0,false,false,"ReadonlyAttribute",1,"");c.addSingleLineEdit(367,172,"TBM21_STUDY_NM","","","TBM21_STUDY_NM","svchar",80,"chr",100,80,"left",null,[],367,"TBM21_STUDY_NM",true,0,false,false,"ReadonlyAttribute",1,"");c.endCell();c.startCell("","","","","","","100px","","","");c.addComboBox(607,174,"TBM21_STATUS","","TBM21_STATUS","svchar",null,0,true,false,1,"chr","");c.endCell();
c.startCell("","","","","","","100px","","","");c.addComboBox(369,176,"TBM21_DEL_FLG","","TBM21_DEL_FLG","svchar",null,0,true,false,1,"chr","");c.endCell();c.endRow();c.addHtmlCode("</tbody>");c.endTable();c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[6]={fld:"TABLE2",grid:0};b[12]={fld:"TBL_UPD_BTNSET",grid:0};b[15]={fld:"TXT_BTN_REG",format:0,grid:0};b[18]={fld:"TABLE3",grid:0};b[21]={fld:"TABLE4",grid:0};b[24]={fld:"TABLE10",grid:0};b[27]={fld:"TEXTBLOCK16",format:0,grid:0};
b[29]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_STUDY_NM",gxz:"ZV9D_STUDY_NM",gxold:"OV9D_STUDY_NM",gxvar:"AV9D_STUDY_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9D_STUDY_NM=a},v2z:function(a){gx.O.ZV9D_STUDY_NM=a},v2c:function(){gx.fn.setControlValue("vD_STUDY_NM",gx.O.AV9D_STUDY_NM,0)},c2v:function(){gx.O.AV9D_STUDY_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_STUDY_NM")},nac:gx.falseFn};
b[31]={fld:"TEXTBLOCK18",format:0,grid:0};b[33]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_STATUS",gxz:"ZV8D_STATUS",gxold:"OV8D_STATUS",gxvar:"AV8D_STATUS",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",v2v:function(a){gx.O.AV8D_STATUS=a},v2z:function(a){gx.O.ZV8D_STATUS=a},v2c:function(){gx.fn.setRadioValue("vD_STATUS",gx.O.AV8D_STATUS)},c2v:function(){gx.O.AV8D_STATUS=this.val()},val:function(){return gx.fn.getControlValue("vD_STATUS")},
nac:gx.falseFn};b[35]={fld:"TEXTBLOCK84",format:0,grid:0};b[37]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_DEL_FLG",gxz:"ZV7D_DEL_FLG",gxold:"OV7D_DEL_FLG",gxvar:"AV7D_DEL_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",v2v:function(a){gx.O.AV7D_DEL_FLG=a},v2z:function(a){gx.O.ZV7D_DEL_FLG=a},v2c:function(){gx.fn.setRadioValue("vD_DEL_FLG",gx.O.AV7D_DEL_FLG)},c2v:function(){gx.O.AV7D_DEL_FLG=this.val()},val:function(){return gx.fn.getControlValue("vD_DEL_FLG")},
nac:gx.falseFn};b[40]={fld:"TABLE9",grid:0};b[43]={fld:"TEXTBLOCK45",format:0,grid:0};b[46]={fld:"TEXTBLOCK44",format:0,grid:0};b[52]={fld:"TBL_LIST",grid:0};b[55]={fld:"TBL_PAGE_AREA",grid:0};b[58]={fld:"TXT_REC_CNT",format:0,grid:0};b[61]={fld:"TBL_PAGE",grid:0};b[64]={fld:"TBL_FIRST",grid:0};b[67]={fld:"TXT_FIRST",format:0,grid:0};b[70]={fld:"TBL_BACK",grid:0};b[73]={fld:"TXT_BACK",format:0,grid:0};b[76]={fld:"TBL_PAGE01",grid:0};b[79]={fld:"TXT_PAGE01",format:0,grid:0};b[82]={fld:"TBL_PAGE02",
grid:0};b[85]={fld:"TXT_PAGE02",format:0,grid:0};b[88]={fld:"TBL_PAGE03",grid:0};b[91]={fld:"TXT_PAGE03",format:0,grid:0};b[94]={fld:"TBL_PAGE04",grid:0};b[97]={fld:"TXT_PAGE04",format:0,grid:0};b[100]={fld:"TBL_PAGE05",grid:0};b[103]={fld:"TXT_PAGE05",format:0,grid:0};b[106]={fld:"TBL_PAGE06",grid:0};b[109]={fld:"TXT_PAGE06",format:0,grid:0};b[112]={fld:"TBL_PAGE07",grid:0};b[115]={fld:"TXT_PAGE07",format:0,grid:0};b[118]={fld:"TBL_PAGE08",grid:0};b[121]={fld:"TXT_PAGE08",format:0,grid:0};b[124]=
{fld:"TBL_PAGE09",grid:0};b[127]={fld:"TXT_PAGE09",format:0,grid:0};b[130]={fld:"TBL_PAGE10",grid:0};b[133]={fld:"TXT_PAGE10",format:0,grid:0};b[136]={fld:"TBL_NEXT",grid:0};b[139]={fld:"TXT_NEXT",format:0,grid:0};b[142]={fld:"TBL_LAST",grid:0};b[145]={fld:"TXT_LAST",format:0,grid:0};b[151]={fld:"TBL_GRID_HEADER",grid:0};b[155]={fld:"TEXTBLOCK13",format:0,grid:0};b[157]={fld:"TEXTBLOCK43",format:0,grid:0};b[159]={fld:"TEXTBLOCK46",format:0,grid:0};b[165]={fld:"TBL_GRID_HEADER2",grid:162};b[168]={fld:"BTN_SEL",
format:0,grid:162};b[170]={lvl:2,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM21_STUDY_ID",gxz:"Z63TBM21_STUDY_ID",gxold:"O63TBM21_STUDY_ID",gxvar:"A63TBM21_STUDY_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A63TBM21_STUDY_ID=gx.num.intval(a)},v2z:function(a){gx.O.Z63TBM21_STUDY_ID=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TBM21_STUDY_ID",a||gx.fn.currentGridRowImpl(162),
gx.O.A63TBM21_STUDY_ID,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A63TBM21_STUDY_ID=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TBM21_STUDY_ID",a||gx.fn.currentGridRowImpl(162),",")},nac:gx.falseFn};b[171]={lvl:2,type:"char",len:1,dec:0,sign:false,ro:0,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_SPACE",gxz:"ZV27D_SPACE",gxold:"OV27D_SPACE",gxvar:"AV27D_SPACE",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV27D_SPACE=a},v2z:function(a){gx.O.ZV27D_SPACE=a},v2c:function(a){gx.fn.setGridControlValue("vD_SPACE",a||gx.fn.currentGridRowImpl(162),gx.O.AV27D_SPACE,0)},c2v:function(){gx.O.AV27D_SPACE=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_SPACE",a||gx.fn.currentGridRowImpl(162))},nac:gx.falseFn};b[172]={lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,
rgrid:[],fld:"TBM21_STUDY_NM",gxz:"Z367TBM21_STUDY_NM",gxold:"O367TBM21_STUDY_NM",gxvar:"A367TBM21_STUDY_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A367TBM21_STUDY_NM=a},v2z:function(a){gx.O.Z367TBM21_STUDY_NM=a},v2c:function(a){gx.fn.setGridControlValue("TBM21_STUDY_NM",a||gx.fn.currentGridRowImpl(162),gx.O.A367TBM21_STUDY_NM,0)},c2v:function(){gx.O.A367TBM21_STUDY_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("TBM21_STUDY_NM",
a||gx.fn.currentGridRowImpl(162))},nac:gx.falseFn};b[174]={lvl:2,type:"svchar",len:1,dec:0,sign:false,ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM21_STATUS",gxz:"Z607TBM21_STATUS",gxold:"O607TBM21_STATUS",gxvar:"A607TBM21_STATUS",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:"text",v2v:function(a){gx.O.A607TBM21_STATUS=a},v2z:function(a){gx.O.Z607TBM21_STATUS=a},v2c:function(a){gx.fn.setGridComboBoxValue("TBM21_STATUS",a||gx.fn.currentGridRowImpl(162),
gx.O.A607TBM21_STATUS)},c2v:function(){gx.O.A607TBM21_STATUS=this.val()},val:function(a){return gx.fn.getGridControlValue("TBM21_STATUS",a||gx.fn.currentGridRowImpl(162))},nac:gx.falseFn};b[176]={lvl:2,type:"svchar",len:1,dec:0,sign:false,ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM21_DEL_FLG",gxz:"Z369TBM21_DEL_FLG",gxold:"O369TBM21_DEL_FLG",gxvar:"A369TBM21_DEL_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:"text",v2v:function(a){gx.O.A369TBM21_DEL_FLG=
a},v2z:function(a){gx.O.Z369TBM21_DEL_FLG=a},v2c:function(a){gx.fn.setGridComboBoxValue("TBM21_DEL_FLG",a||gx.fn.currentGridRowImpl(162),gx.O.A369TBM21_DEL_FLG);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A369TBM21_DEL_FLG=this.val()},val:function(a){return gx.fn.getGridControlValue("TBM21_DEL_FLG",a||gx.fn.currentGridRowImpl(162))},nac:gx.falseFn};b[181]={fld:"TBL_HIDDEN",grid:0};b[184]={fld:"TXT_JS_EVENT",format:1,grid:0};b[185]={lvl:0,type:"svchar",len:1,dec:0,
sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV12H_INIT_FLG",gxold:"OV12H_INIT_FLG",gxvar:"AV12H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12H_INIT_FLG=a},v2z:function(a){gx.O.ZV12H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV12H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV12H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},
nac:gx.falseFn};this.declareDomainHdlr(185,function(){});b[186]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SRCH_FLG",gxz:"ZV14H_SRCH_FLG",gxold:"OV14H_SRCH_FLG",gxvar:"AV14H_SRCH_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV14H_SRCH_FLG=a},v2z:function(a){gx.O.ZV14H_SRCH_FLG=a},v2c:function(){gx.fn.setControlValue("vH_SRCH_FLG",gx.O.AV14H_SRCH_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},
c2v:function(){gx.O.AV14H_SRCH_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_SRCH_FLG")},nac:gx.falseFn};this.declareDomainHdlr(186,function(){});b[187]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV13H_KNGN_FLG",gxold:"OV13H_KNGN_FLG",gxvar:"AV13H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_KNGN_FLG=a},v2z:function(a){gx.O.ZV13H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",
gx.O.AV13H_KNGN_FLG,0)},c2v:function(){gx.O.AV13H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[188]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_DEL_FLG",gxz:"ZV11H_DEL_FLG",gxold:"OV11H_DEL_FLG",gxvar:"AV11H_DEL_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11H_DEL_FLG=a},v2z:function(a){gx.O.ZV11H_DEL_FLG=a},v2c:function(){gx.fn.setControlValue("vH_DEL_FLG",
gx.O.AV11H_DEL_FLG,0)},c2v:function(){gx.O.AV11H_DEL_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_DEL_FLG")},nac:gx.falseFn};b[189]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_STUDY_NM",gxz:"ZV16H_STUDY_NM",gxold:"OV16H_STUDY_NM",gxvar:"AV16H_STUDY_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV16H_STUDY_NM=a},v2z:function(a){gx.O.ZV16H_STUDY_NM=a},v2c:function(){gx.fn.setControlValue("vH_STUDY_NM",
gx.O.AV16H_STUDY_NM,0)},c2v:function(){gx.O.AV16H_STUDY_NM=this.val()},val:function(){return gx.fn.getControlValue("vH_STUDY_NM")},nac:gx.falseFn};b[190]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_STATUS",gxz:"ZV15H_STATUS",gxold:"OV15H_STATUS",gxvar:"AV15H_STATUS",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_STATUS=a},v2z:function(a){gx.O.ZV15H_STATUS=a},v2c:function(){gx.fn.setControlValue("vH_STATUS",
gx.O.AV15H_STATUS,0)},c2v:function(){gx.O.AV15H_STATUS=this.val()},val:function(){return gx.fn.getControlValue("vH_STATUS")},nac:gx.falseFn};b[191]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLREC_CNT",gxz:"ZV32GXV1",gxold:"OV32GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=gx.num.intval(a)},v2z:function(a){gx.O.ZV32GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",
gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",",")},nac:gx.falseFn};this.OV7D_DEL_FLG=this.ZV7D_DEL_FLG=this.AV7D_DEL_FLG=this.OV8D_STATUS=this.ZV8D_STATUS=this.AV8D_STATUS=this.OV9D_STUDY_NM=this.ZV9D_STUDY_NM=this.AV9D_STUDY_NM="";this.O63TBM21_STUDY_ID=this.Z63TBM21_STUDY_ID=0;this.OV15H_STATUS=this.ZV15H_STATUS=this.AV15H_STATUS=this.OV16H_STUDY_NM=this.ZV16H_STUDY_NM=this.AV16H_STUDY_NM=this.OV11H_DEL_FLG=this.ZV11H_DEL_FLG=
this.AV11H_DEL_FLG=this.OV13H_KNGN_FLG=this.ZV13H_KNGN_FLG=this.AV13H_KNGN_FLG=this.OV14H_SRCH_FLG=this.ZV14H_SRCH_FLG=this.AV14H_SRCH_FLG=this.OV12H_INIT_FLG=this.ZV12H_INIT_FLG=this.AV12H_INIT_FLG=this.O369TBM21_DEL_FLG=this.Z369TBM21_DEL_FLG=this.O607TBM21_STATUS=this.Z607TBM21_STATUS=this.O367TBM21_STUDY_NM=this.Z367TBM21_STUDY_NM=this.OV27D_SPACE=this.ZV27D_SPACE="";this.OV32GXV1=this.ZV32GXV1=this.GXV1=0;this.AV15H_STATUS=this.AV16H_STUDY_NM=this.AV11H_DEL_FLG=this.AV13H_KNGN_FLG=this.AV14H_SRCH_FLG=
this.AV12H_INIT_FLG=this.AV7D_DEL_FLG=this.AV8D_STATUS=this.AV9D_STUDY_NM="";this.A63TBM21_STUDY_ID=this.AV17P_MOVE_KBN=this.GXV1=0;this.AV5C_APP_ID=this.AV34Pgmname=this.A369TBM21_DEL_FLG=this.A607TBM21_STATUS=this.A367TBM21_STUDY_NM=this.AV27D_SPACE="";this.AV10H_A_PAGING_SDT={};this.AV24W_ERRFLG=false;this.AV19W_A819_JS="";this.Events={e110x2_client:["'BTN_REG'",true],e120x2_client:["'BTN_SRCH'",true],e130x2_client:["'BTN_CLER'",true],e300x2_client:["'BTN_SEL'",true],e140x2_client:["'PAGE_FIRST'",
true],e150x2_client:["'PAGE_LAST'",true],e160x2_client:["'PAGE_BACK'",true],e170x2_client:["'PAGE_NEXT'",true],e180x2_client:["'PAGE01'",true],e190x2_client:["'PAGE02'",true],e200x2_client:["'PAGE03'",true],e210x2_client:["'PAGE04'",true],e220x2_client:["'PAGE05'",true],e230x2_client:["'PAGE06'",true],e240x2_client:["'PAGE07'",true],e250x2_client:["'PAGE08'",true],e260x2_client:["'PAGE09'",true],e270x2_client:["'PAGE10'",true],e320x2_client:["ENTER",true],e330x2_client:["CANCEL",true]};this.setVCMap("AV34Pgmname",
"vPGMNAME",0,"char");this.setVCMap("AV5C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV17P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV10H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV24W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV34Pgmname","vPGMNAME",0,"char");this.setVCMap("AV5C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV17P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV10H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV24W_ERRFLG",
"vW_ERRFLG",0,"boolean");c.addRefreshingVar(this.GXValidFnc[186]);c.addRefreshingVar(this.GXValidFnc[188]);c.addRefreshingVar(this.GXValidFnc[189]);c.addRefreshingVar(this.GXValidFnc[190]);c.addRefreshingVar({rfrVar:"AV27D_SPACE",rfrProp:"Value",gxAttId:"D_space"});c.addRefreshingVar(this.GXValidFnc[185]);c.addRefreshingVar({rfrVar:"AV34Pgmname"});c.addRefreshingVar({rfrVar:"AV5C_APP_ID"});c.addRefreshingVar({rfrVar:"AV17P_MOVE_KBN"});c.addRefreshingVar({rfrVar:"AV10H_A_PAGING_SDT"});c.addRefreshingVar(this.GXValidFnc[187]);
c.addRefreshingVar({rfrVar:"AV24W_ERRFLG"});c.addRefreshingVar(this.GXValidFnc[29]);c.addRefreshingVar(this.GXValidFnc[33]);c.addRefreshingVar(this.GXValidFnc[37]);this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[191],"AV10H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0179",lvl:1})});gx.setParentObj(new b402_wp01_study_list);
