gx.evt.autoSkip=!1;
gx.define("b402_wp02_study_reg",!1,function(){this.ServerClass="b402_wp02_study_reg";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110w2_client");this.addKeyListener("4","e120w2_client");this.addKeyListener("5","e130w2_client");this.addKeyListener("6","e140w2_client");this.addKeyListener("11","e150w2_client");this.SetStandaloneVars=function(){this.AV13P_STUDY_ID=gx.fn.getIntegerValue("vP_STUDY_ID",",")};
this.s162_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");if(""!=this.AV20W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV20W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");""!=this.AV19W_A819_JS&&
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV19W_A819_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.s182_client=function(){gx.fn.setCtrlProperty("CTLTBM21_STUDY_ID",
"Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTBM21_OUTER_STUDY_ID","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTBM21_STUDY_NM","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTBM21_PROC_NM","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTBM21_NOTE","Backcolor",gx.color.rgb(255,255,255))};this.s192_client=function(){for(this.AV48GXV13=1;this.AV48GXV13<=this.AV14W_A_CHK_RESULT_SDT.length;){this.AV15W_A_CHK_RESULT_SDT_ITEM=this.AV14W_A_CHK_RESULT_SDT[this.AV48GXV13-
1];this.s202_client();this.AV48GXV13=this.AV48GXV13+1}};this.s202_client=function(){if(this.AV15W_A_CHK_RESULT_SDT_ITEM.ID=="TBM21_STUDY_ID"){gx.fn.setCtrlProperty("CTLTBM21_STUDY_ID","Backcolor",gx.color.rgb(255,192,203));this.AV15W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM21_STUDY_ID")}else if(this.AV15W_A_CHK_RESULT_SDT_ITEM.ID=="TBM21_STUDY_NM"){gx.fn.setCtrlProperty("CTLTBM21_STUDY_NM","Backcolor",gx.color.rgb(255,192,203));this.AV15W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM21_STUDY_NM")}else if(this.AV15W_A_CHK_RESULT_SDT_ITEM.ID==
"TBM21_OUTER_STUDY_ID"){gx.fn.setCtrlProperty("CTLTBM21_OUTER_STUDY_ID","Backcolor",gx.color.rgb(255,192,203));this.AV15W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM21_OUTER_STUDY_ID")}else if(this.AV15W_A_CHK_RESULT_SDT_ITEM.ID=="TBM21_PROC_NM"){gx.fn.setCtrlProperty("CTLTBM21_PROC_NM","Backcolor",gx.color.rgb(255,192,203));this.AV15W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM21_PROC_NM")}else if(this.AV15W_A_CHK_RESULT_SDT_ITEM.ID=="TBM21_NOTE"){gx.fn.setCtrlProperty("CTLTBM21_NOTE",
"Backcolor",gx.color.rgb(255,192,203));this.AV15W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM21_NOTE")}else this.AV15W_A_CHK_RESULT_SDT_ITEM.ID=="TBM21_STATUS"&&this.AV15W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM21_STATUS")};this.e110w2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e180w2_client=function(){this.executeServerEvent("'BTN_REG_EXEC'",true)};this.e120w2_client=function(){this.executeServerEvent("'BTN_UPD'",true)};this.e190w2_client=
function(){this.executeServerEvent("'BTN_UPD_EXEC'",true)};this.e130w2_client=function(){this.executeServerEvent("'BTN_CSV'",true)};this.e140w2_client=function(){this.executeServerEvent("'BTN_DLT'",true)};this.e200w2_client=function(){this.executeServerEvent("'BTN_DLT_EXEC'",true)};this.e150w2_client=function(){this.executeServerEvent("'BTN_CAN'",true)};this.e210w2_client=function(){this.executeServerEvent("'BTN_STAFF'",true)};this.e220w2_client=function(){this.executeServerEvent("'BTN_CRF_DETAIL'",
true)};this.e230w2_client=function(){this.executeServerEvent("'BTN_SITE'",true)};this.e240w2_client=function(){this.executeServerEvent("'BTN_CRF_COND'",true)};this.e250w2_client=function(){this.executeServerEvent("'BTN_CRF_DOMAIN'",true)};this.e270w2_client=function(){this.executeServerEvent("ENTER",true)};this.e280w2_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,17,19,21,23,26,32,37,38,40,42,44,47,48,50,53,55,57,59,62,64,67,69,70,75,
77,80,82,84,86,89,91,94,96,99,101,103,105,109,112,114,117,119,124,126,128,130,133,135,137,139,142,144,146,148,153,156,157,158,159,160,161,162];this.GXLastCtrlId=162;a[2]={fld:"TABLE1",grid:0};a[6]={fld:"TABLE2",grid:0};a[12]={fld:"TBL_UPD_BTNSET",grid:0};a[15]={fld:"TXT_BTN_REG",format:0,grid:0};a[17]={fld:"TXT_BTN_UPD",format:0,grid:0};a[19]={fld:"TXT_BTN_CSV",format:0,grid:0};a[21]={fld:"TXT_BTN_DLT",format:0,grid:0};a[23]={fld:"TXT_BTN_CAN",format:0,grid:0};a[26]={fld:"TABLE4",grid:0};a[32]={fld:"TABLE5",
grid:0};a[37]={fld:"IMAGE6",grid:0};a[38]={fld:"TEXTBLOCK63",format:0,grid:0};a[40]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_STUDY_ID",gxz:"ZV33GXV1",gxold:"OV33GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=gx.num.intval(a)},v2z:function(a){gx.O.ZV33GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLTBM21_STUDY_ID",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},
val:function(){return gx.fn.getIntegerValue("CTLTBM21_STUDY_ID",",")},nac:gx.falseFn};a[42]={fld:"TEXTBLOCK68",format:0,grid:0};a[44]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_OUTER_STUDY_ID",gxz:"ZV34GXV2",gxold:"OV34GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV2=a},v2z:function(a){gx.O.ZV34GXV2=a},v2c:function(){gx.fn.setControlValue("CTLTBM21_OUTER_STUDY_ID",gx.O.GXV2,0)},c2v:function(){gx.O.GXV2=
this.val()},val:function(){return gx.fn.getControlValue("CTLTBM21_OUTER_STUDY_ID")},nac:gx.falseFn};a[47]={fld:"IMAGE7",grid:0};a[48]={fld:"TEXTBLOCK64",format:0,grid:0};a[50]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_STUDY_NM",gxz:"ZV35GXV3",gxold:"OV35GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV3=a},v2z:function(a){gx.O.ZV35GXV3=a},v2c:function(){gx.fn.setControlValue("CTLTBM21_STUDY_NM",
gx.O.GXV3,0)},c2v:function(){gx.O.GXV3=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM21_STUDY_NM")},nac:gx.falseFn};a[53]={fld:"TEXTBLOCK65",format:0,grid:0};a[55]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_STATUS",gxz:"ZV36GXV4",gxold:"OV36GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",v2v:function(a){gx.O.GXV4=a},v2z:function(a){gx.O.ZV36GXV4=a},v2c:function(){gx.fn.setRadioValue("CTLTBM21_STATUS",
gx.O.GXV4)},c2v:function(){gx.O.GXV4=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM21_STATUS")},nac:gx.falseFn};a[57]={fld:"TEXTBLOCK69",format:0,grid:0};a[59]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_PROC_NM",gxz:"ZV37GXV5",gxold:"OV37GXV5",gxvar:"GXV5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV5=a},v2z:function(a){gx.O.ZV37GXV5=a},v2c:function(){gx.fn.setControlValue("CTLTBM21_PROC_NM",
gx.O.GXV5,0)},c2v:function(){gx.O.GXV5=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM21_PROC_NM")},nac:gx.falseFn};a[62]={fld:"TEXTBLOCK79",format:0,grid:0};a[64]={lvl:0,type:"svchar",len:1E3,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_NOTE",gxz:"ZV38GXV6",gxold:"OV38GXV6",gxvar:"GXV6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV6=a},v2z:function(a){gx.O.ZV38GXV6=a},v2c:function(){gx.fn.setControlValue("CTLTBM21_NOTE",
gx.O.GXV6,0)},c2v:function(){gx.O.GXV6=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM21_NOTE")},nac:gx.falseFn};a[67]={fld:"TEXTBLOCK84",format:0,grid:0};a[69]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_DEL_FLG",gxz:"ZV39GXV7",gxold:"OV39GXV7",gxvar:"GXV7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",v2v:function(a){gx.O.GXV7=a},v2z:function(a){gx.O.ZV39GXV7=a},v2c:function(){gx.fn.setRadioValue("CTLTBM21_DEL_FLG",
gx.O.GXV7)},c2v:function(){gx.O.GXV7=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM21_DEL_FLG")},nac:gx.falseFn};a[70]={fld:"TABLE3",grid:0};a[75]={fld:"TEXTBLOCK85",format:0,grid:0};a[77]={fld:"TABLE6",grid:0};a[80]={fld:"TXT_SITE_INFO",format:0,grid:0};a[82]={fld:"TXT_BTN_SITE",format:0,grid:0};a[84]={fld:"TEXTBLOCK76",format:0,grid:0};a[86]={fld:"TABLE7",grid:0};a[89]={fld:"TXT_USER_INFO",format:0,grid:0};a[91]={fld:"TXT_BTN_STAFF",format:0,grid:0};a[94]={fld:"TEXTBLOCK77",format:0,
grid:0};a[96]={fld:"TABLE8",grid:0};a[99]={fld:"TXT_CRF_INFO",format:0,grid:0};a[101]={fld:"TXT_BTN_CRF_DETAIL",format:0,grid:0};a[103]={fld:"TEXTBLOCK78",format:0,grid:0};a[105]={fld:"TABLE9",grid:0};a[109]={fld:"TXT_BTN_CRF_COND",format:0,grid:0};a[112]={fld:"TEXTBLOCK80",format:0,grid:0};a[114]={fld:"TABLE10",grid:0};a[117]={fld:"TXT_DOMAIN_INFO",format:0,grid:0};a[119]={fld:"TXT_BTN_DOMAIN",format:0,grid:0};a[124]={fld:"TEXTBLOCK67",format:0,grid:0};a[126]={lvl:0,type:"dtime",len:10,dec:8,sign:false,
ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_CRT_DATETIME",gxz:"ZV40GXV8",gxold:"OV40GXV8",gxvar:"GXV8",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV8=gx.fn.toDatetimeValue(a,"Y4MD")},v2z:function(a){gx.O.ZV40GXV8=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTBM21_CRT_DATETIME",gx.O.GXV8,0)},c2v:function(){gx.O.GXV8=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTBM21_CRT_DATETIME")},
nac:gx.falseFn};a[128]={fld:"TEXTBLOCK72",format:0,grid:0};a[130]={lvl:0,type:"dtime",len:10,dec:8,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_UPD_DATETIME",gxz:"ZV41GXV9",gxold:"OV41GXV9",gxvar:"GXV9",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV9=gx.fn.toDatetimeValue(a,"Y4MD")},v2z:function(a){gx.O.ZV41GXV9=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTBM21_UPD_DATETIME",
gx.O.GXV9,0)},c2v:function(){gx.O.GXV9=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTBM21_UPD_DATETIME")},nac:gx.falseFn};a[133]={fld:"TEXTBLOCK70",format:0,grid:0};a[135]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_CRT_USER_NM",gxz:"ZV8D_CRT_USER_NM",gxold:"OV8D_CRT_USER_NM",gxvar:"AV8D_CRT_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV8D_CRT_USER_NM=a},v2z:function(a){gx.O.ZV8D_CRT_USER_NM=
a},v2c:function(){gx.fn.setControlValue("vD_CRT_USER_NM",gx.O.AV8D_CRT_USER_NM,1)},c2v:function(){gx.O.AV8D_CRT_USER_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_CRT_USER_NM")},nac:gx.falseFn};a[137]={fld:"TEXTBLOCK73",format:0,grid:0};a[139]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_UPD_USER_NM",gxz:"ZV9D_UPD_USER_NM",gxold:"OV9D_UPD_USER_NM",gxvar:"AV9D_UPD_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9D_UPD_USER_NM=
a},v2z:function(a){gx.O.ZV9D_UPD_USER_NM=a},v2c:function(){gx.fn.setControlValue("vD_UPD_USER_NM",gx.O.AV9D_UPD_USER_NM,1)},c2v:function(){gx.O.AV9D_UPD_USER_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_UPD_USER_NM")},nac:gx.falseFn};a[142]={fld:"TEXTBLOCK71",format:0,grid:0};a[144]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_CRT_PROG_NM",gxz:"ZV42GXV10",gxold:"OV42GXV10",gxvar:"GXV10",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",v2v:function(a){gx.O.GXV10=a},v2z:function(a){gx.O.ZV42GXV10=a},v2c:function(){gx.fn.setControlValue("CTLTBM21_CRT_PROG_NM",gx.O.GXV10,0)},c2v:function(){gx.O.GXV10=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM21_CRT_PROG_NM")},nac:gx.falseFn};a[146]={fld:"TEXTBLOCK74",format:0,grid:0};a[148]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM21_UPD_PROG_NM",gxz:"ZV43GXV11",gxold:"OV43GXV11",gxvar:"GXV11",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV11=a},v2z:function(a){gx.O.ZV43GXV11=a},v2c:function(){gx.fn.setControlValue("CTLTBM21_UPD_PROG_NM",gx.O.GXV11,0)},c2v:function(){gx.O.GXV11=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM21_UPD_PROG_NM")},nac:gx.falseFn};a[153]={fld:"TBL_HIDDEN",grid:0};a[156]={fld:"TXT_JS_EVENT",format:1,grid:0};a[157]={fld:"BTN_UPD_EXEC",format:0,grid:0};a[158]={fld:"BTN_REG_EXEC",format:0,grid:0};a[159]={fld:"BTN_DLT_EXEC",format:0,
grid:0};a[160]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV10H_INIT_FLG",gxold:"OV10H_INIT_FLG",gxvar:"AV10H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10H_INIT_FLG=a},v2z:function(a){gx.O.ZV10H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV10H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV10H_INIT_FLG=this.val()},
val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(160,function(){});a[161]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_MODE",gxz:"ZV12H_MODE",gxold:"OV12H_MODE",gxvar:"AV12H_MODE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12H_MODE=a},v2z:function(a){gx.O.ZV12H_MODE=a},v2c:function(){gx.fn.setControlValue("vH_MODE",gx.O.AV12H_MODE,0)},c2v:function(){gx.O.AV12H_MODE=
this.val()},val:function(){return gx.fn.getControlValue("vH_MODE")},nac:gx.falseFn};a[162]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV11H_KNGN_FLG",gxold:"OV11H_KNGN_FLG",gxvar:"AV11H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11H_KNGN_FLG=a},v2z:function(a){gx.O.ZV11H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV11H_KNGN_FLG,0)},c2v:function(){gx.O.AV11H_KNGN_FLG=
this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};this.OV33GXV1=this.ZV33GXV1=this.GXV1=0;this.OV39GXV7=this.ZV39GXV7=this.GXV7=this.OV38GXV6=this.ZV38GXV6=this.GXV6=this.OV37GXV5=this.ZV37GXV5=this.GXV5=this.OV36GXV4=this.ZV36GXV4=this.GXV4=this.OV35GXV3=this.ZV35GXV3=this.GXV3=this.OV34GXV2=this.ZV34GXV2=this.GXV2="";this.GXV8=gx.date.nullDate();this.ZV40GXV8=gx.date.nullDate();this.OV40GXV8=gx.date.nullDate();this.GXV9=gx.date.nullDate();this.ZV41GXV9=gx.date.nullDate();
this.OV41GXV9=gx.date.nullDate();this.OV11H_KNGN_FLG=this.ZV11H_KNGN_FLG=this.AV11H_KNGN_FLG=this.OV12H_MODE=this.ZV12H_MODE=this.AV12H_MODE=this.OV10H_INIT_FLG=this.ZV10H_INIT_FLG=this.AV10H_INIT_FLG=this.OV43GXV11=this.ZV43GXV11=this.GXV11=this.OV42GXV10=this.ZV42GXV10=this.GXV10=this.OV9D_UPD_USER_NM=this.ZV9D_UPD_USER_NM=this.AV9D_UPD_USER_NM=this.OV8D_CRT_USER_NM=this.ZV8D_CRT_USER_NM=this.AV8D_CRT_USER_NM="";this.GXV1=0;this.GXV7=this.GXV6=this.GXV5=this.GXV4=this.GXV3=this.GXV2="";this.GXV8=
gx.date.nullDate();this.GXV9=gx.date.nullDate();this.AV11H_KNGN_FLG=this.AV12H_MODE=this.AV10H_INIT_FLG=this.GXV11=this.GXV10=this.AV9D_UPD_USER_NM=this.AV8D_CRT_USER_NM="";this.AV13P_STUDY_ID=0;this.A893TBM42_DEL_FLG="";this.A203TBM42_STUDY_ID=0;this.A397TBM31_DEL_FLG="";this.A68TBM31_STUDY_ID=0;this.A385TBM23_DEL_FLG=this.A214TAM07_DEL_FLG=this.A333TAM07_SITE_ID="";this.A107TBM23_STUDY_ID=0;this.A377TBM22_DEL_FLG=this.A325TAM08_DEL_FLG=this.A18TBM22_SITE_ID=this.A108TBM23_USER_ID="";this.A17TBM22_STUDY_ID=
0;this.A205TAM07_USER_NM=this.A55TAM07_USER_ID="";this.A789VBM01_TBM32_CRF_ID=0;this.A794VBM01_TBM32_CRF_ITEM_GRP_CD=this.A793VBM01_TBM32_CRF_ITEM_DIV=this.A792VBM01_TBM32_CRF_ITEM_NM=this.A791VBM01_TBM32_CRF_ITEM_CD=this.A790VBM01_TBM31_CRF_SNM="";this.A799VBM01_TBM32_LOCATION_Y2=this.A798VBM01_TBM32_LOCATION_X2=this.A797VBM01_TBM32_LOCATION_Y=this.A796VBM01_TBM32_LOCATION_X=this.A795VBM01_TBM32_CRF_ITEM_GRP_ORDER=0;this.A800VBM01_TBM32_TEXT_ALIGN_DIV="";this.A803VBM01_TBM32_DECIMAL_DIGITS=this.A802VBM01_TBM32_TEXT_MAXLENGTH=
this.A801VBM01_TBM32_TEXT_MAXROWS=0;this.A810VBM01_TBM32_TEXT=this.A809VBM01_TBM32_IMAGE_CD=this.A808VBM01_TBM25_LIST_NM=this.A807VBM01_TBM32_LIST_CD=this.A806VBM01_TBM32_FIXED_VALUE=this.A805VBM01_TBM32_CHK_FALSE_INNER_VA=this.A804VBM01_TBM32_CHK_TRUE_INNER_VAL="";this.A811VBM01_TBM32_FONT_SIZE=0;this.A812VBM01_TBM32_FONT_UL_FLG="";this.A815VBM01_TBM32_LINE_COLOR_DIV=this.A814VBM01_TBM32_LINE_SIZE_DIV=this.A813VBM01_TBM32_FONT_COLOR_DIV=0;this.A817VBM01_TBM32_LINE_END_POINT_DIV=this.A816VBM01_TBM32_LINE_START_POINT_D=
"";this.A821VBM01_TBM32_TAB_ORDER=this.A820VBM01_TBM32_ZORDER=this.A819VBM01_TBM32_AUTH_LVL_MIN=this.A818VBM01_TBM32_LINE_ANGLE=0;this.A826VBM01_TBM32_CRF_ITEM_NOTE=this.A825VBM01_TBM32_MAX_VALUE=this.A824VBM01_TBM32_MIN_VALUE=this.A823VBM01_TBM32_REQUIRED_INPUT_FLG=this.A822VBM01_TBM32_TABSTOP_FLG="";this.A827VBM01_TBM32_REF_CRF_ID=0;this.A828VBM01_TBM32_REF_CRF_ITEM_CD="";this.A829VBM01_TBM37_VISIT_NO=0;this.A832VBM01_TBM37_DOM_ITM_GRP_OID=this.A831VBM01_TBM37_DOM_VAR_NM=this.A830VBM01_TBM37_DOM_CD=
"";this.A834VBM01_TBM37_DOM_ITM_GRP_ROWNO=this.A833VBM01_TBM37_DOM_ITM_GRP_ATTR_S=0;this.A835VBM01_TBM41_NCM_METADATA_ID="";this.A788VBM01_TBM32_STUDY_ID=0;this.AV20W_A821_JS=this.AV19W_A819_JS="";this.AV15W_A_CHK_RESULT_SDT_ITEM={};this.AV14W_A_CHK_RESULT_SDT=[];this.AV48GXV13=0;this.Events={e110w2_client:["'BTN_REG'",true],e180w2_client:["'BTN_REG_EXEC'",true],e120w2_client:["'BTN_UPD'",true],e190w2_client:["'BTN_UPD_EXEC'",true],e130w2_client:["'BTN_CSV'",true],e140w2_client:["'BTN_DLT'",true],
e200w2_client:["'BTN_DLT_EXEC'",true],e150w2_client:["'BTN_CAN'",true],e210w2_client:["'BTN_STAFF'",true],e220w2_client:["'BTN_CRF_DETAIL'",true],e230w2_client:["'BTN_SITE'",true],e240w2_client:["'BTN_CRF_COND'",true],e250w2_client:["'BTN_CRF_DOMAIN'",true],e270w2_client:["ENTER",true],e280w2_client:["CANCEL",true]};this.setVCMap("AV13P_STUDY_ID","vP_STUDY_ID",0,"int");this.addBCProperty("Bc_study",["TBM21_STUDY_ID"],this.GXValidFnc[40],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_OUTER_STUDY_ID"],
this.GXValidFnc[44],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_STUDY_NM"],this.GXValidFnc[50],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_STATUS"],this.GXValidFnc[55],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_PROC_NM"],this.GXValidFnc[59],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_NOTE"],this.GXValidFnc[64],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_DEL_FLG"],this.GXValidFnc[69],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_CRT_DATETIME"],this.GXValidFnc[126],
"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_UPD_DATETIME"],this.GXValidFnc[130],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_CRT_PROG_NM"],this.GXValidFnc[144],"AV5BC_STUDY");this.addBCProperty("Bc_study",["TBM21_UPD_PROG_NM"],this.GXValidFnc[148],"AV5BC_STUDY");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0151",lvl:1})});gx.setParentObj(new b402_wp02_study_reg);
