gx.evt.autoSkip=!1;
gx.define("b405_wp02_kanja_crf_reg",!1,function(){this.ServerClass="b405_wp02_kanja_crf_reg";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e111e2_client");this.addKeyListener("11","e121e2_client");this.SetStandaloneVars=function(){this.AV33Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV8C_TAM02_APP_ID=gx.fn.getControlValue("vC_TAM02_APP_ID");this.A68TBM31_STUDY_ID=gx.fn.getIntegerValue("TBM31_STUDY_ID",",");
this.A69TBM31_CRF_ID=gx.fn.getIntegerValue("TBM31_CRF_ID",",");this.A643TBM31_STATUS=gx.fn.getControlValue("TBM31_STATUS");this.A397TBM31_DEL_FLG=gx.fn.getControlValue("TBM31_DEL_FLG");this.AV23W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.AV22W_A819_JS=gx.fn.getControlValue("vW_A819_JS");this.AV24W_B405_WP01_SD01=gx.fn.getControlValue("vW_B405_WP01_SD01");this.A642TBM31_CRF_SNM=gx.fn.getControlValue("TBM31_CRF_SNM");this.AV20P_SESSION_ID=gx.fn.getControlValue("vP_SESSION_ID");this.AV16P_APP_ID=
gx.fn.getControlValue("vP_APP_ID");this.AV18P_DISP_DATETIME=gx.fn.getControlValue("vP_DISP_DATETIME");this.AV19P_SEL_LINE_NO=gx.fn.getIntegerValue("vP_SEL_LINE_NO",",")};this.s152_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");if(""!=this.AV23W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV23W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");""!=this.AV22W_A819_JS&&gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV22W_A819_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.e111e2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e131e2_client=function(){this.executeServerEvent("'BTN_REG_EXEC'",true)};this.e121e2_client=function(){this.executeServerEvent("'BTN_CAN'",true)};this.e191e2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e201e2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var c=this.GXValidFnc=
[];this.GXCtrlIds=[2,6,12,15,17,20,26,29,31,34,35,38,41,44,49,52,58,61,64,69,72,73,78,81,82,83,84,85,86,87];this.GXLastCtrlId=87;var d=this.Grd_titleContainer=new gx.grid.grid(this,2,"WbpLvl2",46,"Grd_title","Grd_title","Grd_titleContainer",this.CmpContext,this.IsMasterPage,"b405_wp02_kanja_crf_reg",[],true,0,true,true,0,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",false,false,false,null,null,false,"",false,[1,1,1,1]);d.startRow("","","","","","");d.startCell("","","","","","","","","","");d.startTable("Tbl_in_grid_header2",
49,"150px");d.addHtmlCode("<tbody>");d.startRow("","","","","","");d.startCell("","","","","","","","","","");d.addSingleLineEdit("D_crfsnm",52,"vD_CRFSNM","","","D_CRFSNM","svchar",20,"chr",20,20,"left",null,[],"D_crfsnm","D_CRFSNM",true,0,false,false,"ReadonlyAttribute",1,"");d.endCell();d.endRow();d.addHtmlCode("</tbody>");d.endTable();d.endCell();d.endRow();this.setGrid(d);var e=this.Grid2Container=new gx.grid.grid(this,5,"WbpLvl5",66,"Grid2","Grid2","Grid2Container",this.CmpContext,this.IsMasterPage,
"b405_wp02_kanja_crf_reg",[],true,0,true,true,0,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",false,false,true,null,null,false,"",false,[1,1,1,1]);e.startRow("","","","","","");e.startCell("","","","","","","","","","");e.startTable("Tbl_in_grid3",69,"150px");e.addHtmlCode("<tbody>");e.startRow("","","","","","");e.startCell("","center","","","","","","","","");e.addCheckBox("D_grd2_crf_status",72,"vD_GRD2_CRF_STATUS","","","D_GRD2_CRF_STATUS","boolean","true","false",null,true,false,2,"chr","");
e.endCell();e.endRow();e.addHtmlCode("</tbody>");e.endTable();e.addSingleLineEdit("D_grd1_crf_id",73,"vD_GRD1_CRF_ID","","","D_GRD1_CRF_ID","int",4,"chr",4,4,"right",null,[],"D_grd1_crf_id","D_GRD1_CRF_ID",true,0,false,false,"Attribute",1,"");e.endCell();e.endRow();var b=this.Grid1Container=new gx.grid.grid(this,4,"WbpLvl4",55,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"b405_wp02_kanja_crf_reg",[],true,1,true,true,2,true,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,
true,null,null,false,"",false,[1,1,1,1]);b.startRow("","","","","","");b.startCell("","","","","","","","","","");b.startTable("Tbl_grid",58,"0px");b.addHtmlCode("<tbody>");b.startRow("","","","","","");b.startCell("","","top","","","","","","","");b.startTable("Tbl_in_grid2",61,"70px");b.addHtmlCode("<tbody>");b.startRow("","","","","","");b.startCell("","","","","","","","","","");b.addSingleLineEdit("D_grd1_hikensha",64,"vD_GRD1_HIKENSHA","","","D_GRD1_HIKENSHA","svchar",6,"chr",6,6,"left",null,
[],"D_grd1_hikensha","D_GRD1_HIKENSHA",true,0,false,false,"ReadonlyAttribute",1,"");b.endCell();b.endRow();b.addHtmlCode("</tbody>");b.endTable();b.endCell();b.startCell("","","","","","","","","","");b.addGrid(this.Grid2Container);b.endCell();b.endRow();b.addHtmlCode("</tbody>");b.endTable();b.endCell();b.endRow();this.setGrid(b);c[2]={fld:"TABLE1",grid:0};c[6]={fld:"TABLE2",grid:0};c[12]={fld:"TBL_UPD_BTNSET",grid:0};c[15]={fld:"TXT_BTN_REG",format:0,grid:0};c[17]={fld:"TXT_BTN_CAN",format:0,grid:0};
c[20]={fld:"TABLE4",grid:0};c[26]={fld:"TABLE10",grid:0};c[29]={fld:"TEXTBLOCK16",format:0,grid:0};c[31]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_STUDY_NM",gxz:"ZV13D_STUDY_NM",gxold:"OV13D_STUDY_NM",gxvar:"AV13D_STUDY_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13D_STUDY_NM=a},v2z:function(a){gx.O.ZV13D_STUDY_NM=a},v2c:function(){gx.fn.setControlValue("vD_STUDY_NM",gx.O.AV13D_STUDY_NM,0)},c2v:function(){gx.O.AV13D_STUDY_NM=
this.val()},val:function(){return gx.fn.getControlValue("vD_STUDY_NM")},nac:gx.falseFn};c[34]={fld:"SECTION1",grid:0};c[35]={fld:"TBL_LIST",grid:0};c[38]={fld:"TBL_GRID_HEADER",grid:0};c[41]={fld:"TBL_IN_GRID_HEADER",grid:0};c[44]={fld:"TEXTBLOCK13",format:0,grid:0};c[49]={fld:"TBL_IN_GRID_HEADER2",grid:46};c[52]={lvl:2,type:"svchar",len:20,dec:0,sign:false,ro:1,isacc:0,grid:46,gxgrid:this.Grd_titleContainer,fnc:null,isvalid:null,rgrid:[],fld:"vD_CRFSNM",gxz:"ZV9D_CRFSNM",gxold:"OV9D_CRFSNM",gxvar:"AV9D_CRFSNM",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV9D_CRFSNM=a},v2z:function(a){gx.O.ZV9D_CRFSNM=a},v2c:function(a){gx.fn.setGridControlValue("vD_CRFSNM",a||gx.fn.currentGridRowImpl(46),gx.O.AV9D_CRFSNM,0)},c2v:function(){gx.O.AV9D_CRFSNM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_CRFSNM",a||gx.fn.currentGridRowImpl(46))},nac:gx.falseFn};c[58]={fld:"TBL_GRID",grid:55};c[61]={fld:"TBL_IN_GRID2",grid:55};c[64]={lvl:4,type:"svchar",
len:6,dec:0,sign:false,ro:0,isacc:0,grid:55,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD1_HIKENSHA",gxz:"ZV11D_GRD1_HIKENSHA",gxold:"OV11D_GRD1_HIKENSHA",gxvar:"AV11D_GRD1_HIKENSHA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV11D_GRD1_HIKENSHA=a},v2z:function(a){gx.O.ZV11D_GRD1_HIKENSHA=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD1_HIKENSHA",a||gx.fn.currentGridRowImpl(55),gx.O.AV11D_GRD1_HIKENSHA,0)},c2v:function(){gx.O.AV11D_GRD1_HIKENSHA=
this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD1_HIKENSHA",a||gx.fn.currentGridRowImpl(55))},nac:gx.falseFn};c[69]={fld:"TBL_IN_GRID3",grid:66};c[72]={lvl:5,type:"boolean",len:2,dec:0,sign:false,ro:0,isacc:0,grid:66,gxgrid:this.Grid2Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD2_CRF_STATUS",gxz:"ZV12D_GRD2_CRF_STATUS",gxold:"OV12D_GRD2_CRF_STATUS",gxvar:"AV12D_GRD2_CRF_STATUS",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",inputType:"text",v2v:function(a){gx.O.AV12D_GRD2_CRF_STATUS=
gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV12D_GRD2_CRF_STATUS=gx.lang.booleanValue(a)},v2c:function(a){gx.fn.setGridCheckBoxValue("vD_GRD2_CRF_STATUS",a||gx.fn.currentGridRowImpl(66),gx.O.AV12D_GRD2_CRF_STATUS,true)},c2v:function(){gx.O.AV12D_GRD2_CRF_STATUS=gx.lang.booleanValue(this.val())},val:function(a){return gx.fn.getGridCheckBoxValue("vD_GRD2_CRF_STATUS",a||gx.fn.currentGridRowImpl(66),true,false)},nac:gx.falseFn};c[73]={lvl:5,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,isacc:0,
grid:66,gxgrid:this.Grid2Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD1_CRF_ID",gxz:"ZV10D_GRD1_CRF_ID",gxold:"OV10D_GRD1_CRF_ID",gxvar:"AV10D_GRD1_CRF_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV10D_GRD1_CRF_ID=gx.num.intval(a)},v2z:function(a){gx.O.ZV10D_GRD1_CRF_ID=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("vD_GRD1_CRF_ID",a||gx.fn.currentGridRowImpl(66),gx.O.AV10D_GRD1_CRF_ID,0)},c2v:function(){gx.O.AV10D_GRD1_CRF_ID=gx.num.intval(this.val())},
val:function(a){return gx.fn.getGridIntegerValue("vD_GRD1_CRF_ID",a||gx.fn.currentGridRowImpl(66),",")},nac:gx.falseFn};c[78]={fld:"TBL_HIDDEN",grid:0};c[81]={fld:"TXT_JS_EVENT",format:1,grid:0};c[82]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV14H_INIT_FLG",gxold:"OV14H_INIT_FLG",gxvar:"AV14H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV14H_INIT_FLG=a},v2z:function(a){gx.O.ZV14H_INIT_FLG=
a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV14H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV14H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(82,function(){});c[83]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV15H_KNGN_FLG",gxold:"OV15H_KNGN_FLG",gxvar:"AV15H_KNGN_FLG",ucs:[],op:[],
ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_KNGN_FLG=a},v2z:function(a){gx.O.ZV15H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV15H_KNGN_FLG,0)},c2v:function(){gx.O.AV15H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};c[84]={fld:"TEXTBLOCK2",format:0,grid:0};c[85]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vP_COL_COUNT",gxz:"ZV17P_COL_COUNT",
gxold:"OV17P_COL_COUNT",gxvar:"AV17P_COL_COUNT",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV17P_COL_COUNT=gx.num.intval(a)},v2z:function(a){gx.O.ZV17P_COL_COUNT=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vP_COL_COUNT",gx.O.AV17P_COL_COUNT,0)},c2v:function(){gx.O.AV17P_COL_COUNT=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vP_COL_COUNT",",")},nac:gx.falseFn};c[86]={lvl:0,type:"vchar",len:2097152,dec:0,sign:false,ro:0,multiline:true,grid:0,
gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vW_TBW01_FREE_SAVE_1",gxz:"ZV29W_TBW01_FREE_SAVE_1",gxold:"OV29W_TBW01_FREE_SAVE_1",gxvar:"AV29W_TBW01_FREE_SAVE_1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV29W_TBW01_FREE_SAVE_1=a},v2z:function(a){gx.O.ZV29W_TBW01_FREE_SAVE_1=a},v2c:function(){gx.fn.setControlValue("vW_TBW01_FREE_SAVE_1",gx.O.AV29W_TBW01_FREE_SAVE_1,0)},c2v:function(){gx.O.AV29W_TBW01_FREE_SAVE_1=this.val()},val:function(){return gx.fn.getControlValue("vW_TBW01_FREE_SAVE_1")},
nac:gx.falseFn};c[87]={lvl:0,type:"vchar",len:2097152,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vW_TBW01_FREE_SAVE_1_BAK",gxz:"ZV30W_TBW01_FREE_SAVE_1_BAK",gxold:"OV30W_TBW01_FREE_SAVE_1_BAK",gxvar:"AV30W_TBW01_FREE_SAVE_1_BAK",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV30W_TBW01_FREE_SAVE_1_BAK=a},v2z:function(a){gx.O.ZV30W_TBW01_FREE_SAVE_1_BAK=a},v2c:function(){gx.fn.setControlValue("vW_TBW01_FREE_SAVE_1_BAK",gx.O.AV30W_TBW01_FREE_SAVE_1_BAK,
0)},c2v:function(){gx.O.AV30W_TBW01_FREE_SAVE_1_BAK=this.val()},val:function(){return gx.fn.getControlValue("vW_TBW01_FREE_SAVE_1_BAK")},nac:gx.falseFn};this.OV11D_GRD1_HIKENSHA=this.ZV11D_GRD1_HIKENSHA=this.OV9D_CRFSNM=this.ZV9D_CRFSNM=this.OV13D_STUDY_NM=this.ZV13D_STUDY_NM=this.AV13D_STUDY_NM="";this.OV12D_GRD2_CRF_STATUS=this.ZV12D_GRD2_CRF_STATUS=false;this.OV10D_GRD1_CRF_ID=this.ZV10D_GRD1_CRF_ID=0;this.OV15H_KNGN_FLG=this.ZV15H_KNGN_FLG=this.AV15H_KNGN_FLG=this.OV14H_INIT_FLG=this.ZV14H_INIT_FLG=
this.AV14H_INIT_FLG="";this.OV17P_COL_COUNT=this.ZV17P_COL_COUNT=this.AV17P_COL_COUNT=0;this.AV15H_KNGN_FLG=this.AV14H_INIT_FLG=this.AV13D_STUDY_NM=this.OV30W_TBW01_FREE_SAVE_1_BAK=this.ZV30W_TBW01_FREE_SAVE_1_BAK=this.AV30W_TBW01_FREE_SAVE_1_BAK=this.OV29W_TBW01_FREE_SAVE_1=this.ZV29W_TBW01_FREE_SAVE_1=this.AV29W_TBW01_FREE_SAVE_1="";this.AV17P_COL_COUNT=0;this.AV18P_DISP_DATETIME=this.AV16P_APP_ID=this.AV20P_SESSION_ID=this.AV30W_TBW01_FREE_SAVE_1_BAK=this.AV29W_TBW01_FREE_SAVE_1="";this.AV19P_SEL_LINE_NO=
0;this.AV9D_CRFSNM="";this.A63TBM21_STUDY_ID=0;this.AV11D_GRD1_HIKENSHA=this.A367TBM21_STUDY_NM="";this.AV12D_GRD2_CRF_STATUS=false;this.AV10D_GRD1_CRF_ID=0;this.A643TBM31_STATUS=this.A397TBM31_DEL_FLG="";this.A89TBT02_STUDY_ID=this.A90TBT02_SUBJECT_ID=this.A91TBT02_CRF_ID=this.A935TBT02_CRF_EDA_NO=this.A68TBM31_STUDY_ID=this.A69TBM31_CRF_ID=0;this.AV22W_A819_JS=this.AV23W_A821_JS=this.AV8C_TAM02_APP_ID=this.AV33Pgmname=this.A642TBM31_CRF_SNM="";this.AV24W_B405_WP01_SD01={};this.Events={e111e2_client:["'BTN_REG'",
true],e131e2_client:["'BTN_REG_EXEC'",true],e121e2_client:["'BTN_CAN'",true],e191e2_client:["ENTER",true],e201e2_client:["CANCEL",true]};this.setVCMap("AV33Pgmname","vPGMNAME",0,"char");this.setVCMap("AV8C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("A68TBM31_STUDY_ID","TBM31_STUDY_ID",0,"int");this.setVCMap("A69TBM31_CRF_ID","TBM31_CRF_ID",0,"int");this.setVCMap("A643TBM31_STATUS","TBM31_STATUS",0,"svchar");this.setVCMap("A397TBM31_DEL_FLG","TBM31_DEL_FLG",0,"svchar");this.setVCMap("AV23W_A821_JS",
"vW_A821_JS",0,"svchar");this.setVCMap("AV22W_A819_JS","vW_A819_JS",0,"svchar");this.setVCMap("AV24W_B405_WP01_SD01","vW_B405_WP01_SD01",0,"B405_SD01");this.setVCMap("A642TBM31_CRF_SNM","TBM31_CRF_SNM",0,"svchar");this.setVCMap("AV20P_SESSION_ID","vP_SESSION_ID",0,"svchar");this.setVCMap("AV16P_APP_ID","vP_APP_ID",0,"svchar");this.setVCMap("AV18P_DISP_DATETIME","vP_DISP_DATETIME",0,"svchar");this.setVCMap("AV19P_SEL_LINE_NO","vP_SEL_LINE_NO",0,"int");this.setVCMap("AV33Pgmname","vPGMNAME",0,"char");
this.setVCMap("AV8C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("A68TBM31_STUDY_ID","TBM31_STUDY_ID",0,"int");this.setVCMap("A69TBM31_CRF_ID","TBM31_CRF_ID",0,"int");this.setVCMap("A643TBM31_STATUS","TBM31_STATUS",0,"svchar");this.setVCMap("A397TBM31_DEL_FLG","TBM31_DEL_FLG",0,"svchar");this.setVCMap("AV23W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV22W_A819_JS","vW_A819_JS",0,"svchar");this.setVCMap("AV24W_B405_WP01_SD01","vW_B405_WP01_SD01",0,"B405_SD01");this.setVCMap("A642TBM31_CRF_SNM",
"TBM31_CRF_SNM",0,"svchar");d.addRefreshingVar(this.GXValidFnc[82]);d.addRefreshingVar({rfrVar:"AV33Pgmname"});d.addRefreshingVar({rfrVar:"AV8C_TAM02_APP_ID"});d.addRefreshingVar(this.GXValidFnc[86]);d.addRefreshingVar({rfrVar:"A68TBM31_STUDY_ID"});d.addRefreshingVar({rfrVar:"A69TBM31_CRF_ID"});d.addRefreshingVar({rfrVar:"A643TBM31_STATUS"});d.addRefreshingVar({rfrVar:"A397TBM31_DEL_FLG"});d.addRefreshingVar({rfrVar:"AV23W_A821_JS"});d.addRefreshingVar({rfrVar:"AV22W_A819_JS"});d.addRefreshingVar({rfrVar:"AV24W_B405_WP01_SD01"});
d.addRefreshingVar({rfrVar:"A642TBM31_CRF_SNM"});e.addRefreshingVar(this.GXValidFnc[82]);e.addRefreshingVar({rfrVar:"AV33Pgmname"});e.addRefreshingVar({rfrVar:"AV8C_TAM02_APP_ID"});e.addRefreshingVar(this.GXValidFnc[86]);e.addRefreshingVar({rfrVar:"A68TBM31_STUDY_ID"});e.addRefreshingVar({rfrVar:"A69TBM31_CRF_ID"});e.addRefreshingVar({rfrVar:"A643TBM31_STATUS"});e.addRefreshingVar({rfrVar:"A397TBM31_DEL_FLG"});e.addRefreshingVar({rfrVar:"AV23W_A821_JS"});e.addRefreshingVar({rfrVar:"AV22W_A819_JS"});
e.addRefreshingVar({rfrVar:"AV24W_B405_WP01_SD01"});b.addRefreshingVar(this.GXValidFnc[82]);b.addRefreshingVar({rfrVar:"AV33Pgmname"});b.addRefreshingVar({rfrVar:"AV8C_TAM02_APP_ID"});b.addRefreshingVar(this.GXValidFnc[86]);b.addRefreshingVar({rfrVar:"A68TBM31_STUDY_ID"});b.addRefreshingVar({rfrVar:"A69TBM31_CRF_ID"});b.addRefreshingVar({rfrVar:"A643TBM31_STATUS"});b.addRefreshingVar({rfrVar:"A397TBM31_DEL_FLG"});b.addRefreshingVar({rfrVar:"AV23W_A821_JS"});b.addRefreshingVar({rfrVar:"AV22W_A819_JS"});
this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0076",lvl:1})});gx.setParentObj(new b405_wp02_kanja_crf_reg);
