gx.evt.autoSkip=!1;
gx.define("b717_wp01_rekiinfo_crf",!1,function(){this.ServerClass="b717_wp01_rekiinfo_crf";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.SetStandaloneVars=function(){this.AV47Pgmname=gx.fn.getControlValue("vPGMNAME");this.A63TBM21_STUDY_ID=gx.fn.getIntegerValue("TBM21_STUDY_ID",",");this.AV17P_STUDY_ID=gx.fn.getIntegerValue("vP_STUDY_ID",",");this.A369TBM21_DEL_FLG=gx.fn.getControlValue("TBM21_DEL_FLG");this.A367TBM21_STUDY_NM=
gx.fn.getControlValue("TBM21_STUDY_NM");this.AV18P_SUBJECT_ID=gx.fn.getIntegerValue("vP_SUBJECT_ID",",");this.A68TBM31_STUDY_ID=gx.fn.getIntegerValue("TBM31_STUDY_ID",",");this.A69TBM31_CRF_ID=gx.fn.getIntegerValue("TBM31_CRF_ID",",");this.AV16P_CRF_ID=gx.fn.getIntegerValue("vP_CRF_ID",",");this.A397TBM31_DEL_FLG=gx.fn.getControlValue("TBM31_DEL_FLG");this.A393TBM31_CRF_NM=gx.fn.getControlValue("TBM31_CRF_NM");this.A642TBM31_CRF_SNM=gx.fn.getControlValue("TBM31_CRF_SNM");this.A945TBM44_STUDY_ID=gx.fn.getIntegerValue("TBM44_STUDY_ID",
",");this.A946TBM44_CRF_ID=gx.fn.getIntegerValue("TBM44_CRF_ID",",");this.A947TBM44_CRF_EDA_NO=gx.fn.getIntegerValue("TBM44_CRF_EDA_NO",",");this.AV34P_CRF_EDA_NO=gx.fn.getIntegerValue("vP_CRF_EDA_NO",",");this.A948TBM44_VISIT_NO=gx.fn.getIntegerValue("TBM44_VISIT_NO",",");this.A87TBT01_STUDY_ID=gx.fn.getIntegerValue("TBT01_STUDY_ID",",");this.A88TBT01_SUBJECT_ID=gx.fn.getIntegerValue("TBT01_SUBJECT_ID",",");this.A441TBT01_DEL_FLG=gx.fn.getControlValue("TBT01_DEL_FLG");this.A698TBT01_SITE_ID=gx.fn.getControlValue("TBT01_SITE_ID");
this.A57TAM08_SITE_ID=gx.fn.getControlValue("TAM08_SITE_ID");this.A325TAM08_DEL_FLG=gx.fn.getControlValue("TAM08_DEL_FLG");this.A319TAM08_SITE_NM=gx.fn.getControlValue("TAM08_SITE_NM");this.A92TBT11_STUDY_ID=gx.fn.getIntegerValue("TBT11_STUDY_ID",",");this.A93TBT11_SUBJECT_ID=gx.fn.getIntegerValue("TBT11_SUBJECT_ID",",");this.A94TBT11_CRF_ID=gx.fn.getIntegerValue("TBT11_CRF_ID",",");this.A95TBT11_CRF_VERSION=gx.fn.getIntegerValue("TBT11_CRF_VERSION",",");this.A936TBT11_CRF_EDA_NO=gx.fn.getIntegerValue("TBT11_CRF_EDA_NO",
",");this.A670TBT11_DM_ARRIVAL_DATETIME=gx.fn.getDateTimeValue("TBT11_DM_ARRIVAL_DATETIME");this.A457TBT11_DEL_FLG=gx.fn.getControlValue("TBT11_DEL_FLG");this.A669TBT11_DM_ARRIVAL_FLG=gx.fn.getControlValue("TBT11_DM_ARRIVAL_FLG");this.A675TBT11_INPUT_END_FLG=gx.fn.getControlValue("TBT11_INPUT_END_FLG");this.A666TBT11_UPLOAD_DATETIME=gx.fn.getDateTimeValue("TBT11_UPLOAD_DATETIME");this.A667TBT11_UPLOAD_USER_ID=gx.fn.getControlValue("TBT11_UPLOAD_USER_ID");this.A55TAM07_USER_ID=gx.fn.getControlValue("TAM07_USER_ID");
this.A205TAM07_USER_NM=gx.fn.getControlValue("TAM07_USER_NM");this.A891TBT11_UPD_RIYU=gx.fn.getControlValue("TBT11_UPD_RIYU");this.AV21W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.AV33W_JS=gx.fn.getControlValue("vW_JS");this.AV13H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT")};this.s122_client=function(){this.AV13H_A_PAGING_SDT.PAGE_NO=1;this.AV33W_JS=this.AV20W_A819_JS=""};this.s132_client=function(){};this.s152_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+
"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");if(""!=this.AV21W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV21W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");""!=this.AV33W_JS&&gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV33W_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.e111l2_client=function(){this.executeServerEvent("'BTN_EXIT'",true)};this.e121l2_client=function(){this.executeServerEvent("'PAGE_FIRST'",true)};this.e131l2_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};this.e141l2_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e151l2_client=function(){this.executeServerEvent("'PAGE_NEXT'",
true)};this.e161l2_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e171l2_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e181l2_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e191l2_client=function(){this.executeServerEvent("'PAGE04'",true)};this.e201l2_client=function(){this.executeServerEvent("'PAGE05'",true)};this.e211l2_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e221l2_client=function(){this.executeServerEvent("'PAGE07'",
true)};this.e231l2_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e241l2_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e251l2_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e291l2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e301l2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,11,15,17,22,26,29,32,35,38,40,42,44,47,49,51,53,56,58,60,62,67,70,73,76,79,82,85,88,91,94,
97,100,103,106,109,112,115,118,121,124,127,130,133,136,139,142,145,148,151,154,157,162,165,167,169,171,173,175,179,181,183,185,187,189,191,194,195,196,197];this.GXLastCtrlId=197;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",176,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"b717_wp01_rekiinfo_crf",[],true,1,true,true,10,false,false,false,"CollB717_SD01_REKIINFO_CRF_LIST.B717_SD01_REKIINFO_CRF_LISTItem",0,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,
"AV22W_B717_SD01_REKIINFO_CRF_LIST",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","center","","","","25px","60px","","","");c.addSingleLineEdit("GXV2",179,"CTLTBT11_CRF_VERSION","","","TBT11_CRF_VERSION","int",4,"chr",4,4,"right",null,[],"GXV2","GXV2",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","center","","","","","60px","","","");c.addSingleLineEdit("GXV3",181,"CTLDM_ARRIVAL","","","DM_ARRIVAL","svchar",1,"chr",1,1,"left",null,[],"GXV3","GXV3",true,0,false,false,
"Attribute",1,"");c.endCell();c.startCell("","center","","","","","70px","","","");c.addSingleLineEdit("GXV4",183,"CTLINPUT_END","","","INPUT_END","svchar",1,"chr",1,1,"left",null,[],"GXV4","GXV4",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","","","","","","155px","","","");c.addSingleLineEdit("GXV5",185,"CTLTBT11_UPLOAD_DATETIME_VC","","","TBT11_UPLOAD_DATETIME_VC","svchar",20,"chr",20,20,"left",null,[],"GXV5","GXV5",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("",
"","","","","","210px","","","");c.addSingleLineEdit("GXV6",187,"CTLTAM07_USER_NM","","","TAM07_USER_NM","svchar",210,"px",30,30,"left",null,[],"GXV6","GXV6",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","","","","","","255px","","","");c.addMultipleLineEdit("GXV7",189,"CTLTBT11_UPD_RIYU","","TBT11_UPD_RIYU","svchar",250,"px",3,"row","2000",2E3,"left",null,true,false,0,"");c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[6]={fld:"TABLE2",grid:0};b[11]={fld:"TABLE6",
grid:0};b[15]={fld:"TEXTBLOCK33",format:0,grid:0};b[17]={fld:"TBL_UPD_BTNSET",grid:0};b[22]={fld:"TXT_BTN_EXIT",format:0,grid:0};b[26]={fld:"TABLE3",grid:0};b[29]={fld:"TABLE4",grid:0};b[32]={fld:"TABLE5",grid:0};b[35]={fld:"TEXTBLOCK72",format:0,grid:0};b[38]={fld:"TEXTBLOCK67",format:0,grid:0};b[40]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_STUDY_NM",gxz:"ZV11D_STUDY_NM",gxold:"OV11D_STUDY_NM",gxvar:"AV11D_STUDY_NM",ucs:[],op:[],
ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11D_STUDY_NM=a},v2z:function(a){gx.O.ZV11D_STUDY_NM=a},v2c:function(){gx.fn.setControlValue("vD_STUDY_NM",gx.O.AV11D_STUDY_NM,0)},c2v:function(){gx.O.AV11D_STUDY_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_STUDY_NM")},nac:gx.falseFn};b[42]={fld:"TEXTBLOCK71",format:0,grid:0};b[44]={lvl:0,type:"int",len:6,dec:0,sign:false,pic:"ZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_SUBJECT_ID",gxz:"ZV12D_SUBJECT_ID",
gxold:"OV12D_SUBJECT_ID",gxvar:"AV12D_SUBJECT_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12D_SUBJECT_ID=gx.num.intval(a)},v2z:function(a){gx.O.ZV12D_SUBJECT_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vD_SUBJECT_ID",gx.O.AV12D_SUBJECT_ID,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV12D_SUBJECT_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vD_SUBJECT_ID",",")},nac:gx.falseFn};this.declareDomainHdlr(44,
function(){});b[47]={fld:"TEXTBLOCK69",format:0,grid:0};b[49]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_CRF_NM",gxz:"ZV8D_CRF_NM",gxold:"OV8D_CRF_NM",gxvar:"AV8D_CRF_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV8D_CRF_NM=a},v2z:function(a){gx.O.ZV8D_CRF_NM=a},v2c:function(){gx.fn.setControlValue("vD_CRF_NM",gx.O.AV8D_CRF_NM,0)},c2v:function(){gx.O.AV8D_CRF_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_CRF_NM")},
nac:gx.falseFn};b[51]={fld:"TEXTBLOCK70",format:0,grid:0};b[53]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_CRF_SNM",gxz:"ZV9D_CRF_SNM",gxold:"OV9D_CRF_SNM",gxvar:"AV9D_CRF_SNM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9D_CRF_SNM=a},v2z:function(a){gx.O.ZV9D_CRF_SNM=a},v2c:function(){gx.fn.setControlValue("vD_CRF_SNM",gx.O.AV9D_CRF_SNM,0)},c2v:function(){gx.O.AV9D_CRF_SNM=this.val()},val:function(){return gx.fn.getControlValue("vD_CRF_SNM")},
nac:gx.falseFn};b[56]={fld:"TEXTBLOCK68",format:0,grid:0};b[58]={lvl:0,type:"int",len:6,dec:0,sign:false,pic:"ZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_VISIT_NO",gxz:"ZV35D_VISIT_NO",gxold:"OV35D_VISIT_NO",gxvar:"AV35D_VISIT_NO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV35D_VISIT_NO=gx.num.intval(a)},v2z:function(a){gx.O.ZV35D_VISIT_NO=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vD_VISIT_NO",gx.O.AV35D_VISIT_NO,0);typeof this.dom_hdl==
"function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV35D_VISIT_NO=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vD_VISIT_NO",",")},nac:gx.falseFn};this.declareDomainHdlr(58,function(){});b[60]={fld:"TEXTBLOCK66",format:0,grid:0};b[62]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_SITE_NM",gxz:"ZV10D_SITE_NM",gxold:"OV10D_SITE_NM",gxvar:"AV10D_SITE_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10D_SITE_NM=
a},v2z:function(a){gx.O.ZV10D_SITE_NM=a},v2c:function(){gx.fn.setControlValue("vD_SITE_NM",gx.O.AV10D_SITE_NM,0)},c2v:function(){gx.O.AV10D_SITE_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_SITE_NM")},nac:gx.falseFn};b[67]={fld:"TBL_PAGE_AREA",grid:0};b[70]={fld:"TXT_REC_CNT",format:0,grid:0};b[73]={fld:"TBL_PAGE",grid:0};b[76]={fld:"TBL_FIRST",grid:0};b[79]={fld:"TXT_FIRST",format:0,grid:0};b[82]={fld:"TBL_BACK",grid:0};b[85]={fld:"TXT_BACK",format:0,grid:0};b[88]={fld:"TBL_PAGE01",
grid:0};b[91]={fld:"TXT_PAGE01",format:0,grid:0};b[94]={fld:"TBL_PAGE02",grid:0};b[97]={fld:"TXT_PAGE02",format:0,grid:0};b[100]={fld:"TBL_PAGE03",grid:0};b[103]={fld:"TXT_PAGE03",format:0,grid:0};b[106]={fld:"TBL_PAGE04",grid:0};b[109]={fld:"TXT_PAGE04",format:0,grid:0};b[112]={fld:"TBL_PAGE05",grid:0};b[115]={fld:"TXT_PAGE05",format:0,grid:0};b[118]={fld:"TBL_PAGE06",grid:0};b[121]={fld:"TXT_PAGE06",format:0,grid:0};b[124]={fld:"TBL_PAGE07",grid:0};b[127]={fld:"TXT_PAGE07",format:0,grid:0};b[130]=
{fld:"TBL_PAGE08",grid:0};b[133]={fld:"TXT_PAGE08",format:0,grid:0};b[136]={fld:"TBL_PAGE09",grid:0};b[139]={fld:"TXT_PAGE09",format:0,grid:0};b[142]={fld:"TBL_PAGE10",grid:0};b[145]={fld:"TXT_PAGE10",format:0,grid:0};b[148]={fld:"TBL_NEXT",grid:0};b[151]={fld:"TXT_NEXT",format:0,grid:0};b[154]={fld:"TBL_LAST",grid:0};b[157]={fld:"TXT_LAST",format:0,grid:0};b[162]={fld:"TBL_GRID_HEADER",grid:0};b[165]={fld:"TEXTBLOCK34",format:0,grid:0};b[167]={fld:"TEXTBLOCK35",format:0,grid:0};b[169]={fld:"TEXTBLOCK38",
format:0,grid:0};b[171]={fld:"TEXTBLOCK36",format:0,grid:0};b[173]={fld:"TEXTBLOCK37",format:0,grid:0};b[175]={fld:"TEXTBLOCK39",format:0,grid:0};b[179]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,grid:176,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBT11_CRF_VERSION",gxz:"ZV39GXV2",gxold:"OV39GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.GXV2=gx.num.intval(a)},v2z:function(a){gx.O.ZV39GXV2=gx.num.intval(a)},
v2c:function(a){gx.fn.setGridControlValue("CTLTBT11_CRF_VERSION",a||gx.fn.currentGridRowImpl(176),gx.O.GXV2,0)},c2v:function(){gx.O.GXV2=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("CTLTBT11_CRF_VERSION",a||gx.fn.currentGridRowImpl(176),",")},nac:gx.falseFn};b[181]={lvl:2,type:"svchar",len:1,dec:0,sign:false,ro:1,isacc:0,grid:176,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"CTLDM_ARRIVAL",gxz:"ZV40GXV3",gxold:"OV40GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],
nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.GXV3=a},v2z:function(a){gx.O.ZV40GXV3=a},v2c:function(a){gx.fn.setGridControlValue("CTLDM_ARRIVAL",a||gx.fn.currentGridRowImpl(176),gx.O.GXV3,0)},c2v:function(){gx.O.GXV3=this.val()},val:function(a){return gx.fn.getGridControlValue("CTLDM_ARRIVAL",a||gx.fn.currentGridRowImpl(176))},nac:gx.falseFn};b[183]={lvl:2,type:"svchar",len:1,dec:0,sign:false,ro:1,isacc:0,grid:176,gxgrid:this.Grid1Container,fnc:null,isvalid:null,
rgrid:[],fld:"CTLINPUT_END",gxz:"ZV41GXV4",gxold:"OV41GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.GXV4=a},v2z:function(a){gx.O.ZV41GXV4=a},v2c:function(a){gx.fn.setGridControlValue("CTLINPUT_END",a||gx.fn.currentGridRowImpl(176),gx.O.GXV4,0)},c2v:function(){gx.O.GXV4=this.val()},val:function(a){return gx.fn.getGridControlValue("CTLINPUT_END",a||gx.fn.currentGridRowImpl(176))},nac:gx.falseFn};b[185]={lvl:2,type:"svchar",len:20,
dec:0,sign:false,ro:1,isacc:0,grid:176,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBT11_UPLOAD_DATETIME_VC",gxz:"ZV42GXV5",gxold:"OV42GXV5",gxvar:"GXV5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.GXV5=a},v2z:function(a){gx.O.ZV42GXV5=a},v2c:function(a){gx.fn.setGridControlValue("CTLTBT11_UPLOAD_DATETIME_VC",a||gx.fn.currentGridRowImpl(176),gx.O.GXV5,0)},c2v:function(){gx.O.GXV5=this.val()},val:function(a){return gx.fn.getGridControlValue("CTLTBT11_UPLOAD_DATETIME_VC",
a||gx.fn.currentGridRowImpl(176))},nac:gx.falseFn};b[187]={lvl:2,type:"svchar",len:30,dec:0,sign:false,ro:1,isacc:0,grid:176,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_USER_NM",gxz:"ZV43GXV6",gxold:"OV43GXV6",gxvar:"GXV6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.GXV6=a},v2z:function(a){gx.O.ZV43GXV6=a},v2c:function(a){gx.fn.setGridControlValue("CTLTAM07_USER_NM",a||gx.fn.currentGridRowImpl(176),gx.O.GXV6,0)},c2v:function(){gx.O.GXV6=
this.val()},val:function(a){return gx.fn.getGridControlValue("CTLTAM07_USER_NM",a||gx.fn.currentGridRowImpl(176))},nac:gx.falseFn};b[189]={lvl:2,type:"svchar",len:2E3,dec:0,sign:false,ro:1,isacc:0,multiline:true,grid:176,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBT11_UPD_RIYU",gxz:"ZV44GXV7",gxold:"OV44GXV7",gxvar:"GXV7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.GXV7=a},v2z:function(a){gx.O.ZV44GXV7=a},v2c:function(a){gx.fn.setGridControlValue("CTLTBT11_UPD_RIYU",
a||gx.fn.currentGridRowImpl(176),gx.O.GXV7,0)},c2v:function(){gx.O.GXV7=this.val()},val:function(a){return gx.fn.getGridControlValue("CTLTBT11_UPD_RIYU",a||gx.fn.currentGridRowImpl(176))},nac:gx.falseFn};b[191]={fld:"TBL_HIDDEN",grid:0};b[194]={fld:"TXT_JS_EVENT",format:1,grid:0};b[195]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV14H_INIT_FLG",gxold:"OV14H_INIT_FLG",gxvar:"AV14H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",v2v:function(a){gx.O.AV14H_INIT_FLG=a},v2z:function(a){gx.O.ZV14H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV14H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV14H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(195,function(){});b[196]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",
gxz:"ZV15H_KNGN_FLG",gxold:"OV15H_KNGN_FLG",gxvar:"AV15H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_KNGN_FLG=a},v2z:function(a){gx.O.ZV15H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV15H_KNGN_FLG,0)},c2v:function(){gx.O.AV15H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[197]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],
fld:"CTLREC_CNT",gxz:"ZV45GXV8",gxold:"OV45GXV8",gxvar:"GXV8",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV8=gx.num.intval(a)},v2z:function(a){gx.O.ZV45GXV8=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",gx.O.GXV8,0)},c2v:function(){gx.O.GXV8=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",",")},nac:gx.falseFn};this.OV11D_STUDY_NM=this.ZV11D_STUDY_NM=this.AV11D_STUDY_NM="";this.OV12D_SUBJECT_ID=this.ZV12D_SUBJECT_ID=
this.AV12D_SUBJECT_ID=0;this.OV9D_CRF_SNM=this.ZV9D_CRF_SNM=this.AV9D_CRF_SNM=this.OV8D_CRF_NM=this.ZV8D_CRF_NM=this.AV8D_CRF_NM="";this.OV35D_VISIT_NO=this.ZV35D_VISIT_NO=this.AV35D_VISIT_NO=0;this.OV10D_SITE_NM=this.ZV10D_SITE_NM=this.AV10D_SITE_NM="";this.OV39GXV2=this.ZV39GXV2=0;this.OV15H_KNGN_FLG=this.ZV15H_KNGN_FLG=this.AV15H_KNGN_FLG=this.OV14H_INIT_FLG=this.ZV14H_INIT_FLG=this.AV14H_INIT_FLG=this.OV44GXV7=this.ZV44GXV7=this.OV43GXV6=this.ZV43GXV6=this.OV42GXV5=this.ZV42GXV5=this.OV41GXV4=
this.ZV41GXV4=this.OV40GXV3=this.ZV40GXV3="";this.OV45GXV8=this.ZV45GXV8=this.GXV8=0;this.AV11D_STUDY_NM="";this.AV12D_SUBJECT_ID=0;this.AV9D_CRF_SNM=this.AV8D_CRF_NM="";this.AV35D_VISIT_NO=0;this.AV15H_KNGN_FLG=this.AV14H_INIT_FLG=this.AV10D_SITE_NM="";this.GXV2=this.AV34P_CRF_EDA_NO=this.AV16P_CRF_ID=this.AV18P_SUBJECT_ID=this.AV17P_STUDY_ID=this.GXV8=0;this.GXV7=this.GXV6=this.GXV5=this.GXV4=this.GXV3="";this.A936TBT11_CRF_EDA_NO=this.A94TBT11_CRF_ID=this.A93TBT11_SUBJECT_ID=this.A92TBT11_STUDY_ID=
0;this.A457TBT11_DEL_FLG="";this.A670TBT11_DM_ARRIVAL_DATETIME=gx.date.nullDate();this.A675TBT11_INPUT_END_FLG=this.A669TBT11_DM_ARRIVAL_FLG="";this.A666TBT11_UPLOAD_DATETIME=gx.date.nullDate();this.A891TBT11_UPD_RIYU=this.A667TBT11_UPLOAD_USER_ID="";this.A95TBT11_CRF_VERSION=0;this.A441TBT01_DEL_FLG=this.A205TAM07_USER_NM=this.A55TAM07_USER_ID="";this.A87TBT01_STUDY_ID=this.A88TBT01_SUBJECT_ID=0;this.A319TAM08_SITE_NM=this.A57TAM08_SITE_ID=this.A325TAM08_DEL_FLG=this.A698TBT01_SITE_ID="";this.A948TBM44_VISIT_NO=
this.A945TBM44_STUDY_ID=this.A946TBM44_CRF_ID=this.A947TBM44_CRF_EDA_NO=0;this.A397TBM31_DEL_FLG="";this.A68TBM31_STUDY_ID=this.A69TBM31_CRF_ID=0;this.A369TBM21_DEL_FLG=this.A642TBM31_CRF_SNM=this.A393TBM31_CRF_NM="";this.A63TBM21_STUDY_ID=0;this.AV33W_JS=this.AV21W_A821_JS=this.AV47Pgmname=this.A367TBM21_STUDY_NM="";this.AV13H_A_PAGING_SDT={};this.AV20W_A819_JS="";this.Events={e111l2_client:["'BTN_EXIT'",true],e121l2_client:["'PAGE_FIRST'",true],e131l2_client:["'PAGE_LAST'",true],e141l2_client:["'PAGE_BACK'",
true],e151l2_client:["'PAGE_NEXT'",true],e161l2_client:["'PAGE01'",true],e171l2_client:["'PAGE02'",true],e181l2_client:["'PAGE03'",true],e191l2_client:["'PAGE04'",true],e201l2_client:["'PAGE05'",true],e211l2_client:["'PAGE06'",true],e221l2_client:["'PAGE07'",true],e231l2_client:["'PAGE08'",true],e241l2_client:["'PAGE09'",true],e251l2_client:["'PAGE10'",true],e291l2_client:["ENTER",true],e301l2_client:["CANCEL",true]};this.setVCMap("AV47Pgmname","vPGMNAME",0,"char");this.setVCMap("A63TBM21_STUDY_ID",
"TBM21_STUDY_ID",0,"int");this.setVCMap("AV17P_STUDY_ID","vP_STUDY_ID",0,"int");this.setVCMap("A369TBM21_DEL_FLG","TBM21_DEL_FLG",0,"svchar");this.setVCMap("A367TBM21_STUDY_NM","TBM21_STUDY_NM",0,"svchar");this.setVCMap("AV18P_SUBJECT_ID","vP_SUBJECT_ID",0,"int");this.setVCMap("A68TBM31_STUDY_ID","TBM31_STUDY_ID",0,"int");this.setVCMap("A69TBM31_CRF_ID","TBM31_CRF_ID",0,"int");this.setVCMap("AV16P_CRF_ID","vP_CRF_ID",0,"int");this.setVCMap("A397TBM31_DEL_FLG","TBM31_DEL_FLG",0,"svchar");this.setVCMap("A393TBM31_CRF_NM",
"TBM31_CRF_NM",0,"svchar");this.setVCMap("A642TBM31_CRF_SNM","TBM31_CRF_SNM",0,"svchar");this.setVCMap("A945TBM44_STUDY_ID","TBM44_STUDY_ID",0,"int");this.setVCMap("A946TBM44_CRF_ID","TBM44_CRF_ID",0,"int");this.setVCMap("A947TBM44_CRF_EDA_NO","TBM44_CRF_EDA_NO",0,"int");this.setVCMap("AV34P_CRF_EDA_NO","vP_CRF_EDA_NO",0,"int");this.setVCMap("A948TBM44_VISIT_NO","TBM44_VISIT_NO",0,"int");this.setVCMap("A87TBT01_STUDY_ID","TBT01_STUDY_ID",0,"int");this.setVCMap("A88TBT01_SUBJECT_ID","TBT01_SUBJECT_ID",
0,"int");this.setVCMap("A441TBT01_DEL_FLG","TBT01_DEL_FLG",0,"svchar");this.setVCMap("A698TBT01_SITE_ID","TBT01_SITE_ID",0,"svchar");this.setVCMap("A57TAM08_SITE_ID","TAM08_SITE_ID",0,"svchar");this.setVCMap("A325TAM08_DEL_FLG","TAM08_DEL_FLG",0,"svchar");this.setVCMap("A319TAM08_SITE_NM","TAM08_SITE_NM",0,"svchar");this.setVCMap("A92TBT11_STUDY_ID","TBT11_STUDY_ID",0,"int");this.setVCMap("A93TBT11_SUBJECT_ID","TBT11_SUBJECT_ID",0,"int");this.setVCMap("A94TBT11_CRF_ID","TBT11_CRF_ID",0,"int");this.setVCMap("A95TBT11_CRF_VERSION",
"TBT11_CRF_VERSION",0,"int");this.setVCMap("A936TBT11_CRF_EDA_NO","TBT11_CRF_EDA_NO",0,"int");this.setVCMap("A670TBT11_DM_ARRIVAL_DATETIME","TBT11_DM_ARRIVAL_DATETIME",0,"dtime");this.setVCMap("A457TBT11_DEL_FLG","TBT11_DEL_FLG",0,"svchar");this.setVCMap("A669TBT11_DM_ARRIVAL_FLG","TBT11_DM_ARRIVAL_FLG",0,"svchar");this.setVCMap("A675TBT11_INPUT_END_FLG","TBT11_INPUT_END_FLG",0,"svchar");this.setVCMap("A666TBT11_UPLOAD_DATETIME","TBT11_UPLOAD_DATETIME",0,"dtime");this.setVCMap("A667TBT11_UPLOAD_USER_ID",
"TBT11_UPLOAD_USER_ID",0,"svchar");this.setVCMap("A55TAM07_USER_ID","TAM07_USER_ID",0,"svchar");this.setVCMap("A205TAM07_USER_NM","TAM07_USER_NM",0,"svchar");this.setVCMap("A891TBT11_UPD_RIYU","TBT11_UPD_RIYU",0,"svchar");this.setVCMap("AV21W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV33W_JS","vW_JS",0,"svchar");this.setVCMap("AV13H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV47Pgmname","vPGMNAME",0,"char");this.setVCMap("A63TBM21_STUDY_ID","TBM21_STUDY_ID",0,"int");
this.setVCMap("AV17P_STUDY_ID","vP_STUDY_ID",0,"int");this.setVCMap("A369TBM21_DEL_FLG","TBM21_DEL_FLG",0,"svchar");this.setVCMap("A367TBM21_STUDY_NM","TBM21_STUDY_NM",0,"svchar");this.setVCMap("AV18P_SUBJECT_ID","vP_SUBJECT_ID",0,"int");this.setVCMap("A68TBM31_STUDY_ID","TBM31_STUDY_ID",0,"int");this.setVCMap("A69TBM31_CRF_ID","TBM31_CRF_ID",0,"int");this.setVCMap("AV16P_CRF_ID","vP_CRF_ID",0,"int");this.setVCMap("A397TBM31_DEL_FLG","TBM31_DEL_FLG",0,"svchar");this.setVCMap("A393TBM31_CRF_NM","TBM31_CRF_NM",
0,"svchar");this.setVCMap("A642TBM31_CRF_SNM","TBM31_CRF_SNM",0,"svchar");this.setVCMap("A945TBM44_STUDY_ID","TBM44_STUDY_ID",0,"int");this.setVCMap("A946TBM44_CRF_ID","TBM44_CRF_ID",0,"int");this.setVCMap("A947TBM44_CRF_EDA_NO","TBM44_CRF_EDA_NO",0,"int");this.setVCMap("AV34P_CRF_EDA_NO","vP_CRF_EDA_NO",0,"int");this.setVCMap("A948TBM44_VISIT_NO","TBM44_VISIT_NO",0,"int");this.setVCMap("A87TBT01_STUDY_ID","TBT01_STUDY_ID",0,"int");this.setVCMap("A88TBT01_SUBJECT_ID","TBT01_SUBJECT_ID",0,"int");this.setVCMap("A441TBT01_DEL_FLG",
"TBT01_DEL_FLG",0,"svchar");this.setVCMap("A698TBT01_SITE_ID","TBT01_SITE_ID",0,"svchar");this.setVCMap("A57TAM08_SITE_ID","TAM08_SITE_ID",0,"svchar");this.setVCMap("A325TAM08_DEL_FLG","TAM08_DEL_FLG",0,"svchar");this.setVCMap("A319TAM08_SITE_NM","TAM08_SITE_NM",0,"svchar");this.setVCMap("A92TBT11_STUDY_ID","TBT11_STUDY_ID",0,"int");this.setVCMap("A93TBT11_SUBJECT_ID","TBT11_SUBJECT_ID",0,"int");this.setVCMap("A94TBT11_CRF_ID","TBT11_CRF_ID",0,"int");this.setVCMap("A95TBT11_CRF_VERSION","TBT11_CRF_VERSION",
0,"int");this.setVCMap("A936TBT11_CRF_EDA_NO","TBT11_CRF_EDA_NO",0,"int");this.setVCMap("A670TBT11_DM_ARRIVAL_DATETIME","TBT11_DM_ARRIVAL_DATETIME",0,"dtime");this.setVCMap("A457TBT11_DEL_FLG","TBT11_DEL_FLG",0,"svchar");this.setVCMap("A669TBT11_DM_ARRIVAL_FLG","TBT11_DM_ARRIVAL_FLG",0,"svchar");this.setVCMap("A675TBT11_INPUT_END_FLG","TBT11_INPUT_END_FLG",0,"svchar");this.setVCMap("A666TBT11_UPLOAD_DATETIME","TBT11_UPLOAD_DATETIME",0,"dtime");this.setVCMap("A667TBT11_UPLOAD_USER_ID","TBT11_UPLOAD_USER_ID",
0,"svchar");this.setVCMap("A55TAM07_USER_ID","TAM07_USER_ID",0,"svchar");this.setVCMap("A205TAM07_USER_NM","TAM07_USER_NM",0,"svchar");this.setVCMap("A891TBT11_UPD_RIYU","TBT11_UPD_RIYU",0,"svchar");this.setVCMap("AV21W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV33W_JS","vW_JS",0,"svchar");this.setVCMap("AV13H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");c.addRefreshingVar(this.GXValidFnc[195]);c.addRefreshingVar({rfrVar:"AV47Pgmname"});c.addRefreshingVar({rfrVar:"A63TBM21_STUDY_ID"});
c.addRefreshingVar({rfrVar:"AV17P_STUDY_ID"});c.addRefreshingVar({rfrVar:"A369TBM21_DEL_FLG"});c.addRefreshingVar({rfrVar:"A367TBM21_STUDY_NM"});c.addRefreshingVar({rfrVar:"AV18P_SUBJECT_ID"});c.addRefreshingVar({rfrVar:"A68TBM31_STUDY_ID"});c.addRefreshingVar({rfrVar:"A69TBM31_CRF_ID"});c.addRefreshingVar({rfrVar:"AV16P_CRF_ID"});c.addRefreshingVar({rfrVar:"A397TBM31_DEL_FLG"});c.addRefreshingVar({rfrVar:"A393TBM31_CRF_NM"});c.addRefreshingVar({rfrVar:"A642TBM31_CRF_SNM"});c.addRefreshingVar({rfrVar:"A945TBM44_STUDY_ID"});
c.addRefreshingVar({rfrVar:"A946TBM44_CRF_ID"});c.addRefreshingVar({rfrVar:"A947TBM44_CRF_EDA_NO"});c.addRefreshingVar({rfrVar:"AV34P_CRF_EDA_NO"});c.addRefreshingVar({rfrVar:"A948TBM44_VISIT_NO"});c.addRefreshingVar({rfrVar:"A87TBT01_STUDY_ID"});c.addRefreshingVar({rfrVar:"A88TBT01_SUBJECT_ID"});c.addRefreshingVar({rfrVar:"A441TBT01_DEL_FLG"});c.addRefreshingVar({rfrVar:"A698TBT01_SITE_ID"});c.addRefreshingVar({rfrVar:"A57TAM08_SITE_ID"});c.addRefreshingVar({rfrVar:"A325TAM08_DEL_FLG"});c.addRefreshingVar({rfrVar:"A319TAM08_SITE_NM"});
c.addRefreshingVar({rfrVar:"A92TBT11_STUDY_ID"});c.addRefreshingVar({rfrVar:"A93TBT11_SUBJECT_ID"});c.addRefreshingVar({rfrVar:"A94TBT11_CRF_ID"});c.addRefreshingVar({rfrVar:"A95TBT11_CRF_VERSION"});c.addRefreshingVar({rfrVar:"A936TBT11_CRF_EDA_NO"});c.addRefreshingVar({rfrVar:"A670TBT11_DM_ARRIVAL_DATETIME"});c.addRefreshingVar({rfrVar:"A457TBT11_DEL_FLG"});c.addRefreshingVar({rfrVar:"A669TBT11_DM_ARRIVAL_FLG"});c.addRefreshingVar({rfrVar:"A675TBT11_INPUT_END_FLG"});c.addRefreshingVar({rfrVar:"A666TBT11_UPLOAD_DATETIME"});
c.addRefreshingVar({rfrVar:"A667TBT11_UPLOAD_USER_ID"});c.addRefreshingVar({rfrVar:"A55TAM07_USER_ID"});c.addRefreshingVar({rfrVar:"A205TAM07_USER_NM"});c.addRefreshingVar({rfrVar:"A891TBT11_UPD_RIYU"});c.addRefreshingVar({rfrVar:"AV21W_A821_JS"});c.addRefreshingVar({rfrVar:"AV33W_JS"});c.addRefreshingVar({rfrVar:"AV13H_A_PAGING_SDT"});this.addGridBCProperty("W_b717_sd01_rekiinfo_crf_list",["TBT11_CRF_VERSION"],this.GXValidFnc[179],"AV22W_B717_SD01_REKIINFO_CRF_LIST");this.addGridBCProperty("W_b717_sd01_rekiinfo_crf_list",
["DM_ARRIVAL"],this.GXValidFnc[181],"AV22W_B717_SD01_REKIINFO_CRF_LIST");this.addGridBCProperty("W_b717_sd01_rekiinfo_crf_list",["INPUT_END"],this.GXValidFnc[183],"AV22W_B717_SD01_REKIINFO_CRF_LIST");this.addGridBCProperty("W_b717_sd01_rekiinfo_crf_list",["TBT11_UPLOAD_DATETIME_VC"],this.GXValidFnc[185],"AV22W_B717_SD01_REKIINFO_CRF_LIST");this.addGridBCProperty("W_b717_sd01_rekiinfo_crf_list",["TAM07_USER_NM"],this.GXValidFnc[187],"AV22W_B717_SD01_REKIINFO_CRF_LIST");this.addGridBCProperty("W_b717_sd01_rekiinfo_crf_list",
["TBT11_UPD_RIYU"],this.GXValidFnc[189],"AV22W_B717_SD01_REKIINFO_CRF_LIST");this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[197],"AV13H_A_PAGING_SDT");this.InitStandaloneVars()});gx.setParentObj(new b717_wp01_rekiinfo_crf);
