gx.evt.autoSkip=!1;
gx.define("a201_wp01_kngn_ptn_list",!1,function(){this.ServerClass="a201_wp01_kngn_ptn_list";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110p2_client");this.addKeyListener("5","e120p2_client");this.addKeyListener("6","e130p2_client");this.addKeyListener("7","e140p2_client");this.SetStandaloneVars=function(){this.AV36Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV8C_TAM02_APP_ID=gx.fn.getControlValue("vC_TAM02_APP_ID");
this.AV16P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV19W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.AV11H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.AV23W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG");this.AV31C_GRID_ROWS=gx.fn.getIntegerValue("vC_GRID_ROWS",",")};this.s122_client=function(){this.AV6H_TAM04_KNGN_PTN_NM=this.AV5D_TAM04_KNGN_PTN_NM="";this.AV11H_A_PAGING_SDT.PAGE_NO=1;this.AV15H_SRCH_FLG="0";this.AV24W_F7FLG=false;this.AV18W_A819_JS=this.AV10D_LINE=
"";this.s232_client()};this.s232_client=function(){gx.fn.setCtrlProperty("vD_LINE","Backcolor",gx.color.rgb(255,255,255))};this.s202_client=function(){this.AV6H_TAM04_KNGN_PTN_NM=this.AV5D_TAM04_KNGN_PTN_NM};this.s152_client=function(){};this.s162_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");if(""!=this.AV19W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV19W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+
"confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.s182_client=function(){this.s232_client()};this.e110p2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e120p2_client=
function(){this.executeServerEvent("'BTN_SRCH'",true)};this.e130p2_client=function(){this.executeServerEvent("'BTN_CLER'",true)};this.e140p2_client=function(){this.executeServerEvent("'BTN_EDIT'",true)};this.e320p2_client=function(a){this.executeServerEvent("'BTN_SEL'",true,a)};this.e330p2_client=function(a){this.executeServerEvent("'BTN_KNGN'",true,a)};this.e150p2_client=function(){this.executeServerEvent("'PAGE_FIRST'",true)};this.e160p2_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};
this.e170p2_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e180p2_client=function(){this.executeServerEvent("'PAGE_NEXT'",true)};this.e190p2_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e200p2_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e210p2_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e220p2_client=function(){this.executeServerEvent("'PAGE04'",true)};this.e230p2_client=function(){this.executeServerEvent("'PAGE05'",
true)};this.e240p2_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e250p2_client=function(){this.executeServerEvent("'PAGE07'",true)};this.e260p2_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e270p2_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e280p2_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e340p2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e350p2_client=function(a){this.executeServerEvent("CANCEL",
true,a)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,18,21,24,27,29,32,35,38,44,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92,95,98,101,104,107,110,113,116,119,122,125,128,131,134,136,139,141,144,149,152,157,159,161,167,169,171,173,175,181,184,185,186,187,188,189,190];this.GXLastCtrlId=190;var b=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",164,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"a201_wp01_kngn_ptn_list",[],true,1,true,true,10,false,false,false,"",
0,"px","\u884c\u8ffd\u52a0",true,false,true,null,null,false,"",false,[1,1,1,1]);b.startRow("","","","","","");b.startCell("","center","","","","","45px","","","");b.addTextBlock("BTN_SEL","e320p2_client");b.endCell();b.startCell("","","","","","","65px","","","");b.addTextBlock("BTN_SEL2","e330p2_client");b.endCell();b.startCell("","","","","","","50px","","","");b.addSingleLineEdit("D_grd_line",171,"vD_GRD_LINE","","","D_GRD_LINE","int",4,"chr",4,4,"right",null,[],"D_grd_line","D_GRD_LINE",true,
0,false,false,"ReadonlyAttribute",1,"");b.endCell();b.startCell("","","","","","","120px","","","");b.addSingleLineEdit(13,173,"TAM04_AUTH_CD","","","TAM04_AUTH_CD","svchar",2,"chr",2,2,"left",null,[],13,"TAM04_AUTH_CD",true,0,false,false,"ReadonlyAttribute",1,"");b.endCell();b.startCell("","","","","","","400px","","","");b.addSingleLineEdit(285,175,"TAM04_AUTH_NM","","","TAM04_AUTH_NM","svchar",40,"chr",40,40,"left",null,[],285,"TAM04_AUTH_NM",true,0,false,false,"ReadonlyAttribute",1,"");b.endCell();
b.endRow();this.setGrid(b);a[2]={fld:"TABLE1",grid:0};a[6]={fld:"TABLE2",grid:0};a[12]={fld:"TABLE14",grid:0};a[15]={fld:"TXT_BTN_REG",format:0,grid:0};a[18]={fld:"TABLE3",grid:0};a[21]={fld:"TABLE4",grid:0};a[24]={fld:"TABLE10",grid:0};a[27]={fld:"TEXTBLOCK16",format:0,grid:0};a[29]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM04_KNGN_PTN_NM",gxz:"ZV5D_TAM04_KNGN_PTN_NM",gxold:"OV5D_TAM04_KNGN_PTN_NM",gxvar:"AV5D_TAM04_KNGN_PTN_NM",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV5D_TAM04_KNGN_PTN_NM=a},v2z:function(a){gx.O.ZV5D_TAM04_KNGN_PTN_NM=a},v2c:function(){gx.fn.setControlValue("vD_TAM04_KNGN_PTN_NM",gx.O.AV5D_TAM04_KNGN_PTN_NM,0)},c2v:function(){gx.O.AV5D_TAM04_KNGN_PTN_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM04_KNGN_PTN_NM")},nac:gx.falseFn};a[32]={fld:"TABLE9",grid:0};a[35]={fld:"TEXTBLOCK45",format:0,grid:0};a[38]={fld:"TEXTBLOCK44",format:0,grid:0};a[44]={fld:"TBL_PAGE_AREA",
grid:0};a[47]={fld:"TXT_REC_CNT",format:0,grid:0};a[50]={fld:"TBL_PAGE",grid:0};a[53]={fld:"TBL_FIRST",grid:0};a[56]={fld:"TXT_FIRST",format:0,grid:0};a[59]={fld:"TBL_BACK",grid:0};a[62]={fld:"TXT_BACK",format:0,grid:0};a[65]={fld:"TBL_PAGE01",grid:0};a[68]={fld:"TXT_PAGE01",format:0,grid:0};a[71]={fld:"TBL_PAGE02",grid:0};a[74]={fld:"TXT_PAGE02",format:0,grid:0};a[77]={fld:"TBL_PAGE03",grid:0};a[80]={fld:"TXT_PAGE03",format:0,grid:0};a[83]={fld:"TBL_PAGE04",grid:0};a[86]={fld:"TXT_PAGE04",format:0,
grid:0};a[89]={fld:"TBL_PAGE05",grid:0};a[92]={fld:"TXT_PAGE05",format:0,grid:0};a[95]={fld:"TBL_PAGE06",grid:0};a[98]={fld:"TXT_PAGE06",format:0,grid:0};a[101]={fld:"TBL_PAGE07",grid:0};a[104]={fld:"TXT_PAGE07",format:0,grid:0};a[107]={fld:"TBL_PAGE08",grid:0};a[110]={fld:"TXT_PAGE08",format:0,grid:0};a[113]={fld:"TBL_PAGE09",grid:0};a[116]={fld:"TXT_PAGE09",format:0,grid:0};a[119]={fld:"TBL_PAGE10",grid:0};a[122]={fld:"TXT_PAGE10",format:0,grid:0};a[125]={fld:"TBL_NEXT",grid:0};a[128]={fld:"TXT_NEXT",
format:0,grid:0};a[131]={fld:"TBL_LAST",grid:0};a[134]={fld:"TXT_LAST",format:0,grid:0};a[136]={fld:"TBL_EDIT",grid:0};a[139]={fld:"TEXTBLOCK49",format:0,grid:0};a[141]={lvl:0,type:"char",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_LINE",gxz:"ZV10D_LINE",gxold:"OV10D_LINE",gxvar:"AV10D_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10D_LINE=a},v2z:function(a){gx.O.ZV10D_LINE=a},v2c:function(){gx.fn.setControlValue("vD_LINE",gx.O.AV10D_LINE,
0)},c2v:function(){gx.O.AV10D_LINE=this.val()},val:function(){return gx.fn.getControlValue("vD_LINE")},nac:gx.falseFn};a[144]={fld:"TEXTBLOCK50",format:0,grid:0};a[149]={fld:"TBL_GRID_HEADER",grid:0};a[152]={fld:"TBL_IN_GRID_HEADER",grid:0};a[157]={fld:"TEXTBLOCK7",format:0,grid:0};a[159]={fld:"TEXTBLOCK8",format:0,grid:0};a[161]={fld:"TEXTBLOCK13",format:0,grid:0};a[167]={fld:"BTN_SEL",format:0,grid:164};a[169]={fld:"BTN_SEL2",format:0,grid:164};a[171]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",
ro:0,isacc:0,grid:164,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_LINE",gxz:"ZV9D_GRD_LINE",gxold:"OV9D_GRD_LINE",gxvar:"AV9D_GRD_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV9D_GRD_LINE=gx.num.intval(a)},v2z:function(a){gx.O.ZV9D_GRD_LINE=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(164),gx.O.AV9D_GRD_LINE,0)},c2v:function(){gx.O.AV9D_GRD_LINE=gx.num.intval(this.val())},
val:function(a){return gx.fn.getGridIntegerValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(164),",")},nac:gx.falseFn};a[173]={lvl:2,type:"svchar",len:2,dec:0,sign:false,ro:1,isacc:0,grid:164,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM04_AUTH_CD",gxz:"Z13TAM04_AUTH_CD",gxold:"O13TAM04_AUTH_CD",gxvar:"A13TAM04_AUTH_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A13TAM04_AUTH_CD=a},v2z:function(a){gx.O.Z13TAM04_AUTH_CD=a},
v2c:function(a){gx.fn.setGridControlValue("TAM04_AUTH_CD",a||gx.fn.currentGridRowImpl(164),gx.O.A13TAM04_AUTH_CD,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A13TAM04_AUTH_CD=this.val()},val:function(a){return gx.fn.getGridControlValue("TAM04_AUTH_CD",a||gx.fn.currentGridRowImpl(164))},nac:gx.falseFn};a[175]={lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:164,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM04_AUTH_NM",gxz:"Z285TAM04_AUTH_NM",
gxold:"O285TAM04_AUTH_NM",gxvar:"A285TAM04_AUTH_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A285TAM04_AUTH_NM=a},v2z:function(a){gx.O.Z285TAM04_AUTH_NM=a},v2c:function(a){gx.fn.setGridControlValue("TAM04_AUTH_NM",a||gx.fn.currentGridRowImpl(164),gx.O.A285TAM04_AUTH_NM,0)},c2v:function(){gx.O.A285TAM04_AUTH_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("TAM04_AUTH_NM",a||gx.fn.currentGridRowImpl(164))},nac:gx.falseFn};a[181]=
{fld:"TBL_HIDDEN",grid:0};a[184]={fld:"TXT_JS_EVENT",format:1,grid:0};a[185]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV12H_INIT_FLG",gxold:"OV12H_INIT_FLG",gxvar:"AV12H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12H_INIT_FLG=a},v2z:function(a){gx.O.ZV12H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV12H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},
c2v:function(){gx.O.AV12H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(185,function(){});a[186]={lvl:0,type:"int",len:2,dec:0,sign:false,pic:"Z9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_ITEM_KBN",gxz:"ZV13H_ITEM_KBN",gxold:"OV13H_ITEM_KBN",gxvar:"AV13H_ITEM_KBN",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_ITEM_KBN=gx.num.intval(a)},v2z:function(a){gx.O.ZV13H_ITEM_KBN=gx.num.intval(a)},
v2c:function(){gx.fn.setControlValue("vH_ITEM_KBN",gx.O.AV13H_ITEM_KBN,0)},c2v:function(){gx.O.AV13H_ITEM_KBN=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vH_ITEM_KBN",",")},nac:gx.falseFn};a[187]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SRCH_FLG",gxz:"ZV15H_SRCH_FLG",gxold:"OV15H_SRCH_FLG",gxvar:"AV15H_SRCH_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_SRCH_FLG=
a},v2z:function(a){gx.O.ZV15H_SRCH_FLG=a},v2c:function(){gx.fn.setControlValue("vH_SRCH_FLG",gx.O.AV15H_SRCH_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV15H_SRCH_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_SRCH_FLG")},nac:gx.falseFn};this.declareDomainHdlr(187,function(){});a[188]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_TAM04_KNGN_PTN_NM",gxz:"ZV6H_TAM04_KNGN_PTN_NM",
gxold:"OV6H_TAM04_KNGN_PTN_NM",gxvar:"AV6H_TAM04_KNGN_PTN_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6H_TAM04_KNGN_PTN_NM=a},v2z:function(a){gx.O.ZV6H_TAM04_KNGN_PTN_NM=a},v2c:function(){gx.fn.setControlValue("vH_TAM04_KNGN_PTN_NM",gx.O.AV6H_TAM04_KNGN_PTN_NM,0)},c2v:function(){gx.O.AV6H_TAM04_KNGN_PTN_NM=this.val()},val:function(){return gx.fn.getControlValue("vH_TAM04_KNGN_PTN_NM")},nac:gx.falseFn};a[189]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,
fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV14H_KNGN_FLG",gxold:"OV14H_KNGN_FLG",gxvar:"AV14H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV14H_KNGN_FLG=a},v2z:function(a){gx.O.ZV14H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV14H_KNGN_FLG,0)},c2v:function(){gx.O.AV14H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};a[190]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",
ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLREC_CNT",gxz:"ZV34GXV1",gxold:"OV34GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=gx.num.intval(a)},v2z:function(a){gx.O.ZV34GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",",")},nac:gx.falseFn};this.OV10D_LINE=this.ZV10D_LINE=this.AV10D_LINE=this.OV5D_TAM04_KNGN_PTN_NM=
this.ZV5D_TAM04_KNGN_PTN_NM=this.AV5D_TAM04_KNGN_PTN_NM="";this.OV9D_GRD_LINE=this.ZV9D_GRD_LINE=0;this.OV12H_INIT_FLG=this.ZV12H_INIT_FLG=this.AV12H_INIT_FLG=this.O285TAM04_AUTH_NM=this.Z285TAM04_AUTH_NM=this.O13TAM04_AUTH_CD=this.Z13TAM04_AUTH_CD="";this.OV13H_ITEM_KBN=this.ZV13H_ITEM_KBN=this.AV13H_ITEM_KBN=0;this.OV14H_KNGN_FLG=this.ZV14H_KNGN_FLG=this.AV14H_KNGN_FLG=this.OV6H_TAM04_KNGN_PTN_NM=this.ZV6H_TAM04_KNGN_PTN_NM=this.AV6H_TAM04_KNGN_PTN_NM=this.OV15H_SRCH_FLG=this.ZV15H_SRCH_FLG=this.AV15H_SRCH_FLG=
"";this.OV34GXV1=this.ZV34GXV1=this.GXV1=0;this.AV12H_INIT_FLG=this.AV10D_LINE=this.AV5D_TAM04_KNGN_PTN_NM="";this.AV13H_ITEM_KBN=0;this.AV14H_KNGN_FLG=this.AV6H_TAM04_KNGN_PTN_NM=this.AV15H_SRCH_FLG="";this.AV9D_GRD_LINE=this.AV16P_MOVE_KBN=this.GXV1=0;this.AV19W_A821_JS=this.AV8C_TAM02_APP_ID=this.AV36Pgmname=this.A285TAM04_AUTH_NM=this.A13TAM04_AUTH_CD="";this.AV11H_A_PAGING_SDT={};this.AV23W_ERRFLG=false;this.AV31C_GRID_ROWS=0;this.AV18W_A819_JS="";this.AV24W_F7FLG=false;this.Events={e110p2_client:["'BTN_REG'",
true],e120p2_client:["'BTN_SRCH'",true],e130p2_client:["'BTN_CLER'",true],e140p2_client:["'BTN_EDIT'",true],e320p2_client:["'BTN_SEL'",true],e330p2_client:["'BTN_KNGN'",true],e150p2_client:["'PAGE_FIRST'",true],e160p2_client:["'PAGE_LAST'",true],e170p2_client:["'PAGE_BACK'",true],e180p2_client:["'PAGE_NEXT'",true],e190p2_client:["'PAGE01'",true],e200p2_client:["'PAGE02'",true],e210p2_client:["'PAGE03'",true],e220p2_client:["'PAGE04'",true],e230p2_client:["'PAGE05'",true],e240p2_client:["'PAGE06'",
true],e250p2_client:["'PAGE07'",true],e260p2_client:["'PAGE08'",true],e270p2_client:["'PAGE09'",true],e280p2_client:["'PAGE10'",true],e340p2_client:["ENTER",true],e350p2_client:["CANCEL",true]};this.setVCMap("AV36Pgmname","vPGMNAME",0,"char");this.setVCMap("AV8C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV16P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV19W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV11H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV23W_ERRFLG",
"vW_ERRFLG",0,"boolean");this.setVCMap("AV31C_GRID_ROWS","vC_GRID_ROWS",0,"int");this.setVCMap("AV36Pgmname","vPGMNAME",0,"char");this.setVCMap("AV8C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV16P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV19W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV11H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV23W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV31C_GRID_ROWS","vC_GRID_ROWS",0,"int");b.addRefreshingVar(this.GXValidFnc[187]);
b.addRefreshingVar(this.GXValidFnc[188]);b.addRefreshingVar(this.GXValidFnc[185]);b.addRefreshingVar({rfrVar:"AV36Pgmname"});b.addRefreshingVar(this.GXValidFnc[29]);b.addRefreshingVar({rfrVar:"AV8C_TAM02_APP_ID"});b.addRefreshingVar({rfrVar:"AV16P_MOVE_KBN"});b.addRefreshingVar({rfrVar:"AV19W_A821_JS"});b.addRefreshingVar({rfrVar:"AV11H_A_PAGING_SDT"});b.addRefreshingVar({rfrVar:"AV23W_ERRFLG"});b.addRefreshingVar({rfrVar:"AV9D_GRD_LINE",rfrProp:"Value",gxAttId:"D_grd_line"});b.addRefreshingVar({rfrVar:"AV31C_GRID_ROWS"});
this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[190],"AV11H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0178",lvl:1})});gx.setParentObj(new a201_wp01_kngn_ptn_list);
