gx.evt.autoSkip=!1;
gx.define("a202_wp01_kngn_ptn_reg",!1,function(){this.ServerClass="a202_wp01_kngn_ptn_reg";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("4","e110r2_client");this.addKeyListener("10","e120r2_client");this.addKeyListener("5","e130r2_client");this.SetStandaloneVars=function(){this.AV54Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV43W_GMN_EDIT_FLG=gx.fn.getControlValue("vW_GMN_EDIT_FLG");this.AV19C_TAM02_APP_ID=
gx.fn.getControlValue("vC_TAM02_APP_ID");this.AV10P_TAM04_KNGN_PTN_KBN=gx.fn.getControlValue("vP_TAM04_KNGN_PTN_KBN");this.AV44W_IKKATU_FLG=gx.fn.getControlValue("vW_IKKATU_FLG");this.AV11W_A202_SD01_APPLI_KNGN_LIST=gx.fn.getControlValue("vW_A202_SD01_APPLI_KNGN_LIST");this.AV38W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.A55TAM07_USER_ID=gx.fn.getControlValue("TAM07_USER_ID");this.AV14BC_KNGN_PTN=gx.fn.getControlValue("vBC_KNGN_PTN");this.A205TAM07_USER_NM=gx.fn.getControlValue("TAM07_USER_NM");
this.A12TAM03_APP_ID=gx.fn.getControlValue("TAM03_APP_ID");this.A314TAM03_APP_NM=gx.fn.getControlValue("TAM03_APP_NM");this.A315TAM03_SUB_MENU_FLG=gx.fn.getControlValue("TAM03_SUB_MENU_FLG");this.A13TAM04_AUTH_CD=gx.fn.getControlValue("TAM04_AUTH_CD");this.A288TAM05_KNGN_FLG=gx.fn.getControlValue("TAM05_KNGN_FLG")};this.Validv_W_tam04_kngn_ptn_kbn=function(){try{var a=gx.util.balloon.getNew("vW_TAM04_KNGN_PTN_KBN");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};
this.s122_client=function(){this.AV38W_A821_JS=""};this.s152_client=function(){this.AV43W_GMN_EDIT_FLG="1";for(var a=1,b=gx.fn.currentGridRowImpl(92),c=gx.O.getGridById(92,0);a<=c.grid.rows.length;){gx.text.padl(gx.text.tostring(a),4,"0");c.instanciateRow(c.grid.getRowById(a-1));if(this.AV44W_IKKATU_FLG=="1"){this.AV5D_GRD_MENU_TAM05_KNGN_FLG="1";this.AV6D_GRD_RIYO_TAM05_KNGN_FLG=this.AV24D_TAM05_KNGN_FLG}for(this.AV57GXV8=1;this.AV57GXV8<=this.AV11W_A202_SD01_APPLI_KNGN_LIST.length;){this.AV37W_A202_SD01_APPLI_KNGN_LIST_Item=
this.AV11W_A202_SD01_APPLI_KNGN_LIST[this.AV57GXV8-1];if(this.AV7D_GRD_TAM03_APP_ID==this.AV37W_A202_SD01_APPLI_KNGN_LIST_Item.TAM03_APP_ID){this.AV37W_A202_SD01_APPLI_KNGN_LIST_Item.TAM05_KNGN_FLG=this.AV9D_GRD_TAM03_SUB_MENU_FLG=="1"?this.AV5D_GRD_MENU_TAM05_KNGN_FLG:this.AV6D_GRD_RIYO_TAM05_KNGN_FLG;break}this.AV57GXV8=this.AV57GXV8+1}a=a+1}b&&c.instanciateRow(b)};this.s162_client=function(){if(this.AV29H_MODE!="0"){gx.fn.setCtrlProperty("TBL_UPD_BTNSET","Visible",true);gx.fn.setCtrlProperty("CTLTAM04_CRT_DATETIME",
"Visible",true);gx.fn.setCtrlProperty("CTLTAM04_UPD_DATETIME","Visible",true);gx.fn.setCtrlProperty("CTLTAM04_AUTH_CD","Enabled",false)}this.s252_client()};this.s252_client=function(){};this.s172_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+
"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");if(""!=this.AV38W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV38W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.e110r2_client=function(){this.executeServerEvent("'BTN_UPD'",true)};this.e140r2_client=function(){this.executeServerEvent("'BTN_REG_EXEC'",true)};this.e120r2_client=function(){this.executeServerEvent("'BTN_CAN'",
true)};this.e130r2_client=function(){this.executeServerEvent("'BTN_SRCH'",true)};this.e150r2_client=function(){this.executeServerEvent("'BTN_IKKATU'",true)};this.e190r2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e200r2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,18,23,26,32,35,37,39,41,46,50,53,56,58,60,64,67,72,75,77,82,85,87,89,95,97,99,100,102,107,110,112,114,116,119,121,123,125,126,129,130,131,132,133,134,
135,136,139,141,144,146,148];this.GXLastCtrlId=148;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",92,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"a202_wp01_kngn_ptn_reg",[],true,1,true,true,0,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",false,false,true,null,null,false,"",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","","","","","","78px","","","");c.addSingleLineEdit("D_grd_tam03_app_id",95,"vD_GRD_TAM03_APP_ID","","","D_GRD_TAM03_APP_ID","svchar",
7,"chr",7,7,"left",null,[],"D_grd_tam03_app_id","D_GRD_TAM03_APP_ID",true,0,false,false,"ReadonlyAttribute",1,"");c.endCell();c.startCell("","","","","","","265px","","","");c.addSingleLineEdit("D_grd_tam03_app_nm",97,"vD_GRD_TAM03_APP_NM","","","D_GRD_TAM03_APP_NM","svchar",40,"chr",40,40,"left",null,[],"D_grd_tam03_app_nm","D_GRD_TAM03_APP_NM",true,0,false,false,"ReadonlyAttribute",1,"");c.endCell();c.startCell("","","","","","","130px","","","");c.addRadioButton("D_grd_menu_tam05_kngn_flg",99,
"vD_GRD_MENU_TAM05_KNGN_FLG","","D_GRD_MENU_TAM05_KNGN_FLG","svchar",null,true,true,false,"");c.addSingleLineEdit("D_grd_tam03_sub_menu_flg",100,"vD_GRD_TAM03_SUB_MENU_FLG","","","D_GRD_TAM03_SUB_MENU_FLG","svchar",1,"chr",1,1,"left",null,[],"D_grd_tam03_sub_menu_flg","D_GRD_TAM03_SUB_MENU_FLG",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","","","","","","345px","","","");c.addRadioButton("D_grd_riyo_tam05_kngn_flg",102,"vD_GRD_RIYO_TAM05_KNGN_FLG","","D_GRD_RIYO_TAM05_KNGN_FLG",
"svchar",null,true,true,false,"");c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE2",grid:0};b[6]={fld:"TABLE3",grid:0};b[12]={fld:"TABLE6",grid:0};b[15]={fld:"TBL_UPD_BTNSET",grid:0};b[18]={fld:"TXT_BTN_UPD",format:0,grid:0};b[23]={fld:"TEXTBLOCK46",format:0,grid:0};b[26]={fld:"TABLE5",grid:0};b[32]={fld:"TABLE10",grid:0};b[35]={fld:"TEXTBLOCK5",format:0,grid:0};b[37]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_AUTH_CD",
gxz:"ZV48GXV1",gxold:"OV48GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=a},v2z:function(a){gx.O.ZV48GXV1=a},v2c:function(){gx.fn.setControlValue("CTLTAM04_AUTH_CD",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM04_AUTH_CD")},nac:gx.falseFn};b[39]={fld:"TEXTBLOCK52",format:0,grid:0};b[41]={fld:"TXT_AUTH_NAME",format:1,grid:0};b[46]={fld:"TABLE4",grid:0};b[50]={fld:"TABLE12",grid:0};b[53]={fld:"TABLE11",
grid:0};b[56]={fld:"TEXTBLOCK29",format:0,grid:0};b[58]={lvl:0,type:"svchar",len:7,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM03_APP_ID",gxz:"ZV20D_TAM03_APP_ID",gxold:"OV20D_TAM03_APP_ID",gxvar:"AV20D_TAM03_APP_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV20D_TAM03_APP_ID=a},v2z:function(a){gx.O.ZV20D_TAM03_APP_ID=a},v2c:function(){gx.fn.setControlValue("vD_TAM03_APP_ID",gx.O.AV20D_TAM03_APP_ID,0)},c2v:function(){gx.O.AV20D_TAM03_APP_ID=
this.val()},val:function(){return gx.fn.getControlValue("vD_TAM03_APP_ID")},nac:gx.falseFn};b[60]={fld:"TEXTBLOCK54",format:0,grid:0};b[64]={fld:"TBL_PAGE_AREA",grid:0};b[67]={fld:"TXT_REC_CNT",format:0,grid:0};b[72]={fld:"TABLE9",grid:0};b[75]={fld:"TEXTBLOCK48",format:0,grid:0};b[77]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM05_KNGN_FLG",gxz:"ZV24D_TAM05_KNGN_FLG",gxold:"OV24D_TAM05_KNGN_FLG",gxvar:"AV24D_TAM05_KNGN_FLG",ucs:[],
op:[],ip:[],nacdep:[],ctrltype:"radio",v2v:function(a){gx.O.AV24D_TAM05_KNGN_FLG=a},v2z:function(a){gx.O.ZV24D_TAM05_KNGN_FLG=a},v2c:function(){gx.fn.setRadioValue("vD_TAM05_KNGN_FLG",gx.O.AV24D_TAM05_KNGN_FLG)},c2v:function(){gx.O.AV24D_TAM05_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM05_KNGN_FLG")},nac:gx.falseFn};b[82]={fld:"TABLE15",grid:0};b[85]={fld:"TEXTBLOCK13",format:0,grid:0};b[87]={fld:"TEXTBLOCK17",format:0,grid:0};b[89]={fld:"TEXTBLOCK22",format:0,grid:0};
b[95]={lvl:2,type:"svchar",len:7,dec:0,sign:false,ro:0,isacc:0,grid:92,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_TAM03_APP_ID",gxz:"ZV7D_GRD_TAM03_APP_ID",gxold:"OV7D_GRD_TAM03_APP_ID",gxvar:"AV7D_GRD_TAM03_APP_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV7D_GRD_TAM03_APP_ID=a},v2z:function(a){gx.O.ZV7D_GRD_TAM03_APP_ID=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_TAM03_APP_ID",a||gx.fn.currentGridRowImpl(92),
gx.O.AV7D_GRD_TAM03_APP_ID,0)},c2v:function(){gx.O.AV7D_GRD_TAM03_APP_ID=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_TAM03_APP_ID",a||gx.fn.currentGridRowImpl(92))},nac:gx.falseFn};b[97]={lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:0,isacc:0,grid:92,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_TAM03_APP_NM",gxz:"ZV8D_GRD_TAM03_APP_NM",gxold:"OV8D_GRD_TAM03_APP_NM",gxvar:"AV8D_GRD_TAM03_APP_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",
autoCorrect:"1",v2v:function(a){gx.O.AV8D_GRD_TAM03_APP_NM=a},v2z:function(a){gx.O.ZV8D_GRD_TAM03_APP_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_TAM03_APP_NM",a||gx.fn.currentGridRowImpl(92),gx.O.AV8D_GRD_TAM03_APP_NM,0)},c2v:function(){gx.O.AV8D_GRD_TAM03_APP_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_TAM03_APP_NM",a||gx.fn.currentGridRowImpl(92))},nac:gx.falseFn};b[99]={lvl:2,type:"svchar",len:1,dec:0,sign:false,ro:0,isacc:0,grid:92,gxgrid:this.Grid1Container,
fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_MENU_TAM05_KNGN_FLG",gxz:"ZV5D_GRD_MENU_TAM05_KNGN_FLG",gxold:"OV5D_GRD_MENU_TAM05_KNGN_FLG",gxvar:"AV5D_GRD_MENU_TAM05_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",inputType:"text",v2v:function(a){gx.O.AV5D_GRD_MENU_TAM05_KNGN_FLG=a},v2z:function(a){gx.O.ZV5D_GRD_MENU_TAM05_KNGN_FLG=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_MENU_TAM05_KNGN_FLG",a||gx.fn.currentGridRowImpl(92),gx.O.AV5D_GRD_MENU_TAM05_KNGN_FLG,0)},c2v:function(){gx.O.AV5D_GRD_MENU_TAM05_KNGN_FLG=
this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_MENU_TAM05_KNGN_FLG",a||gx.fn.currentGridRowImpl(92))},nac:gx.falseFn};b[100]={lvl:2,type:"svchar",len:1,dec:0,sign:false,ro:0,isacc:0,grid:92,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_TAM03_SUB_MENU_FLG",gxz:"ZV9D_GRD_TAM03_SUB_MENU_FLG",gxold:"OV9D_GRD_TAM03_SUB_MENU_FLG",gxvar:"AV9D_GRD_TAM03_SUB_MENU_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV9D_GRD_TAM03_SUB_MENU_FLG=
a},v2z:function(a){gx.O.ZV9D_GRD_TAM03_SUB_MENU_FLG=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_TAM03_SUB_MENU_FLG",a||gx.fn.currentGridRowImpl(92),gx.O.AV9D_GRD_TAM03_SUB_MENU_FLG,0)},c2v:function(){gx.O.AV9D_GRD_TAM03_SUB_MENU_FLG=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_TAM03_SUB_MENU_FLG",a||gx.fn.currentGridRowImpl(92))},nac:gx.falseFn};b[102]={lvl:2,type:"svchar",len:1,dec:0,sign:false,ro:0,isacc:0,grid:92,gxgrid:this.Grid1Container,fnc:null,isvalid:null,
rgrid:[],fld:"vD_GRD_RIYO_TAM05_KNGN_FLG",gxz:"ZV6D_GRD_RIYO_TAM05_KNGN_FLG",gxold:"OV6D_GRD_RIYO_TAM05_KNGN_FLG",gxvar:"AV6D_GRD_RIYO_TAM05_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",inputType:"text",v2v:function(a){gx.O.AV6D_GRD_RIYO_TAM05_KNGN_FLG=a},v2z:function(a){gx.O.ZV6D_GRD_RIYO_TAM05_KNGN_FLG=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_RIYO_TAM05_KNGN_FLG",a||gx.fn.currentGridRowImpl(92),gx.O.AV6D_GRD_RIYO_TAM05_KNGN_FLG,0)},c2v:function(){gx.O.AV6D_GRD_RIYO_TAM05_KNGN_FLG=
this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_RIYO_TAM05_KNGN_FLG",a||gx.fn.currentGridRowImpl(92))},nac:gx.falseFn};b[107]={fld:"TABLE13",grid:0};b[110]={fld:"TEXTBLOCK24",format:0,grid:0};b[112]={lvl:0,type:"dtime",len:10,dec:8,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_CRT_DATETIME",gxz:"ZV49GXV2",gxold:"OV49GXV2",gxvar:"GXV2",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",
v2v:function(a){gx.O.GXV2=gx.fn.toDatetimeValue(a,"Y4MD")},v2z:function(a){gx.O.ZV49GXV2=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTAM04_CRT_DATETIME",gx.O.GXV2,0)},c2v:function(){gx.O.GXV2=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTAM04_CRT_DATETIME")},nac:gx.falseFn};b[114]={fld:"TEXTBLOCK26",format:0,grid:0};b[116]={lvl:0,type:"dtime",len:10,dec:8,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_UPD_DATETIME",
gxz:"ZV50GXV3",gxold:"OV50GXV3",gxvar:"GXV3",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV3=gx.fn.toDatetimeValue(a,"Y4MD")},v2z:function(a){gx.O.ZV50GXV3=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTAM04_UPD_DATETIME",gx.O.GXV3,0)},c2v:function(){gx.O.GXV3=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTAM04_UPD_DATETIME")},nac:gx.falseFn};b[119]=
{fld:"TEXTBLOCK25",format:0,grid:0};b[121]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM04_CRT_USER_NM",gxz:"ZV22D_TAM04_CRT_USER_NM",gxold:"OV22D_TAM04_CRT_USER_NM",gxvar:"AV22D_TAM04_CRT_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV22D_TAM04_CRT_USER_NM=a},v2z:function(a){gx.O.ZV22D_TAM04_CRT_USER_NM=a},v2c:function(){gx.fn.setControlValue("vD_TAM04_CRT_USER_NM",gx.O.AV22D_TAM04_CRT_USER_NM,1)},c2v:function(){gx.O.AV22D_TAM04_CRT_USER_NM=
this.val()},val:function(){return gx.fn.getControlValue("vD_TAM04_CRT_USER_NM")},nac:gx.falseFn};b[123]={fld:"TEXTBLOCK27",format:0,grid:0};b[125]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM04_UPD_USER_NM",gxz:"ZV23D_TAM04_UPD_USER_NM",gxold:"OV23D_TAM04_UPD_USER_NM",gxvar:"AV23D_TAM04_UPD_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV23D_TAM04_UPD_USER_NM=a},v2z:function(a){gx.O.ZV23D_TAM04_UPD_USER_NM=
a},v2c:function(){gx.fn.setControlValue("vD_TAM04_UPD_USER_NM",gx.O.AV23D_TAM04_UPD_USER_NM,1)},c2v:function(){gx.O.AV23D_TAM04_UPD_USER_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM04_UPD_USER_NM")},nac:gx.falseFn};b[126]={fld:"TBL_HIDDEN",grid:0};b[129]={fld:"TXT_JS_EVENT",format:1,grid:0};b[130]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV27H_INIT_FLG",gxold:"OV27H_INIT_FLG",gxvar:"AV27H_INIT_FLG",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV27H_INIT_FLG=a},v2z:function(a){gx.O.ZV27H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV27H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV27H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(130,function(){});b[131]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,
isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV28H_KNGN_FLG",gxold:"OV28H_KNGN_FLG",gxvar:"AV28H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV28H_KNGN_FLG=a},v2z:function(a){gx.O.ZV28H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV28H_KNGN_FLG,0)},c2v:function(){gx.O.AV28H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[132]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,
fnc:null,isvalid:null,rgrid:[],fld:"vH_MODE",gxz:"ZV29H_MODE",gxold:"OV29H_MODE",gxvar:"AV29H_MODE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV29H_MODE=a},v2z:function(a){gx.O.ZV29H_MODE=a},v2c:function(){gx.fn.setControlValue("vH_MODE",gx.O.AV29H_MODE,0)},c2v:function(){gx.O.AV29H_MODE=this.val()},val:function(){return gx.fn.getControlValue("vH_MODE")},nac:gx.falseFn};b[133]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_W_tam04_kngn_ptn_kbn,
isvalid:null,rgrid:[],fld:"vW_TAM04_KNGN_PTN_KBN",gxz:"ZV12W_TAM04_KNGN_PTN_KBN",gxold:"OV12W_TAM04_KNGN_PTN_KBN",gxvar:"AV12W_TAM04_KNGN_PTN_KBN",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12W_TAM04_KNGN_PTN_KBN=a},v2z:function(a){gx.O.ZV12W_TAM04_KNGN_PTN_KBN=a},v2c:function(){gx.fn.setControlValue("vW_TAM04_KNGN_PTN_KBN",gx.O.AV12W_TAM04_KNGN_PTN_KBN,0)},c2v:function(){gx.O.AV12W_TAM04_KNGN_PTN_KBN=this.val()},val:function(){return gx.fn.getControlValue("vW_TAM04_KNGN_PTN_KBN")},
nac:gx.falseFn};b[134]={lvl:0,type:"svchar",len:7,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_TAM03_APP_ID",gxz:"ZV30H_TAM03_APP_ID",gxold:"OV30H_TAM03_APP_ID",gxvar:"AV30H_TAM03_APP_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV30H_TAM03_APP_ID=a},v2z:function(a){gx.O.ZV30H_TAM03_APP_ID=a},v2c:function(){gx.fn.setControlValue("vH_TAM03_APP_ID",gx.O.AV30H_TAM03_APP_ID,0)},c2v:function(){gx.O.AV30H_TAM03_APP_ID=this.val()},val:function(){return gx.fn.getControlValue("vH_TAM03_APP_ID")},
nac:gx.falseFn};b[135]={fld:"TXT_BTN_REG_EXEC",format:0,grid:0};b[136]={fld:"TABLE7",grid:0};b[139]={fld:"TEXTBLOCK30",format:0,grid:0};b[141]={lvl:0,type:"svchar",len:128,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_CRT_USER_ID",gxz:"ZV51GXV4",gxold:"OV51GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV4=a},v2z:function(a){gx.O.ZV51GXV4=a},v2c:function(){gx.fn.setControlValue("CTLTAM04_CRT_USER_ID",gx.O.GXV4,0)},c2v:function(){gx.O.GXV4=
this.val()},val:function(){return gx.fn.getControlValue("CTLTAM04_CRT_USER_ID")},nac:gx.falseFn};b[144]={fld:"TEXTBLOCK33",format:0,grid:0};b[146]={lvl:0,type:"svchar",len:128,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM04_UPD_USER_ID",gxz:"ZV52GXV5",gxold:"OV52GXV5",gxvar:"GXV5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV5=a},v2z:function(a){gx.O.ZV52GXV5=a},v2c:function(){gx.fn.setControlValue("CTLTAM04_UPD_USER_ID",gx.O.GXV5,0)},
c2v:function(){gx.O.GXV5=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM04_UPD_USER_ID")},nac:gx.falseFn};b[148]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vW_CNT",gxz:"ZV39W_CNT",gxold:"OV39W_CNT",gxvar:"AV39W_CNT",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV39W_CNT=gx.num.intval(a)},v2z:function(a){gx.O.ZV39W_CNT=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vW_CNT",gx.O.AV39W_CNT,
0)},c2v:function(){gx.O.AV39W_CNT=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vW_CNT",",")},nac:gx.falseFn};this.OV6D_GRD_RIYO_TAM05_KNGN_FLG=this.ZV6D_GRD_RIYO_TAM05_KNGN_FLG=this.OV9D_GRD_TAM03_SUB_MENU_FLG=this.ZV9D_GRD_TAM03_SUB_MENU_FLG=this.OV5D_GRD_MENU_TAM05_KNGN_FLG=this.ZV5D_GRD_MENU_TAM05_KNGN_FLG=this.OV8D_GRD_TAM03_APP_NM=this.ZV8D_GRD_TAM03_APP_NM=this.OV7D_GRD_TAM03_APP_ID=this.ZV7D_GRD_TAM03_APP_ID=this.OV24D_TAM05_KNGN_FLG=this.ZV24D_TAM05_KNGN_FLG=this.AV24D_TAM05_KNGN_FLG=
this.OV20D_TAM03_APP_ID=this.ZV20D_TAM03_APP_ID=this.AV20D_TAM03_APP_ID=this.OV48GXV1=this.ZV48GXV1=this.GXV1="";this.GXV2=gx.date.nullDate();this.ZV49GXV2=gx.date.nullDate();this.OV49GXV2=gx.date.nullDate();this.GXV3=gx.date.nullDate();this.ZV50GXV3=gx.date.nullDate();this.OV50GXV3=gx.date.nullDate();this.OV52GXV5=this.ZV52GXV5=this.GXV5=this.OV51GXV4=this.ZV51GXV4=this.GXV4=this.OV30H_TAM03_APP_ID=this.ZV30H_TAM03_APP_ID=this.AV30H_TAM03_APP_ID=this.OV12W_TAM04_KNGN_PTN_KBN=this.ZV12W_TAM04_KNGN_PTN_KBN=
this.AV12W_TAM04_KNGN_PTN_KBN=this.OV29H_MODE=this.ZV29H_MODE=this.AV29H_MODE=this.OV28H_KNGN_FLG=this.ZV28H_KNGN_FLG=this.AV28H_KNGN_FLG=this.OV27H_INIT_FLG=this.ZV27H_INIT_FLG=this.AV27H_INIT_FLG=this.OV23D_TAM04_UPD_USER_NM=this.ZV23D_TAM04_UPD_USER_NM=this.AV23D_TAM04_UPD_USER_NM=this.OV22D_TAM04_CRT_USER_NM=this.ZV22D_TAM04_CRT_USER_NM=this.AV22D_TAM04_CRT_USER_NM="";this.OV39W_CNT=this.ZV39W_CNT=this.AV39W_CNT=0;this.AV24D_TAM05_KNGN_FLG=this.AV20D_TAM03_APP_ID=this.GXV1="";this.GXV2=gx.date.nullDate();
this.GXV3=gx.date.nullDate();this.GXV6=this.GXV5=this.GXV4=this.AV30H_TAM03_APP_ID=this.AV12W_TAM04_KNGN_PTN_KBN=this.AV29H_MODE=this.AV28H_KNGN_FLG=this.AV27H_INIT_FLG=this.AV23D_TAM04_UPD_USER_NM=this.AV22D_TAM04_CRT_USER_NM="";this.AV39W_CNT=0;this.AV44W_IKKATU_FLG=this.AV19C_TAM02_APP_ID=this.AV43W_GMN_EDIT_FLG=this.AV54Pgmname=this.A205TAM07_USER_NM=this.A55TAM07_USER_ID=this.A288TAM05_KNGN_FLG=this.A13TAM04_AUTH_CD=this.A315TAM03_SUB_MENU_FLG=this.A314TAM03_APP_NM=this.A12TAM03_APP_ID=this.AV6D_GRD_RIYO_TAM05_KNGN_FLG=
this.AV9D_GRD_TAM03_SUB_MENU_FLG=this.AV5D_GRD_MENU_TAM05_KNGN_FLG=this.AV8D_GRD_TAM03_APP_NM=this.AV7D_GRD_TAM03_APP_ID=this.AV10P_TAM04_KNGN_PTN_KBN="";this.AV11W_A202_SD01_APPLI_KNGN_LIST=[];this.AV38W_A821_JS="";this.AV14BC_KNGN_PTN={};this.AV37W_A202_SD01_APPLI_KNGN_LIST_Item={};this.AV57GXV8=0;this.Events={e110r2_client:["'BTN_UPD'",true],e140r2_client:["'BTN_REG_EXEC'",true],e120r2_client:["'BTN_CAN'",true],e130r2_client:["'BTN_SRCH'",true],e150r2_client:["'BTN_IKKATU'",true],e190r2_client:["ENTER",
true],e200r2_client:["CANCEL",true]};this.setVCMap("AV54Pgmname","vPGMNAME",0,"char");this.setVCMap("AV43W_GMN_EDIT_FLG","vW_GMN_EDIT_FLG",0,"svchar");this.setVCMap("AV19C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV10P_TAM04_KNGN_PTN_KBN","vP_TAM04_KNGN_PTN_KBN",0,"svchar");this.setVCMap("AV44W_IKKATU_FLG","vW_IKKATU_FLG",0,"svchar");this.setVCMap("AV11W_A202_SD01_APPLI_KNGN_LIST","vW_A202_SD01_APPLI_KNGN_LIST",0,"CollA202_SD01_APPLI_KNGN_LIST.A202_SD01_APPLI_KNGN_LISTItem");this.setVCMap("AV38W_A821_JS",
"vW_A821_JS",0,"svchar");this.setVCMap("A55TAM07_USER_ID","TAM07_USER_ID",0,"svchar");this.setVCMap("AV14BC_KNGN_PTN","vBC_KNGN_PTN",0,"TAM04BC_KNGN");this.setVCMap("A205TAM07_USER_NM","TAM07_USER_NM",0,"svchar");this.setVCMap("A12TAM03_APP_ID","TAM03_APP_ID",0,"svchar");this.setVCMap("A314TAM03_APP_NM","TAM03_APP_NM",0,"svchar");this.setVCMap("A315TAM03_SUB_MENU_FLG","TAM03_SUB_MENU_FLG",0,"svchar");this.setVCMap("A13TAM04_AUTH_CD","TAM04_AUTH_CD",0,"svchar");this.setVCMap("A288TAM05_KNGN_FLG","TAM05_KNGN_FLG",
0,"svchar");this.setVCMap("AV54Pgmname","vPGMNAME",0,"char");this.setVCMap("AV43W_GMN_EDIT_FLG","vW_GMN_EDIT_FLG",0,"svchar");this.setVCMap("AV19C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV10P_TAM04_KNGN_PTN_KBN","vP_TAM04_KNGN_PTN_KBN",0,"svchar");this.setVCMap("AV44W_IKKATU_FLG","vW_IKKATU_FLG",0,"svchar");this.setVCMap("AV11W_A202_SD01_APPLI_KNGN_LIST","vW_A202_SD01_APPLI_KNGN_LIST",0,"CollA202_SD01_APPLI_KNGN_LIST.A202_SD01_APPLI_KNGN_LISTItem");this.setVCMap("AV38W_A821_JS",
"vW_A821_JS",0,"svchar");this.setVCMap("A55TAM07_USER_ID","TAM07_USER_ID",0,"svchar");this.setVCMap("AV14BC_KNGN_PTN","vBC_KNGN_PTN",0,"TAM04BC_KNGN");this.setVCMap("A205TAM07_USER_NM","TAM07_USER_NM",0,"svchar");this.setVCMap("A12TAM03_APP_ID","TAM03_APP_ID",0,"svchar");this.setVCMap("A314TAM03_APP_NM","TAM03_APP_NM",0,"svchar");this.setVCMap("A315TAM03_SUB_MENU_FLG","TAM03_SUB_MENU_FLG",0,"svchar");this.setVCMap("A13TAM04_AUTH_CD","TAM04_AUTH_CD",0,"svchar");this.setVCMap("A288TAM05_KNGN_FLG","TAM05_KNGN_FLG",
0,"svchar");c.addRefreshingVar(this.GXValidFnc[130]);c.addRefreshingVar({rfrVar:"AV54Pgmname"});c.addRefreshingVar({rfrVar:"AV43W_GMN_EDIT_FLG"});c.addRefreshingVar({rfrVar:"AV19C_TAM02_APP_ID"});c.addRefreshingVar({rfrVar:"AV10P_TAM04_KNGN_PTN_KBN"});c.addRefreshingVar(this.GXValidFnc[58]);c.addRefreshingVar({rfrVar:"AV44W_IKKATU_FLG"});c.addRefreshingVar(this.GXValidFnc[77]);c.addRefreshingVar({rfrVar:"AV11W_A202_SD01_APPLI_KNGN_LIST"});c.addRefreshingVar({rfrVar:"AV7D_GRD_TAM03_APP_ID",rfrProp:"Value",
gxAttId:"D_grd_tam03_app_id"});c.addRefreshingVar({rfrVar:"AV9D_GRD_TAM03_SUB_MENU_FLG",rfrProp:"Value",gxAttId:"D_grd_tam03_sub_menu_flg"});c.addRefreshingVar({rfrVar:"AV5D_GRD_MENU_TAM05_KNGN_FLG",rfrProp:"Value",gxAttId:"D_grd_menu_tam05_kngn_flg"});c.addRefreshingVar({rfrVar:"AV6D_GRD_RIYO_TAM05_KNGN_FLG",rfrProp:"Value",gxAttId:"D_grd_riyo_tam05_kngn_flg"});c.addRefreshingVar(this.GXValidFnc[132]);c.addRefreshingVar({rfrVar:"AV38W_A821_JS"});c.addRefreshingVar(this.GXValidFnc[148]);c.addRefreshingVar(this.GXValidFnc[133]);
c.addRefreshingVar({rfrVar:"A55TAM07_USER_ID"});c.addRefreshingVar({rfrVar:"AV14BC_KNGN_PTN"});c.addRefreshingVar({rfrVar:"A205TAM07_USER_NM"});c.addRefreshingVar({rfrVar:"A12TAM03_APP_ID"});c.addRefreshingVar({rfrVar:"A314TAM03_APP_NM"});c.addRefreshingVar({rfrVar:"A315TAM03_SUB_MENU_FLG"});c.addRefreshingVar({rfrVar:"A13TAM04_AUTH_CD"});c.addRefreshingVar({rfrVar:"A288TAM05_KNGN_FLG"});c.addRefreshingVar(this.GXValidFnc[134]);this.addBCProperty("Bc_kngn_ptn",["TAM04_AUTH_CD"],this.GXValidFnc[37],
"AV14BC_KNGN_PTN");this.addBCProperty("Bc_kngn_ptn",["TAM04_CRT_DATETIME"],this.GXValidFnc[112],"AV14BC_KNGN_PTN");this.addBCProperty("Bc_kngn_ptn",["TAM04_UPD_DATETIME"],this.GXValidFnc[116],"AV14BC_KNGN_PTN");this.addBCProperty("Bc_kngn_ptn",["TAM04_CRT_USER_ID"],this.GXValidFnc[141],"AV14BC_KNGN_PTN");this.addBCProperty("Bc_kngn_ptn",["TAM04_UPD_USER_ID"],this.GXValidFnc[146],"AV14BC_KNGN_PTN");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",
GXClass:null,Prefix:"W0151",lvl:1})});gx.setParentObj(new a202_wp01_kngn_ptn_reg);
