gx.evt.autoSkip=!1;
gx.define("a204_wp01_site_mst_list",!1,function(){this.ServerClass="a204_wp01_site_mst_list";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110s2_client");this.addKeyListener("4","e120s2_client");this.addKeyListener("5","e130s2_client");this.addKeyListener("6","e140s2_client");this.addKeyListener("7","e150s2_client");this.SetStandaloneVars=function(){this.AV36Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV6C_TAM02_APP_ID=
gx.fn.getControlValue("vC_TAM02_APP_ID");this.AV20P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV23W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.AV14H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.AV25W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG");this.AV31C_GRID_ROWS=gx.fn.getIntegerValue("vC_GRID_ROWS",",");this.A325TAM08_DEL_FLG=gx.fn.getControlValue("TAM08_DEL_FLG")};this.s122_client=function(){this.AV18H_SITE_NM=this.AV17H_SITE_ID=this.AV13D_SITE_NM=this.AV12D_SITE_ID=
"";this.AV14H_A_PAGING_SDT.PAGE_NO=1;this.AV19H_SRCH_FLG="0";this.AV22W_A819_JS="";this.AV26W_F7FLG=false;this.AV11D_LINE="";this.s252_client()};this.s252_client=function(){gx.fn.setCtrlProperty("vD_LINE","Backcolor",gx.color.rgb(255,255,255))};this.s222_client=function(){this.AV17H_SITE_ID=this.AV12D_SITE_ID;this.AV18H_SITE_NM=this.AV13D_SITE_NM};this.s152_client=function(){};this.s172_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");if(""!=this.AV23W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV23W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.s202_client=
function(){this.s252_client()};this.e110s2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e120s2_client=function(){this.executeServerEvent("'BTN_CSV'",true)};this.e130s2_client=function(){this.executeServerEvent("'BTN_SRCH'",true)};this.e140s2_client=function(){this.executeServerEvent("'BTN_CLER'",true)};this.e150s2_client=function(){this.executeServerEvent("'BTN_EDIT'",true)};this.e330s2_client=function(a){this.executeServerEvent("'BTN_SEL'",true,a)};this.e160s2_client=function(){this.executeServerEvent("'PAGE_FIRST'",
true)};this.e170s2_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};this.e180s2_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e190s2_client=function(){this.executeServerEvent("'PAGE_NEXT'",true)};this.e200s2_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e210s2_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e220s2_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e230s2_client=function(){this.executeServerEvent("'PAGE04'",
true)};this.e240s2_client=function(){this.executeServerEvent("'PAGE05'",true)};this.e250s2_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e260s2_client=function(){this.executeServerEvent("'PAGE07'",true)};this.e270s2_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e280s2_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e290s2_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e340s2_client=function(a){this.executeServerEvent("ENTER",
true,a)};this.e350s2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,16,19,22,25,28,32,35,38,41,44,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92,95,98,101,104,107,110,113,116,119,122,125,128,131,134,137,140,142,145,147,150,155,158,162,164,166,168,174,176,178,179,181,182,184,191,194,195,196,197,198,199,200];this.GXLastCtrlId=200;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",171,"Grid1","Grid1","Grid1Container",this.CmpContext,
this.IsMasterPage,"a204_wp01_site_mst_list",[],true,1,true,true,10,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,true,null,null,false,"",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","center","","","","","45px","","","");c.addTextBlock("BTN_SEL","e330s2_client");c.endCell();c.startCell("","","","","","","50px","","","");c.addSingleLineEdit("D_grd_line",176,"vD_GRD_LINE","","","D_GRD_LINE","int",4,"chr",4,4,"right",null,[],"D_grd_line","D_GRD_LINE",true,0,false,false,
"ReadonlyAttribute",1,"");c.endCell();c.startCell("","","","","","","120px","","","");c.startDiv("Section1","0px","115px");c.addSingleLineEdit(57,179,"TAM08_SITE_ID","","","TAM08_SITE_ID","svchar",20,"chr",20,20,"left",null,[],57,"TAM08_SITE_ID",true,0,false,false,"ReadonlyAttribute",1,"");c.endDiv();c.endCell();c.startCell("","","","","","","300px","","","");c.startDiv("Section2","0px","295px");c.addSingleLineEdit(319,182,"TAM08_SITE_NM","","","TAM08_SITE_NM","svchar",50,"chr",50,50,"left",null,
[],319,"TAM08_SITE_NM",true,0,false,false,"ReadonlyAttribute",1,"");c.endDiv();c.endCell();c.startCell("","center","","","","","100px","","","");c.addSingleLineEdit("D_grd_del",184,"vD_GRD_DEL","","","D_GRD_DEL","svchar",10,"chr",10,10,"left",null,[],"D_grd_del","D_GRD_DEL",true,0,false,false,"ReadonlyAttribute",1,"");c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[6]={fld:"TABLE2",grid:0};b[12]={fld:"TABLE8",grid:0};b[15]={fld:"TXT_BTN_REG",format:0,grid:0};b[16]={fld:"TXT_BTN_REG2",
format:0,grid:0};b[19]={fld:"TEXTBLOCK43",format:0,grid:0};b[22]={fld:"TABLE3",grid:0};b[25]={fld:"TABLE4",grid:0};b[28]={fld:"TABLE5",grid:0};b[32]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_SITE_ID",gxz:"ZV12D_SITE_ID",gxold:"OV12D_SITE_ID",gxvar:"AV12D_SITE_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12D_SITE_ID=a},v2z:function(a){gx.O.ZV12D_SITE_ID=a},v2c:function(){gx.fn.setControlValue("vD_SITE_ID",
gx.O.AV12D_SITE_ID,0)},c2v:function(){gx.O.AV12D_SITE_ID=this.val()},val:function(){return gx.fn.getControlValue("vD_SITE_ID")},nac:gx.falseFn};b[35]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_SITE_NM",gxz:"ZV13D_SITE_NM",gxold:"OV13D_SITE_NM",gxvar:"AV13D_SITE_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13D_SITE_NM=a},v2z:function(a){gx.O.ZV13D_SITE_NM=a},v2c:function(){gx.fn.setControlValue("vD_SITE_NM",
gx.O.AV13D_SITE_NM,0)},c2v:function(){gx.O.AV13D_SITE_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_SITE_NM")},nac:gx.falseFn};b[38]={fld:"TABLE9",grid:0};b[41]={fld:"TEXTBLOCK45",format:0,grid:0};b[44]={fld:"TEXTBLOCK44",format:0,grid:0};b[50]={fld:"TBL_PAGE_AREA",grid:0};b[53]={fld:"TXT_REC_CNT",format:0,grid:0};b[56]={fld:"TBL_PAGE",grid:0};b[59]={fld:"TBL_FIRST",grid:0};b[62]={fld:"TXT_FIRST",format:0,grid:0};b[65]={fld:"TBL_BACK",grid:0};b[68]={fld:"TXT_BACK",format:0,grid:0};
b[71]={fld:"TBL_PAGE01",grid:0};b[74]={fld:"TXT_PAGE01",format:0,grid:0};b[77]={fld:"TBL_PAGE02",grid:0};b[80]={fld:"TXT_PAGE02",format:0,grid:0};b[83]={fld:"TBL_PAGE03",grid:0};b[86]={fld:"TXT_PAGE03",format:0,grid:0};b[89]={fld:"TBL_PAGE04",grid:0};b[92]={fld:"TXT_PAGE04",format:0,grid:0};b[95]={fld:"TBL_PAGE05",grid:0};b[98]={fld:"TXT_PAGE05",format:0,grid:0};b[101]={fld:"TBL_PAGE06",grid:0};b[104]={fld:"TXT_PAGE06",format:0,grid:0};b[107]={fld:"TBL_PAGE07",grid:0};b[110]={fld:"TXT_PAGE07",format:0,
grid:0};b[113]={fld:"TBL_PAGE08",grid:0};b[116]={fld:"TXT_PAGE08",format:0,grid:0};b[119]={fld:"TBL_PAGE09",grid:0};b[122]={fld:"TXT_PAGE09",format:0,grid:0};b[125]={fld:"TBL_PAGE10",grid:0};b[128]={fld:"TXT_PAGE10",format:0,grid:0};b[131]={fld:"TBL_NEXT",grid:0};b[134]={fld:"TXT_NEXT",format:0,grid:0};b[137]={fld:"TBL_LAST",grid:0};b[140]={fld:"TXT_LAST",format:0,grid:0};b[142]={fld:"TBL_EDIT",grid:0};b[145]={fld:"TEXTBLOCK29",format:0,grid:0};b[147]={lvl:0,type:"char",len:4,dec:0,sign:false,ro:0,
grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_LINE",gxz:"ZV11D_LINE",gxold:"OV11D_LINE",gxvar:"AV11D_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11D_LINE=a},v2z:function(a){gx.O.ZV11D_LINE=a},v2c:function(){gx.fn.setControlValue("vD_LINE",gx.O.AV11D_LINE,0)},c2v:function(){gx.O.AV11D_LINE=this.val()},val:function(){return gx.fn.getControlValue("vD_LINE")},nac:gx.falseFn};b[150]={fld:"TEXTBLOCK28",format:0,grid:0};b[155]={fld:"TBL_GRID_HEADER",grid:0};b[158]=
{fld:"TBL_IN_GRID_HEADER",grid:0};b[162]={fld:"TEXTBLOCK34",format:0,grid:0};b[164]={fld:"TEXTBLOCK30",format:0,grid:0};b[166]={fld:"TEXTBLOCK31",format:0,grid:0};b[168]={fld:"TEXTBLOCK33",format:0,grid:0};b[174]={fld:"BTN_SEL",format:0,grid:171};b[176]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,isacc:0,grid:171,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_LINE",gxz:"ZV8D_GRD_LINE",gxold:"OV8D_GRD_LINE",gxvar:"AV8D_GRD_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",
inputType:"text",v2v:function(a){gx.O.AV8D_GRD_LINE=gx.num.intval(a)},v2z:function(a){gx.O.ZV8D_GRD_LINE=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(171),gx.O.AV8D_GRD_LINE,0)},c2v:function(){gx.O.AV8D_GRD_LINE=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(171),",")},nac:gx.falseFn};b[178]={fld:"SECTION1",grid:171};b[179]={lvl:2,type:"svchar",len:20,dec:0,sign:false,ro:1,
isacc:0,grid:171,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM08_SITE_ID",gxz:"Z57TAM08_SITE_ID",gxold:"O57TAM08_SITE_ID",gxvar:"A57TAM08_SITE_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A57TAM08_SITE_ID=a},v2z:function(a){gx.O.Z57TAM08_SITE_ID=a},v2c:function(a){gx.fn.setGridControlValue("TAM08_SITE_ID",a||gx.fn.currentGridRowImpl(171),gx.O.A57TAM08_SITE_ID,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},
c2v:function(){gx.O.A57TAM08_SITE_ID=this.val()},val:function(a){return gx.fn.getGridControlValue("TAM08_SITE_ID",a||gx.fn.currentGridRowImpl(171))},nac:gx.falseFn};b[181]={fld:"SECTION2",grid:171};b[182]={lvl:2,type:"svchar",len:50,dec:0,sign:false,ro:1,isacc:0,grid:171,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM08_SITE_NM",gxz:"Z319TAM08_SITE_NM",gxold:"O319TAM08_SITE_NM",gxvar:"A319TAM08_SITE_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",
v2v:function(a){gx.O.A319TAM08_SITE_NM=a},v2z:function(a){gx.O.Z319TAM08_SITE_NM=a},v2c:function(a){gx.fn.setGridControlValue("TAM08_SITE_NM",a||gx.fn.currentGridRowImpl(171),gx.O.A319TAM08_SITE_NM,0)},c2v:function(){gx.O.A319TAM08_SITE_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("TAM08_SITE_NM",a||gx.fn.currentGridRowImpl(171))},nac:gx.falseFn};b[184]={lvl:2,type:"svchar",len:10,dec:0,sign:false,ro:0,isacc:0,grid:171,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_DEL",
gxz:"ZV7D_GRD_DEL",gxold:"OV7D_GRD_DEL",gxvar:"AV7D_GRD_DEL",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV7D_GRD_DEL=a},v2z:function(a){gx.O.ZV7D_GRD_DEL=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_DEL",a||gx.fn.currentGridRowImpl(171),gx.O.AV7D_GRD_DEL,0)},c2v:function(){gx.O.AV7D_GRD_DEL=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_DEL",a||gx.fn.currentGridRowImpl(171))},nac:gx.falseFn};b[191]={fld:"TBL_HIDDEN",
grid:0};b[194]={fld:"TXT_JS_EVENT",format:1,grid:0};b[195]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV15H_INIT_FLG",gxold:"OV15H_INIT_FLG",gxvar:"AV15H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_INIT_FLG=a},v2z:function(a){gx.O.ZV15H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV15H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV15H_INIT_FLG=
this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(195,function(){});b[196]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SRCH_FLG",gxz:"ZV19H_SRCH_FLG",gxold:"OV19H_SRCH_FLG",gxvar:"AV19H_SRCH_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV19H_SRCH_FLG=a},v2z:function(a){gx.O.ZV19H_SRCH_FLG=a},v2c:function(){gx.fn.setControlValue("vH_SRCH_FLG",
gx.O.AV19H_SRCH_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV19H_SRCH_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_SRCH_FLG")},nac:gx.falseFn};this.declareDomainHdlr(196,function(){});b[197]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SITE_ID",gxz:"ZV17H_SITE_ID",gxold:"OV17H_SITE_ID",gxvar:"AV17H_SITE_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV17H_SITE_ID=
a},v2z:function(a){gx.O.ZV17H_SITE_ID=a},v2c:function(){gx.fn.setControlValue("vH_SITE_ID",gx.O.AV17H_SITE_ID,0)},c2v:function(){gx.O.AV17H_SITE_ID=this.val()},val:function(){return gx.fn.getControlValue("vH_SITE_ID")},nac:gx.falseFn};b[198]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SITE_NM",gxz:"ZV18H_SITE_NM",gxold:"OV18H_SITE_NM",gxvar:"AV18H_SITE_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV18H_SITE_NM=
a},v2z:function(a){gx.O.ZV18H_SITE_NM=a},v2c:function(){gx.fn.setControlValue("vH_SITE_NM",gx.O.AV18H_SITE_NM,0)},c2v:function(){gx.O.AV18H_SITE_NM=this.val()},val:function(){return gx.fn.getControlValue("vH_SITE_NM")},nac:gx.falseFn};b[199]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV16H_KNGN_FLG",gxold:"OV16H_KNGN_FLG",gxvar:"AV16H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV16H_KNGN_FLG=
a},v2z:function(a){gx.O.ZV16H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV16H_KNGN_FLG,0)},c2v:function(){gx.O.AV16H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[200]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLREC_CNT",gxz:"ZV34GXV1",gxold:"OV34GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=gx.num.intval(a)},
v2z:function(a){gx.O.ZV34GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",",")},nac:gx.falseFn};this.OV11D_LINE=this.ZV11D_LINE=this.AV11D_LINE=this.OV13D_SITE_NM=this.ZV13D_SITE_NM=this.AV13D_SITE_NM=this.OV12D_SITE_ID=this.ZV12D_SITE_ID=this.AV12D_SITE_ID="";this.OV8D_GRD_LINE=this.ZV8D_GRD_LINE=0;this.OV16H_KNGN_FLG=this.ZV16H_KNGN_FLG=this.AV16H_KNGN_FLG=
this.OV18H_SITE_NM=this.ZV18H_SITE_NM=this.AV18H_SITE_NM=this.OV17H_SITE_ID=this.ZV17H_SITE_ID=this.AV17H_SITE_ID=this.OV19H_SRCH_FLG=this.ZV19H_SRCH_FLG=this.AV19H_SRCH_FLG=this.OV15H_INIT_FLG=this.ZV15H_INIT_FLG=this.AV15H_INIT_FLG=this.OV7D_GRD_DEL=this.ZV7D_GRD_DEL=this.O319TAM08_SITE_NM=this.Z319TAM08_SITE_NM=this.O57TAM08_SITE_ID=this.Z57TAM08_SITE_ID="";this.OV34GXV1=this.ZV34GXV1=this.GXV1=0;this.AV16H_KNGN_FLG=this.AV18H_SITE_NM=this.AV17H_SITE_ID=this.AV19H_SRCH_FLG=this.AV15H_INIT_FLG=
this.AV11D_LINE=this.AV13D_SITE_NM=this.AV12D_SITE_ID="";this.AV20P_MOVE_KBN=this.GXV1=0;this.A325TAM08_DEL_FLG="";this.AV8D_GRD_LINE=0;this.AV23W_A821_JS=this.AV6C_TAM02_APP_ID=this.AV36Pgmname=this.AV7D_GRD_DEL=this.A319TAM08_SITE_NM=this.A57TAM08_SITE_ID="";this.AV14H_A_PAGING_SDT={};this.AV25W_ERRFLG=false;this.AV31C_GRID_ROWS=0;this.AV26W_F7FLG=false;this.AV22W_A819_JS="";this.Events={e110s2_client:["'BTN_REG'",true],e120s2_client:["'BTN_CSV'",true],e130s2_client:["'BTN_SRCH'",true],e140s2_client:["'BTN_CLER'",
true],e150s2_client:["'BTN_EDIT'",true],e330s2_client:["'BTN_SEL'",true],e160s2_client:["'PAGE_FIRST'",true],e170s2_client:["'PAGE_LAST'",true],e180s2_client:["'PAGE_BACK'",true],e190s2_client:["'PAGE_NEXT'",true],e200s2_client:["'PAGE01'",true],e210s2_client:["'PAGE02'",true],e220s2_client:["'PAGE03'",true],e230s2_client:["'PAGE04'",true],e240s2_client:["'PAGE05'",true],e250s2_client:["'PAGE06'",true],e260s2_client:["'PAGE07'",true],e270s2_client:["'PAGE08'",true],e280s2_client:["'PAGE09'",true],
e290s2_client:["'PAGE10'",true],e340s2_client:["ENTER",true],e350s2_client:["CANCEL",true]};this.setVCMap("AV36Pgmname","vPGMNAME",0,"char");this.setVCMap("AV6C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV20P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV23W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV14H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV25W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV31C_GRID_ROWS","vC_GRID_ROWS",0,"int");this.setVCMap("A325TAM08_DEL_FLG",
"TAM08_DEL_FLG",0,"svchar");this.setVCMap("AV36Pgmname","vPGMNAME",0,"char");this.setVCMap("AV6C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV20P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV23W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV14H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV25W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV31C_GRID_ROWS","vC_GRID_ROWS",0,"int");this.setVCMap("A325TAM08_DEL_FLG","TAM08_DEL_FLG",0,"svchar");c.addRefreshingVar(this.GXValidFnc[196]);
c.addRefreshingVar(this.GXValidFnc[197]);c.addRefreshingVar(this.GXValidFnc[198]);c.addRefreshingVar(this.GXValidFnc[195]);c.addRefreshingVar({rfrVar:"AV36Pgmname"});c.addRefreshingVar({rfrVar:"AV6C_TAM02_APP_ID"});c.addRefreshingVar({rfrVar:"AV20P_MOVE_KBN"});c.addRefreshingVar(this.GXValidFnc[199]);c.addRefreshingVar({rfrVar:"AV23W_A821_JS"});c.addRefreshingVar({rfrVar:"AV14H_A_PAGING_SDT"});c.addRefreshingVar({rfrVar:"AV25W_ERRFLG"});c.addRefreshingVar(this.GXValidFnc[32]);c.addRefreshingVar(this.GXValidFnc[35]);
c.addRefreshingVar({rfrVar:"AV8D_GRD_LINE",rfrProp:"Value",gxAttId:"D_grd_line"});c.addRefreshingVar({rfrVar:"AV31C_GRID_ROWS"});c.addRefreshingVar({rfrVar:"A325TAM08_DEL_FLG"});this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[200],"AV14H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0189",lvl:1})});gx.setParentObj(new a204_wp01_site_mst_list);
