gx.evt.autoSkip=!1;
gx.define("a207_wp01_user_mst",!1,function(){this.ServerClass="a207_wp01_user_mst";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110v2_client");this.addKeyListener("4","e120v2_client");this.addKeyListener("6","e130v2_client");this.addKeyListener("11","e140v2_client");this.SetStandaloneVars=function(){this.AV16P_TAM07_USER_ID=gx.fn.getControlValue("vP_TAM07_USER_ID")};this.s152_client=function(){};
this.s172_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");""!=this.AV24W_A821_JS&&gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV24W_A821_JS);""!=this.AV23W_A819_JS&&gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV23W_A819_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.s212_client=function(){gx.fn.setCtrlProperty("CTLTAM07_USER_ID","Backcolor",gx.color.rgb(255,
255,255));gx.fn.setCtrlProperty("CTLTAM07_USER_NM","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTAM07_USER_KANA_NM","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("vD_TAM07_PWD","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTAM07_KNGN_PTN_KBN","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTAM07_SITE_ID","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTAM07_EMAIL","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTAM07_NOTE",
"Backcolor",gx.color.rgb(255,255,255))};this.s222_client=function(){for(this.AV57GXV15=1;this.AV57GXV15<=this.AV18W_A_CHK_RESULT_SDT.length;){this.AV19W_A_CHK_RESULT_SDT_ITEM=this.AV18W_A_CHK_RESULT_SDT[this.AV57GXV15-1];this.s232_client();this.AV57GXV15=this.AV57GXV15+1}};this.s232_client=function(){if(this.AV19W_A_CHK_RESULT_SDT_ITEM.ID=="TAM07_USER_ID"){gx.fn.setCtrlProperty("CTLTAM07_USER_ID","Backcolor",gx.color.rgb(255,192,203));this.AV19W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTAM07_USER_ID")}else if(this.AV19W_A_CHK_RESULT_SDT_ITEM.ID==
"TAM07_USER_NM"){gx.fn.setCtrlProperty("CTLTAM07_USER_NM","Backcolor",gx.color.rgb(255,192,203));this.AV19W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTAM07_USER_NM")}else if(this.AV19W_A_CHK_RESULT_SDT_ITEM.ID=="TAM07_USER_KANA_NM"){gx.fn.setCtrlProperty("CTLTAM07_USER_KANA_NM","Backcolor",gx.color.rgb(255,192,203));this.AV19W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTAM07_USER_KANA_NM")}else if(this.AV19W_A_CHK_RESULT_SDT_ITEM.ID=="TAM07_PWD"){gx.fn.setCtrlProperty("vD_TAM07_PWD",
"Backcolor",gx.color.rgb(255,192,203));this.AV19W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("vD_TAM07_PWD")}else if(this.AV19W_A_CHK_RESULT_SDT_ITEM.ID=="TAM07_EMAIL"){gx.fn.setCtrlProperty("CTLTAM07_EMAIL","Backcolor",gx.color.rgb(255,192,203));this.AV19W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTAM07_EMAIL")}else if(this.AV19W_A_CHK_RESULT_SDT_ITEM.ID=="TAM07_NOTE"){gx.fn.setCtrlProperty("CTLTAM07_NOTE","Backcolor",gx.color.rgb(255,192,203));this.AV19W_A_CHK_RESULT_SDT_ITEM.FOCUS==
true&&gx.fn.usrSetFocus("CTLTAM07_NOTE")}};this.e110v2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e170v2_client=function(){this.executeServerEvent("'BTN_REG_EXEC'",true)};this.e120v2_client=function(){this.executeServerEvent("'BTN_UPD'",true)};this.e180v2_client=function(){this.executeServerEvent("'BTN_UPD_EXEC'",true)};this.e130v2_client=function(){this.executeServerEvent("'BTN_DLT'",true)};this.e190v2_client=function(){this.executeServerEvent("'BTN_DLT_EXEC'",true)};this.e140v2_client=
function(){this.executeServerEvent("'BTN_CAN'",true)};this.e200v2_client=function(){this.executeServerEvent("CTLTAM07_KNGN_PTN_KBN.CLICK",true)};this.e220v2_client=function(){this.executeServerEvent("ENTER",true)};this.e230v2_client=function(){this.executeServerEvent("CANCEL",true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,16,19,20,23,24,27,28,31,34,40,45,47,50,52,54,56,59,61,64,67,71,74,76,80,83,86,87,91,94,98,99,105,108,112,115,119,122,123,126,127,128,129,130,131,132];this.GXLastCtrlId=
132;b[2]={fld:"TABLE2",grid:0};b[6]={fld:"TABLE3",grid:0};b[12]={fld:"TBL_INS_BTNSET",grid:0};b[15]={fld:"TXT_BTN_REG",format:0,grid:0};b[16]={fld:"TXT_BTN_REG2",format:0,grid:0};b[19]={fld:"TEXTBLOCK43",format:0,grid:0};b[20]={fld:"TBL_UPD_BTNSET",grid:0};b[23]={fld:"TXT_BTN_UPD",format:0,grid:0};b[24]={fld:"TXT_BTN_UPD2",format:0,grid:0};b[27]={fld:"TXT_BTN_DLT",format:0,grid:0};b[28]={fld:"TXT_BTN_DLT2",format:0,grid:0};b[31]={fld:"TEXTBLOCK46",format:0,grid:0};b[34]={fld:"TABLE5",grid:0};b[40]=
{fld:"TABLE4",grid:0};b[45]={fld:"IMAGE1",grid:0};b[47]={fld:"TABLE10",grid:0};b[50]={fld:"NC_RENKEI_TXT",format:0,grid:0};b[52]={lvl:0,type:"svchar",len:128,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_USER_ID",gxz:"ZV36GXV1",gxold:"OV36GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=a},v2z:function(a){gx.O.ZV36GXV1=a},v2c:function(){gx.fn.setControlValue("CTLTAM07_USER_ID",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=this.val()},
val:function(){return gx.fn.getControlValue("CTLTAM07_USER_ID")},nac:gx.falseFn};b[54]={fld:"IMAGE4",grid:0};b[56]={lvl:0,type:"svchar",len:128,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM07_PWD",gxz:"ZV11D_TAM07_PWD",gxold:"OV11D_TAM07_PWD",gxvar:"AV11D_TAM07_PWD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11D_TAM07_PWD=a},v2z:function(a){gx.O.ZV11D_TAM07_PWD=a},v2c:function(){gx.fn.setControlValue("vD_TAM07_PWD",gx.O.AV11D_TAM07_PWD,
0)},c2v:function(){gx.O.AV11D_TAM07_PWD=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM07_PWD")},nac:gx.falseFn};b[59]={fld:"IMAGE3",grid:0};b[61]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_USER_NM",gxz:"ZV37GXV2",gxold:"OV37GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV2=a},v2z:function(a){gx.O.ZV37GXV2=a},v2c:function(){gx.fn.setControlValue("CTLTAM07_USER_NM",gx.O.GXV2,
0)},c2v:function(){gx.O.GXV2=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_USER_NM")},nac:gx.falseFn};b[64]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_USER_KANA_NM",gxz:"ZV38GXV3",gxold:"OV38GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV3=a},v2z:function(a){gx.O.ZV38GXV3=a},v2c:function(){gx.fn.setControlValue("CTLTAM07_USER_KANA_NM",gx.O.GXV3,0)},c2v:function(){gx.O.GXV3=
this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_USER_KANA_NM")},nac:gx.falseFn};b[67]={fld:"TABLE9",grid:0};b[71]={fld:"TABLE8",grid:0};b[74]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_SITE_ID",gxz:"ZV39GXV4",gxold:"OV39GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"dyncombo",v2v:function(a){gx.O.GXV4=a},v2z:function(a){gx.O.ZV39GXV4=a},v2c:function(){gx.fn.setComboBoxValue("CTLTAM07_SITE_ID",gx.O.GXV4)},
c2v:function(){gx.O.GXV4=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_SITE_ID")},nac:gx.falseFn};b[76]={fld:"TABLE7",grid:0};b[80]={fld:"TABLE6",grid:0};b[83]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_KNGN_PTN_KBN",gxz:"ZV40GXV5",gxold:"OV40GXV5",gxvar:"GXV5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"dyncombo",v2v:function(a){gx.O.GXV5=a},v2z:function(a){gx.O.ZV40GXV5=a},v2c:function(){gx.fn.setComboBoxValue("CTLTAM07_KNGN_PTN_KBN",
gx.O.GXV5)},c2v:function(){gx.O.GXV5=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_KNGN_PTN_KBN")},nac:gx.falseFn};b[86]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_ADMIN_AUTH_FLG",gxz:"ZV41GXV6",gxold:"OV41GXV6",gxvar:"GXV6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.GXV6=a},v2z:function(a){gx.O.ZV41GXV6=a},v2c:function(){gx.fn.setCheckBoxValue("CTLTAM07_ADMIN_AUTH_FLG",gx.O.GXV6,"1")},
c2v:function(){gx.O.GXV6=this.val()},val:function(){return gx.fn.getCheckBoxValue("CTLTAM07_ADMIN_AUTH_FLG","1","0")},nac:gx.falseFn};b[87]={fld:"TXT_ADMIN_AUTH",format:0,grid:0};b[91]={lvl:0,type:"svchar",len:256,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_EMAIL",gxz:"ZV42GXV7",gxold:"OV42GXV7",gxvar:"GXV7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV7=a},v2z:function(a){gx.O.ZV42GXV7=a},v2c:function(){gx.fn.setControlValue("CTLTAM07_EMAIL",
gx.O.GXV7,0)},c2v:function(){gx.O.GXV7=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_EMAIL")},nac:gx.falseFn};b[94]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_DEL_FLG",gxz:"ZV43GXV8",gxold:"OV43GXV8",gxvar:"GXV8",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",v2v:function(a){gx.O.GXV8=a},v2z:function(a){gx.O.ZV43GXV8=a},v2c:function(){gx.fn.setRadioValue("CTLTAM07_DEL_FLG",gx.O.GXV8)},c2v:function(){gx.O.GXV8=
this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_DEL_FLG")},nac:gx.falseFn};b[98]={lvl:0,type:"svchar",len:1E3,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_NOTE",gxz:"ZV44GXV9",gxold:"OV44GXV9",gxvar:"GXV9",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV9=a},v2z:function(a){gx.O.ZV44GXV9=a},v2c:function(){gx.fn.setControlValue("CTLTAM07_NOTE",gx.O.GXV9,0)},c2v:function(){gx.O.GXV9=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_NOTE")},
nac:gx.falseFn};b[99]={fld:"TABLE1",grid:0};b[105]={lvl:0,type:"dtime",len:10,dec:8,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_CRT_DATETIME",gxz:"ZV45GXV10",gxold:"OV45GXV10",gxvar:"GXV10",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV10=gx.fn.toDatetimeValue(a,"Y4MD")},v2z:function(a){gx.O.ZV45GXV10=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTAM07_CRT_DATETIME",
gx.O.GXV10,0)},c2v:function(){gx.O.GXV10=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTAM07_CRT_DATETIME")},nac:gx.falseFn};b[108]={lvl:0,type:"dtime",len:10,dec:8,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_UPD_DATETIME",gxz:"ZV46GXV11",gxold:"OV46GXV11",gxvar:"GXV11",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV11=gx.fn.toDatetimeValue(a,
"Y4MD")},v2z:function(a){gx.O.ZV46GXV11=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTAM07_UPD_DATETIME",gx.O.GXV11,0)},c2v:function(){gx.O.GXV11=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTAM07_UPD_DATETIME")},nac:gx.falseFn};b[112]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM07_CRT_USER_NM",gxz:"ZV10D_TAM07_CRT_USER_NM",gxold:"OV10D_TAM07_CRT_USER_NM",gxvar:"AV10D_TAM07_CRT_USER_NM",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10D_TAM07_CRT_USER_NM=a},v2z:function(a){gx.O.ZV10D_TAM07_CRT_USER_NM=a},v2c:function(){gx.fn.setControlValue("vD_TAM07_CRT_USER_NM",gx.O.AV10D_TAM07_CRT_USER_NM,1)},c2v:function(){gx.O.AV10D_TAM07_CRT_USER_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM07_CRT_USER_NM")},nac:gx.falseFn};b[115]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_TAM07_UPD_USER_NM",
gxz:"ZV12D_TAM07_UPD_USER_NM",gxold:"OV12D_TAM07_UPD_USER_NM",gxvar:"AV12D_TAM07_UPD_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12D_TAM07_UPD_USER_NM=a},v2z:function(a){gx.O.ZV12D_TAM07_UPD_USER_NM=a},v2c:function(){gx.fn.setControlValue("vD_TAM07_UPD_USER_NM",gx.O.AV12D_TAM07_UPD_USER_NM,1)},c2v:function(){gx.O.AV12D_TAM07_UPD_USER_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_TAM07_UPD_USER_NM")},nac:gx.falseFn};b[119]={lvl:0,type:"svchar",len:40,
dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_CRT_PG_NM",gxz:"ZV47GXV12",gxold:"OV47GXV12",gxvar:"GXV12",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV12=a},v2z:function(a){gx.O.ZV47GXV12=a},v2c:function(){gx.fn.setControlValue("CTLTAM07_CRT_PG_NM",gx.O.GXV12,0)},c2v:function(){gx.O.GXV12=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_CRT_PG_NM")},nac:gx.falseFn};b[122]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,
grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTAM07_UPD_PG_NM",gxz:"ZV48GXV13",gxold:"OV48GXV13",gxvar:"GXV13",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV13=a},v2z:function(a){gx.O.ZV48GXV13=a},v2c:function(){gx.fn.setControlValue("CTLTAM07_UPD_PG_NM",gx.O.GXV13,0)},c2v:function(){gx.O.GXV13=this.val()},val:function(){return gx.fn.getControlValue("CTLTAM07_UPD_PG_NM")},nac:gx.falseFn};b[123]={fld:"TBL_HIDDEN",grid:0};b[126]={fld:"TXT_JS_EVENT",format:1,grid:0};
b[127]={fld:"BTN_UPD_EXEC",format:0,grid:0};b[128]={fld:"BTN_DLT_EXEC",format:0,grid:0};b[129]={fld:"BTN_REG_EXEC",format:0,grid:0};b[130]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV13H_INIT_FLG",gxold:"OV13H_INIT_FLG",gxvar:"AV13H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_INIT_FLG=a},v2z:function(a){gx.O.ZV13H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV13H_INIT_FLG,
0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV13H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(130,function(){});b[131]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_MODE",gxz:"ZV15H_MODE",gxold:"OV15H_MODE",gxvar:"AV15H_MODE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_MODE=a},v2z:function(a){gx.O.ZV15H_MODE=
a},v2c:function(){gx.fn.setControlValue("vH_MODE",gx.O.AV15H_MODE,0)},c2v:function(){gx.O.AV15H_MODE=this.val()},val:function(){return gx.fn.getControlValue("vH_MODE")},nac:gx.falseFn};b[132]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV14H_KNGN_FLG",gxold:"OV14H_KNGN_FLG",gxvar:"AV14H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV14H_KNGN_FLG=a},v2z:function(a){gx.O.ZV14H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",
gx.O.AV14H_KNGN_FLG,0)},c2v:function(){gx.O.AV14H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};this.OV44GXV9=this.ZV44GXV9=this.GXV9=this.OV43GXV8=this.ZV43GXV8=this.GXV8=this.OV42GXV7=this.ZV42GXV7=this.GXV7=this.OV41GXV6=this.ZV41GXV6=this.GXV6=this.OV40GXV5=this.ZV40GXV5=this.GXV5=this.OV39GXV4=this.ZV39GXV4=this.GXV4=this.OV38GXV3=this.ZV38GXV3=this.GXV3=this.OV37GXV2=this.ZV37GXV2=this.GXV2=this.OV11D_TAM07_PWD=this.ZV11D_TAM07_PWD=this.AV11D_TAM07_PWD=
this.OV36GXV1=this.ZV36GXV1=this.GXV1="";this.GXV10=gx.date.nullDate();this.ZV45GXV10=gx.date.nullDate();this.OV45GXV10=gx.date.nullDate();this.GXV11=gx.date.nullDate();this.ZV46GXV11=gx.date.nullDate();this.OV46GXV11=gx.date.nullDate();this.GXV9=this.GXV8=this.GXV7=this.GXV6=this.GXV5=this.GXV4=this.GXV3=this.GXV2=this.AV11D_TAM07_PWD=this.GXV1=this.OV14H_KNGN_FLG=this.ZV14H_KNGN_FLG=this.AV14H_KNGN_FLG=this.OV15H_MODE=this.ZV15H_MODE=this.AV15H_MODE=this.OV13H_INIT_FLG=this.ZV13H_INIT_FLG=this.AV13H_INIT_FLG=
this.OV48GXV13=this.ZV48GXV13=this.GXV13=this.OV47GXV12=this.ZV47GXV12=this.GXV12=this.OV12D_TAM07_UPD_USER_NM=this.ZV12D_TAM07_UPD_USER_NM=this.AV12D_TAM07_UPD_USER_NM=this.OV10D_TAM07_CRT_USER_NM=this.ZV10D_TAM07_CRT_USER_NM=this.AV10D_TAM07_CRT_USER_NM="";this.GXV10=gx.date.nullDate();this.GXV11=gx.date.nullDate();this.A57TAM08_SITE_ID=this.A325TAM08_DEL_FLG=this.A13TAM04_AUTH_CD=this.A215TAM04_DEL_FLG=this.A205TAM07_USER_NM=this.A55TAM07_USER_ID=this.A608TBM01_SYS_VALUE=this.A351TBM01_DEL_FLG=
this.A58TBM01_SYS_ID=this.AV16P_TAM07_USER_ID=this.AV14H_KNGN_FLG=this.AV15H_MODE=this.AV13H_INIT_FLG=this.GXV13=this.GXV12=this.AV12D_TAM07_UPD_USER_NM=this.AV10D_TAM07_CRT_USER_NM="";this.A231TAM07_UPD_DATETIME=gx.date.nullDate();this.A109TBM23_STYDY_AUTH_CD=this.A108TBM23_USER_ID=this.A385TBM23_DEL_FLG="";this.A107TBM23_STUDY_ID=0;this.AV24W_A821_JS=this.AV23W_A819_JS="";this.AV19W_A_CHK_RESULT_SDT_ITEM={};this.AV18W_A_CHK_RESULT_SDT=[];this.AV57GXV15=0;this.Events={e110v2_client:["'BTN_REG'",
true],e170v2_client:["'BTN_REG_EXEC'",true],e120v2_client:["'BTN_UPD'",true],e180v2_client:["'BTN_UPD_EXEC'",true],e130v2_client:["'BTN_DLT'",true],e190v2_client:["'BTN_DLT_EXEC'",true],e140v2_client:["'BTN_CAN'",true],e200v2_client:["CTLTAM07_KNGN_PTN_KBN.CLICK",true],e220v2_client:["ENTER",true],e230v2_client:["CANCEL",true]};this.setVCMap("AV16P_TAM07_USER_ID","vP_TAM07_USER_ID",0,"svchar");this.addBCProperty("Bc_tam07_user",["TAM07_USER_ID"],this.GXValidFnc[52],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",
["TAM07_USER_NM"],this.GXValidFnc[61],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_USER_KANA_NM"],this.GXValidFnc[64],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_SITE_ID"],this.GXValidFnc[74],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_AUTH_CD"],this.GXValidFnc[83],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_ADMIN_AUTH_FLG"],this.GXValidFnc[86],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_EMAIL"],this.GXValidFnc[91],
"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_DEL_FLG"],this.GXValidFnc[94],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_NOTE"],this.GXValidFnc[98],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_CRT_DATETIME"],this.GXValidFnc[105],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_UPD_DATETIME"],this.GXValidFnc[108],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",["TAM07_CRT_PROG_NM"],this.GXValidFnc[119],"AV5BC_TAM07_USER");this.addBCProperty("Bc_tam07_user",
["TAM07_UPD_PROG_NM"],this.GXValidFnc[122],"AV5BC_TAM07_USER");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0135",lvl:1})});gx.setParentObj(new a207_wp01_user_mst);
