gx.evt.autoSkip=!1;
gx.define("a208_wp01_domain_list",!1,function(){this.ServerClass="a208_wp01_domain_list";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e111t2_client");this.addKeyListener("4","e121t2_client");this.addKeyListener("5","e131t2_client");this.addKeyListener("6","e141t2_client");this.addKeyListener("7","e151t2_client");this.addKeyListener("8","e161t2_client");this.SetStandaloneVars=function(){this.AV39Pgmname=
gx.fn.getControlValue("vPGMNAME");this.AV6C_TAM02_APP_ID=gx.fn.getControlValue("vC_TAM02_APP_ID");this.AV20P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV23W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.AV14H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.AV25W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG");this.AV32C_GRID_ROWS=gx.fn.getIntegerValue("vC_GRID_ROWS",",");this.A615TBM02_DEL_FLG=gx.fn.getControlValue("TBM02_DEL_FLG")};this.s122_client=function(){this.AV16H_DOM_JNM=
this.AV15H_DOM_CD=this.AV8D_DOM_JNM=this.AV7D_DOM_CD="";this.AV14H_A_PAGING_SDT.PAGE_NO=1;this.AV19H_SRCH_FLG="0";this.AV22W_A819_JS="";this.AV26W_F7FLG=false;this.AV13D_LINE="";this.s292_client()};this.s292_client=function(){gx.fn.setCtrlProperty("vD_LINE","Backcolor",gx.color.rgb(255,255,255))};this.s242_client=function(){this.AV15H_DOM_CD=this.AV7D_DOM_CD;this.AV16H_DOM_JNM=this.AV8D_DOM_JNM};this.s152_client=function(){};this.s172_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
"<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+
"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");if(""!=this.AV23W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV23W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"<\/script>")};this.s192_client=function(){gx.fn.setCtrlProperty("TXT_SORT01_ASC","Class","TextBlockSort");gx.fn.setCtrlProperty("TXT_SORT01_DESC","Class","TextBlockSort");gx.fn.setCtrlProperty("TXT_SORT02_ASC","Class","TextBlockSort");gx.fn.setCtrlProperty("TXT_SORT02_DESC","Class","TextBlockSort");gx.fn.setCtrlProperty("TXT_SORT03_ASC","Class","TextBlockSort");gx.fn.setCtrlProperty("TXT_SORT03_DESC","Class","TextBlockSort");gx.fn.setCtrlProperty("TXT_SORT04_ASC","Class","TextBlockSort");
gx.fn.setCtrlProperty("TXT_SORT04_DESC","Class","TextBlockSort");this.AV34H_SORT_ITEM_KBN==1&&this.AV33H_SORT_ASDC_KBN==0?gx.fn.setCtrlProperty("TXT_SORT01_ASC","Class","TextBlockSortSel"):this.AV34H_SORT_ITEM_KBN==1&&this.AV33H_SORT_ASDC_KBN==1?gx.fn.setCtrlProperty("TXT_SORT01_DESC","Class","TextBlockSortSel"):this.AV34H_SORT_ITEM_KBN==2&&this.AV33H_SORT_ASDC_KBN==0?gx.fn.setCtrlProperty("TXT_SORT02_ASC","Class","TextBlockSortSel"):this.AV34H_SORT_ITEM_KBN==2&&this.AV33H_SORT_ASDC_KBN==1?gx.fn.setCtrlProperty("TXT_SORT02_DESC",
"Class","TextBlockSortSel"):this.AV34H_SORT_ITEM_KBN==3&&this.AV33H_SORT_ASDC_KBN==0?gx.fn.setCtrlProperty("TXT_SORT03_ASC","Class","TextBlockSortSel"):this.AV34H_SORT_ITEM_KBN==3&&this.AV33H_SORT_ASDC_KBN==1?gx.fn.setCtrlProperty("TXT_SORT03_DESC","Class","TextBlockSortSel"):this.AV34H_SORT_ITEM_KBN==4&&this.AV33H_SORT_ASDC_KBN==0?gx.fn.setCtrlProperty("TXT_SORT04_ASC","Class","TextBlockSortSel"):this.AV34H_SORT_ITEM_KBN==4&&this.AV33H_SORT_ASDC_KBN==1&&gx.fn.setCtrlProperty("TXT_SORT04_DESC","Class",
"TextBlockSortSel")};this.s222_client=function(){this.s292_client()};this.e111t2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e121t2_client=function(){this.executeServerEvent("'BTN_CSV'",true)};this.e131t2_client=function(){this.executeServerEvent("'BTN_SRCH'",true)};this.e141t2_client=function(){this.executeServerEvent("'BTN_CLER'",true)};this.e151t2_client=function(){this.executeServerEvent("'BTN_EDIT'",true)};this.e161t2_client=function(){this.executeServerEvent("'BTN_IMPORT_DOMAIN'",
true)};this.e421t2_client=function(a){this.executeServerEvent("'BTN_SEL'",true,a)};this.e431t2_client=function(a){this.executeServerEvent("'BTN_CDISC_ITEM'",true,a)};this.e171t2_client=function(){this.executeServerEvent("'PAGE_FIRST'",true)};this.e181t2_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};this.e191t2_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e201t2_client=function(){this.executeServerEvent("'PAGE_NEXT'",true)};this.e211t2_client=function(){this.executeServerEvent("'PAGE01'",
true)};this.e221t2_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e231t2_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e241t2_client=function(){this.executeServerEvent("'PAGE04'",true)};this.e251t2_client=function(){this.executeServerEvent("'PAGE05'",true)};this.e261t2_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e271t2_client=function(){this.executeServerEvent("'PAGE07'",true)};this.e281t2_client=function(){this.executeServerEvent("'PAGE08'",
true)};this.e291t2_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e301t2_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e311t2_client=function(){this.executeServerEvent("'SORT01_ASC'",true)};this.e321t2_client=function(){this.executeServerEvent("'SORT01_DESC'",true)};this.e331t2_client=function(){this.executeServerEvent("'SORT02_ASC'",true)};this.e341t2_client=function(){this.executeServerEvent("'SORT02_DESC'",true)};this.e351t2_client=function(){this.executeServerEvent("'SORT03_ASC'",
true)};this.e361t2_client=function(){this.executeServerEvent("'SORT03_DESC'",true)};this.e371t2_client=function(){this.executeServerEvent("'SORT04_ASC'",true)};this.e381t2_client=function(){this.executeServerEvent("'SORT04_DESC'",true)};this.e441t2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e451t2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,16,19,22,25,28,31,35,38,41,44,47,53,56,59,62,65,68,71,74,77,80,83,86,
89,92,95,98,101,104,107,110,113,116,119,122,125,128,131,134,137,140,143,145,148,150,153,158,162,164,165,166,168,169,170,172,173,174,176,177,178,185,187,189,191,193,195,197,204,207,208,209,210,211,212,213,216,218,221,224,226,229,231];this.GXLastCtrlId=231;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",182,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"a208_wp01_domain_list",[],true,1,true,true,10,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,true,null,
null,false,"",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","center","","","","","45px","","","");c.addTextBlock("BTN_SEL","e421t2_client");c.endCell();c.startCell("","right","","","","","50px","","","");c.addSingleLineEdit("D_grd_line",187,"vD_GRD_LINE","","","D_GRD_LINE","int",4,"chr",4,4,"right",null,[],"D_grd_line","D_GRD_LINE",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","center","","","","","160px","","","");c.addSingleLineEdit(49,189,"TBM02_DOM_CD","","",
"TBM02_DOM_CD","svchar",16,"chr",16,16,"left",null,[],49,"TBM02_DOM_CD",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","","","","","","370px","","","");c.addSingleLineEdit(611,191,"TBM02_DOM_JNM","","","TBM02_DOM_JNM","svchar",50,"chr",50,50,"left",null,[],611,"TBM02_DOM_JNM",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","right","","","","","100px","","","");c.addSingleLineEdit(614,193,"TBM02_ORDER","","","TBM02_ORDER","int",5,"chr",5,5,"right",null,[],614,"TBM02_ORDER",
true,0,false,false,"AttributeNum",1,"");c.endCell();c.startCell("","center","","","","","100px","","","");c.addSingleLineEdit("D_grd_del",195,"vD_GRD_DEL","","","D_GRD_DEL","svchar",10,"chr",10,10,"left",null,[],"D_grd_del","D_GRD_DEL",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","center","","","","","90px","","","");c.addTextBlock("BTN_CDISC_ITEM","e431t2_client");c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[6]={fld:"TABLE2",grid:0};b[12]={fld:"TABLE8",grid:0};
b[15]={fld:"TXT_BTN_REG",format:0,grid:0};b[16]={fld:"TXT_BTN_REG2",format:0,grid:0};b[19]={fld:"TEXTBLOCK43",format:0,grid:0};b[22]={fld:"TEXTBLOCK46",format:0,grid:0};b[25]={fld:"TABLE3",grid:0};b[28]={fld:"TABLE4",grid:0};b[31]={fld:"TABLE5",grid:0};b[35]={lvl:0,type:"svchar",len:16,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_DOM_CD",gxz:"ZV7D_DOM_CD",gxold:"OV7D_DOM_CD",gxvar:"AV7D_DOM_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV7D_DOM_CD=
a},v2z:function(a){gx.O.ZV7D_DOM_CD=a},v2c:function(){gx.fn.setControlValue("vD_DOM_CD",gx.O.AV7D_DOM_CD,0)},c2v:function(){gx.O.AV7D_DOM_CD=this.val()},val:function(){return gx.fn.getControlValue("vD_DOM_CD")},nac:gx.falseFn};b[38]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_DOM_JNM",gxz:"ZV8D_DOM_JNM",gxold:"OV8D_DOM_JNM",gxvar:"AV8D_DOM_JNM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV8D_DOM_JNM=a},v2z:function(a){gx.O.ZV8D_DOM_JNM=
a},v2c:function(){gx.fn.setControlValue("vD_DOM_JNM",gx.O.AV8D_DOM_JNM,0)},c2v:function(){gx.O.AV8D_DOM_JNM=this.val()},val:function(){return gx.fn.getControlValue("vD_DOM_JNM")},nac:gx.falseFn};b[41]={fld:"TABLE9",grid:0};b[44]={fld:"TEXTBLOCK45",format:0,grid:0};b[47]={fld:"TEXTBLOCK44",format:0,grid:0};b[53]={fld:"TBL_PAGE_AREA",grid:0};b[56]={fld:"TXT_REC_CNT",format:0,grid:0};b[59]={fld:"TBL_PAGE",grid:0};b[62]={fld:"TBL_FIRST",grid:0};b[65]={fld:"TXT_FIRST",format:0,grid:0};b[68]={fld:"TBL_BACK",
grid:0};b[71]={fld:"TXT_BACK",format:0,grid:0};b[74]={fld:"TBL_PAGE01",grid:0};b[77]={fld:"TXT_PAGE01",format:0,grid:0};b[80]={fld:"TBL_PAGE02",grid:0};b[83]={fld:"TXT_PAGE02",format:0,grid:0};b[86]={fld:"TBL_PAGE03",grid:0};b[89]={fld:"TXT_PAGE03",format:0,grid:0};b[92]={fld:"TBL_PAGE04",grid:0};b[95]={fld:"TXT_PAGE04",format:0,grid:0};b[98]={fld:"TBL_PAGE05",grid:0};b[101]={fld:"TXT_PAGE05",format:0,grid:0};b[104]={fld:"TBL_PAGE06",grid:0};b[107]={fld:"TXT_PAGE06",format:0,grid:0};b[110]={fld:"TBL_PAGE07",
grid:0};b[113]={fld:"TXT_PAGE07",format:0,grid:0};b[116]={fld:"TBL_PAGE08",grid:0};b[119]={fld:"TXT_PAGE08",format:0,grid:0};b[122]={fld:"TBL_PAGE09",grid:0};b[125]={fld:"TXT_PAGE09",format:0,grid:0};b[128]={fld:"TBL_PAGE10",grid:0};b[131]={fld:"TXT_PAGE10",format:0,grid:0};b[134]={fld:"TBL_NEXT",grid:0};b[137]={fld:"TXT_NEXT",format:0,grid:0};b[140]={fld:"TBL_LAST",grid:0};b[143]={fld:"TXT_LAST",format:0,grid:0};b[145]={fld:"TBL_EDIT",grid:0};b[148]={fld:"TEXTBLOCK29",format:0,grid:0};b[150]={lvl:0,
type:"char",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_LINE",gxz:"ZV13D_LINE",gxold:"OV13D_LINE",gxvar:"AV13D_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13D_LINE=a},v2z:function(a){gx.O.ZV13D_LINE=a},v2c:function(){gx.fn.setControlValue("vD_LINE",gx.O.AV13D_LINE,0)},c2v:function(){gx.O.AV13D_LINE=this.val()},val:function(){return gx.fn.getControlValue("vD_LINE")},nac:gx.falseFn};b[153]={fld:"TEXTBLOCK28",format:0,grid:0};b[158]=
{fld:"TBL_GRID_HEADER",grid:0};b[162]={fld:"TEXTBLOCK35",format:0,grid:0};b[164]={fld:"TEXTBLOCK30",format:0,grid:0};b[165]={fld:"TXT_SORT01_DESC",format:0,grid:0};b[166]={fld:"TXT_SORT01_ASC",format:0,grid:0};b[168]={fld:"TEXTBLOCK31",format:0,grid:0};b[169]={fld:"TXT_SORT02_DESC",format:0,grid:0};b[170]={fld:"TXT_SORT02_ASC",format:0,grid:0};b[172]={fld:"TEXTBLOCK34",format:0,grid:0};b[173]={fld:"TXT_SORT03_DESC",format:0,grid:0};b[174]={fld:"TXT_SORT03_ASC",format:0,grid:0};b[176]={fld:"TEXTBLOCK33",
format:0,grid:0};b[177]={fld:"TXT_SORT04_DESC",format:0,grid:0};b[178]={fld:"TXT_SORT04_ASC",format:0,grid:0};b[185]={fld:"BTN_SEL",format:0,grid:182};b[187]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,isacc:0,grid:182,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_LINE",gxz:"ZV10D_GRD_LINE",gxold:"OV10D_GRD_LINE",gxvar:"AV10D_GRD_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV10D_GRD_LINE=gx.num.intval(a)},v2z:function(a){gx.O.ZV10D_GRD_LINE=
gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(182),gx.O.AV10D_GRD_LINE,0)},c2v:function(){gx.O.AV10D_GRD_LINE=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(182),",")},nac:gx.falseFn};b[189]={lvl:2,type:"svchar",len:16,dec:0,sign:false,ro:1,isacc:0,grid:182,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM02_DOM_CD",gxz:"Z49TBM02_DOM_CD",gxold:"O49TBM02_DOM_CD",
gxvar:"A49TBM02_DOM_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A49TBM02_DOM_CD=a},v2z:function(a){gx.O.Z49TBM02_DOM_CD=a},v2c:function(a){gx.fn.setGridControlValue("TBM02_DOM_CD",a||gx.fn.currentGridRowImpl(182),gx.O.A49TBM02_DOM_CD,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A49TBM02_DOM_CD=this.val()},val:function(a){return gx.fn.getGridControlValue("TBM02_DOM_CD",a||gx.fn.currentGridRowImpl(182))},
nac:gx.falseFn};b[191]={lvl:2,type:"svchar",len:50,dec:0,sign:false,ro:1,isacc:0,grid:182,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM02_DOM_JNM",gxz:"Z611TBM02_DOM_JNM",gxold:"O611TBM02_DOM_JNM",gxvar:"A611TBM02_DOM_JNM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A611TBM02_DOM_JNM=a},v2z:function(a){gx.O.Z611TBM02_DOM_JNM=a},v2c:function(a){gx.fn.setGridControlValue("TBM02_DOM_JNM",a||gx.fn.currentGridRowImpl(182),gx.O.A611TBM02_DOM_JNM,
0)},c2v:function(){gx.O.A611TBM02_DOM_JNM=this.val()},val:function(a){return gx.fn.getGridControlValue("TBM02_DOM_JNM",a||gx.fn.currentGridRowImpl(182))},nac:gx.falseFn};b[193]={lvl:2,type:"int",len:5,dec:0,sign:false,pic:"ZZZZ9",ro:1,isacc:0,grid:182,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM02_ORDER",gxz:"Z614TBM02_ORDER",gxold:"O614TBM02_ORDER",gxvar:"A614TBM02_ORDER",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A614TBM02_ORDER=gx.num.intval(a)},
v2z:function(a){gx.O.Z614TBM02_ORDER=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TBM02_ORDER",a||gx.fn.currentGridRowImpl(182),gx.O.A614TBM02_ORDER,0)},c2v:function(){gx.O.A614TBM02_ORDER=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TBM02_ORDER",a||gx.fn.currentGridRowImpl(182),",")},nac:gx.falseFn};b[195]={lvl:2,type:"svchar",len:10,dec:0,sign:false,ro:0,isacc:0,grid:182,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_DEL",gxz:"ZV9D_GRD_DEL",
gxold:"OV9D_GRD_DEL",gxvar:"AV9D_GRD_DEL",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV9D_GRD_DEL=a},v2z:function(a){gx.O.ZV9D_GRD_DEL=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_DEL",a||gx.fn.currentGridRowImpl(182),gx.O.AV9D_GRD_DEL,0)},c2v:function(){gx.O.AV9D_GRD_DEL=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_DEL",a||gx.fn.currentGridRowImpl(182))},nac:gx.falseFn};b[197]={fld:"BTN_CDISC_ITEM",format:0,grid:182};
b[204]={fld:"TBL_HIDDEN",grid:0};b[207]={fld:"TXT_JS_EVENT",format:1,grid:0};b[208]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV17H_INIT_FLG",gxold:"OV17H_INIT_FLG",gxvar:"AV17H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV17H_INIT_FLG=a},v2z:function(a){gx.O.ZV17H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV17H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},
c2v:function(){gx.O.AV17H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(208,function(){});b[209]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SRCH_FLG",gxz:"ZV19H_SRCH_FLG",gxold:"OV19H_SRCH_FLG",gxvar:"AV19H_SRCH_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV19H_SRCH_FLG=a},v2z:function(a){gx.O.ZV19H_SRCH_FLG=a},v2c:function(){gx.fn.setControlValue("vH_SRCH_FLG",
gx.O.AV19H_SRCH_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV19H_SRCH_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_SRCH_FLG")},nac:gx.falseFn};this.declareDomainHdlr(209,function(){});b[210]={lvl:0,type:"svchar",len:16,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_DOM_CD",gxz:"ZV15H_DOM_CD",gxold:"OV15H_DOM_CD",gxvar:"AV15H_DOM_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_DOM_CD=
a},v2z:function(a){gx.O.ZV15H_DOM_CD=a},v2c:function(){gx.fn.setControlValue("vH_DOM_CD",gx.O.AV15H_DOM_CD,0)},c2v:function(){gx.O.AV15H_DOM_CD=this.val()},val:function(){return gx.fn.getControlValue("vH_DOM_CD")},nac:gx.falseFn};b[211]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_DOM_JNM",gxz:"ZV16H_DOM_JNM",gxold:"OV16H_DOM_JNM",gxvar:"AV16H_DOM_JNM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV16H_DOM_JNM=
a},v2z:function(a){gx.O.ZV16H_DOM_JNM=a},v2c:function(){gx.fn.setControlValue("vH_DOM_JNM",gx.O.AV16H_DOM_JNM,0)},c2v:function(){gx.O.AV16H_DOM_JNM=this.val()},val:function(){return gx.fn.getControlValue("vH_DOM_JNM")},nac:gx.falseFn};b[212]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV18H_KNGN_FLG",gxold:"OV18H_KNGN_FLG",gxvar:"AV18H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV18H_KNGN_FLG=
a},v2z:function(a){gx.O.ZV18H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV18H_KNGN_FLG,0)},c2v:function(){gx.O.AV18H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[213]={fld:"TABLE7",grid:0};b[216]={fld:"TEXTBLOCK1",format:0,grid:0};b[218]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLMAX_ROW",gxz:"ZV37GXV1",gxold:"OV37GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],
nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=gx.num.intval(a)},v2z:function(a){gx.O.ZV37GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLMAX_ROW",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLMAX_ROW",",")},nac:gx.falseFn};b[221]={fld:"TABLE6",grid:0};b[224]={fld:"TEXTBLOCK2",format:0,grid:0};b[226]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],
fld:"vH_SORT_ASDC_KBN",gxz:"ZV33H_SORT_ASDC_KBN",gxold:"OV33H_SORT_ASDC_KBN",gxvar:"AV33H_SORT_ASDC_KBN",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV33H_SORT_ASDC_KBN=gx.num.intval(a)},v2z:function(a){gx.O.ZV33H_SORT_ASDC_KBN=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vH_SORT_ASDC_KBN",gx.O.AV33H_SORT_ASDC_KBN,0)},c2v:function(){gx.O.AV33H_SORT_ASDC_KBN=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vH_SORT_ASDC_KBN",",")},nac:gx.falseFn};
b[229]={fld:"TEXTBLOCK3",format:0,grid:0};b[231]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SORT_ITEM_KBN",gxz:"ZV34H_SORT_ITEM_KBN",gxold:"OV34H_SORT_ITEM_KBN",gxvar:"AV34H_SORT_ITEM_KBN",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV34H_SORT_ITEM_KBN=gx.num.intval(a)},v2z:function(a){gx.O.ZV34H_SORT_ITEM_KBN=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vH_SORT_ITEM_KBN",gx.O.AV34H_SORT_ITEM_KBN,
0)},c2v:function(){gx.O.AV34H_SORT_ITEM_KBN=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vH_SORT_ITEM_KBN",",")},nac:gx.falseFn};this.OV13D_LINE=this.ZV13D_LINE=this.AV13D_LINE=this.OV8D_DOM_JNM=this.ZV8D_DOM_JNM=this.AV8D_DOM_JNM=this.OV7D_DOM_CD=this.ZV7D_DOM_CD=this.AV7D_DOM_CD="";this.OV10D_GRD_LINE=this.ZV10D_GRD_LINE=0;this.O611TBM02_DOM_JNM=this.Z611TBM02_DOM_JNM=this.O49TBM02_DOM_CD=this.Z49TBM02_DOM_CD="";this.O614TBM02_ORDER=this.Z614TBM02_ORDER=0;this.OV18H_KNGN_FLG=
this.ZV18H_KNGN_FLG=this.AV18H_KNGN_FLG=this.OV16H_DOM_JNM=this.ZV16H_DOM_JNM=this.AV16H_DOM_JNM=this.OV15H_DOM_CD=this.ZV15H_DOM_CD=this.AV15H_DOM_CD=this.OV19H_SRCH_FLG=this.ZV19H_SRCH_FLG=this.AV19H_SRCH_FLG=this.OV17H_INIT_FLG=this.ZV17H_INIT_FLG=this.AV17H_INIT_FLG=this.OV9D_GRD_DEL=this.ZV9D_GRD_DEL="";this.OV34H_SORT_ITEM_KBN=this.ZV34H_SORT_ITEM_KBN=this.AV34H_SORT_ITEM_KBN=this.OV33H_SORT_ASDC_KBN=this.ZV33H_SORT_ASDC_KBN=this.AV33H_SORT_ASDC_KBN=this.OV37GXV1=this.ZV37GXV1=this.GXV1=0;this.AV18H_KNGN_FLG=
this.AV16H_DOM_JNM=this.AV15H_DOM_CD=this.AV19H_SRCH_FLG=this.AV17H_INIT_FLG=this.AV13D_LINE=this.AV8D_DOM_JNM=this.AV7D_DOM_CD="";this.AV20P_MOVE_KBN=this.AV34H_SORT_ITEM_KBN=this.AV33H_SORT_ASDC_KBN=this.GXV1=0;this.A615TBM02_DEL_FLG="";this.AV10D_GRD_LINE=0;this.A611TBM02_DOM_JNM=this.A49TBM02_DOM_CD="";this.A614TBM02_ORDER=0;this.AV23W_A821_JS=this.AV6C_TAM02_APP_ID=this.AV39Pgmname=this.AV9D_GRD_DEL="";this.AV14H_A_PAGING_SDT={};this.AV25W_ERRFLG=false;this.AV32C_GRID_ROWS=0;this.AV26W_F7FLG=
false;this.AV22W_A819_JS="";this.Events={e111t2_client:["'BTN_REG'",true],e121t2_client:["'BTN_CSV'",true],e131t2_client:["'BTN_SRCH'",true],e141t2_client:["'BTN_CLER'",true],e151t2_client:["'BTN_EDIT'",true],e161t2_client:["'BTN_IMPORT_DOMAIN'",true],e421t2_client:["'BTN_SEL'",true],e431t2_client:["'BTN_CDISC_ITEM'",true],e171t2_client:["'PAGE_FIRST'",true],e181t2_client:["'PAGE_LAST'",true],e191t2_client:["'PAGE_BACK'",true],e201t2_client:["'PAGE_NEXT'",true],e211t2_client:["'PAGE01'",true],e221t2_client:["'PAGE02'",
true],e231t2_client:["'PAGE03'",true],e241t2_client:["'PAGE04'",true],e251t2_client:["'PAGE05'",true],e261t2_client:["'PAGE06'",true],e271t2_client:["'PAGE07'",true],e281t2_client:["'PAGE08'",true],e291t2_client:["'PAGE09'",true],e301t2_client:["'PAGE10'",true],e311t2_client:["'SORT01_ASC'",true],e321t2_client:["'SORT01_DESC'",true],e331t2_client:["'SORT02_ASC'",true],e341t2_client:["'SORT02_DESC'",true],e351t2_client:["'SORT03_ASC'",true],e361t2_client:["'SORT03_DESC'",true],e371t2_client:["'SORT04_ASC'",
true],e381t2_client:["'SORT04_DESC'",true],e441t2_client:["ENTER",true],e451t2_client:["CANCEL",true]};this.setVCMap("AV39Pgmname","vPGMNAME",0,"char");this.setVCMap("AV6C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV20P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV23W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV14H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV25W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV32C_GRID_ROWS","vC_GRID_ROWS",0,"int");
this.setVCMap("A615TBM02_DEL_FLG","TBM02_DEL_FLG",0,"svchar");this.setVCMap("AV39Pgmname","vPGMNAME",0,"char");this.setVCMap("AV6C_TAM02_APP_ID","vC_TAM02_APP_ID",0,"svchar");this.setVCMap("AV20P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV23W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV14H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV25W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV32C_GRID_ROWS","vC_GRID_ROWS",0,"int");this.setVCMap("A615TBM02_DEL_FLG","TBM02_DEL_FLG",
0,"svchar");c.addRefreshingVar(this.GXValidFnc[209]);c.addRefreshingVar(this.GXValidFnc[210]);c.addRefreshingVar(this.GXValidFnc[211]);c.addRefreshingVar(this.GXValidFnc[226]);c.addRefreshingVar(this.GXValidFnc[231]);c.addRefreshingVar(this.GXValidFnc[208]);c.addRefreshingVar({rfrVar:"AV39Pgmname"});c.addRefreshingVar(this.GXValidFnc[35]);c.addRefreshingVar({rfrVar:"AV6C_TAM02_APP_ID"});c.addRefreshingVar({rfrVar:"AV20P_MOVE_KBN"});c.addRefreshingVar(this.GXValidFnc[212]);c.addRefreshingVar({rfrVar:"AV23W_A821_JS"});
c.addRefreshingVar({rfrVar:"AV14H_A_PAGING_SDT"});c.addRefreshingVar({rfrVar:"AV25W_ERRFLG"});c.addRefreshingVar(this.GXValidFnc[38]);c.addRefreshingVar({rfrVar:"AV10D_GRD_LINE",rfrProp:"Value",gxAttId:"D_grd_line"});c.addRefreshingVar({rfrVar:"AV32C_GRID_ROWS"});c.addRefreshingVar({rfrVar:"A615TBM02_DEL_FLG"});this.addBCProperty("H_a_paging_sdt",["MAX_ROW"],this.GXValidFnc[218],"AV14H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",
GXClass:null,Prefix:"W0202",lvl:1})});gx.setParentObj(new a208_wp01_domain_list);
