gx.evt.autoSkip=!1;
gx.define("b201_wp01_image_mst_list",!1,function(){this.ServerClass="b201_wp01_image_mst_list";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e11132_client");this.addKeyListener("5","e12132_client");this.addKeyListener("6","e13132_client");this.addKeyListener("7","e14132_client");this.SetStandaloneVars=function(){this.AV36Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV5C_APP_ID=gx.fn.getControlValue("vC_APP_ID");
this.AV18P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV21W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.AV12H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.AV23W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG");this.AV31C_GRID_ROWS=gx.fn.getIntegerValue("vC_GRID_ROWS",",");this.A63TBM21_STUDY_ID=gx.fn.getIntegerValue("TBM21_STUDY_ID",",");this.A606TBM11_STUDY_ID=gx.fn.getIntegerValue("TBM11_STUDY_ID",",");this.A367TBM21_STUDY_NM=gx.fn.getControlValue("TBM21_STUDY_NM");this.A535TBM11_DEL_FLG=
gx.fn.getControlValue("TBM11_DEL_FLG")};this.s122_client=function(){this.AV13H_FILE_NAME=this.AV14H_IMAGE_CD=this.AV7D_FILE_NAME=this.AV10D_IMAGE_CD="";this.AV12H_A_PAGING_SDT.PAGE_NO=1;this.AV17H_SRCH_FLG="0";this.AV20W_A819_JS="";this.AV24W_F7FLG=false;this.AV11D_LINE="";gx.fn.setCtrlProperty("vD_LINE","Backcolor",gx.color.rgb(255,255,255))};this.s192_client=function(){this.AV14H_IMAGE_CD=this.AV10D_IMAGE_CD;this.AV13H_FILE_NAME=this.AV7D_FILE_NAME};this.s162_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");if(""!=this.AV21W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV21W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"<\/script>")};this.e11132_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e12132_client=function(){this.executeServerEvent("'BTN_SRCH'",true)};this.e13132_client=function(){this.executeServerEvent("'BTN_CLER'",true)};this.e14132_client=function(){this.executeServerEvent("'BTN_EDIT'",true)};this.e32132_client=function(a){this.executeServerEvent("'BTN_SEL'",true,a)};this.e15132_client=function(){this.executeServerEvent("'PAGE_FIRST'",true)};this.e16132_client=function(){this.executeServerEvent("'PAGE_LAST'",
true)};this.e17132_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e18132_client=function(){this.executeServerEvent("'PAGE_NEXT'",true)};this.e19132_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e20132_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e21132_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e22132_client=function(){this.executeServerEvent("'PAGE04'",true)};this.e23132_client=function(){this.executeServerEvent("'PAGE05'",
true)};this.e24132_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e25132_client=function(){this.executeServerEvent("'PAGE07'",true)};this.e26132_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e27132_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e28132_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e33132_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e34132_client=function(a){this.executeServerEvent("CANCEL",
true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,16,19,22,25,29,32,35,38,41,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92,95,98,101,104,107,110,113,116,119,122,125,128,131,134,137,139,142,144,147,152,156,158,160,162,164,170,172,174,175,177,178,180,181,183,190,193,194,195,196,197,198,199];this.GXLastCtrlId=199;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",167,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"b201_wp01_image_mst_list",[],true,1,true,true,
10,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,true,null,null,false,"",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","center","","","","","45px","","","");c.addTextBlock("BTN_SEL","e32132_client");c.endCell();c.startCell("","","","","","","50px","","","");c.addSingleLineEdit("D_grd_line",172,"vD_GRD_LINE","","","D_GRD_LINE","int",4,"chr",4,4,"right",null,[],"D_grd_line","D_GRD_LINE",true,0,false,false,"ReadonlyAttribute",1,"");c.endCell();c.startCell("","","","","",
"","120px","","","");c.startDiv("Section1","0px","115px");c.addSingleLineEdit(62,175,"TBM11_IMAGE_CD","","","TBM11_IMAGE_CD","svchar",10,"chr",50,50,"left",null,[],62,"TBM11_IMAGE_CD",true,0,false,false,"ReadonlyAttribute",1,"");c.endDiv();c.endCell();c.startCell("","","","","","","200px","","","");c.startDiv("Section2","0px","195px");c.addSingleLineEdit("D_grd_study_nm",178,"vD_GRD_STUDY_NM","","","D_GRD_STUDY_NM","svchar",30,"chr",100,80,"left",null,[],"D_grd_study_nm","D_GRD_STUDY_NM",true,0,false,
false,"ReadonlyAttribute",1,"");c.endDiv();c.endCell();c.startCell("","","","","","","300px","","","");c.startDiv("Section3","0px","295px");c.addSingleLineEdit(534,181,"TBM11_FILE_NAME","","","TBM11_FILE_NAME","svchar",20,"chr",100,80,"left",null,[],534,"TBM11_FILE_NAME",true,0,false,false,"ReadonlyAttribute",1,"");c.endDiv();c.endCell();c.startCell("","center","","","","","100px","","","");c.addSingleLineEdit("D_grd_del",183,"vD_GRD_DEL","","","D_GRD_DEL","svchar",10,"chr",10,10,"left",null,[],"D_grd_del",
"D_GRD_DEL",true,0,false,false,"ReadonlyAttribute",1,"");c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[6]={fld:"TABLE2",grid:0};b[12]={fld:"TABLE8",grid:0};b[15]={fld:"TXT_BTN_REG",format:0,grid:0};b[16]={fld:"TXT_BTN_REG2",format:0,grid:0};b[19]={fld:"TABLE3",grid:0};b[22]={fld:"TABLE4",grid:0};b[25]={fld:"TABLE5",grid:0};b[29]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_IMAGE_CD",gxz:"ZV10D_IMAGE_CD",gxold:"OV10D_IMAGE_CD",
gxvar:"AV10D_IMAGE_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10D_IMAGE_CD=a},v2z:function(a){gx.O.ZV10D_IMAGE_CD=a},v2c:function(){gx.fn.setControlValue("vD_IMAGE_CD",gx.O.AV10D_IMAGE_CD,0)},c2v:function(){gx.O.AV10D_IMAGE_CD=this.val()},val:function(){return gx.fn.getControlValue("vD_IMAGE_CD")},nac:gx.falseFn};b[32]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_FILE_NAME",gxz:"ZV7D_FILE_NAME",gxold:"OV7D_FILE_NAME",
gxvar:"AV7D_FILE_NAME",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV7D_FILE_NAME=a},v2z:function(a){gx.O.ZV7D_FILE_NAME=a},v2c:function(){gx.fn.setControlValue("vD_FILE_NAME",gx.O.AV7D_FILE_NAME,0)},c2v:function(){gx.O.AV7D_FILE_NAME=this.val()},val:function(){return gx.fn.getControlValue("vD_FILE_NAME")},nac:gx.falseFn};b[35]={fld:"TABLE9",grid:0};b[38]={fld:"TEXTBLOCK45",format:0,grid:0};b[41]={fld:"TEXTBLOCK44",format:0,grid:0};b[47]={fld:"TBL_PAGE_AREA",grid:0};b[50]={fld:"TXT_REC_CNT",
format:0,grid:0};b[53]={fld:"TBL_PAGE",grid:0};b[56]={fld:"TBL_FIRST",grid:0};b[59]={fld:"TXT_FIRST",format:0,grid:0};b[62]={fld:"TBL_BACK",grid:0};b[65]={fld:"TXT_BACK",format:0,grid:0};b[68]={fld:"TBL_PAGE01",grid:0};b[71]={fld:"TXT_PAGE01",format:0,grid:0};b[74]={fld:"TBL_PAGE02",grid:0};b[77]={fld:"TXT_PAGE02",format:0,grid:0};b[80]={fld:"TBL_PAGE03",grid:0};b[83]={fld:"TXT_PAGE03",format:0,grid:0};b[86]={fld:"TBL_PAGE04",grid:0};b[89]={fld:"TXT_PAGE04",format:0,grid:0};b[92]={fld:"TBL_PAGE05",
grid:0};b[95]={fld:"TXT_PAGE05",format:0,grid:0};b[98]={fld:"TBL_PAGE06",grid:0};b[101]={fld:"TXT_PAGE06",format:0,grid:0};b[104]={fld:"TBL_PAGE07",grid:0};b[107]={fld:"TXT_PAGE07",format:0,grid:0};b[110]={fld:"TBL_PAGE08",grid:0};b[113]={fld:"TXT_PAGE08",format:0,grid:0};b[116]={fld:"TBL_PAGE09",grid:0};b[119]={fld:"TXT_PAGE09",format:0,grid:0};b[122]={fld:"TBL_PAGE10",grid:0};b[125]={fld:"TXT_PAGE10",format:0,grid:0};b[128]={fld:"TBL_NEXT",grid:0};b[131]={fld:"TXT_NEXT",format:0,grid:0};b[134]=
{fld:"TBL_LAST",grid:0};b[137]={fld:"TXT_LAST",format:0,grid:0};b[139]={fld:"TBL_EDIT",grid:0};b[142]={fld:"TEXTBLOCK29",format:0,grid:0};b[144]={lvl:0,type:"char",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_LINE",gxz:"ZV11D_LINE",gxold:"OV11D_LINE",gxvar:"AV11D_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11D_LINE=a},v2z:function(a){gx.O.ZV11D_LINE=a},v2c:function(){gx.fn.setControlValue("vD_LINE",gx.O.AV11D_LINE,0)},c2v:function(){gx.O.AV11D_LINE=
this.val()},val:function(){return gx.fn.getControlValue("vD_LINE")},nac:gx.falseFn};b[147]={fld:"TEXTBLOCK28",format:0,grid:0};b[152]={fld:"TBL_GRID_HEADER",grid:0};b[156]={fld:"TEXTBLOCK34",format:0,grid:0};b[158]={fld:"TEXTBLOCK32",format:0,grid:0};b[160]={fld:"TEXTBLOCK30",format:0,grid:0};b[162]={fld:"TEXTBLOCK31",format:0,grid:0};b[164]={fld:"TEXTBLOCK33",format:0,grid:0};b[170]={fld:"BTN_SEL",format:0,grid:167};b[172]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,isacc:0,grid:167,
gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_LINE",gxz:"ZV9D_GRD_LINE",gxold:"OV9D_GRD_LINE",gxvar:"AV9D_GRD_LINE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV9D_GRD_LINE=gx.num.intval(a)},v2z:function(a){gx.O.ZV9D_GRD_LINE=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_LINE",a||gx.fn.currentGridRowImpl(167),gx.O.AV9D_GRD_LINE,0)},c2v:function(){gx.O.AV9D_GRD_LINE=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("vD_GRD_LINE",
a||gx.fn.currentGridRowImpl(167),",")},nac:gx.falseFn};b[174]={fld:"SECTION1",grid:167};b[175]={lvl:2,type:"svchar",len:50,dec:0,sign:false,ro:1,isacc:0,grid:167,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM11_IMAGE_CD",gxz:"Z62TBM11_IMAGE_CD",gxold:"O62TBM11_IMAGE_CD",gxvar:"A62TBM11_IMAGE_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A62TBM11_IMAGE_CD=a},v2z:function(a){gx.O.Z62TBM11_IMAGE_CD=a},v2c:function(a){gx.fn.setGridControlValue("TBM11_IMAGE_CD",
a||gx.fn.currentGridRowImpl(167),gx.O.A62TBM11_IMAGE_CD,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A62TBM11_IMAGE_CD=this.val()},val:function(a){return gx.fn.getGridControlValue("TBM11_IMAGE_CD",a||gx.fn.currentGridRowImpl(167))},nac:gx.falseFn};b[177]={fld:"SECTION2",grid:167};b[178]={lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:0,isacc:0,grid:167,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_STUDY_NM",gxz:"ZV30D_GRD_STUDY_NM",gxold:"OV30D_GRD_STUDY_NM",
gxvar:"AV30D_GRD_STUDY_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV30D_GRD_STUDY_NM=a},v2z:function(a){gx.O.ZV30D_GRD_STUDY_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_STUDY_NM",a||gx.fn.currentGridRowImpl(167),gx.O.AV30D_GRD_STUDY_NM,0)},c2v:function(){gx.O.AV30D_GRD_STUDY_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_STUDY_NM",a||gx.fn.currentGridRowImpl(167))},nac:gx.falseFn};b[180]={fld:"SECTION3",
grid:167};b[181]={lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:167,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM11_FILE_NAME",gxz:"Z534TBM11_FILE_NAME",gxold:"O534TBM11_FILE_NAME",gxvar:"A534TBM11_FILE_NAME",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A534TBM11_FILE_NAME=a},v2z:function(a){gx.O.Z534TBM11_FILE_NAME=a},v2c:function(a){gx.fn.setGridControlValue("TBM11_FILE_NAME",a||gx.fn.currentGridRowImpl(167),
gx.O.A534TBM11_FILE_NAME,0)},c2v:function(){gx.O.A534TBM11_FILE_NAME=this.val()},val:function(a){return gx.fn.getGridControlValue("TBM11_FILE_NAME",a||gx.fn.currentGridRowImpl(167))},nac:gx.falseFn};b[183]={lvl:2,type:"svchar",len:10,dec:0,sign:false,ro:0,isacc:0,grid:167,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_DEL",gxz:"ZV8D_GRD_DEL",gxold:"OV8D_GRD_DEL",gxvar:"AV8D_GRD_DEL",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV8D_GRD_DEL=
a},v2z:function(a){gx.O.ZV8D_GRD_DEL=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_DEL",a||gx.fn.currentGridRowImpl(167),gx.O.AV8D_GRD_DEL,0)},c2v:function(){gx.O.AV8D_GRD_DEL=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_DEL",a||gx.fn.currentGridRowImpl(167))},nac:gx.falseFn};b[190]={fld:"TBL_HIDDEN",grid:0};b[193]={fld:"TXT_JS_EVENT",format:1,grid:0};b[194]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",
gxz:"ZV15H_INIT_FLG",gxold:"OV15H_INIT_FLG",gxvar:"AV15H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_INIT_FLG=a},v2z:function(a){gx.O.ZV15H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV15H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV15H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(194,function(){});b[195]={lvl:0,type:"svchar",
len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SRCH_FLG",gxz:"ZV17H_SRCH_FLG",gxold:"OV17H_SRCH_FLG",gxvar:"AV17H_SRCH_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV17H_SRCH_FLG=a},v2z:function(a){gx.O.ZV17H_SRCH_FLG=a},v2c:function(){gx.fn.setControlValue("vH_SRCH_FLG",gx.O.AV17H_SRCH_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV17H_SRCH_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_SRCH_FLG")},
nac:gx.falseFn};this.declareDomainHdlr(195,function(){});b[196]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV16H_KNGN_FLG",gxold:"OV16H_KNGN_FLG",gxvar:"AV16H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV16H_KNGN_FLG=a},v2z:function(a){gx.O.ZV16H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV16H_KNGN_FLG,0)},c2v:function(){gx.O.AV16H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},
nac:gx.falseFn};b[197]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_IMAGE_CD",gxz:"ZV14H_IMAGE_CD",gxold:"OV14H_IMAGE_CD",gxvar:"AV14H_IMAGE_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV14H_IMAGE_CD=a},v2z:function(a){gx.O.ZV14H_IMAGE_CD=a},v2c:function(){gx.fn.setControlValue("vH_IMAGE_CD",gx.O.AV14H_IMAGE_CD,0)},c2v:function(){gx.O.AV14H_IMAGE_CD=this.val()},val:function(){return gx.fn.getControlValue("vH_IMAGE_CD")},
nac:gx.falseFn};b[198]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_FILE_NAME",gxz:"ZV13H_FILE_NAME",gxold:"OV13H_FILE_NAME",gxvar:"AV13H_FILE_NAME",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_FILE_NAME=a},v2z:function(a){gx.O.ZV13H_FILE_NAME=a},v2c:function(){gx.fn.setControlValue("vH_FILE_NAME",gx.O.AV13H_FILE_NAME,0)},c2v:function(){gx.O.AV13H_FILE_NAME=this.val()},val:function(){return gx.fn.getControlValue("vH_FILE_NAME")},
nac:gx.falseFn};b[199]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLREC_CNT",gxz:"ZV34GXV1",gxold:"OV34GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=gx.num.intval(a)},v2z:function(a){gx.O.ZV34GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",
",")},nac:gx.falseFn};this.OV11D_LINE=this.ZV11D_LINE=this.AV11D_LINE=this.OV7D_FILE_NAME=this.ZV7D_FILE_NAME=this.AV7D_FILE_NAME=this.OV10D_IMAGE_CD=this.ZV10D_IMAGE_CD=this.AV10D_IMAGE_CD="";this.OV9D_GRD_LINE=this.ZV9D_GRD_LINE=0;this.OV13H_FILE_NAME=this.ZV13H_FILE_NAME=this.AV13H_FILE_NAME=this.OV14H_IMAGE_CD=this.ZV14H_IMAGE_CD=this.AV14H_IMAGE_CD=this.OV16H_KNGN_FLG=this.ZV16H_KNGN_FLG=this.AV16H_KNGN_FLG=this.OV17H_SRCH_FLG=this.ZV17H_SRCH_FLG=this.AV17H_SRCH_FLG=this.OV15H_INIT_FLG=this.ZV15H_INIT_FLG=
this.AV15H_INIT_FLG=this.OV8D_GRD_DEL=this.ZV8D_GRD_DEL=this.O534TBM11_FILE_NAME=this.Z534TBM11_FILE_NAME=this.OV30D_GRD_STUDY_NM=this.ZV30D_GRD_STUDY_NM=this.O62TBM11_IMAGE_CD=this.Z62TBM11_IMAGE_CD="";this.OV34GXV1=this.ZV34GXV1=this.GXV1=0;this.AV13H_FILE_NAME=this.AV14H_IMAGE_CD=this.AV16H_KNGN_FLG=this.AV17H_SRCH_FLG=this.AV15H_INIT_FLG=this.AV11D_LINE=this.AV7D_FILE_NAME=this.AV10D_IMAGE_CD="";this.A606TBM11_STUDY_ID=this.AV18P_MOVE_KBN=this.GXV1=0;this.A535TBM11_DEL_FLG="";this.AV9D_GRD_LINE=
0;this.AV8D_GRD_DEL=this.A534TBM11_FILE_NAME=this.AV30D_GRD_STUDY_NM=this.A62TBM11_IMAGE_CD="";this.A63TBM21_STUDY_ID=0;this.AV21W_A821_JS=this.AV5C_APP_ID=this.AV36Pgmname=this.A367TBM21_STUDY_NM="";this.AV12H_A_PAGING_SDT={};this.AV23W_ERRFLG=false;this.AV31C_GRID_ROWS=0;this.AV24W_F7FLG=false;this.AV20W_A819_JS="";this.Events={e11132_client:["'BTN_REG'",true],e12132_client:["'BTN_SRCH'",true],e13132_client:["'BTN_CLER'",true],e14132_client:["'BTN_EDIT'",true],e32132_client:["'BTN_SEL'",true],e15132_client:["'PAGE_FIRST'",
true],e16132_client:["'PAGE_LAST'",true],e17132_client:["'PAGE_BACK'",true],e18132_client:["'PAGE_NEXT'",true],e19132_client:["'PAGE01'",true],e20132_client:["'PAGE02'",true],e21132_client:["'PAGE03'",true],e22132_client:["'PAGE04'",true],e23132_client:["'PAGE05'",true],e24132_client:["'PAGE06'",true],e25132_client:["'PAGE07'",true],e26132_client:["'PAGE08'",true],e27132_client:["'PAGE09'",true],e28132_client:["'PAGE10'",true],e33132_client:["ENTER",true],e34132_client:["CANCEL",true]};this.setVCMap("AV36Pgmname",
"vPGMNAME",0,"char");this.setVCMap("AV5C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV18P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV21W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV12H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV23W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV31C_GRID_ROWS","vC_GRID_ROWS",0,"int");this.setVCMap("A63TBM21_STUDY_ID","TBM21_STUDY_ID",0,"int");this.setVCMap("A606TBM11_STUDY_ID","TBM11_STUDY_ID",0,"int");this.setVCMap("A367TBM21_STUDY_NM",
"TBM21_STUDY_NM",0,"svchar");this.setVCMap("A535TBM11_DEL_FLG","TBM11_DEL_FLG",0,"svchar");this.setVCMap("AV36Pgmname","vPGMNAME",0,"char");this.setVCMap("AV5C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV18P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV21W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV12H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV23W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV31C_GRID_ROWS","vC_GRID_ROWS",0,"int");this.setVCMap("A63TBM21_STUDY_ID",
"TBM21_STUDY_ID",0,"int");this.setVCMap("A606TBM11_STUDY_ID","TBM11_STUDY_ID",0,"int");this.setVCMap("A367TBM21_STUDY_NM","TBM21_STUDY_NM",0,"svchar");this.setVCMap("A535TBM11_DEL_FLG","TBM11_DEL_FLG",0,"svchar");c.addRefreshingVar(this.GXValidFnc[195]);c.addRefreshingVar(this.GXValidFnc[197]);c.addRefreshingVar(this.GXValidFnc[198]);c.addRefreshingVar(this.GXValidFnc[194]);c.addRefreshingVar({rfrVar:"AV36Pgmname"});c.addRefreshingVar({rfrVar:"AV5C_APP_ID"});c.addRefreshingVar({rfrVar:"AV18P_MOVE_KBN"});
c.addRefreshingVar(this.GXValidFnc[196]);c.addRefreshingVar({rfrVar:"AV21W_A821_JS"});c.addRefreshingVar({rfrVar:"AV12H_A_PAGING_SDT"});c.addRefreshingVar({rfrVar:"AV23W_ERRFLG"});c.addRefreshingVar(this.GXValidFnc[29]);c.addRefreshingVar(this.GXValidFnc[32]);c.addRefreshingVar({rfrVar:"AV9D_GRD_LINE",rfrProp:"Value",gxAttId:"D_grd_line"});c.addRefreshingVar({rfrVar:"AV31C_GRID_ROWS"});c.addRefreshingVar({rfrVar:"A63TBM21_STUDY_ID"});c.addRefreshingVar({rfrVar:"A606TBM11_STUDY_ID"});c.addRefreshingVar({rfrVar:"A367TBM21_STUDY_NM"});
c.addRefreshingVar({rfrVar:"A535TBM11_DEL_FLG"});this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[199],"AV12H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0188",lvl:1})});gx.setParentObj(new b201_wp01_image_mst_list);
