gx.evt.autoSkip=!1;
gx.define("b202_wp01_image_mst",!1,function(){this.ServerClass="b202_wp01_image_mst";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e11142_client");this.addKeyListener("4","e12142_client");this.addKeyListener("6","e13142_client");this.addKeyListener("11","e14142_client");this.SetStandaloneVars=function(){this.AV14P_IMAGE_CD=gx.fn.getControlValue("vP_IMAGE_CD")};this.s152_client=function(){};this.s182_client=
function(){gx.fn.setCtrlProperty("CTLTBM11_IMAGE_CD","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTBM11_IMAGE_NM","Backcolor",gx.color.rgb(255,255,255));gx.fn.setCtrlProperty("CTLTBM11_STUDY_ID","Backcolor",gx.color.rgb(255,255,255))};this.s192_client=function(){for(this.AV45GXV11=1;this.AV45GXV11<=this.AV15W_A_CHK_RESULT_SDT.length;){this.AV16W_A_CHK_RESULT_SDT_ITEM=this.AV15W_A_CHK_RESULT_SDT[this.AV45GXV11-1];this.s202_client();this.AV45GXV11=this.AV45GXV11+1}};this.s202_client=
function(){if(this.AV16W_A_CHK_RESULT_SDT_ITEM.ID=="TBM11_IMAGE_CD"){gx.fn.setCtrlProperty("CTLTBM11_IMAGE_CD","Backcolor",gx.color.rgb(255,192,203));this.AV16W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM11_IMAGE_CD")}else if(this.AV16W_A_CHK_RESULT_SDT_ITEM.ID=="TBM11_IMAGE_NM"){gx.fn.setCtrlProperty("CTLTBM11_IMAGE_NM","Backcolor",gx.color.rgb(255,192,203));this.AV16W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM11_IMAGE_NM")}else if(this.AV16W_A_CHK_RESULT_SDT_ITEM.ID==
"TBM11_IMAGE")this.AV16W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("vD_IMAGE_UPLOAD");else if(this.AV16W_A_CHK_RESULT_SDT_ITEM.ID=="TBM11_STUDY_ID"){gx.fn.setCtrlProperty("CTLTBM11_STUDY_ID","Backcolor",gx.color.rgb(255,192,203));this.AV16W_A_CHK_RESULT_SDT_ITEM.FOCUS==true&&gx.fn.usrSetFocus("CTLTBM11_STUDY_ID")}};this.e11142_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e17142_client=function(){this.executeServerEvent("'BTN_REG_EXEC'",true)};this.e12142_client=function(){this.executeServerEvent("'BTN_UPD'",
true)};this.e18142_client=function(){this.executeServerEvent("'BTN_UPD_EXEC'",true)};this.e13142_client=function(){this.executeServerEvent("'BTN_DLT'",true)};this.e19142_client=function(){this.executeServerEvent("'BTN_DLT_EXEC'",true)};this.e14142_client=function(){this.executeServerEvent("'BTN_CAN'",true)};this.e21142_client=function(){this.executeServerEvent("ENTER",true)};this.e22142_client=function(){this.executeServerEvent("CANCEL",true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,16,
19,20,23,24,27,28,31,34,40,45,47,48,50,52,55,56,58,59,60,63,64,68,71,77,80,84,87,91,94,95,98,99,100,101,102];this.GXLastCtrlId=102;b[2]={fld:"TABLE2",grid:0};b[6]={fld:"TABLE3",grid:0};b[12]={fld:"TBL_INS_BTNSET",grid:0};b[15]={fld:"TXT_BTN_REG",format:0,grid:0};b[16]={fld:"TXT_BTN_REG2",format:0,grid:0};b[19]={fld:"TEXTBLOCK44",format:0,grid:0};b[20]={fld:"TBL_UPD_BTNSET",grid:0};b[23]={fld:"TXT_BTN_UPD",format:0,grid:0};b[24]={fld:"TXT_BTN_UPD2",format:0,grid:0};b[27]={fld:"TXT_BTN_DLT",format:0,
grid:0};b[28]={fld:"TXT_BTN_DLT2",format:0,grid:0};b[31]={fld:"TEXTBLOCK46",format:0,grid:0};b[34]={fld:"TABLE5",grid:0};b[40]={fld:"TABLE4",grid:0};b[45]={fld:"IMAGE4",grid:0};b[47]={fld:"SECTION2",grid:0};b[48]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_IMAGE_CD",gxz:"ZV33GXV1",gxold:"OV33GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=a},v2z:function(a){gx.O.ZV33GXV1=a},v2c:function(){gx.fn.setControlValue("CTLTBM11_IMAGE_CD",
gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM11_IMAGE_CD")},nac:gx.falseFn};b[50]={fld:"IMAGE5",grid:0};b[52]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_IMAGE_NM",gxz:"ZV34GXV2",gxold:"OV34GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV2=a},v2z:function(a){gx.O.ZV34GXV2=a},v2c:function(){gx.fn.setControlValue("CTLTBM11_IMAGE_NM",gx.O.GXV2,
0)},c2v:function(){gx.O.GXV2=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM11_IMAGE_NM")},nac:gx.falseFn};b[55]={fld:"IMAGE3",grid:0};b[56]={fld:"TXT_SIZE",format:0,grid:0};b[58]={fld:"SECTION3",grid:0};b[59]={fld:"TXT_IMAGE",format:2,grid:0};b[60]={lvl:0,type:"bitstr",len:1024,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_IMAGE_UPLOAD",gxz:"ZV9D_IMAGE_UPLOAD",gxold:"OV9D_IMAGE_UPLOAD",gxvar:"AV9D_IMAGE_UPLOAD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",
v2v:function(a){gx.O.AV9D_IMAGE_UPLOAD=a},v2z:function(a){gx.O.ZV9D_IMAGE_UPLOAD=a},v2c:function(){gx.fn.setBlobValue("vD_IMAGE_UPLOAD",gx.O.AV9D_IMAGE_UPLOAD)},c2v:function(){gx.O.AV9D_IMAGE_UPLOAD=this.val()},val:function(){return gx.fn.getBlobValue("vD_IMAGE_UPLOAD")},nac:gx.falseFn};b[63]={fld:"SECTION1",grid:0};b[64]={fld:"TXT_FILE_NAME",format:1,grid:0};b[68]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_STUDY_ID",
gxz:"ZV35GXV3",gxold:"OV35GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV3=gx.num.intval(a)},v2z:function(a){gx.O.ZV35GXV3=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLTBM11_STUDY_ID",gx.O.GXV3,0)},c2v:function(){gx.O.GXV3=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLTBM11_STUDY_ID",",")},nac:gx.falseFn};b[71]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_DEL_FLG",
gxz:"ZV36GXV4",gxold:"OV36GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"radio",v2v:function(a){gx.O.GXV4=a},v2z:function(a){gx.O.ZV36GXV4=a},v2c:function(){gx.fn.setRadioValue("CTLTBM11_DEL_FLG",gx.O.GXV4)},c2v:function(){gx.O.GXV4=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM11_DEL_FLG")},nac:gx.falseFn};b[77]={lvl:0,type:"dtime",len:10,dec:8,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_CRT_DATETIME",gxz:"ZV37GXV5",gxold:"OV37GXV5",
gxvar:"GXV5",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV5=gx.fn.toDatetimeValue(a,"Y4MD")},v2z:function(a){gx.O.ZV37GXV5=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTBM11_CRT_DATETIME",gx.O.GXV5,0)},c2v:function(){gx.O.GXV5=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getDateTimeValue("CTLTBM11_CRT_DATETIME")},nac:gx.falseFn};b[80]={lvl:0,type:"dtime",len:10,dec:8,
sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_UPD_DATETIME",gxz:"ZV38GXV6",gxold:"OV38GXV6",gxvar:"GXV6",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV6=gx.fn.toDatetimeValue(a,"Y4MD")},v2z:function(a){gx.O.ZV38GXV6=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("CTLTBM11_UPD_DATETIME",gx.O.GXV6,0)},c2v:function(){gx.O.GXV6=gx.fn.toDatetimeValue(this.val())},
val:function(){return gx.fn.getDateTimeValue("CTLTBM11_UPD_DATETIME")},nac:gx.falseFn};b[84]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_CRT_USER_NM",gxz:"ZV8D_CRT_USER_NM",gxold:"OV8D_CRT_USER_NM",gxvar:"AV8D_CRT_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV8D_CRT_USER_NM=a},v2z:function(a){gx.O.ZV8D_CRT_USER_NM=a},v2c:function(){gx.fn.setControlValue("vD_CRT_USER_NM",gx.O.AV8D_CRT_USER_NM,1)},c2v:function(){gx.O.AV8D_CRT_USER_NM=
this.val()},val:function(){return gx.fn.getControlValue("vD_CRT_USER_NM")},nac:gx.falseFn};b[87]={lvl:0,type:"svchar",len:30,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_UPD_USER_NM",gxz:"ZV10D_UPD_USER_NM",gxold:"OV10D_UPD_USER_NM",gxvar:"AV10D_UPD_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10D_UPD_USER_NM=a},v2z:function(a){gx.O.ZV10D_UPD_USER_NM=a},v2c:function(){gx.fn.setControlValue("vD_UPD_USER_NM",gx.O.AV10D_UPD_USER_NM,1)},
c2v:function(){gx.O.AV10D_UPD_USER_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_UPD_USER_NM")},nac:gx.falseFn};b[91]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_CRT_PROG_NM",gxz:"ZV39GXV7",gxold:"OV39GXV7",gxvar:"GXV7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV7=a},v2z:function(a){gx.O.ZV39GXV7=a},v2c:function(){gx.fn.setControlValue("CTLTBM11_CRT_PROG_NM",gx.O.GXV7,0)},c2v:function(){gx.O.GXV7=
this.val()},val:function(){return gx.fn.getControlValue("CTLTBM11_CRT_PROG_NM")},nac:gx.falseFn};b[94]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_UPD_PROG_NM",gxz:"ZV40GXV8",gxold:"OV40GXV8",gxvar:"GXV8",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV8=a},v2z:function(a){gx.O.ZV40GXV8=a},v2c:function(){gx.fn.setControlValue("CTLTBM11_UPD_PROG_NM",gx.O.GXV8,0)},c2v:function(){gx.O.GXV8=this.val()},val:function(){return gx.fn.getControlValue("CTLTBM11_UPD_PROG_NM")},
nac:gx.falseFn};b[95]={fld:"TBL_HIDDEN",grid:0};b[98]={fld:"TXT_JS_EVENT",format:1,grid:0};b[99]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV11H_INIT_FLG",gxold:"OV11H_INIT_FLG",gxvar:"AV11H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11H_INIT_FLG=a},v2z:function(a){gx.O.ZV11H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV11H_INIT_FLG,0);typeof this.dom_hdl=="function"&&
this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV11H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(99,function(){});b[100]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_MODE",gxz:"ZV13H_MODE",gxold:"OV13H_MODE",gxvar:"AV13H_MODE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_MODE=a},v2z:function(a){gx.O.ZV13H_MODE=a},v2c:function(){gx.fn.setControlValue("vH_MODE",
gx.O.AV13H_MODE,0)},c2v:function(){gx.O.AV13H_MODE=this.val()},val:function(){return gx.fn.getControlValue("vH_MODE")},nac:gx.falseFn};b[101]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV12H_KNGN_FLG",gxold:"OV12H_KNGN_FLG",gxvar:"AV12H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12H_KNGN_FLG=a},v2z:function(a){gx.O.ZV12H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV12H_KNGN_FLG,
0)},c2v:function(){gx.O.AV12H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[102]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM11_FILE_NAME",gxz:"ZV41GXV9",gxold:"OV41GXV9",gxvar:"GXV9",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV9=a},v2z:function(a){gx.O.ZV41GXV9=a},v2c:function(){gx.fn.setControlValue("CTLTBM11_FILE_NAME",gx.O.GXV9,0)},c2v:function(){gx.O.GXV9=
this.val()},val:function(){return gx.fn.getControlValue("CTLTBM11_FILE_NAME")},nac:gx.falseFn};this.OV9D_IMAGE_UPLOAD=this.ZV9D_IMAGE_UPLOAD=this.AV9D_IMAGE_UPLOAD=this.OV34GXV2=this.ZV34GXV2=this.GXV2=this.OV33GXV1=this.ZV33GXV1=this.GXV1="";this.OV35GXV3=this.ZV35GXV3=this.GXV3=0;this.OV36GXV4=this.ZV36GXV4=this.GXV4="";this.GXV5=gx.date.nullDate();this.ZV37GXV5=gx.date.nullDate();this.OV37GXV5=gx.date.nullDate();this.GXV6=gx.date.nullDate();this.ZV38GXV6=gx.date.nullDate();this.OV38GXV6=gx.date.nullDate();
this.AV9D_IMAGE_UPLOAD=this.GXV2=this.GXV1=this.OV41GXV9=this.ZV41GXV9=this.GXV9=this.OV12H_KNGN_FLG=this.ZV12H_KNGN_FLG=this.AV12H_KNGN_FLG=this.OV13H_MODE=this.ZV13H_MODE=this.AV13H_MODE=this.OV11H_INIT_FLG=this.ZV11H_INIT_FLG=this.AV11H_INIT_FLG=this.OV40GXV8=this.ZV40GXV8=this.GXV8=this.OV39GXV7=this.ZV39GXV7=this.GXV7=this.OV10D_UPD_USER_NM=this.ZV10D_UPD_USER_NM=this.AV10D_UPD_USER_NM=this.OV8D_CRT_USER_NM=this.ZV8D_CRT_USER_NM=this.AV8D_CRT_USER_NM="";this.GXV3=0;this.GXV4="";this.GXV5=gx.date.nullDate();
this.GXV6=gx.date.nullDate();this.A205TAM07_USER_NM=this.A55TAM07_USER_ID=this.AV14P_IMAGE_CD=this.GXV9=this.AV12H_KNGN_FLG=this.AV13H_MODE=this.AV11H_INIT_FLG=this.GXV8=this.GXV7=this.AV10D_UPD_USER_NM=this.AV8D_CRT_USER_NM="";this.AV16W_A_CHK_RESULT_SDT_ITEM={};this.AV15W_A_CHK_RESULT_SDT=[];this.AV45GXV11=0;this.Events={e11142_client:["'BTN_REG'",true],e17142_client:["'BTN_REG_EXEC'",true],e12142_client:["'BTN_UPD'",true],e18142_client:["'BTN_UPD_EXEC'",true],e13142_client:["'BTN_DLT'",true],e19142_client:["'BTN_DLT_EXEC'",
true],e14142_client:["'BTN_CAN'",true],e21142_client:["ENTER",true],e22142_client:["CANCEL",true]};this.setVCMap("AV14P_IMAGE_CD","vP_IMAGE_CD",0,"svchar");this.addBCProperty("Bc_image",["TBM11_IMAGE_CD"],this.GXValidFnc[48],"AV5BC_IMAGE");this.addBCProperty("Bc_image",["TBM11_IMAGE_NM"],this.GXValidFnc[52],"AV5BC_IMAGE");this.addBCProperty("Bc_image",["TBM11_STUDY_ID"],this.GXValidFnc[68],"AV5BC_IMAGE");this.addBCProperty("Bc_image",["TBM11_DEL_FLG"],this.GXValidFnc[71],"AV5BC_IMAGE");this.addBCProperty("Bc_image",
["TBM11_CRT_DATETIME"],this.GXValidFnc[77],"AV5BC_IMAGE");this.addBCProperty("Bc_image",["TBM11_UPD_DATETIME"],this.GXValidFnc[80],"AV5BC_IMAGE");this.addBCProperty("Bc_image",["TBM11_CRT_PROG_NM"],this.GXValidFnc[91],"AV5BC_IMAGE");this.addBCProperty("Bc_image",["TBM11_UPD_PROG_NM"],this.GXValidFnc[94],"AV5BC_IMAGE");this.addBCProperty("Bc_image",["TBM11_FILE_NAME"],this.GXValidFnc[102],"AV5BC_IMAGE");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});
this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0105",lvl:1})});gx.setParentObj(new b202_wp01_image_mst);
