gx.evt.autoSkip=!1;
gx.define("b402_wp05_study_staff_reg",!1,function(){this.ServerClass="b402_wp05_study_staff_reg";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e11172_client");this.addKeyListener("11","e12172_client");this.SetStandaloneVars=function(){this.AV5C_APP_ID=gx.fn.getControlValue("vC_APP_ID");this.AV35Pgmname=gx.fn.getControlValue("vPGMNAME");this.A63TBM21_STUDY_ID=gx.fn.getIntegerValue("TBM21_STUDY_ID",",");
this.AV16P_STUDY_ID=gx.fn.getIntegerValue("vP_STUDY_ID",",");this.A367TBM21_STUDY_NM=gx.fn.getControlValue("TBM21_STUDY_NM");this.A57TAM08_SITE_ID=gx.fn.getControlValue("TAM08_SITE_ID");this.AV15P_SITE_ID=gx.fn.getControlValue("vP_SITE_ID");this.A319TAM08_SITE_NM=gx.fn.getControlValue("TAM08_SITE_NM");this.AV14P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV9H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.AV24W_GRID_READ_FLG=gx.fn.getControlValue("vW_GRID_READ_FLG");this.AV19W_A821_JS=
gx.fn.getControlValue("vW_A821_JS");this.AV23W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG");this.A685TBW01_FREE_SAVE_1=gx.fn.getControlValue("TBW01_FREE_SAVE_1")};this.s132_client=function(){this.AV9H_A_PAGING_SDT.PAGE_NO=1;this.AV13H_SRCH_FLG="0";this.AV18W_A819_JS=""};this.s172_client=function(){};this.s192_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");if(""!=
this.AV19W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV19W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.e11172_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e13172_client=
function(){this.executeServerEvent("'BTN_REG_EXEC'",true)};this.e12172_client=function(){this.executeServerEvent("'BTN_CAN'",true)};this.e31172_client=function(a){this.executeServerEvent("'BTN_AUTH'",true,a)};this.e14172_client=function(){this.executeServerEvent("'PAGE_FIRST'",true)};this.e15172_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};this.e16172_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e17172_client=function(){this.executeServerEvent("'PAGE_NEXT'",
true)};this.e18172_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e19172_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e20172_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e21172_client=function(){this.executeServerEvent("'PAGE04'",true)};this.e22172_client=function(){this.executeServerEvent("'PAGE05'",true)};this.e23172_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e24172_client=function(){this.executeServerEvent("'PAGE07'",
true)};this.e25172_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e26172_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e27172_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e32172_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e33172_client=function(a){this.executeServerEvent("CANCEL",true,a)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,17,20,23,26,29,31,32,34,36,37,43,46,49,52,55,58,61,64,67,70,73,76,79,82,85,88,91,94,
97,100,103,106,109,112,115,118,121,124,127,130,133,136,142,145,147,149,156,159,160,162,163,165,167,172,175,176,177,178,179,180,185,186];this.GXLastCtrlId=186;var b=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",153,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"b402_wp05_study_staff_reg",[],true,1,true,true,10,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,true,null,null,false,"",false,[1,1,1,1]);b.startRow("","","","","","");b.startCell("","","","","","",
"","","","");b.startTable("Tbl_grid",156,"0px");b.addHtmlCode("<tbody>");b.startRow("","","","","","");b.startCell("","center","","","","","45px","","","");b.addCheckBox("D_grd_check",159,"vD_GRD_CHECK","","","D_GRD_CHECK","boolean","true","false",null,true,false,4,"chr","");b.addSingleLineEdit(54,160,"TBW01_LINE_NO","","","TBW01_LINE_NO","int",10,"chr",10,10,"right",null,[],54,"TBW01_LINE_NO",true,0,false,false,"Attribute",1,"");b.endCell();b.startCell("","","","","","","120px","","","");b.startDiv("Section3",
"0px","115px");b.addSingleLineEdit("D_grd_user_id",163,"vD_GRD_USER_ID","","","D_GRD_USER_ID","svchar",80,"chr",128,80,"left",null,[],"D_grd_user_id","D_GRD_USER_ID",true,0,false,false,"Attribute",1,"");b.endDiv();b.endCell();b.startCell("","","","","","","250px","","","");b.addSingleLineEdit("D_grd_user_nm",165,"vD_GRD_USER_NM","","","D_GRD_USER_NM","svchar",30,"chr",30,30,"left",null,[],"D_grd_user_nm","D_GRD_USER_NM",true,0,false,false,"ReadonlyAttribute",1,"");b.endCell();b.startCell("","center",
"","","","","70px","","","");b.addTextBlock("TXT_BTN_AUTH","e31172_client");b.endCell();b.endRow();b.addHtmlCode("</tbody>");b.endTable();b.endCell();b.endRow();this.setGrid(b);a[2]={fld:"TABLE1",grid:0};a[6]={fld:"TABLE2",grid:0};a[12]={fld:"TBL_UPD_BTNSET",grid:0};a[15]={fld:"TXT_BTN_REG",format:0,grid:0};a[17]={fld:"TEXTBLOCK46",format:0,grid:0};a[20]={fld:"TABLE3",grid:0};a[23]={fld:"TABLE4",grid:0};a[26]={fld:"TABLE10",grid:0};a[29]={fld:"TEXTBLOCK16",format:0,grid:0};a[31]={fld:"SECTION1",grid:0};
a[32]={fld:"TXT_STUDY",format:0,grid:0};a[34]={fld:"TEXTBLOCK34",format:0,grid:0};a[36]={fld:"SECTION2",grid:0};a[37]={fld:"TXT_SITE",format:0,grid:0};a[43]={fld:"TBL_LIST",grid:0};a[46]={fld:"TBL_PAGE_AREA",grid:0};a[49]={fld:"TXT_REC_CNT",format:0,grid:0};a[52]={fld:"TBL_PAGE",grid:0};a[55]={fld:"TBL_FIRST",grid:0};a[58]={fld:"TXT_FIRST",format:0,grid:0};a[61]={fld:"TBL_BACK",grid:0};a[64]={fld:"TXT_BACK",format:0,grid:0};a[67]={fld:"TBL_PAGE01",grid:0};a[70]={fld:"TXT_PAGE01",format:0,grid:0};
a[73]={fld:"TBL_PAGE02",grid:0};a[76]={fld:"TXT_PAGE02",format:0,grid:0};a[79]={fld:"TBL_PAGE03",grid:0};a[82]={fld:"TXT_PAGE03",format:0,grid:0};a[85]={fld:"TBL_PAGE04",grid:0};a[88]={fld:"TXT_PAGE04",format:0,grid:0};a[91]={fld:"TBL_PAGE05",grid:0};a[94]={fld:"TXT_PAGE05",format:0,grid:0};a[97]={fld:"TBL_PAGE06",grid:0};a[100]={fld:"TXT_PAGE06",format:0,grid:0};a[103]={fld:"TBL_PAGE07",grid:0};a[106]={fld:"TXT_PAGE07",format:0,grid:0};a[109]={fld:"TBL_PAGE08",grid:0};a[112]={fld:"TXT_PAGE08",format:0,
grid:0};a[115]={fld:"TBL_PAGE09",grid:0};a[118]={fld:"TXT_PAGE09",format:0,grid:0};a[121]={fld:"TBL_PAGE10",grid:0};a[124]={fld:"TXT_PAGE10",format:0,grid:0};a[127]={fld:"TBL_NEXT",grid:0};a[130]={fld:"TXT_NEXT",format:0,grid:0};a[133]={fld:"TBL_LAST",grid:0};a[136]={fld:"TXT_LAST",format:0,grid:0};a[142]={fld:"TBL_GRID_HEADER",grid:0};a[145]={fld:"TEXTBLOCK18",format:0,grid:0};a[147]={fld:"TEXTBLOCK35",format:0,grid:0};a[149]={fld:"TEXTBLOCK33",format:0,grid:0};a[156]={fld:"TBL_GRID",grid:153};a[159]=
{lvl:2,type:"boolean",len:4,dec:0,sign:false,ro:0,isacc:0,grid:153,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_CHECK",gxz:"ZV7D_GRD_CHECK",gxold:"OV7D_GRD_CHECK",gxvar:"AV7D_GRD_CHECK",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",inputType:"text",v2v:function(a){gx.O.AV7D_GRD_CHECK=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV7D_GRD_CHECK=gx.lang.booleanValue(a)},v2c:function(a){gx.fn.setGridCheckBoxValue("vD_GRD_CHECK",a||gx.fn.currentGridRowImpl(153),gx.O.AV7D_GRD_CHECK,
true)},c2v:function(){gx.O.AV7D_GRD_CHECK=gx.lang.booleanValue(this.val())},val:function(a){return gx.fn.getGridCheckBoxValue("vD_GRD_CHECK",a||gx.fn.currentGridRowImpl(153),true,false)},nac:gx.falseFn};a[160]={lvl:2,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:1,isacc:0,grid:153,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBW01_LINE_NO",gxz:"Z54TBW01_LINE_NO",gxold:"O54TBW01_LINE_NO",gxvar:"A54TBW01_LINE_NO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",
v2v:function(a){gx.O.A54TBW01_LINE_NO=gx.num.intval(a)},v2z:function(a){gx.O.Z54TBW01_LINE_NO=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TBW01_LINE_NO",a||gx.fn.currentGridRowImpl(153),gx.O.A54TBW01_LINE_NO,0)},c2v:function(){gx.O.A54TBW01_LINE_NO=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TBW01_LINE_NO",a||gx.fn.currentGridRowImpl(153),",")},nac:gx.falseFn};a[162]={fld:"SECTION3",grid:153};a[163]={lvl:2,type:"svchar",len:128,dec:0,sign:false,ro:0,
isacc:0,grid:153,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_USER_ID",gxz:"ZV30D_GRD_USER_ID",gxold:"OV30D_GRD_USER_ID",gxvar:"AV30D_GRD_USER_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV30D_GRD_USER_ID=a},v2z:function(a){gx.O.ZV30D_GRD_USER_ID=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_USER_ID",a||gx.fn.currentGridRowImpl(153),gx.O.AV30D_GRD_USER_ID,0)},c2v:function(){gx.O.AV30D_GRD_USER_ID=this.val()},
val:function(a){return gx.fn.getGridControlValue("vD_GRD_USER_ID",a||gx.fn.currentGridRowImpl(153))},nac:gx.falseFn};a[165]={lvl:2,type:"svchar",len:30,dec:0,sign:false,ro:0,isacc:0,grid:153,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_USER_NM",gxz:"ZV8D_GRD_USER_NM",gxold:"OV8D_GRD_USER_NM",gxvar:"AV8D_GRD_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV8D_GRD_USER_NM=a},v2z:function(a){gx.O.ZV8D_GRD_USER_NM=a},
v2c:function(a){gx.fn.setGridControlValue("vD_GRD_USER_NM",a||gx.fn.currentGridRowImpl(153),gx.O.AV8D_GRD_USER_NM,0)},c2v:function(){gx.O.AV8D_GRD_USER_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_USER_NM",a||gx.fn.currentGridRowImpl(153))},nac:gx.falseFn};a[167]={fld:"TXT_BTN_AUTH",format:0,grid:153};a[172]={fld:"TBL_HIDDEN",grid:0};a[175]={fld:"TXT_JS_EVENT",format:1,grid:0};a[176]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,
rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV11H_INIT_FLG",gxold:"OV11H_INIT_FLG",gxvar:"AV11H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11H_INIT_FLG=a},v2z:function(a){gx.O.ZV11H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV11H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV11H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(176,function(){});
a[177]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SRCH_FLG",gxz:"ZV13H_SRCH_FLG",gxold:"OV13H_SRCH_FLG",gxvar:"AV13H_SRCH_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_SRCH_FLG=a},v2z:function(a){gx.O.ZV13H_SRCH_FLG=a},v2c:function(){gx.fn.setControlValue("vH_SRCH_FLG",gx.O.AV13H_SRCH_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV13H_SRCH_FLG=this.val()},
val:function(){return gx.fn.getControlValue("vH_SRCH_FLG")},nac:gx.falseFn};this.declareDomainHdlr(177,function(){});a[178]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV12H_KNGN_FLG",gxold:"OV12H_KNGN_FLG",gxvar:"AV12H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12H_KNGN_FLG=a},v2z:function(a){gx.O.ZV12H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV12H_KNGN_FLG,
0)},c2v:function(){gx.O.AV12H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};a[179]={fld:"TXT_BTN_REG_EXEC",format:1,grid:0};a[180]={fld:"TABLE5",grid:0};a[185]={lvl:0,type:"svchar",len:14,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_DISP_DATETIME",gxz:"ZV10H_DISP_DATETIME",gxold:"OV10H_DISP_DATETIME",gxvar:"AV10H_DISP_DATETIME",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10H_DISP_DATETIME=
a},v2z:function(a){gx.O.ZV10H_DISP_DATETIME=a},v2c:function(){gx.fn.setControlValue("vH_DISP_DATETIME",gx.O.AV10H_DISP_DATETIME,0)},c2v:function(){gx.O.AV10H_DISP_DATETIME=this.val()},val:function(){return gx.fn.getControlValue("vH_DISP_DATETIME")},nac:gx.falseFn};a[186]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLREC_CNT",gxz:"ZV33GXV1",gxold:"OV33GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=
gx.num.intval(a)},v2z:function(a){gx.O.ZV33GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",",")},nac:gx.falseFn};this.OV7D_GRD_CHECK=this.ZV7D_GRD_CHECK=false;this.O54TBW01_LINE_NO=this.Z54TBW01_LINE_NO=0;this.OV10H_DISP_DATETIME=this.ZV10H_DISP_DATETIME=this.AV10H_DISP_DATETIME=this.OV12H_KNGN_FLG=this.ZV12H_KNGN_FLG=this.AV12H_KNGN_FLG=this.OV13H_SRCH_FLG=
this.ZV13H_SRCH_FLG=this.AV13H_SRCH_FLG=this.OV11H_INIT_FLG=this.ZV11H_INIT_FLG=this.AV11H_INIT_FLG=this.OV8D_GRD_USER_NM=this.ZV8D_GRD_USER_NM=this.OV30D_GRD_USER_ID=this.ZV30D_GRD_USER_ID="";this.OV33GXV1=this.ZV33GXV1=this.GXV1=0;this.AV10H_DISP_DATETIME=this.AV12H_KNGN_FLG=this.AV13H_SRCH_FLG=this.AV11H_INIT_FLG="";this.AV16P_STUDY_ID=this.AV14P_MOVE_KBN=this.GXV1=0;this.A51TBW01_SESSION_ID=this.A52TBW01_APP_ID=this.A53TBW01_DISP_DATETIME=this.A685TBW01_FREE_SAVE_1=this.AV15P_SITE_ID="";this.AV7D_GRD_CHECK=
false;this.A54TBW01_LINE_NO=0;this.A319TAM08_SITE_NM=this.A57TAM08_SITE_ID=this.AV8D_GRD_USER_NM=this.AV30D_GRD_USER_ID="";this.A63TBM21_STUDY_ID=0;this.AV35Pgmname=this.AV5C_APP_ID=this.A367TBM21_STUDY_NM="";this.AV9H_A_PAGING_SDT={};this.AV24W_GRID_READ_FLG=false;this.AV19W_A821_JS="";this.AV23W_ERRFLG=false;this.AV18W_A819_JS="";this.Events={e11172_client:["'BTN_REG'",true],e13172_client:["'BTN_REG_EXEC'",true],e12172_client:["'BTN_CAN'",true],e31172_client:["'BTN_AUTH'",true],e14172_client:["'PAGE_FIRST'",
true],e15172_client:["'PAGE_LAST'",true],e16172_client:["'PAGE_BACK'",true],e17172_client:["'PAGE_NEXT'",true],e18172_client:["'PAGE01'",true],e19172_client:["'PAGE02'",true],e20172_client:["'PAGE03'",true],e21172_client:["'PAGE04'",true],e22172_client:["'PAGE05'",true],e23172_client:["'PAGE06'",true],e24172_client:["'PAGE07'",true],e25172_client:["'PAGE08'",true],e26172_client:["'PAGE09'",true],e27172_client:["'PAGE10'",true],e32172_client:["ENTER",true],e33172_client:["CANCEL",true]};this.setVCMap("AV5C_APP_ID",
"vC_APP_ID",0,"svchar");this.setVCMap("AV35Pgmname","vPGMNAME",0,"char");this.setVCMap("A63TBM21_STUDY_ID","TBM21_STUDY_ID",0,"int");this.setVCMap("AV16P_STUDY_ID","vP_STUDY_ID",0,"int");this.setVCMap("A367TBM21_STUDY_NM","TBM21_STUDY_NM",0,"svchar");this.setVCMap("A57TAM08_SITE_ID","TAM08_SITE_ID",0,"svchar");this.setVCMap("AV15P_SITE_ID","vP_SITE_ID",0,"svchar");this.setVCMap("A319TAM08_SITE_NM","TAM08_SITE_NM",0,"svchar");this.setVCMap("AV14P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV9H_A_PAGING_SDT",
"vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV24W_GRID_READ_FLG","vW_GRID_READ_FLG",0,"boolean");this.setVCMap("AV19W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV23W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("A685TBW01_FREE_SAVE_1","TBW01_FREE_SAVE_1",0,"vchar");this.setVCMap("AV5C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV35Pgmname","vPGMNAME",0,"char");this.setVCMap("A63TBM21_STUDY_ID","TBM21_STUDY_ID",0,"int");this.setVCMap("AV16P_STUDY_ID","vP_STUDY_ID",0,"int");this.setVCMap("A367TBM21_STUDY_NM",
"TBM21_STUDY_NM",0,"svchar");this.setVCMap("A57TAM08_SITE_ID","TAM08_SITE_ID",0,"svchar");this.setVCMap("AV15P_SITE_ID","vP_SITE_ID",0,"svchar");this.setVCMap("A319TAM08_SITE_NM","TAM08_SITE_NM",0,"svchar");this.setVCMap("AV14P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV9H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV24W_GRID_READ_FLG","vW_GRID_READ_FLG",0,"boolean");this.setVCMap("AV19W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV23W_ERRFLG","vW_ERRFLG",0,"boolean");
this.setVCMap("A685TBW01_FREE_SAVE_1","TBW01_FREE_SAVE_1",0,"vchar");b.addRefreshingVar(this.GXValidFnc[177]);b.addRefreshingVar(this.GXValidFnc[185]);b.addRefreshingVar({rfrVar:"AV5C_APP_ID"});b.addRefreshingVar(this.GXValidFnc[176]);b.addRefreshingVar({rfrVar:"AV35Pgmname"});b.addRefreshingVar({rfrVar:"A63TBM21_STUDY_ID"});b.addRefreshingVar({rfrVar:"AV16P_STUDY_ID"});b.addRefreshingVar({rfrVar:"A367TBM21_STUDY_NM"});b.addRefreshingVar({rfrVar:"A57TAM08_SITE_ID"});b.addRefreshingVar({rfrVar:"AV15P_SITE_ID"});
b.addRefreshingVar({rfrVar:"A319TAM08_SITE_NM"});b.addRefreshingVar({rfrVar:"AV14P_MOVE_KBN"});b.addRefreshingVar({rfrVar:"AV9H_A_PAGING_SDT"});b.addRefreshingVar({rfrVar:"AV24W_GRID_READ_FLG"});b.addRefreshingVar({rfrVar:"AV7D_GRD_CHECK",rfrProp:"Value",gxAttId:"D_grd_check"});b.addRefreshingVar({rfrVar:"A54TBW01_LINE_NO",rfrProp:"Value",gxAttId:"54"});b.addRefreshingVar(this.GXValidFnc[178]);b.addRefreshingVar({rfrVar:"AV19W_A821_JS"});b.addRefreshingVar({rfrVar:"AV23W_ERRFLG"});b.addRefreshingVar({rfrVar:"A685TBW01_FREE_SAVE_1"});
this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[186],"AV9H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0170",lvl:1})});gx.setParentObj(new b402_wp05_study_staff_reg);
