gx.evt.autoSkip=!1;
gx.define("b402_wp04_study_staff_list",!1,function(){this.ServerClass="b402_wp04_study_staff_list";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e110y2_client");this.addKeyListener("5","e120y2_client");this.addKeyListener("6","e130y2_client");this.addKeyListener("11","e140y2_client");this.SetStandaloneVars=function(){this.AV5C_APP_ID=gx.fn.getControlValue("vC_APP_ID");this.AV35Pgmname=gx.fn.getControlValue("vPGMNAME");
this.A63TBM21_STUDY_ID=gx.fn.getIntegerValue("TBM21_STUDY_ID",",");this.AV18P_STUDY_ID=gx.fn.getIntegerValue("vP_STUDY_ID",",");this.A367TBM21_STUDY_NM=gx.fn.getControlValue("TBM21_STUDY_NM");this.AV17P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV11H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.A17TBM22_STUDY_ID=gx.fn.getIntegerValue("TBM22_STUDY_ID",",");this.A18TBM22_SITE_ID=gx.fn.getControlValue("TBM22_SITE_ID");this.A377TBM22_DEL_FLG=gx.fn.getControlValue("TBM22_DEL_FLG");
this.A325TAM08_DEL_FLG=gx.fn.getControlValue("TAM08_DEL_FLG");this.A319TAM08_SITE_NM=gx.fn.getControlValue("TAM08_SITE_NM");this.AV25W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG");this.A685TBW01_FREE_SAVE_1=gx.fn.getControlValue("TBW01_FREE_SAVE_1")};this.s122_client=function(){this.AV15H_SITE_ID=this.AV10D_SITE_ID="";this.AV11H_A_PAGING_SDT.PAGE_NO=1;this.AV16H_SRCH_FLG="0";this.AV20W_A819_JS=""};this.s202_client=function(){this.AV15H_SITE_ID=this.AV10D_SITE_ID};this.s172_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.e110y2_client=function(){this.executeServerEvent("'BTN_REG'",
true)};this.e120y2_client=function(){this.executeServerEvent("'BTN_SRCH'",true)};this.e130y2_client=function(){this.executeServerEvent("'BTN_CLER'",true)};this.e140y2_client=function(){this.executeServerEvent("'BTN_CAN'",true)};this.e150y2_client=function(){this.executeServerEvent("'PAGE_FIRST'",true)};this.e160y2_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};this.e170y2_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e180y2_client=function(){this.executeServerEvent("'PAGE_NEXT'",
true)};this.e190y2_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e200y2_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e210y2_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e220y2_client=function(){this.executeServerEvent("'PAGE04'",true)};this.e230y2_client=function(){this.executeServerEvent("'PAGE05'",true)};this.e240y2_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e250y2_client=function(){this.executeServerEvent("'PAGE07'",
true)};this.e260y2_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e270y2_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e280y2_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e320y2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e330y2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,17,20,23,26,29,31,32,34,36,39,42,45,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,96,
99,102,105,108,111,114,117,120,123,126,129,132,135,138,141,144,150,153,155,157,159,165,168,169,170,172,173,175,177,178,183,186,187,188,189,190,191,192];this.GXLastCtrlId=192;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",162,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"b402_wp04_study_staff_list",[],true,1,true,true,10,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,"",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("",
"","","","","","","","","");c.startTable("Tbl_grid_header2",165,"0px");c.addHtmlCode("<tbody>");c.startRow("","","","","","");c.startCell("","","","","","25px","200px","","","");c.startDiv("Section2","0px","195px");c.addSingleLineEdit("D_grd_site_nm",169,"vD_GRD_SITE_NM","","","D_GRD_SITE_NM","svchar",50,"chr",50,50,"left",null,[],"D_grd_site_nm","D_GRD_SITE_NM",true,0,false,false,"ReadonlyAttribute",1,"");c.endDiv();c.addSingleLineEdit(54,170,"TBW01_LINE_NO","","","TBW01_LINE_NO","int",10,"chr",
10,10,"right",null,[],54,"TBW01_LINE_NO",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","","","","","","120px","","","");c.startDiv("Section3","0px","115px");c.addSingleLineEdit("D_grd_user_id",173,"vD_GRD_USER_ID","","","D_GRD_USER_ID","svchar",80,"chr",128,80,"left",null,[],"D_grd_user_id","D_GRD_USER_ID",true,0,false,false,"Attribute",1,"");c.endDiv();c.endCell();c.startCell("","","","","","","250px","","","");c.addSingleLineEdit("D_grd_user_nm",175,"vD_GRD_USER_NM","","","D_GRD_USER_NM",
"svchar",30,"chr",30,30,"left",null,[],"D_grd_user_nm","D_GRD_USER_NM",true,0,false,false,"Attribute",1,"");c.endCell();c.startCell("","","","","","","230px","","","");c.startDiv("Section4","0px","225px");c.addSingleLineEdit("D_grd_auth_nm",178,"vD_GRD_AUTH_NM","","","D_GRD_AUTH_NM","svchar",40,"chr",40,40,"left",null,[],"D_grd_auth_nm","D_GRD_AUTH_NM",true,0,false,false,"Attribute",1,"");c.endDiv();c.endCell();c.endRow();c.addHtmlCode("</tbody>");c.endTable();c.endCell();c.endRow();this.setGrid(c);
b[2]={fld:"TABLE1",grid:0};b[6]={fld:"TABLE2",grid:0};b[12]={fld:"TBL_UPD_BTNSET",grid:0};b[15]={fld:"TXT_BTN_REG",format:0,grid:0};b[17]={fld:"TXT_BTN_CAN",format:0,grid:0};b[20]={fld:"TABLE3",grid:0};b[23]={fld:"TABLE4",grid:0};b[26]={fld:"TABLE10",grid:0};b[29]={fld:"TEXTBLOCK16",format:0,grid:0};b[31]={fld:"SECTION1",grid:0};b[32]={fld:"TXT_STUDY",format:0,grid:0};b[34]={fld:"TEXTBLOCK18",format:0,grid:0};b[36]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,
rgrid:[],fld:"vD_SITE_ID",gxz:"ZV10D_SITE_ID",gxold:"OV10D_SITE_ID",gxvar:"AV10D_SITE_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV10D_SITE_ID=a},v2z:function(a){gx.O.ZV10D_SITE_ID=a},v2c:function(){gx.fn.setComboBoxValue("vD_SITE_ID",gx.O.AV10D_SITE_ID);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV10D_SITE_ID=this.val()},val:function(){return gx.fn.getControlValue("vD_SITE_ID")},nac:gx.falseFn};this.declareDomainHdlr(36,function(){});
b[39]={fld:"TABLE9",grid:0};b[42]={fld:"TEXTBLOCK45",format:0,grid:0};b[45]={fld:"TEXTBLOCK44",format:0,grid:0};b[51]={fld:"TBL_LIST",grid:0};b[54]={fld:"TBL_PAGE_AREA",grid:0};b[57]={fld:"TXT_REC_CNT",format:0,grid:0};b[60]={fld:"TBL_PAGE",grid:0};b[63]={fld:"TBL_FIRST",grid:0};b[66]={fld:"TXT_FIRST",format:0,grid:0};b[69]={fld:"TBL_BACK",grid:0};b[72]={fld:"TXT_BACK",format:0,grid:0};b[75]={fld:"TBL_PAGE01",grid:0};b[78]={fld:"TXT_PAGE01",format:0,grid:0};b[81]={fld:"TBL_PAGE02",grid:0};b[84]={fld:"TXT_PAGE02",
format:0,grid:0};b[87]={fld:"TBL_PAGE03",grid:0};b[90]={fld:"TXT_PAGE03",format:0,grid:0};b[93]={fld:"TBL_PAGE04",grid:0};b[96]={fld:"TXT_PAGE04",format:0,grid:0};b[99]={fld:"TBL_PAGE05",grid:0};b[102]={fld:"TXT_PAGE05",format:0,grid:0};b[105]={fld:"TBL_PAGE06",grid:0};b[108]={fld:"TXT_PAGE06",format:0,grid:0};b[111]={fld:"TBL_PAGE07",grid:0};b[114]={fld:"TXT_PAGE07",format:0,grid:0};b[117]={fld:"TBL_PAGE08",grid:0};b[120]={fld:"TXT_PAGE08",format:0,grid:0};b[123]={fld:"TBL_PAGE09",grid:0};b[126]=
{fld:"TXT_PAGE09",format:0,grid:0};b[129]={fld:"TBL_PAGE10",grid:0};b[132]={fld:"TXT_PAGE10",format:0,grid:0};b[135]={fld:"TBL_NEXT",grid:0};b[138]={fld:"TXT_NEXT",format:0,grid:0};b[141]={fld:"TBL_LAST",grid:0};b[144]={fld:"TXT_LAST",format:0,grid:0};b[150]={fld:"TBL_IN_GRID_HEADER",grid:0};b[153]={fld:"TEXTBLOCK33",format:0,grid:0};b[155]={fld:"TEXTBLOCK41",format:0,grid:0};b[157]={fld:"TEXTBLOCK42",format:0,grid:0};b[159]={fld:"TEXTBLOCK13",format:0,grid:0};b[165]={fld:"TBL_GRID_HEADER2",grid:162};
b[168]={fld:"SECTION2",grid:162};b[169]={lvl:2,type:"svchar",len:50,dec:0,sign:false,ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_SITE_NM",gxz:"ZV8D_GRD_SITE_NM",gxold:"OV8D_GRD_SITE_NM",gxvar:"AV8D_GRD_SITE_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV8D_GRD_SITE_NM=a},v2z:function(a){gx.O.ZV8D_GRD_SITE_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_SITE_NM",a||gx.fn.currentGridRowImpl(162),
gx.O.AV8D_GRD_SITE_NM,0)},c2v:function(){gx.O.AV8D_GRD_SITE_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_SITE_NM",a||gx.fn.currentGridRowImpl(162))},nac:gx.falseFn};b[170]={lvl:2,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBW01_LINE_NO",gxz:"Z54TBW01_LINE_NO",gxold:"O54TBW01_LINE_NO",gxvar:"A54TBW01_LINE_NO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A54TBW01_LINE_NO=
gx.num.intval(a)},v2z:function(a){gx.O.Z54TBW01_LINE_NO=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TBW01_LINE_NO",a||gx.fn.currentGridRowImpl(162),gx.O.A54TBW01_LINE_NO,0)},c2v:function(){gx.O.A54TBW01_LINE_NO=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TBW01_LINE_NO",a||gx.fn.currentGridRowImpl(162),",")},nac:gx.falseFn};b[172]={fld:"SECTION3",grid:162};b[173]={lvl:2,type:"svchar",len:128,dec:0,sign:false,ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,
fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_USER_ID",gxz:"ZV30D_GRD_USER_ID",gxold:"OV30D_GRD_USER_ID",gxvar:"AV30D_GRD_USER_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV30D_GRD_USER_ID=a},v2z:function(a){gx.O.ZV30D_GRD_USER_ID=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_USER_ID",a||gx.fn.currentGridRowImpl(162),gx.O.AV30D_GRD_USER_ID,0)},c2v:function(){gx.O.AV30D_GRD_USER_ID=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_USER_ID",
a||gx.fn.currentGridRowImpl(162))},nac:gx.falseFn};b[175]={lvl:2,type:"svchar",len:30,dec:0,sign:false,ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_USER_NM",gxz:"ZV9D_GRD_USER_NM",gxold:"OV9D_GRD_USER_NM",gxvar:"AV9D_GRD_USER_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV9D_GRD_USER_NM=a},v2z:function(a){gx.O.ZV9D_GRD_USER_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_USER_NM",a||gx.fn.currentGridRowImpl(162),
gx.O.AV9D_GRD_USER_NM,0)},c2v:function(){gx.O.AV9D_GRD_USER_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_USER_NM",a||gx.fn.currentGridRowImpl(162))},nac:gx.falseFn};b[177]={fld:"SECTION4",grid:162};b[178]={lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:162,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_AUTH_NM",gxz:"ZV7D_GRD_AUTH_NM",gxold:"OV7D_GRD_AUTH_NM",gxvar:"AV7D_GRD_AUTH_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",
autoCorrect:"1",v2v:function(a){gx.O.AV7D_GRD_AUTH_NM=a},v2z:function(a){gx.O.ZV7D_GRD_AUTH_NM=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_AUTH_NM",a||gx.fn.currentGridRowImpl(162),gx.O.AV7D_GRD_AUTH_NM,0)},c2v:function(){gx.O.AV7D_GRD_AUTH_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_AUTH_NM",a||gx.fn.currentGridRowImpl(162))},nac:gx.falseFn};b[183]={fld:"TBL_HIDDEN",grid:0};b[186]={fld:"TXT_JS_EVENT",format:1,grid:0};b[187]={lvl:0,type:"svchar",len:1,dec:0,sign:false,
ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV13H_INIT_FLG",gxold:"OV13H_INIT_FLG",gxvar:"AV13H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_INIT_FLG=a},v2z:function(a){gx.O.ZV13H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV13H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV13H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},
nac:gx.falseFn};this.declareDomainHdlr(187,function(){});b[188]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_SRCH_FLG",gxz:"ZV16H_SRCH_FLG",gxold:"OV16H_SRCH_FLG",gxvar:"AV16H_SRCH_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV16H_SRCH_FLG=a},v2z:function(a){gx.O.ZV16H_SRCH_FLG=a},v2c:function(){gx.fn.setControlValue("vH_SRCH_FLG",gx.O.AV16H_SRCH_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},
c2v:function(){gx.O.AV16H_SRCH_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_SRCH_FLG")},nac:gx.falseFn};this.declareDomainHdlr(188,function(){});b[189]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV14H_KNGN_FLG",gxold:"OV14H_KNGN_FLG",gxvar:"AV14H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV14H_KNGN_FLG=a},v2z:function(a){gx.O.ZV14H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",
gx.O.AV14H_KNGN_FLG,0)},c2v:function(){gx.O.AV14H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[190]={lvl:0,type:"svchar",len:20,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_SITE_ID",gxz:"ZV15H_SITE_ID",gxold:"OV15H_SITE_ID",gxvar:"AV15H_SITE_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_SITE_ID=a},v2z:function(a){gx.O.ZV15H_SITE_ID=a},v2c:function(){gx.fn.setControlValue("vH_SITE_ID",
gx.O.AV15H_SITE_ID,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV15H_SITE_ID=this.val()},val:function(){return gx.fn.getControlValue("vH_SITE_ID")},nac:gx.falseFn};this.declareDomainHdlr(190,function(){});b[191]={lvl:0,type:"svchar",len:14,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vH_DISP_DATETIME",gxz:"ZV12H_DISP_DATETIME",gxold:"OV12H_DISP_DATETIME",gxvar:"AV12H_DISP_DATETIME",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",v2v:function(a){gx.O.AV12H_DISP_DATETIME=a},v2z:function(a){gx.O.ZV12H_DISP_DATETIME=a},v2c:function(){gx.fn.setControlValue("vH_DISP_DATETIME",gx.O.AV12H_DISP_DATETIME,0)},c2v:function(){gx.O.AV12H_DISP_DATETIME=this.val()},val:function(){return gx.fn.getControlValue("vH_DISP_DATETIME")},nac:gx.falseFn};b[192]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLREC_CNT",gxz:"ZV33GXV1",gxold:"OV33GXV1",gxvar:"GXV1",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=gx.num.intval(a)},v2z:function(a){gx.O.ZV33GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",",")},nac:gx.falseFn};this.OV8D_GRD_SITE_NM=this.ZV8D_GRD_SITE_NM=this.OV10D_SITE_ID=this.ZV10D_SITE_ID=this.AV10D_SITE_ID="";this.O54TBW01_LINE_NO=this.Z54TBW01_LINE_NO=0;this.OV12H_DISP_DATETIME=
this.ZV12H_DISP_DATETIME=this.AV12H_DISP_DATETIME=this.OV15H_SITE_ID=this.ZV15H_SITE_ID=this.AV15H_SITE_ID=this.OV14H_KNGN_FLG=this.ZV14H_KNGN_FLG=this.AV14H_KNGN_FLG=this.OV16H_SRCH_FLG=this.ZV16H_SRCH_FLG=this.AV16H_SRCH_FLG=this.OV13H_INIT_FLG=this.ZV13H_INIT_FLG=this.AV13H_INIT_FLG=this.OV7D_GRD_AUTH_NM=this.ZV7D_GRD_AUTH_NM=this.OV9D_GRD_USER_NM=this.ZV9D_GRD_USER_NM=this.OV30D_GRD_USER_ID=this.ZV30D_GRD_USER_ID="";this.OV33GXV1=this.ZV33GXV1=this.GXV1=0;this.AV12H_DISP_DATETIME=this.AV15H_SITE_ID=
this.AV14H_KNGN_FLG=this.AV16H_SRCH_FLG=this.AV13H_INIT_FLG=this.AV10D_SITE_ID="";this.AV18P_STUDY_ID=this.AV17P_MOVE_KBN=this.GXV1=0;this.AV8D_GRD_SITE_NM=this.A51TBW01_SESSION_ID=this.A52TBW01_APP_ID=this.A53TBW01_DISP_DATETIME=this.A685TBW01_FREE_SAVE_1="";this.A54TBW01_LINE_NO=0;this.A377TBM22_DEL_FLG=this.A325TAM08_DEL_FLG=this.AV7D_GRD_AUTH_NM=this.AV9D_GRD_USER_NM=this.AV30D_GRD_USER_ID="";this.A17TBM22_STUDY_ID=0;this.A18TBM22_SITE_ID=this.A319TAM08_SITE_NM="";this.A63TBM21_STUDY_ID=0;this.AV35Pgmname=
this.AV5C_APP_ID=this.A367TBM21_STUDY_NM="";this.AV11H_A_PAGING_SDT={};this.AV25W_ERRFLG=false;this.AV20W_A819_JS="";this.Events={e110y2_client:["'BTN_REG'",true],e120y2_client:["'BTN_SRCH'",true],e130y2_client:["'BTN_CLER'",true],e140y2_client:["'BTN_CAN'",true],e150y2_client:["'PAGE_FIRST'",true],e160y2_client:["'PAGE_LAST'",true],e170y2_client:["'PAGE_BACK'",true],e180y2_client:["'PAGE_NEXT'",true],e190y2_client:["'PAGE01'",true],e200y2_client:["'PAGE02'",true],e210y2_client:["'PAGE03'",true],
e220y2_client:["'PAGE04'",true],e230y2_client:["'PAGE05'",true],e240y2_client:["'PAGE06'",true],e250y2_client:["'PAGE07'",true],e260y2_client:["'PAGE08'",true],e270y2_client:["'PAGE09'",true],e280y2_client:["'PAGE10'",true],e320y2_client:["ENTER",true],e330y2_client:["CANCEL",true]};this.setVCMap("AV5C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV35Pgmname","vPGMNAME",0,"char");this.setVCMap("A63TBM21_STUDY_ID","TBM21_STUDY_ID",0,"int");this.setVCMap("AV18P_STUDY_ID","vP_STUDY_ID",0,"int");this.setVCMap("A367TBM21_STUDY_NM",
"TBM21_STUDY_NM",0,"svchar");this.setVCMap("AV17P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV11H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("A17TBM22_STUDY_ID","TBM22_STUDY_ID",0,"int");this.setVCMap("A18TBM22_SITE_ID","TBM22_SITE_ID",0,"svchar");this.setVCMap("A377TBM22_DEL_FLG","TBM22_DEL_FLG",0,"svchar");this.setVCMap("A325TAM08_DEL_FLG","TAM08_DEL_FLG",0,"svchar");this.setVCMap("A319TAM08_SITE_NM","TAM08_SITE_NM",0,"svchar");this.setVCMap("AV25W_ERRFLG","vW_ERRFLG",
0,"boolean");this.setVCMap("A685TBW01_FREE_SAVE_1","TBW01_FREE_SAVE_1",0,"vchar");this.setVCMap("AV5C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV35Pgmname","vPGMNAME",0,"char");this.setVCMap("A63TBM21_STUDY_ID","TBM21_STUDY_ID",0,"int");this.setVCMap("AV18P_STUDY_ID","vP_STUDY_ID",0,"int");this.setVCMap("A367TBM21_STUDY_NM","TBM21_STUDY_NM",0,"svchar");this.setVCMap("AV17P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV11H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("A17TBM22_STUDY_ID",
"TBM22_STUDY_ID",0,"int");this.setVCMap("A18TBM22_SITE_ID","TBM22_SITE_ID",0,"svchar");this.setVCMap("A377TBM22_DEL_FLG","TBM22_DEL_FLG",0,"svchar");this.setVCMap("A325TAM08_DEL_FLG","TAM08_DEL_FLG",0,"svchar");this.setVCMap("A319TAM08_SITE_NM","TAM08_SITE_NM",0,"svchar");this.setVCMap("AV25W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("A685TBW01_FREE_SAVE_1","TBW01_FREE_SAVE_1",0,"vchar");c.addRefreshingVar(this.GXValidFnc[188]);c.addRefreshingVar(this.GXValidFnc[191]);c.addRefreshingVar({rfrVar:"AV5C_APP_ID"});
c.addRefreshingVar(this.GXValidFnc[187]);c.addRefreshingVar({rfrVar:"AV35Pgmname"});c.addRefreshingVar({rfrVar:"A63TBM21_STUDY_ID"});c.addRefreshingVar({rfrVar:"AV18P_STUDY_ID"});c.addRefreshingVar({rfrVar:"A367TBM21_STUDY_NM"});c.addRefreshingVar({rfrVar:"AV17P_MOVE_KBN"});c.addRefreshingVar({rfrVar:"AV11H_A_PAGING_SDT"});c.addRefreshingVar(this.GXValidFnc[36]);c.addRefreshingVar({rfrVar:"A17TBM22_STUDY_ID"});c.addRefreshingVar({rfrVar:"A18TBM22_SITE_ID"});c.addRefreshingVar({rfrVar:"A377TBM22_DEL_FLG"});
c.addRefreshingVar({rfrVar:"A325TAM08_DEL_FLG"});c.addRefreshingVar({rfrVar:"A319TAM08_SITE_NM"});c.addRefreshingVar(this.GXValidFnc[189]);c.addRefreshingVar({rfrVar:"AV25W_ERRFLG"});c.addRefreshingVar({rfrVar:"A685TBW01_FREE_SAVE_1"});this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[192],"AV11H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0181",lvl:1})});gx.setParentObj(new b402_wp04_study_staff_list);
