gx.evt.autoSkip=!1;
gx.define("b403_wp01_import_confinfo",!1,function(){this.ServerClass="b403_wp01_import_confinfo";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e111f2_client");this.SetStandaloneVars=function(){this.AV21P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",")};this.s152_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",
gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"function proc() {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"ST_CLICK_SPACE();");if(""!=this.AV13W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV13W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+
"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");""!=this.AV12W_A819_JS&&gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV12W_A819_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.e111f2_client=function(){this.executeServerEvent("'BTN_IMPORT'",true)};this.e141f2_client=function(){this.executeServerEvent("'BTN_IMPORT_EXEC'",true)};this.e161f2_client=function(){this.executeServerEvent("ENTER",true)};this.e171f2_client=function(){this.executeServerEvent("CANCEL",true)};
var a=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,18,21,24,27,29,41,44,45,46];this.GXLastCtrlId=46;a[2]={fld:"TABLE1",grid:0};a[6]={fld:"TABLE2",grid:0};a[12]={fld:"TBL_UPD_BTNSET",grid:0};a[15]={fld:"TXT_BTN_IMPORT",format:0,grid:0};a[18]={fld:"TABLE3",grid:0};a[21]={fld:"TABLE4",grid:0};a[24]={fld:"TABLE10",grid:0};a[27]={fld:"TEXTBLOCK16",format:0,grid:0};a[29]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_STUDY_ID",gxz:"ZV8D_STUDY_ID",
gxold:"OV8D_STUDY_ID",gxvar:"AV8D_STUDY_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV8D_STUDY_ID=gx.num.intval(a)},v2z:function(a){gx.O.ZV8D_STUDY_ID=gx.num.intval(a)},v2c:function(){gx.fn.setComboBoxValue("vD_STUDY_ID",gx.O.AV8D_STUDY_ID)},c2v:function(){gx.O.AV8D_STUDY_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vD_STUDY_ID",",")},nac:gx.falseFn};a[41]={fld:"TBL_HIDDEN",grid:0};a[44]={fld:"TXT_JS_EVENT",format:1,grid:0};a[45]={lvl:0,type:"svchar",
len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV9H_INIT_FLG",gxold:"OV9H_INIT_FLG",gxvar:"AV9H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9H_INIT_FLG=a},v2z:function(a){gx.O.ZV9H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV9H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV9H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},
nac:gx.falseFn};this.declareDomainHdlr(45,function(){});a[46]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV10H_KNGN_FLG",gxold:"OV10H_KNGN_FLG",gxvar:"AV10H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10H_KNGN_FLG=a},v2z:function(a){gx.O.ZV10H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV10H_KNGN_FLG,0)},c2v:function(){gx.O.AV10H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},
nac:gx.falseFn};this.OV8D_STUDY_ID=this.ZV8D_STUDY_ID=this.AV8D_STUDY_ID=0;this.OV10H_KNGN_FLG=this.ZV10H_KNGN_FLG=this.AV10H_KNGN_FLG=this.OV9H_INIT_FLG=this.ZV9H_INIT_FLG=this.AV9H_INIT_FLG="";this.AV8D_STUDY_ID=0;this.AV10H_KNGN_FLG=this.AV9H_INIT_FLG="";this.AV21P_MOVE_KBN=0;this.A607TBM21_STATUS=this.A369TBM21_DEL_FLG="";this.A63TBM21_STUDY_ID=0;this.AV13W_A821_JS=this.AV12W_A819_JS=this.A210TAM07_PWD=this.A55TAM07_USER_ID=this.A214TAM07_DEL_FLG=this.A367TBM21_STUDY_NM="";this.Events={e111f2_client:["'BTN_IMPORT'",
true],e141f2_client:["'BTN_IMPORT_EXEC'",true],e161f2_client:["ENTER",true],e171f2_client:["CANCEL",true]};this.setVCMap("AV21P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",GXClass:null,Prefix:"W0039",lvl:1})});gx.setParentObj(new b403_wp01_import_confinfo);
