gx.evt.autoSkip=!1;
gx.define("b407_wp01_design_import",!1,function(){this.ServerClass="b407_wp01_design_import";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.addKeyListener("3","e112k2_client");this.SetStandaloneVars=function(){this.AV66Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV29C_APP_ID=gx.fn.getControlValue("vC_APP_ID");this.AV14P_MOVE_KBN=gx.fn.getIntegerValue("vP_MOVE_KBN",",");this.AV8H_A_PAGING_SDT=gx.fn.getControlValue("vH_A_PAGING_SDT");this.AV16W_A821_JS=
gx.fn.getControlValue("vW_A821_JS");this.AV11H_SRCH_FLG=gx.fn.getControlValue("vH_SRCH_FLG");this.AV21W_ERRFLG=gx.fn.getControlValue("vW_ERRFLG")};this.e112k2_client=function(){this.executeServerEvent("'BTN_IMPORT'",true)};this.e122k2_client=function(){this.executeServerEvent("'BTN_IMPORT_EXEC'",true)};this.e132k2_client=function(){this.executeServerEvent("'BTN_UPLOAD'",true)};this.e142k2_client=function(){this.executeServerEvent("VD_GRD_ALL_CHK.CLICK",true)};this.e152k2_client=function(){this.executeServerEvent("'PAGE_FIRST'",
true)};this.e162k2_client=function(){this.executeServerEvent("'PAGE_LAST'",true)};this.e172k2_client=function(){this.executeServerEvent("'PAGE_BACK'",true)};this.e182k2_client=function(){this.executeServerEvent("'PAGE_NEXT'",true)};this.e192k2_client=function(){this.executeServerEvent("'PAGE01'",true)};this.e202k2_client=function(){this.executeServerEvent("'PAGE02'",true)};this.e212k2_client=function(){this.executeServerEvent("'PAGE03'",true)};this.e222k2_client=function(){this.executeServerEvent("'PAGE04'",
true)};this.e232k2_client=function(){this.executeServerEvent("'PAGE05'",true)};this.e242k2_client=function(){this.executeServerEvent("'PAGE06'",true)};this.e252k2_client=function(){this.executeServerEvent("'PAGE07'",true)};this.e262k2_client=function(){this.executeServerEvent("'PAGE08'",true)};this.e272k2_client=function(){this.executeServerEvent("'PAGE09'",true)};this.e282k2_client=function(){this.executeServerEvent("'PAGE10'",true)};this.e322k2_client=function(a){this.executeServerEvent("ENTER",
true,a)};this.e332k2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,6,12,15,18,21,24,26,29,32,33,38,41,43,46,48,51,53,61,64,67,69,72,74,75,78,80,83,86,88,90,93,95,101,104,107,110,113,116,119,122,125,128,131,134,137,140,143,146,149,152,155,158,161,164,167,170,173,176,179,182,185,188,191,194,199,202,203,205,209,212,214,217,220,225,228,229,230,231,232,233,234,235,236,237,238,239,240];this.GXLastCtrlId=240;var c=this.Grid1Container=new gx.grid.grid(this,
2,"WbpLvl2",206,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"b407_wp01_design_import",[],true,1,true,true,10,false,false,false,"CollB407_SD01_IMPORT_LIST.B407_SD01_IMPORT_LISTItem",0,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,"AV5B407_SD01_IMPORT_LIST_C",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","","","","","","","","","");c.startTable("Tbl_grid_header3",209,"725px");c.addHtmlCode("<tbody>");c.startRow("","","","","","");c.startCell("","center",
"","","","","60px","","","");c.addHtmlCode("&nbsp;");c.addCheckBox("GXV2",212,"CTLCHECK","","","CHECK","boolean","true","false",null,true,false,4,"chr","");c.endCell();c.startCell("","","","","","","","","","");c.startTable("Table4",214,"0px");c.addHtmlCode("<tbody>");c.startRow("","","","","","");c.startCell("","","","","","","","","","");c.addSingleLineEdit("GXV3",217,"CTLTBM31_CRF_ID","","","TBM31_CRF_ID","svchar",10,"chr",10,10,"left",null,[],"GXV3","GXV3",true,0,false,false,"ReadonlyAttribute",
1,"");c.endCell();c.startCell("","","","","","","5px","","","");c.endCell();c.startCell("","","","","","","","","","");c.addSingleLineEdit("GXV4",220,"CTLTBM31_CRF_NM","","","TBM31_CRF_NM","svchar",80,"chr",100,80,"left",null,[],"GXV4","GXV4",true,0,false,false,"ReadonlyAttribute",1,"");c.endCell();c.endRow();c.addHtmlCode("</tbody>");c.endTable();c.endCell();c.endRow();c.addHtmlCode("</tbody>");c.endTable();c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[6]={fld:"TABLE2",grid:0};
b[12]={fld:"TBL_UPD_BTNSET",grid:0};b[15]={fld:"TXT_BTN_IMPORT",format:0,grid:0};b[18]={fld:"TABLE5",grid:0};b[21]={fld:"TABLE6",grid:0};b[24]={fld:"TEXTBLOCK16",format:0,grid:0};b[26]={lvl:0,type:"bitstr",len:1024,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_UPLOAD_FILE",gxz:"ZV7D_UPLOAD_FILE",gxold:"OV7D_UPLOAD_FILE",gxvar:"AV7D_UPLOAD_FILE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV7D_UPLOAD_FILE=a},v2z:function(a){gx.O.ZV7D_UPLOAD_FILE=
a},v2c:function(){gx.fn.setBlobValue("vD_UPLOAD_FILE",gx.O.AV7D_UPLOAD_FILE)},c2v:function(){gx.O.AV7D_UPLOAD_FILE=this.val()},val:function(){return gx.fn.getBlobValue("vD_UPLOAD_FILE")},nac:gx.falseFn};b[29]={fld:"TABLE9",grid:0};b[32]={fld:"TXT_BTN_UPLOAD",format:0,grid:0};b[33]={fld:"TBL_INFO",grid:0};b[38]={fld:"TEXTBLOCK3",format:0,grid:0};b[41]={fld:"TEXTBLOCK4",format:0,grid:0};b[43]={fld:"TEXTBLOCK8",format:0,grid:0};b[46]={fld:"TEXTBLOCK5",format:0,grid:0};b[48]={fld:"TEXTBLOCK7",format:0,
grid:0};b[51]={fld:"TEXTBLOCK6",format:0,grid:0};b[53]={fld:"TEXTBLOCK2",format:0,grid:0};b[61]={fld:"TBL_STUDY",grid:0};b[64]={fld:"TEXTBLOCK17",format:0,grid:0};b[67]={fld:"TEXTBLOCK19",format:0,grid:0};b[69]={fld:"TABLE3",grid:0};b[72]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_STUDY_ID",gxz:"ZV40D_STUDY_ID",gxold:"OV40D_STUDY_ID",gxvar:"AV40D_STUDY_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV40D_STUDY_ID=
gx.num.intval(a)},v2z:function(a){gx.O.ZV40D_STUDY_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vD_STUDY_ID",gx.O.AV40D_STUDY_ID,0)},c2v:function(){gx.O.AV40D_STUDY_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vD_STUDY_ID",",")},nac:gx.falseFn};b[74]={fld:"TEXTBLOCK1",format:0,grid:0};b[75]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_CHG_STUDY_ID",gxz:"ZV48D_CHG_STUDY_ID",gxold:"OV48D_CHG_STUDY_ID",
gxvar:"AV48D_CHG_STUDY_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV48D_CHG_STUDY_ID=gx.num.intval(a)},v2z:function(a){gx.O.ZV48D_CHG_STUDY_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vD_CHG_STUDY_ID",gx.O.AV48D_CHG_STUDY_ID,0)},c2v:function(){gx.O.AV48D_CHG_STUDY_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vD_CHG_STUDY_ID",",")},nac:gx.falseFn};b[78]={fld:"TEXTBLOCK20",format:0,grid:0};b[80]={lvl:0,type:"svchar",len:100,dec:0,
sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_STUDY_NM",gxz:"ZV41D_STUDY_NM",gxold:"OV41D_STUDY_NM",gxvar:"AV41D_STUDY_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV41D_STUDY_NM=a},v2z:function(a){gx.O.ZV41D_STUDY_NM=a},v2c:function(){gx.fn.setControlValue("vD_STUDY_NM",gx.O.AV41D_STUDY_NM,0)},c2v:function(){gx.O.AV41D_STUDY_NM=this.val()},val:function(){return gx.fn.getControlValue("vD_STUDY_NM")},nac:gx.falseFn};b[83]={fld:"TABLE8",grid:0};b[86]=
{lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_BASE_FLG",gxz:"ZV35D_BASE_FLG",gxold:"OV35D_BASE_FLG",gxvar:"AV35D_BASE_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV35D_BASE_FLG=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV35D_BASE_FLG=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vD_BASE_FLG",gx.O.AV35D_BASE_FLG,true)},c2v:function(){gx.O.AV35D_BASE_FLG=gx.lang.booleanValue(this.val())},
val:function(){return gx.fn.getCheckBoxValue("vD_BASE_FLG",true,false)},nac:gx.falseFn};b[88]={lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_SITE_FLG",gxz:"ZV38D_SITE_FLG",gxold:"OV38D_SITE_FLG",gxvar:"AV38D_SITE_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV38D_SITE_FLG=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV38D_SITE_FLG=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vD_SITE_FLG",
gx.O.AV38D_SITE_FLG,true)},c2v:function(){gx.O.AV38D_SITE_FLG=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getCheckBoxValue("vD_SITE_FLG",true,false)},nac:gx.falseFn};b[90]={lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_STAFF_FLG",gxz:"ZV39D_STAFF_FLG",gxold:"OV39D_STAFF_FLG",gxvar:"AV39D_STAFF_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV39D_STAFF_FLG=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV39D_STAFF_FLG=
gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vD_STAFF_FLG",gx.O.AV39D_STAFF_FLG,true)},c2v:function(){gx.O.AV39D_STAFF_FLG=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getCheckBoxValue("vD_STAFF_FLG",true,false)},nac:gx.falseFn};b[93]={lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_LIST_CHK",gxz:"ZV37D_LIST_CHK",gxold:"OV37D_LIST_CHK",gxvar:"AV37D_LIST_CHK",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",
v2v:function(a){gx.O.AV37D_LIST_CHK=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV37D_LIST_CHK=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vD_LIST_CHK",gx.O.AV37D_LIST_CHK,true)},c2v:function(){gx.O.AV37D_LIST_CHK=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getCheckBoxValue("vD_LIST_CHK",true,false)},nac:gx.falseFn};b[95]={lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_SUBJECT_CHK",gxz:"ZV42D_SUBJECT_CHK",
gxold:"OV42D_SUBJECT_CHK",gxvar:"AV42D_SUBJECT_CHK",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV42D_SUBJECT_CHK=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV42D_SUBJECT_CHK=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vD_SUBJECT_CHK",gx.O.AV42D_SUBJECT_CHK,true)},c2v:function(){gx.O.AV42D_SUBJECT_CHK=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getCheckBoxValue("vD_SUBJECT_CHK",true,false)},nac:gx.falseFn};b[101]={fld:"TBL_LIST",grid:0};
b[104]={fld:"TBL_PAGE_AREA",grid:0};b[107]={fld:"TXT_REC_CNT",format:0,grid:0};b[110]={fld:"TBL_PAGE",grid:0};b[113]={fld:"TBL_FIRST",grid:0};b[116]={fld:"TXT_FIRST",format:0,grid:0};b[119]={fld:"TBL_BACK",grid:0};b[122]={fld:"TXT_BACK",format:0,grid:0};b[125]={fld:"TBL_PAGE01",grid:0};b[128]={fld:"TXT_PAGE01",format:0,grid:0};b[131]={fld:"TBL_PAGE02",grid:0};b[134]={fld:"TXT_PAGE02",format:0,grid:0};b[137]={fld:"TBL_PAGE03",grid:0};b[140]={fld:"TXT_PAGE03",format:0,grid:0};b[143]={fld:"TBL_PAGE04",
grid:0};b[146]={fld:"TXT_PAGE04",format:0,grid:0};b[149]={fld:"TBL_PAGE05",grid:0};b[152]={fld:"TXT_PAGE05",format:0,grid:0};b[155]={fld:"TBL_PAGE06",grid:0};b[158]={fld:"TXT_PAGE06",format:0,grid:0};b[161]={fld:"TBL_PAGE07",grid:0};b[164]={fld:"TXT_PAGE07",format:0,grid:0};b[167]={fld:"TBL_PAGE08",grid:0};b[170]={fld:"TXT_PAGE08",format:0,grid:0};b[173]={fld:"TBL_PAGE09",grid:0};b[176]={fld:"TXT_PAGE09",format:0,grid:0};b[179]={fld:"TBL_PAGE10",grid:0};b[182]={fld:"TXT_PAGE10",format:0,grid:0};b[185]=
{fld:"TBL_NEXT",grid:0};b[188]={fld:"TXT_NEXT",format:0,grid:0};b[191]={fld:"TBL_LAST",grid:0};b[194]={fld:"TXT_LAST",format:0,grid:0};b[199]={fld:"TBL_GRID_HEADER",grid:0};b[202]={lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_ALL_CHK",gxz:"ZV36D_GRD_ALL_CHK",gxold:"OV36D_GRD_ALL_CHK",gxvar:"AV36D_GRD_ALL_CHK",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV36D_GRD_ALL_CHK=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV36D_GRD_ALL_CHK=
gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vD_GRD_ALL_CHK",gx.O.AV36D_GRD_ALL_CHK,true)},c2v:function(){gx.O.AV36D_GRD_ALL_CHK=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getCheckBoxValue("vD_GRD_ALL_CHK",true,false)},nac:gx.falseFn};b[203]={fld:"TEXTBLOCK15",format:0,grid:0};b[205]={fld:"TEXTBLOCK14",format:0,grid:0};b[209]={fld:"TBL_GRID_HEADER3",grid:206};b[212]={lvl:2,type:"boolean",len:4,dec:0,sign:false,ro:1,isacc:0,grid:206,gxgrid:this.Grid1Container,
fnc:null,isvalid:null,rgrid:[],fld:"CTLCHECK",gxz:"ZV61GXV2",gxold:"OV61GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",inputType:"text",v2v:function(a){gx.O.GXV2=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV61GXV2=gx.lang.booleanValue(a)},v2c:function(a){gx.fn.setGridCheckBoxValue("CTLCHECK",a||gx.fn.currentGridRowImpl(206),gx.O.GXV2,true)},c2v:function(){gx.O.GXV2=gx.lang.booleanValue(this.val())},val:function(a){return gx.fn.getGridCheckBoxValue("CTLCHECK",a||gx.fn.currentGridRowImpl(206),
true,false)},nac:gx.falseFn};b[214]={fld:"TABLE4",grid:206};b[217]={lvl:2,type:"svchar",len:10,dec:0,sign:false,ro:1,isacc:0,grid:206,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM31_CRF_ID",gxz:"ZV62GXV3",gxold:"OV62GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.GXV3=a},v2z:function(a){gx.O.ZV62GXV3=a},v2c:function(a){gx.fn.setGridControlValue("CTLTBM31_CRF_ID",a||gx.fn.currentGridRowImpl(206),gx.O.GXV3,
0)},c2v:function(){gx.O.GXV3=this.val()},val:function(a){return gx.fn.getGridControlValue("CTLTBM31_CRF_ID",a||gx.fn.currentGridRowImpl(206))},nac:gx.falseFn};b[220]={lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:206,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"CTLTBM31_CRF_NM",gxz:"ZV63GXV4",gxold:"OV63GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.GXV4=a},v2z:function(a){gx.O.ZV63GXV4=a},v2c:function(a){gx.fn.setGridControlValue("CTLTBM31_CRF_NM",
a||gx.fn.currentGridRowImpl(206),gx.O.GXV4,0)},c2v:function(){gx.O.GXV4=this.val()},val:function(a){return gx.fn.getGridControlValue("CTLTBM31_CRF_NM",a||gx.fn.currentGridRowImpl(206))},nac:gx.falseFn};b[225]={fld:"TBL_HIDDEN",grid:0};b[228]={fld:"TXT_JS_EVENT",format:1,grid:0};b[229]={fld:"TEXT_ONCLICK",format:1,grid:0};b[230]={fld:"BTN_IMPORT_EXEC",format:0,grid:0};b[231]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV9H_INIT_FLG",
gxold:"OV9H_INIT_FLG",gxvar:"AV9H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9H_INIT_FLG=a},v2z:function(a){gx.O.ZV9H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV9H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV9H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},nac:gx.falseFn};this.declareDomainHdlr(231,function(){});b[232]={lvl:0,type:"svchar",len:1,dec:0,sign:false,
ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV10H_KNGN_FLG",gxold:"OV10H_KNGN_FLG",gxvar:"AV10H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10H_KNGN_FLG=a},v2z:function(a){gx.O.ZV10H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV10H_KNGN_FLG,0)},c2v:function(){gx.O.AV10H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},nac:gx.falseFn};b[233]={lvl:0,type:"int",len:10,dec:0,sign:false,
pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLREC_CNT",gxz:"ZV64GXV5",gxold:"OV64GXV5",gxvar:"GXV5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV5=gx.num.intval(a)},v2z:function(a){gx.O.ZV64GXV5=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",gx.O.GXV5,0)},c2v:function(){gx.O.GXV5=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",",")},nac:gx.falseFn};b[234]={lvl:0,type:"boolean",len:4,
dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_BASE_ENABLED",gxz:"ZV43H_BASE_ENABLED",gxold:"OV43H_BASE_ENABLED",gxvar:"AV43H_BASE_ENABLED",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV43H_BASE_ENABLED=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV43H_BASE_ENABLED=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vH_BASE_ENABLED",gx.O.AV43H_BASE_ENABLED,true)},c2v:function(){gx.O.AV43H_BASE_ENABLED=gx.lang.booleanValue(this.val())},
val:function(){return gx.fn.getCheckBoxValue("vH_BASE_ENABLED",true,false)},nac:gx.falseFn};b[235]={lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_LIST_ENABLED",gxz:"ZV44H_LIST_ENABLED",gxold:"OV44H_LIST_ENABLED",gxvar:"AV44H_LIST_ENABLED",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV44H_LIST_ENABLED=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV44H_LIST_ENABLED=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vH_LIST_ENABLED",
gx.O.AV44H_LIST_ENABLED,true)},c2v:function(){gx.O.AV44H_LIST_ENABLED=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getCheckBoxValue("vH_LIST_ENABLED",true,false)},nac:gx.falseFn};b[236]={lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_SITE_ENABLED",gxz:"ZV45H_SITE_ENABLED",gxold:"OV45H_SITE_ENABLED",gxvar:"AV45H_SITE_ENABLED",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV45H_SITE_ENABLED=gx.lang.booleanValue(a)},
v2z:function(a){gx.O.ZV45H_SITE_ENABLED=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vH_SITE_ENABLED",gx.O.AV45H_SITE_ENABLED,true)},c2v:function(){gx.O.AV45H_SITE_ENABLED=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getCheckBoxValue("vH_SITE_ENABLED",true,false)},nac:gx.falseFn};b[237]={lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_STAFF_ENABLED",gxz:"ZV46H_STAFF_ENABLED",gxold:"OV46H_STAFF_ENABLED",
gxvar:"AV46H_STAFF_ENABLED",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV46H_STAFF_ENABLED=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV46H_STAFF_ENABLED=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vH_STAFF_ENABLED",gx.O.AV46H_STAFF_ENABLED,true)},c2v:function(){gx.O.AV46H_STAFF_ENABLED=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getCheckBoxValue("vH_STAFF_ENABLED",true,false)},nac:gx.falseFn};b[238]={lvl:0,type:"boolean",len:4,dec:0,
sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_SUBJECT_ENABLED",gxz:"ZV47H_SUBJECT_ENABLED",gxold:"OV47H_SUBJECT_ENABLED",gxvar:"AV47H_SUBJECT_ENABLED",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"checkbox",v2v:function(a){gx.O.AV47H_SUBJECT_ENABLED=gx.lang.booleanValue(a)},v2z:function(a){gx.O.ZV47H_SUBJECT_ENABLED=gx.lang.booleanValue(a)},v2c:function(){gx.fn.setCheckBoxValue("vH_SUBJECT_ENABLED",gx.O.AV47H_SUBJECT_ENABLED,true)},c2v:function(){gx.O.AV47H_SUBJECT_ENABLED=gx.lang.booleanValue(this.val())},
val:function(){return gx.fn.getCheckBoxValue("vH_SUBJECT_ENABLED",true,false)},nac:gx.falseFn};b[239]={lvl:0,type:"svchar",len:200,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vD_ORIGINAL_NAME",gxz:"ZV50D_ORIGINAL_NAME",gxold:"OV50D_ORIGINAL_NAME",gxvar:"AV50D_ORIGINAL_NAME",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV50D_ORIGINAL_NAME=a},v2z:function(a){gx.O.ZV50D_ORIGINAL_NAME=a},v2c:function(){gx.fn.setControlValue("vD_ORIGINAL_NAME",gx.O.AV50D_ORIGINAL_NAME,
0)},c2v:function(){gx.O.AV50D_ORIGINAL_NAME=this.val()},val:function(){return gx.fn.getControlValue("vD_ORIGINAL_NAME")},nac:gx.falseFn};b[240]={lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_FILE_PATH_NAME",gxz:"ZV55H_FILE_PATH_NAME",gxold:"OV55H_FILE_PATH_NAME",gxvar:"AV55H_FILE_PATH_NAME",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV55H_FILE_PATH_NAME=a},v2z:function(a){gx.O.ZV55H_FILE_PATH_NAME=a},v2c:function(){gx.fn.setControlValue("vH_FILE_PATH_NAME",
gx.O.AV55H_FILE_PATH_NAME,0)},c2v:function(){gx.O.AV55H_FILE_PATH_NAME=this.val()},val:function(){return gx.fn.getControlValue("vH_FILE_PATH_NAME")},nac:gx.falseFn};this.OV7D_UPLOAD_FILE=this.ZV7D_UPLOAD_FILE=this.AV7D_UPLOAD_FILE="";this.OV48D_CHG_STUDY_ID=this.ZV48D_CHG_STUDY_ID=this.AV48D_CHG_STUDY_ID=this.OV40D_STUDY_ID=this.ZV40D_STUDY_ID=this.AV40D_STUDY_ID=0;this.OV41D_STUDY_NM=this.ZV41D_STUDY_NM=this.AV41D_STUDY_NM="";this.OV61GXV2=this.ZV61GXV2=this.OV36D_GRD_ALL_CHK=this.ZV36D_GRD_ALL_CHK=
this.AV36D_GRD_ALL_CHK=this.OV42D_SUBJECT_CHK=this.ZV42D_SUBJECT_CHK=this.AV42D_SUBJECT_CHK=this.OV37D_LIST_CHK=this.ZV37D_LIST_CHK=this.AV37D_LIST_CHK=this.OV39D_STAFF_FLG=this.ZV39D_STAFF_FLG=this.AV39D_STAFF_FLG=this.OV38D_SITE_FLG=this.ZV38D_SITE_FLG=this.AV38D_SITE_FLG=this.OV35D_BASE_FLG=this.ZV35D_BASE_FLG=this.AV35D_BASE_FLG=false;this.OV10H_KNGN_FLG=this.ZV10H_KNGN_FLG=this.AV10H_KNGN_FLG=this.OV9H_INIT_FLG=this.ZV9H_INIT_FLG=this.AV9H_INIT_FLG=this.OV63GXV4=this.ZV63GXV4=this.OV62GXV3=this.ZV62GXV3=
"";this.OV64GXV5=this.ZV64GXV5=this.GXV5=0;this.OV47H_SUBJECT_ENABLED=this.ZV47H_SUBJECT_ENABLED=this.AV47H_SUBJECT_ENABLED=this.OV46H_STAFF_ENABLED=this.ZV46H_STAFF_ENABLED=this.AV46H_STAFF_ENABLED=this.OV45H_SITE_ENABLED=this.ZV45H_SITE_ENABLED=this.AV45H_SITE_ENABLED=this.OV44H_LIST_ENABLED=this.ZV44H_LIST_ENABLED=this.AV44H_LIST_ENABLED=this.OV43H_BASE_ENABLED=this.ZV43H_BASE_ENABLED=this.AV43H_BASE_ENABLED=false;this.AV7D_UPLOAD_FILE=this.OV55H_FILE_PATH_NAME=this.ZV55H_FILE_PATH_NAME=this.AV55H_FILE_PATH_NAME=
this.OV50D_ORIGINAL_NAME=this.ZV50D_ORIGINAL_NAME=this.AV50D_ORIGINAL_NAME="";this.AV48D_CHG_STUDY_ID=this.AV40D_STUDY_ID=0;this.AV41D_STUDY_NM="";this.AV36D_GRD_ALL_CHK=this.AV42D_SUBJECT_CHK=this.AV37D_LIST_CHK=this.AV39D_STAFF_FLG=this.AV38D_SITE_FLG=this.AV35D_BASE_FLG=false;this.AV10H_KNGN_FLG=this.AV9H_INIT_FLG="";this.GXV5=0;this.AV47H_SUBJECT_ENABLED=this.AV46H_STAFF_ENABLED=this.AV45H_SITE_ENABLED=this.AV44H_LIST_ENABLED=this.AV43H_BASE_ENABLED=false;this.AV55H_FILE_PATH_NAME=this.AV50D_ORIGINAL_NAME=
"";this.AV14P_MOVE_KBN=0;this.GXV2=false;this.AV29C_APP_ID=this.AV66Pgmname=this.GXV4=this.GXV3="";this.AV8H_A_PAGING_SDT={};this.AV11H_SRCH_FLG=this.AV16W_A821_JS="";this.AV21W_ERRFLG=false;this.Events={e112k2_client:["'BTN_IMPORT'",true],e122k2_client:["'BTN_IMPORT_EXEC'",true],e132k2_client:["'BTN_UPLOAD'",true],e142k2_client:["VD_GRD_ALL_CHK.CLICK",true],e152k2_client:["'PAGE_FIRST'",true],e162k2_client:["'PAGE_LAST'",true],e172k2_client:["'PAGE_BACK'",true],e182k2_client:["'PAGE_NEXT'",true],
e192k2_client:["'PAGE01'",true],e202k2_client:["'PAGE02'",true],e212k2_client:["'PAGE03'",true],e222k2_client:["'PAGE04'",true],e232k2_client:["'PAGE05'",true],e242k2_client:["'PAGE06'",true],e252k2_client:["'PAGE07'",true],e262k2_client:["'PAGE08'",true],e272k2_client:["'PAGE09'",true],e282k2_client:["'PAGE10'",true],e322k2_client:["ENTER",true],e332k2_client:["CANCEL",true]};this.setVCMap("AV66Pgmname","vPGMNAME",0,"char");this.setVCMap("AV29C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV14P_MOVE_KBN",
"vP_MOVE_KBN",0,"int");this.setVCMap("AV8H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV16W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("AV11H_SRCH_FLG","vH_SRCH_FLG",0,"svchar");this.setVCMap("AV21W_ERRFLG","vW_ERRFLG",0,"boolean");this.setVCMap("AV66Pgmname","vPGMNAME",0,"char");this.setVCMap("AV29C_APP_ID","vC_APP_ID",0,"svchar");this.setVCMap("AV14P_MOVE_KBN","vP_MOVE_KBN",0,"int");this.setVCMap("AV8H_A_PAGING_SDT","vH_A_PAGING_SDT",0,"A_PAGING_SDT");this.setVCMap("AV16W_A821_JS",
"vW_A821_JS",0,"svchar");this.setVCMap("AV11H_SRCH_FLG","vH_SRCH_FLG",0,"svchar");this.setVCMap("AV21W_ERRFLG","vW_ERRFLG",0,"boolean");c.addRefreshingVar(this.GXValidFnc[231]);c.addRefreshingVar({rfrVar:"AV66Pgmname"});c.addRefreshingVar({rfrVar:"AV29C_APP_ID"});c.addRefreshingVar({rfrVar:"AV14P_MOVE_KBN"});c.addRefreshingVar({rfrVar:"AV8H_A_PAGING_SDT"});c.addRefreshingVar({rfrVar:"AV16W_A821_JS"});c.addRefreshingVar({rfrVar:"AV11H_SRCH_FLG"});c.addRefreshingVar({rfrVar:"AV21W_ERRFLG"});this.addGridBCProperty("B407_sd01_import_list_c",
["CHECK"],this.GXValidFnc[212],"AV5B407_SD01_IMPORT_LIST_C");this.addGridBCProperty("B407_sd01_import_list_c",["TBM31_CRF_ID"],this.GXValidFnc[217],"AV5B407_SD01_IMPORT_LIST_C");this.addGridBCProperty("B407_sd01_import_list_c",["TBM31_CRF_NM"],this.GXValidFnc[220],"AV5B407_SD01_IMPORT_LIST_C");this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[233],"AV8H_A_PAGING_SDT");this.InitStandaloneVars();this.setComponent({id:"WEBCOMP1",GXClass:null,Prefix:"W0009",lvl:1});this.setComponent({id:"WEBCOMP2",
GXClass:null,Prefix:"W0223",lvl:1})});gx.setParentObj(new b407_wp01_design_import);
