gx.evt.autoSkip=!1;
gx.define("b712_wp03_crf_filter_list",!1,function(){this.ServerClass="b712_wp03_crf_filter_list";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.skipOnEnter=this.hasEnterEvent=false;this.SetStandaloneVars=function(){this.AV16P_STUDY_ID=gx.fn.getIntegerValue("vP_STUDY_ID",",");this.AV59Pgmname=gx.fn.getControlValue("vPGMNAME");this.AV19W_A821_JS=gx.fn.getControlValue("vW_A821_JS");this.A980TBM45_FILETR_NM=gx.fn.getControlValue("TBM45_FILETR_NM")};this.s122_client=
function(){};this.s132_client=function(){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption","<script language=javascript>");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"var confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (window.addEventListener) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"  window.addEventListener('load', function(){init();}, false);");
gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"} else if (window.attachEvent) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"\twindow.attachEvent('onload',function(){init();});");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function init() {");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"function proc() {");if(""!=this.AV19W_A821_JS){gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"if (!confirmFlg) {");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+this.AV19W_A821_JS);gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT",
"Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = true;")}else gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"confirmFlg = false;");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"}");gx.fn.setCtrlProperty("TXT_JS_EVENT","Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"timerID = setTimeout('proc()', 10);");gx.fn.setCtrlProperty("TXT_JS_EVENT",
"Caption",gx.fn.getCtrlProperty("TXT_JS_EVENT","Caption")+"<\/script>")};this.e112e2_client=function(){this.executeServerEvent("'BTN_CLOSE'",true)};this.e122e2_client=function(){this.executeServerEvent("'BTN_REG'",true)};this.e162e2_client=function(a){this.executeServerEvent("'BTN_EDIT_SEL'",true,a)};this.e172e2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e182e2_client=function(a){this.executeServerEvent("CANCEL",true,a)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,9,14,18,23,
26,30,32,35,38,41,49,53,54,58,60,61,62,73,76,77,78,79,80,83,85,88,90,93,98,100,103,105,108,110,113,115,118,120,123,125,128,130,133,135,138,140,143,145,148,150,153,155,158,160,163,165,168,170,173,175,178,180,183,185,188,190,193,195,198,200,203,205,208,210,213,215];this.GXLastCtrlId=215;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",55,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"b712_wp03_crf_filter_list",[],true,1,true,true,0,false,false,false,"",0,"px","\u884c\u8ffd\u52a0",
false,false,false,null,null,false,"",false,[1,1,1,1]);c.startRow("","","","","","");c.startCell("","center","","","","","45px","","","");c.addTextBlock("BTN_SEL","e162e2_client");c.endCell();c.startCell("","","","","","","420px","","","");c.addSingleLineEdit("D_grd_f_name",60,"vD_GRD_F_NAME","","","D_GRD_F_NAME","svchar",40,"chr",40,40,"left",null,[],"D_grd_f_name","D_GRD_F_NAME",true,0,false,false,"Attribute",1,"");c.addSingleLineEdit(977,61,"TBM45_STUDY_ID","","","TBM45_STUDY_ID","int",10,"chr",
10,10,"right",null,[],977,"TBM45_STUDY_ID",true,0,false,false,"Attribute",1,"");c.addSingleLineEdit(978,62,"TBM45_FILTER_NO","","","TBM45_FILTER_NO","int",4,"chr",4,4,"right",null,[],978,"TBM45_FILTER_NO",true,0,false,false,"Attribute",1,"");c.endCell();c.endRow();this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[9]={fld:"TABLE2",grid:0};b[14]={fld:"TABLE9",grid:0};b[18]={fld:"TEXTBLOCK31",format:0,grid:0};b[23]={fld:"TABLE5",grid:0};b[26]={fld:"TABLE8",grid:0};b[30]={fld:"TXT_BTN_REG",format:0,grid:0};
b[32]={fld:"TABLE10",grid:0};b[35]={fld:"TXT_BTN_REG2",format:0,grid:0};b[38]={fld:"TABLE3",grid:0};b[41]={fld:"TABLE4",grid:0};b[49]={fld:"TBL_GRID_HEADER",grid:0};b[53]={fld:"TEXTBLOCK3",format:0,grid:0};b[54]={fld:"SECTION1",grid:0};b[58]={fld:"BTN_SEL",format:0,grid:55};b[60]={lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:0,isacc:0,grid:55,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vD_GRD_F_NAME",gxz:"ZV26D_GRD_F_NAME",gxold:"OV26D_GRD_F_NAME",gxvar:"AV26D_GRD_F_NAME",ucs:[],
op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.AV26D_GRD_F_NAME=a},v2z:function(a){gx.O.ZV26D_GRD_F_NAME=a},v2c:function(a){gx.fn.setGridControlValue("vD_GRD_F_NAME",a||gx.fn.currentGridRowImpl(55),gx.O.AV26D_GRD_F_NAME,0)},c2v:function(){gx.O.AV26D_GRD_F_NAME=this.val()},val:function(a){return gx.fn.getGridControlValue("vD_GRD_F_NAME",a||gx.fn.currentGridRowImpl(55))},nac:gx.falseFn};b[61]={lvl:2,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:1,
isacc:0,grid:55,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM45_STUDY_ID",gxz:"Z977TBM45_STUDY_ID",gxold:"O977TBM45_STUDY_ID",gxvar:"A977TBM45_STUDY_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A977TBM45_STUDY_ID=gx.num.intval(a)},v2z:function(a){gx.O.Z977TBM45_STUDY_ID=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TBM45_STUDY_ID",a||gx.fn.currentGridRowImpl(55),gx.O.A977TBM45_STUDY_ID,0);typeof this.dom_hdl=="function"&&
this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A977TBM45_STUDY_ID=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TBM45_STUDY_ID",a||gx.fn.currentGridRowImpl(55),",")},nac:gx.falseFn};b[62]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,grid:55,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TBM45_FILTER_NO",gxz:"Z978TBM45_FILTER_NO",gxold:"O978TBM45_FILTER_NO",gxvar:"A978TBM45_FILTER_NO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",
v2v:function(a){gx.O.A978TBM45_FILTER_NO=gx.num.intval(a)},v2z:function(a){gx.O.Z978TBM45_FILTER_NO=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TBM45_FILTER_NO",a||gx.fn.currentGridRowImpl(55),gx.O.A978TBM45_FILTER_NO,0)},c2v:function(){gx.O.A978TBM45_FILTER_NO=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TBM45_FILTER_NO",a||gx.fn.currentGridRowImpl(55),",")},nac:gx.falseFn};b[73]={fld:"TBL_HIDDEN",grid:0};b[76]={fld:"TXT_JS_EVENT",format:1,grid:0};
b[77]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_INIT_FLG",gxz:"ZV13H_INIT_FLG",gxold:"OV13H_INIT_FLG",gxvar:"AV13H_INIT_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV13H_INIT_FLG=a},v2z:function(a){gx.O.ZV13H_INIT_FLG=a},v2c:function(){gx.fn.setControlValue("vH_INIT_FLG",gx.O.AV13H_INIT_FLG,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV13H_INIT_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_INIT_FLG")},
nac:gx.falseFn};this.declareDomainHdlr(77,function(){});b[78]={lvl:0,type:"svchar",len:1,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_KNGN_FLG",gxz:"ZV14H_KNGN_FLG",gxold:"OV14H_KNGN_FLG",gxvar:"AV14H_KNGN_FLG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV14H_KNGN_FLG=a},v2z:function(a){gx.O.ZV14H_KNGN_FLG=a},v2c:function(){gx.fn.setControlValue("vH_KNGN_FLG",gx.O.AV14H_KNGN_FLG,0)},c2v:function(){gx.O.AV14H_KNGN_FLG=this.val()},val:function(){return gx.fn.getControlValue("vH_KNGN_FLG")},
nac:gx.falseFn};b[79]={lvl:0,type:"int",len:6,dec:0,sign:false,pic:"ZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vH_SUBJECT_ID",gxz:"ZV15H_SUBJECT_ID",gxold:"OV15H_SUBJECT_ID",gxvar:"AV15H_SUBJECT_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15H_SUBJECT_ID=gx.num.intval(a)},v2z:function(a){gx.O.ZV15H_SUBJECT_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vH_SUBJECT_ID",gx.O.AV15H_SUBJECT_ID,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},
c2v:function(){gx.O.AV15H_SUBJECT_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vH_SUBJECT_ID",",")},nac:gx.falseFn};this.declareDomainHdlr(79,function(){});b[80]={fld:"TABLE7",grid:0};b[83]={fld:"TEXTBLOCK28",format:0,grid:0};b[85]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLMAX_ROW",gxz:"ZV32GXV1",gxold:"OV32GXV1",gxvar:"GXV1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV1=
gx.num.intval(a)},v2z:function(a){gx.O.ZV32GXV1=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLMAX_ROW",gx.O.GXV1,0)},c2v:function(){gx.O.GXV1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLMAX_ROW",",")},nac:gx.falseFn};b[88]={fld:"TEXTBLOCK29",format:0,grid:0};b[90]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLREC_CNT",gxz:"ZV33GXV2",gxold:"OV33GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],
nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV2=gx.num.intval(a)},v2z:function(a){gx.O.ZV33GXV2=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLREC_CNT",gx.O.GXV2,0)},c2v:function(){gx.O.GXV2=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLREC_CNT",",")},nac:gx.falseFn};b[93]={fld:"TEXTBLOCK30",format:0,grid:0};b[98]={fld:"TEXTBLOCK4",format:0,grid:0};b[100]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,
rgrid:[],fld:"CTLPAGE_NO",gxz:"ZV34GXV4",gxold:"OV34GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV4=gx.num.intval(a)},v2z:function(a){gx.O.ZV34GXV4=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_NO",gx.O.GXV4,0)},c2v:function(){gx.O.GXV4=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_NO",",")},nac:gx.falseFn};b[103]={fld:"TEXTBLOCK5",format:0,grid:0};b[105]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",
ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE01",gxz:"ZV35GXV5",gxold:"OV35GXV5",gxvar:"GXV5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV5=gx.num.intval(a)},v2z:function(a){gx.O.ZV35GXV5=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE01",gx.O.GXV5,0)},c2v:function(){gx.O.GXV5=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE01",",")},nac:gx.falseFn};b[108]={fld:"TEXTBLOCK6",format:0,grid:0};b[110]={lvl:0,
type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE02",gxz:"ZV36GXV6",gxold:"OV36GXV6",gxvar:"GXV6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV6=gx.num.intval(a)},v2z:function(a){gx.O.ZV36GXV6=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE02",gx.O.GXV6,0)},c2v:function(){gx.O.GXV6=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE02",",")},nac:gx.falseFn};b[113]={fld:"TEXTBLOCK7",
format:0,grid:0};b[115]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE03",gxz:"ZV37GXV7",gxold:"OV37GXV7",gxvar:"GXV7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV7=gx.num.intval(a)},v2z:function(a){gx.O.ZV37GXV7=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE03",gx.O.GXV7,0)},c2v:function(){gx.O.GXV7=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE03",",")},
nac:gx.falseFn};b[118]={fld:"TEXTBLOCK8",format:0,grid:0};b[120]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE04",gxz:"ZV38GXV8",gxold:"OV38GXV8",gxvar:"GXV8",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV8=gx.num.intval(a)},v2z:function(a){gx.O.ZV38GXV8=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE04",gx.O.GXV8,0)},c2v:function(){gx.O.GXV8=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE04",
",")},nac:gx.falseFn};b[123]={fld:"TEXTBLOCK9",format:0,grid:0};b[125]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE05",gxz:"ZV39GXV9",gxold:"OV39GXV9",gxvar:"GXV9",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV9=gx.num.intval(a)},v2z:function(a){gx.O.ZV39GXV9=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE05",gx.O.GXV9,0)},c2v:function(){gx.O.GXV9=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE05",
",")},nac:gx.falseFn};b[128]={fld:"TEXTBLOCK10",format:0,grid:0};b[130]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE06",gxz:"ZV40GXV10",gxold:"OV40GXV10",gxvar:"GXV10",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV10=gx.num.intval(a)},v2z:function(a){gx.O.ZV40GXV10=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE06",gx.O.GXV10,0)},c2v:function(){gx.O.GXV10=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE06",
",")},nac:gx.falseFn};b[133]={fld:"TEXTBLOCK11",format:0,grid:0};b[135]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE07",gxz:"ZV41GXV11",gxold:"OV41GXV11",gxvar:"GXV11",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV11=gx.num.intval(a)},v2z:function(a){gx.O.ZV41GXV11=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE07",gx.O.GXV11,0)},c2v:function(){gx.O.GXV11=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE07",
",")},nac:gx.falseFn};b[138]={fld:"TEXTBLOCK12",format:0,grid:0};b[140]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE08",gxz:"ZV42GXV12",gxold:"OV42GXV12",gxvar:"GXV12",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV12=gx.num.intval(a)},v2z:function(a){gx.O.ZV42GXV12=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE08",gx.O.GXV12,0)},c2v:function(){gx.O.GXV12=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE08",
",")},nac:gx.falseFn};b[143]={fld:"TEXTBLOCK13",format:0,grid:0};b[145]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE09",gxz:"ZV43GXV13",gxold:"OV43GXV13",gxvar:"GXV13",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV13=gx.num.intval(a)},v2z:function(a){gx.O.ZV43GXV13=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE09",gx.O.GXV13,0)},c2v:function(){gx.O.GXV13=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE09",
",")},nac:gx.falseFn};b[148]={fld:"TEXTBLOCK14",format:0,grid:0};b[150]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE10",gxz:"ZV44GXV14",gxold:"OV44GXV14",gxvar:"GXV14",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV14=gx.num.intval(a)},v2z:function(a){gx.O.ZV44GXV14=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE10",gx.O.GXV14,0)},c2v:function(){gx.O.GXV14=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE10",
",")},nac:gx.falseFn};b[153]={fld:"TEXTBLOCK15",format:0,grid:0};b[155]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP01",gxz:"ZV45GXV15",gxold:"OV45GXV15",gxvar:"GXV15",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV15=gx.num.intval(a)},v2z:function(a){gx.O.ZV45GXV15=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP01",gx.O.GXV15,0)},c2v:function(){gx.O.GXV15=gx.num.intval(this.val())},
val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP01",",")},nac:gx.falseFn};b[158]={fld:"TEXTBLOCK16",format:0,grid:0};b[160]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP02",gxz:"ZV46GXV16",gxold:"OV46GXV16",gxvar:"GXV16",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV16=gx.num.intval(a)},v2z:function(a){gx.O.ZV46GXV16=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP02",gx.O.GXV16,
0)},c2v:function(){gx.O.GXV16=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP02",",")},nac:gx.falseFn};b[163]={fld:"TEXTBLOCK17",format:0,grid:0};b[165]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP03",gxz:"ZV47GXV17",gxold:"OV47GXV17",gxvar:"GXV17",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV17=gx.num.intval(a)},v2z:function(a){gx.O.ZV47GXV17=gx.num.intval(a)},
v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP03",gx.O.GXV17,0)},c2v:function(){gx.O.GXV17=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP03",",")},nac:gx.falseFn};b[168]={fld:"TEXTBLOCK18",format:0,grid:0};b[170]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP04",gxz:"ZV48GXV18",gxold:"OV48GXV18",gxvar:"GXV18",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV18=gx.num.intval(a)},
v2z:function(a){gx.O.ZV48GXV18=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP04",gx.O.GXV18,0)},c2v:function(){gx.O.GXV18=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP04",",")},nac:gx.falseFn};b[173]={fld:"TEXTBLOCK19",format:0,grid:0};b[175]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP05",gxz:"ZV49GXV19",gxold:"OV49GXV19",gxvar:"GXV19",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",v2v:function(a){gx.O.GXV19=gx.num.intval(a)},v2z:function(a){gx.O.ZV49GXV19=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP05",gx.O.GXV19,0)},c2v:function(){gx.O.GXV19=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP05",",")},nac:gx.falseFn};b[178]={fld:"TEXTBLOCK20",format:0,grid:0};b[180]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP06",gxz:"ZV50GXV20",
gxold:"OV50GXV20",gxvar:"GXV20",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV20=gx.num.intval(a)},v2z:function(a){gx.O.ZV50GXV20=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP06",gx.O.GXV20,0)},c2v:function(){gx.O.GXV20=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP06",",")},nac:gx.falseFn};b[183]={fld:"TEXTBLOCK21",format:0,grid:0};b[185]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,
isvalid:null,rgrid:[],fld:"CTLPAGE_DISP07",gxz:"ZV51GXV21",gxold:"OV51GXV21",gxvar:"GXV21",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV21=gx.num.intval(a)},v2z:function(a){gx.O.ZV51GXV21=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP07",gx.O.GXV21,0)},c2v:function(){gx.O.GXV21=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP07",",")},nac:gx.falseFn};b[188]={fld:"TEXTBLOCK22",format:0,grid:0};b[190]={lvl:0,type:"int",
len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP08",gxz:"ZV52GXV22",gxold:"OV52GXV22",gxvar:"GXV22",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV22=gx.num.intval(a)},v2z:function(a){gx.O.ZV52GXV22=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP08",gx.O.GXV22,0)},c2v:function(){gx.O.GXV22=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP08",",")},nac:gx.falseFn};b[193]=
{fld:"TEXTBLOCK23",format:0,grid:0};b[195]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP09",gxz:"ZV53GXV23",gxold:"OV53GXV23",gxvar:"GXV23",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV23=gx.num.intval(a)},v2z:function(a){gx.O.ZV53GXV23=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP09",gx.O.GXV23,0)},c2v:function(){gx.O.GXV23=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP09",
",")},nac:gx.falseFn};b[198]={fld:"TEXTBLOCK24",format:0,grid:0};b[200]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP10",gxz:"ZV54GXV24",gxold:"OV54GXV24",gxvar:"GXV24",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV24=gx.num.intval(a)},v2z:function(a){gx.O.ZV54GXV24=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP10",gx.O.GXV24,0)},c2v:function(){gx.O.GXV24=gx.num.intval(this.val())},
val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP10",",")},nac:gx.falseFn};b[203]={fld:"TEXTBLOCK25",format:0,grid:0};b[205]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP_BACK",gxz:"ZV55GXV25",gxold:"OV55GXV25",gxvar:"GXV25",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV25=gx.num.intval(a)},v2z:function(a){gx.O.ZV55GXV25=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP_BACK",
gx.O.GXV25,0)},c2v:function(){gx.O.GXV25=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP_BACK",",")},nac:gx.falseFn};b[208]={fld:"TEXTBLOCK26",format:0,grid:0};b[210]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP_NEXT",gxz:"ZV56GXV26",gxold:"OV56GXV26",gxvar:"GXV26",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV26=gx.num.intval(a)},v2z:function(a){gx.O.ZV56GXV26=
gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP_NEXT",gx.O.GXV26,0)},c2v:function(){gx.O.GXV26=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP_NEXT",",")},nac:gx.falseFn};b[213]={fld:"TEXTBLOCK27",format:0,grid:0};b[215]={lvl:0,type:"int",len:1,dec:0,sign:false,pic:"9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"CTLPAGE_DISP_AREA",gxz:"ZV57GXV27",gxold:"OV57GXV27",gxvar:"GXV27",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.GXV27=
gx.num.intval(a)},v2z:function(a){gx.O.ZV57GXV27=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("CTLPAGE_DISP_AREA",gx.O.GXV27,0)},c2v:function(){gx.O.GXV27=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("CTLPAGE_DISP_AREA",",")},nac:gx.falseFn};this.OV26D_GRD_F_NAME=this.ZV26D_GRD_F_NAME="";this.O978TBM45_FILTER_NO=this.Z978TBM45_FILTER_NO=this.O977TBM45_STUDY_ID=this.Z977TBM45_STUDY_ID=0;this.OV14H_KNGN_FLG=this.ZV14H_KNGN_FLG=this.AV14H_KNGN_FLG=this.OV13H_INIT_FLG=
this.ZV13H_INIT_FLG=this.AV13H_INIT_FLG="";this.OV57GXV27=this.ZV57GXV27=this.GXV27=this.OV56GXV26=this.ZV56GXV26=this.GXV26=this.OV55GXV25=this.ZV55GXV25=this.GXV25=this.OV54GXV24=this.ZV54GXV24=this.GXV24=this.OV53GXV23=this.ZV53GXV23=this.GXV23=this.OV52GXV22=this.ZV52GXV22=this.GXV22=this.OV51GXV21=this.ZV51GXV21=this.GXV21=this.OV50GXV20=this.ZV50GXV20=this.GXV20=this.OV49GXV19=this.ZV49GXV19=this.GXV19=this.OV48GXV18=this.ZV48GXV18=this.GXV18=this.OV47GXV17=this.ZV47GXV17=this.GXV17=this.OV46GXV16=
this.ZV46GXV16=this.GXV16=this.OV45GXV15=this.ZV45GXV15=this.GXV15=this.OV44GXV14=this.ZV44GXV14=this.GXV14=this.OV43GXV13=this.ZV43GXV13=this.GXV13=this.OV42GXV12=this.ZV42GXV12=this.GXV12=this.OV41GXV11=this.ZV41GXV11=this.GXV11=this.OV40GXV10=this.ZV40GXV10=this.GXV10=this.OV39GXV9=this.ZV39GXV9=this.GXV9=this.OV38GXV8=this.ZV38GXV8=this.GXV8=this.OV37GXV7=this.ZV37GXV7=this.GXV7=this.OV36GXV6=this.ZV36GXV6=this.GXV6=this.OV35GXV5=this.ZV35GXV5=this.GXV5=this.OV34GXV4=this.ZV34GXV4=this.GXV4=this.OV33GXV2=
this.ZV33GXV2=this.GXV2=this.OV32GXV1=this.ZV32GXV1=this.GXV1=this.OV15H_SUBJECT_ID=this.ZV15H_SUBJECT_ID=this.AV15H_SUBJECT_ID=0;this.AV14H_KNGN_FLG=this.AV13H_INIT_FLG="";this.GXV2=this.GXV1=this.AV15H_SUBJECT_ID=0;this.GXV3="";this.AV16P_STUDY_ID=this.GXV27=this.GXV26=this.GXV25=this.GXV24=this.GXV23=this.GXV22=this.GXV21=this.GXV20=this.GXV19=this.GXV18=this.GXV17=this.GXV16=this.GXV15=this.GXV14=this.GXV13=this.GXV12=this.GXV11=this.GXV10=this.GXV9=this.GXV8=this.GXV7=this.GXV6=this.GXV5=this.GXV4=
0;this.AV26D_GRD_F_NAME=this.A982TBM45_DEL_FLG=this.A980TBM45_FILETR_NM="";this.A978TBM45_FILTER_NO=this.A977TBM45_STUDY_ID=0;this.AV19W_A821_JS=this.AV59Pgmname="";this.Events={e112e2_client:["'BTN_CLOSE'",true],e122e2_client:["'BTN_REG'",true],e162e2_client:["'BTN_EDIT_SEL'",true],e172e2_client:["ENTER",true],e182e2_client:["CANCEL",true]};this.setVCMap("AV16P_STUDY_ID","vP_STUDY_ID",0,"int");this.setVCMap("AV59Pgmname","vPGMNAME",0,"char");this.setVCMap("AV19W_A821_JS","vW_A821_JS",0,"svchar");
this.setVCMap("A980TBM45_FILETR_NM","TBM45_FILETR_NM",0,"svchar");this.setVCMap("AV16P_STUDY_ID","vP_STUDY_ID",0,"int");this.setVCMap("AV59Pgmname","vPGMNAME",0,"char");this.setVCMap("AV19W_A821_JS","vW_A821_JS",0,"svchar");this.setVCMap("A980TBM45_FILETR_NM","TBM45_FILETR_NM",0,"svchar");c.addRefreshingVar({rfrVar:"AV16P_STUDY_ID"});c.addRefreshingVar(this.GXValidFnc[77]);c.addRefreshingVar({rfrVar:"AV59Pgmname"});c.addRefreshingVar({rfrVar:"AV19W_A821_JS"});c.addRefreshingVar({rfrVar:"A980TBM45_FILETR_NM"});
this.addBCProperty("H_a_paging_sdt",["MAX_ROW"],this.GXValidFnc[85],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["REC_CNT"],this.GXValidFnc[90],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_NO"],this.GXValidFnc[100],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE01"],this.GXValidFnc[105],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE02"],this.GXValidFnc[110],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE03"],this.GXValidFnc[115],
"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE04"],this.GXValidFnc[120],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE05"],this.GXValidFnc[125],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE06"],this.GXValidFnc[130],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE07"],this.GXValidFnc[135],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE08"],this.GXValidFnc[140],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",
["PAGE09"],this.GXValidFnc[145],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE10"],this.GXValidFnc[150],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP01"],this.GXValidFnc[155],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP02"],this.GXValidFnc[160],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP03"],this.GXValidFnc[165],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP04"],this.GXValidFnc[170],
"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP05"],this.GXValidFnc[175],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP06"],this.GXValidFnc[180],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP07"],this.GXValidFnc[185],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP08"],this.GXValidFnc[190],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP09"],this.GXValidFnc[195],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",
["PAGE_DISP10"],this.GXValidFnc[200],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP_BACK"],this.GXValidFnc[205],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP_NEXT"],this.GXValidFnc[210],"AV12H_A_PAGING_SDT");this.addBCProperty("H_a_paging_sdt",["PAGE_DISP_AREA"],this.GXValidFnc[215],"AV12H_A_PAGING_SDT");this.InitStandaloneVars()});gx.setParentObj(new b712_wp03_crf_filter_list);
