gx.evt.autoSkip=!1;
gx.define("tam01_sel",!1,function(){this.ServerClass="tam01_sel";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.hasEnterEvent=true;this.skipOnEnter=false;this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV7pTAM010_SYS_ID=gx.fn.getControlValue("vPTAM010_SYS_ID")};this.e13232_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e14231_client=function(){this.executeServerEvent("CANCEL",true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,
8,9,12,14,17,18,22,23,24,27];this.GXLastCtrlId=27;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",21,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"tam01_sel",[],false,1,false,true,10,true,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,"",false,[1,1,1,1]);c.addBitmap("&Linkselection","vLINKSELECTION",22,0,"px",17,"px",null,"","","Image","");c.addSingleLineEdit(1,23,"TAM01_SYS_ID","\u30b7\u30b9\u30c6\u30e0ID","","TAM01_SYS_ID","svchar",
90,"px",2,2,"left",null,[],1,"TAM01_SYS_ID",true,0,false,false,"Attribute",1,"");c.addSingleLineEdit(206,24,"TAM01_SYS_NM","\u30b7\u30b9\u30c6\u30e0\u540d","\u9078\u629e","TAM01_SYS_NM","svchar",350,"px",40,40,"left",null,[],206,"TAM01_SYS_NM",true,0,false,false,"Attribute",1,"");this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[8]={fld:"GROUP1",grid:0};b[9]={fld:"TABLE2",grid:0};b[12]={fld:"TEXTBLOCKTAM010_SYS_NM",format:0,grid:0};b[14]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,
fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTAM010_SYS_NM",gxz:"ZV5cTAM010_SYS_NM",gxold:"OV5cTAM010_SYS_NM",gxvar:"AV5cTAM010_SYS_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV5cTAM010_SYS_NM=a},v2z:function(a){gx.O.ZV5cTAM010_SYS_NM=a},v2c:function(){gx.fn.setControlValue("vCTAM010_SYS_NM",gx.O.AV5cTAM010_SYS_NM,0)},c2v:function(){gx.O.AV5cTAM010_SYS_NM=this.val()},val:function(){return gx.fn.getControlValue("vCTAM010_SYS_NM")},nac:gx.falseFn};b[17]={fld:"GROUP2",
grid:0};b[18]={fld:"TABLE3",grid:0};b[22]={lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:21,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vLINKSELECTION",gxz:"ZV6LinkSelection",gxold:"OV6LinkSelection",gxvar:"AV6LinkSelection",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV6LinkSelection=a},v2z:function(a){gx.O.ZV6LinkSelection=a},v2c:function(a){gx.fn.setGridMultimediaValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(21),gx.O.AV6LinkSelection,
gx.O.AV14Linkselection_GXI)},c2v:function(){gx.O.AV14Linkselection_GXI=this.val_GXI();gx.O.AV6LinkSelection=this.val()},val:function(a){return gx.fn.getGridControlValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(21))},val_GXI:function(a){return gx.fn.getGridControlValue("vLINKSELECTION_GXI",a||gx.fn.currentGridRowImpl(21))},gxvar_GXI:"AV14Linkselection_GXI",nac:gx.falseFn};b[23]={lvl:2,type:"svchar",len:2,dec:0,sign:false,ro:1,isacc:0,grid:21,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],
fld:"TAM01_SYS_ID",gxz:"Z1TAM01_SYS_ID",gxold:"O1TAM01_SYS_ID",gxvar:"A1TAM01_SYS_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A1TAM01_SYS_ID=a},v2z:function(a){gx.O.Z1TAM01_SYS_ID=a},v2c:function(a){gx.fn.setGridControlValue("TAM01_SYS_ID",a||gx.fn.currentGridRowImpl(21),gx.O.A1TAM01_SYS_ID,0)},c2v:function(){gx.O.A1TAM01_SYS_ID=this.val()},val:function(a){return gx.fn.getGridControlValue("TAM01_SYS_ID",a||gx.fn.currentGridRowImpl(21))},nac:gx.falseFn};
b[24]={lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:21,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM01_SYS_NM",gxz:"Z206TAM01_SYS_NM",gxold:"O206TAM01_SYS_NM",gxvar:"A206TAM01_SYS_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A206TAM01_SYS_NM=a},v2z:function(a){gx.O.Z206TAM01_SYS_NM=a},v2c:function(a){gx.fn.setGridControlValue("TAM01_SYS_NM",a||gx.fn.currentGridRowImpl(21),gx.O.A206TAM01_SYS_NM,0)},c2v:function(){gx.O.A206TAM01_SYS_NM=
this.val()},val:function(a){return gx.fn.getGridControlValue("TAM01_SYS_NM",a||gx.fn.currentGridRowImpl(21))},nac:gx.falseFn};b[27]={fld:"TABLE4",grid:0};this.A206TAM01_SYS_NM=this.A1TAM01_SYS_ID=this.AV6LinkSelection=this.AV7pTAM010_SYS_ID=this.AV5cTAM010_SYS_NM=this.O206TAM01_SYS_NM=this.Z206TAM01_SYS_NM=this.O1TAM01_SYS_ID=this.Z1TAM01_SYS_ID=this.OV6LinkSelection=this.ZV6LinkSelection=this.OV5cTAM010_SYS_NM=this.ZV5cTAM010_SYS_NM=this.AV5cTAM010_SYS_NM="";this.Events={e13232_client:["ENTER",true],
e14231_client:["CANCEL",true]};this.setVCMap("AV7pTAM010_SYS_ID","vPTAM010_SYS_ID",0,"svchar");c.addRefreshingVar(this.GXValidFnc[14]);this.InitStandaloneVars()});gx.setParentObj(new tam01_sel);
