gx.evt.autoSkip=!1;
gx.define("tam03_sel",!1,function(){this.ServerClass="tam03_sel";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.hasEnterEvent=true;this.skipOnEnter=false;this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV8pTAM03_APP_ID=gx.fn.getControlValue("vPTAM03_APP_ID")};this.e13292_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e14291_client=function(){this.executeServerEvent("CANCEL",true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,8,
9,12,14,17,19,22,23,27,28,29,30,33];this.GXLastCtrlId=33;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",26,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"tam03_sel",[],false,1,false,true,10,true,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,"",false,[1,1,1,1]);c.addBitmap("&Linkselection","vLINKSELECTION",27,0,"px",17,"px",null,"","","Image","");c.addSingleLineEdit(12,28,"TAM03_APP_ID","\u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3ID",
"","TAM03_APP_ID","svchar",130,"px",7,7,"left",null,[],12,"TAM03_APP_ID",true,0,false,false,"Attribute",1,"");c.addSingleLineEdit(314,29,"TAM03_APP_NM","\u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3\u540d","","TAM03_APP_NM","svchar",350,"px",40,40,"left",null,[],314,"TAM03_APP_NM",true,0,false,false,"Attribute",1,"");c.addSingleLineEdit(276,30,"TAM03_KIDO_PG","\u8d77\u52d5\u30d7\u30ed\u30b0\u30e9\u30e0","","TAM03_KIDO_PG","svchar",250,"px",40,40,"left",null,[],276,"TAM03_KIDO_PG",true,0,false,
false,"Attribute",1,"");this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[8]={fld:"GROUP1",grid:0};b[9]={fld:"TABLE2",grid:0};b[12]={fld:"TEXTBLOCKTAM03_APP_ID",format:0,grid:0};b[14]={lvl:0,type:"svchar",len:7,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTAM03_APP_ID",gxz:"ZV5cTAM03_APP_ID",gxold:"OV5cTAM03_APP_ID",gxvar:"AV5cTAM03_APP_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV5cTAM03_APP_ID=a},v2z:function(a){gx.O.ZV5cTAM03_APP_ID=
a},v2c:function(){gx.fn.setControlValue("vCTAM03_APP_ID",gx.O.AV5cTAM03_APP_ID,0)},c2v:function(){gx.O.AV5cTAM03_APP_ID=this.val()},val:function(){return gx.fn.getControlValue("vCTAM03_APP_ID")},nac:gx.falseFn};b[17]={fld:"TEXTBLOCKTAM03_APP_ID2",format:0,grid:0};b[19]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTAM03_APP_NM",gxz:"ZV6cTAM03_APP_NM",gxold:"OV6cTAM03_APP_NM",gxvar:"AV6cTAM03_APP_NM",ucs:[],op:[],ip:[],
nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6cTAM03_APP_NM=a},v2z:function(a){gx.O.ZV6cTAM03_APP_NM=a},v2c:function(){gx.fn.setControlValue("vCTAM03_APP_NM",gx.O.AV6cTAM03_APP_NM,0)},c2v:function(){gx.O.AV6cTAM03_APP_NM=this.val()},val:function(){return gx.fn.getControlValue("vCTAM03_APP_NM")},nac:gx.falseFn};b[22]={fld:"GROUP2",grid:0};b[23]={fld:"TABLE3",grid:0};b[27]={lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:26,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],
fld:"vLINKSELECTION",gxz:"ZV7LinkSelection",gxold:"OV7LinkSelection",gxvar:"AV7LinkSelection",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV7LinkSelection=a},v2z:function(a){gx.O.ZV7LinkSelection=a},v2c:function(a){gx.fn.setGridMultimediaValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(26),gx.O.AV7LinkSelection,gx.O.AV15Linkselection_GXI)},c2v:function(){gx.O.AV15Linkselection_GXI=this.val_GXI();gx.O.AV7LinkSelection=this.val()},val:function(a){return gx.fn.getGridControlValue("vLINKSELECTION",
a||gx.fn.currentGridRowImpl(26))},val_GXI:function(a){return gx.fn.getGridControlValue("vLINKSELECTION_GXI",a||gx.fn.currentGridRowImpl(26))},gxvar_GXI:"AV15Linkselection_GXI",nac:gx.falseFn};b[28]={lvl:2,type:"svchar",len:7,dec:0,sign:false,ro:1,isacc:0,grid:26,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM03_APP_ID",gxz:"Z12TAM03_APP_ID",gxold:"O12TAM03_APP_ID",gxvar:"A12TAM03_APP_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A12TAM03_APP_ID=
a},v2z:function(a){gx.O.Z12TAM03_APP_ID=a},v2c:function(a){gx.fn.setGridControlValue("TAM03_APP_ID",a||gx.fn.currentGridRowImpl(26),gx.O.A12TAM03_APP_ID,0)},c2v:function(){gx.O.A12TAM03_APP_ID=this.val()},val:function(a){return gx.fn.getGridControlValue("TAM03_APP_ID",a||gx.fn.currentGridRowImpl(26))},nac:gx.falseFn};b[29]={lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:26,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM03_APP_NM",gxz:"Z314TAM03_APP_NM",gxold:"O314TAM03_APP_NM",
gxvar:"A314TAM03_APP_NM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A314TAM03_APP_NM=a},v2z:function(a){gx.O.Z314TAM03_APP_NM=a},v2c:function(a){gx.fn.setGridControlValue("TAM03_APP_NM",a||gx.fn.currentGridRowImpl(26),gx.O.A314TAM03_APP_NM,0)},c2v:function(){gx.O.A314TAM03_APP_NM=this.val()},val:function(a){return gx.fn.getGridControlValue("TAM03_APP_NM",a||gx.fn.currentGridRowImpl(26))},nac:gx.falseFn};b[30]={lvl:2,type:"svchar",len:40,dec:0,
sign:false,ro:1,isacc:0,grid:26,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM03_KIDO_PG",gxz:"Z276TAM03_KIDO_PG",gxold:"O276TAM03_KIDO_PG",gxvar:"A276TAM03_KIDO_PG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A276TAM03_KIDO_PG=a},v2z:function(a){gx.O.Z276TAM03_KIDO_PG=a},v2c:function(a){gx.fn.setGridControlValue("TAM03_KIDO_PG",a||gx.fn.currentGridRowImpl(26),gx.O.A276TAM03_KIDO_PG,0)},c2v:function(){gx.O.A276TAM03_KIDO_PG=
this.val()},val:function(a){return gx.fn.getGridControlValue("TAM03_KIDO_PG",a||gx.fn.currentGridRowImpl(26))},nac:gx.falseFn};b[33]={fld:"TABLE4",grid:0};this.A276TAM03_KIDO_PG=this.A314TAM03_APP_NM=this.A12TAM03_APP_ID=this.AV7LinkSelection=this.AV8pTAM03_APP_ID=this.AV6cTAM03_APP_NM=this.AV5cTAM03_APP_ID=this.O276TAM03_KIDO_PG=this.Z276TAM03_KIDO_PG=this.O314TAM03_APP_NM=this.Z314TAM03_APP_NM=this.O12TAM03_APP_ID=this.Z12TAM03_APP_ID=this.OV7LinkSelection=this.ZV7LinkSelection=this.OV6cTAM03_APP_NM=
this.ZV6cTAM03_APP_NM=this.AV6cTAM03_APP_NM=this.OV5cTAM03_APP_ID=this.ZV5cTAM03_APP_ID=this.AV5cTAM03_APP_ID="";this.Events={e13292_client:["ENTER",true],e14291_client:["CANCEL",true]};this.setVCMap("AV8pTAM03_APP_ID","vPTAM03_APP_ID",0,"svchar");c.addRefreshingVar(this.GXValidFnc[14]);c.addRefreshingVar(this.GXValidFnc[19]);this.InitStandaloneVars()});gx.setParentObj(new tam03_sel);
