gx.evt.autoSkip=!1;
gx.define("tam06_sel",!1,function(){this.ServerClass="tam06_sel";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.hasEnterEvent=true;this.skipOnEnter=false;this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV8pTAM06_MSG_CD=gx.fn.getControlValue("vPTAM06_MSG_CD")};this.e13252_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e14251_client=function(){this.executeServerEvent("CANCEL",true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,8,
9,12,14,17,18,22,23,24,27];this.GXLastCtrlId=27;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",21,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"tam06_sel",[],false,1,false,true,10,true,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,"",false,[1,1,1,1]);c.addBitmap("&Linkselection","vLINKSELECTION",22,0,"px",17,"px",null,"","","Image","");c.addSingleLineEdit(6,23,"TAM06_MSG_CD","\u30e1\u30c3\u30bb\u30fc\u30b8\u30b3\u30fc\u30c9","","TAM06_MSG_CD",
"svchar",110,"px",7,7,"left",null,[],6,"TAM06_MSG_CD",true,0,false,false,"Attribute",1,"");c.addSingleLineEdit(216,24,"TAM06_MSG","\u30e1\u30c3\u30bb\u30fc\u30b8","","TAM06_MSG","svchar",500,"px",1E3,80,"left",null,[],216,"TAM06_MSG",true,0,false,false,"Attribute",1,"");this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[8]={fld:"GROUP1",grid:0};b[9]={fld:"TABLE2",grid:0};b[12]={fld:"TEXTBLOCKTAM090_MSG_CD",format:0,grid:0};b[14]={lvl:0,type:"svchar",len:7,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,
isvalid:null,rgrid:[this.Grid1Container],fld:"vCTAM06_MSG_CD",gxz:"ZV6cTAM06_MSG_CD",gxold:"OV6cTAM06_MSG_CD",gxvar:"AV6cTAM06_MSG_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6cTAM06_MSG_CD=a},v2z:function(a){gx.O.ZV6cTAM06_MSG_CD=a},v2c:function(){gx.fn.setControlValue("vCTAM06_MSG_CD",gx.O.AV6cTAM06_MSG_CD,0)},c2v:function(){gx.O.AV6cTAM06_MSG_CD=this.val()},val:function(){return gx.fn.getControlValue("vCTAM06_MSG_CD")},nac:gx.falseFn};b[17]={fld:"GROUP2",grid:0};b[18]=
{fld:"TABLE3",grid:0};b[22]={lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:21,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vLINKSELECTION",gxz:"ZV7LinkSelection",gxold:"OV7LinkSelection",gxvar:"AV7LinkSelection",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV7LinkSelection=a},v2z:function(a){gx.O.ZV7LinkSelection=a},v2c:function(a){gx.fn.setGridMultimediaValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(21),gx.O.AV7LinkSelection,
gx.O.AV14Linkselection_GXI)},c2v:function(){gx.O.AV14Linkselection_GXI=this.val_GXI();gx.O.AV7LinkSelection=this.val()},val:function(a){return gx.fn.getGridControlValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(21))},val_GXI:function(a){return gx.fn.getGridControlValue("vLINKSELECTION_GXI",a||gx.fn.currentGridRowImpl(21))},gxvar_GXI:"AV14Linkselection_GXI",nac:gx.falseFn};b[23]={lvl:2,type:"svchar",len:7,dec:0,sign:false,ro:1,isacc:0,grid:21,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],
fld:"TAM06_MSG_CD",gxz:"Z6TAM06_MSG_CD",gxold:"O6TAM06_MSG_CD",gxvar:"A6TAM06_MSG_CD",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A6TAM06_MSG_CD=a},v2z:function(a){gx.O.Z6TAM06_MSG_CD=a},v2c:function(a){gx.fn.setGridControlValue("TAM06_MSG_CD",a||gx.fn.currentGridRowImpl(21),gx.O.A6TAM06_MSG_CD,0)},c2v:function(){gx.O.A6TAM06_MSG_CD=this.val()},val:function(a){return gx.fn.getGridControlValue("TAM06_MSG_CD",a||gx.fn.currentGridRowImpl(21))},nac:gx.falseFn};
b[24]={lvl:2,type:"svchar",len:1E3,dec:0,sign:false,ro:1,isacc:0,grid:21,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAM06_MSG",gxz:"Z216TAM06_MSG",gxold:"O216TAM06_MSG",gxvar:"A216TAM06_MSG",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A216TAM06_MSG=a},v2z:function(a){gx.O.Z216TAM06_MSG=a},v2c:function(a){gx.fn.setGridControlValue("TAM06_MSG",a||gx.fn.currentGridRowImpl(21),gx.O.A216TAM06_MSG,0)},c2v:function(){gx.O.A216TAM06_MSG=
this.val()},val:function(a){return gx.fn.getGridControlValue("TAM06_MSG",a||gx.fn.currentGridRowImpl(21))},nac:gx.falseFn};b[27]={fld:"TABLE4",grid:0};this.A216TAM06_MSG=this.A6TAM06_MSG_CD=this.AV7LinkSelection=this.AV8pTAM06_MSG_CD=this.AV6cTAM06_MSG_CD=this.O216TAM06_MSG=this.Z216TAM06_MSG=this.O6TAM06_MSG_CD=this.Z6TAM06_MSG_CD=this.OV7LinkSelection=this.ZV7LinkSelection=this.OV6cTAM06_MSG_CD=this.ZV6cTAM06_MSG_CD=this.AV6cTAM06_MSG_CD="";this.Events={e13252_client:["ENTER",true],e14251_client:["CANCEL",
true]};this.setVCMap("AV8pTAM06_MSG_CD","vPTAM06_MSG_CD",0,"svchar");c.addRefreshingVar(this.GXValidFnc[14]);this.InitStandaloneVars()});gx.setParentObj(new tam06_sel);
