gx.evt.autoSkip=!1;
gx.define("tat01_sel",!1,function(){this.ServerClass="tat01_sel";this.PackageName="";this.setObjectType("web");this.setOnAjaxSessionTimeout("Warn");this.hasEnterEvent=true;this.skipOnEnter=false;this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV9pTAT01_INFO_NO=gx.fn.getIntegerValue("vPTAT01_INFO_NO",",")};this.Validv_Ctat01_date_start_from=function(){try{var a=gx.util.balloon.getNew("vCTAT01_DATE_START_FROM");this.AnyError=0;if(!((new gx.date.gxdate("")).compare(this.AV6cTAT01_DATE_START_FROM)==0||
(new gx.date.gxdate(this.AV6cTAT01_DATE_START_FROM)).compare(gx.date.ymdtod(1E3,1,1))>=0))try{a.setError("\u30d5\u30a3\u30fc\u30eb\u30c9\u3000cTAT01_DATE_START_FROM \u306f\u7bc4\u56f2\u5916\u3067\u3059");this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.Validv_Ctat01_date_start_to=function(){try{var a=gx.util.balloon.getNew("vCTAT01_DATE_START_TO");this.AnyError=0;if(!((new gx.date.gxdate("")).compare(this.AV7cTAT01_DATE_START_TO)==0||(new gx.date.gxdate(this.AV7cTAT01_DATE_START_TO)).compare(gx.date.ymdtod(1E3,
1,1))>=0))try{a.setError("\u30d5\u30a3\u30fc\u30eb\u30c9\u3000cTAT01_DATE_START_TO \u306f\u7bc4\u56f2\u5916\u3067\u3059");this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.e13282_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e14281_client=function(){this.executeServerEvent("CANCEL",true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,8,9,12,14,17,19,21,24,25,29,30,31,32,35];this.GXLastCtrlId=35;var c=this.Grid1Container=new gx.grid.grid(this,
2,"WbpLvl2",28,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"tat01_sel",[],false,1,false,true,10,true,false,false,"",0,"px","\u884c\u8ffd\u52a0",true,false,false,null,null,false,"",false,[1,1,1,1]);c.addBitmap("&Linkselection","vLINKSELECTION",29,0,"px",17,"px",null,"","","Image","");c.addSingleLineEdit(11,30,"TAT01_INFO_NO","\u304a\u77e5\u3089\u305b\u60c5\u5831\u756a\u53f7","","TAT01_INFO_NO","int",130,"px",6,6,"right",null,[],11,"TAT01_INFO_NO",true,0,false,false,"Attribute",
1,"");c.addSingleLineEdit(207,31,"TAT01_DATE_START","\u516c\u958b\u958b\u59cb\u65e5","\u9078\u629e","TAT01_DATE_START","date",100,"px",10,10,"right",null,[],207,"TAT01_DATE_START",true,0,false,false,"Attribute",1,"");c.addSingleLineEdit(208,32,"TAT01_DATE_END","\u516c\u958b\u7d42\u4e86\u65e5","","TAT01_DATE_END","date",100,"px",10,10,"right",null,[],208,"TAT01_DATE_END",true,0,false,false,"Attribute",1,"");this.setGrid(c);b[2]={fld:"TABLE1",grid:0};b[8]={fld:"GROUP1",grid:0};b[9]={fld:"TABLE2",grid:0};
b[12]={fld:"TEXTBLOCKTAT010_DATE_START",format:0,grid:0};b[14]={fld:"TABLE5",grid:0};b[17]={lvl:0,type:"date",len:10,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_Ctat01_date_start_from,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTAT01_DATE_START_FROM",gxz:"ZV6cTAT01_DATE_START_FROM",gxold:"OV6cTAT01_DATE_START_FROM",gxvar:"AV6cTAT01_DATE_START_FROM",dp:{f:0,st:false,wn:false,mf:false,pic:"99/99/9999",dec:0},ucs:[],op:[17],ip:[17],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6cTAT01_DATE_START_FROM=
gx.fn.toDatetimeValue(a)},v2z:function(a){gx.O.ZV6cTAT01_DATE_START_FROM=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("vCTAT01_DATE_START_FROM",gx.O.AV6cTAT01_DATE_START_FROM,0)},c2v:function(){gx.O.AV6cTAT01_DATE_START_FROM=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getControlValue("vCTAT01_DATE_START_FROM")},nac:gx.falseFn};b[19]={fld:"TEXTBLOCK10",format:0,grid:0};b[21]={lvl:0,type:"date",len:10,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_Ctat01_date_start_to,
isvalid:null,rgrid:[this.Grid1Container],fld:"vCTAT01_DATE_START_TO",gxz:"ZV7cTAT01_DATE_START_TO",gxold:"OV7cTAT01_DATE_START_TO",gxvar:"AV7cTAT01_DATE_START_TO",dp:{f:0,st:false,wn:false,mf:false,pic:"99/99/9999",dec:0},ucs:[],op:[21],ip:[21],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV7cTAT01_DATE_START_TO=gx.fn.toDatetimeValue(a)},v2z:function(a){gx.O.ZV7cTAT01_DATE_START_TO=gx.fn.toDatetimeValue(a)},v2c:function(){gx.fn.setControlValue("vCTAT01_DATE_START_TO",gx.O.AV7cTAT01_DATE_START_TO,
0)},c2v:function(){gx.O.AV7cTAT01_DATE_START_TO=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getControlValue("vCTAT01_DATE_START_TO")},nac:gx.falseFn};b[24]={fld:"GROUP2",grid:0};b[25]={fld:"TABLE3",grid:0};b[29]={lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"vLINKSELECTION",gxz:"ZV8LinkSelection",gxold:"OV8LinkSelection",gxvar:"AV8LinkSelection",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",
v2v:function(a){gx.O.AV8LinkSelection=a},v2z:function(a){gx.O.ZV8LinkSelection=a},v2c:function(a){gx.fn.setGridMultimediaValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(28),gx.O.AV8LinkSelection,gx.O.AV15Linkselection_GXI)},c2v:function(){gx.O.AV15Linkselection_GXI=this.val_GXI();gx.O.AV8LinkSelection=this.val()},val:function(a){return gx.fn.getGridControlValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(28))},val_GXI:function(a){return gx.fn.getGridControlValue("vLINKSELECTION_GXI",a||gx.fn.currentGridRowImpl(28))},
gxvar_GXI:"AV15Linkselection_GXI",nac:gx.falseFn};b[30]={lvl:2,type:"int",len:6,dec:0,sign:false,pic:"ZZZZZ9",ro:1,isacc:0,grid:28,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAT01_INFO_NO",gxz:"Z11TAT01_INFO_NO",gxold:"O11TAT01_INFO_NO",gxvar:"A11TAT01_INFO_NO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A11TAT01_INFO_NO=gx.num.intval(a)},v2z:function(a){gx.O.Z11TAT01_INFO_NO=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TAT01_INFO_NO",
a||gx.fn.currentGridRowImpl(28),gx.O.A11TAT01_INFO_NO,0)},c2v:function(){gx.O.A11TAT01_INFO_NO=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TAT01_INFO_NO",a||gx.fn.currentGridRowImpl(28),",")},nac:gx.falseFn};b[31]={lvl:2,type:"date",len:10,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAT01_DATE_START",gxz:"Z207TAT01_DATE_START",gxold:"O207TAT01_DATE_START",gxvar:"A207TAT01_DATE_START",dp:{f:0,st:false,wn:false,
mf:false,pic:"99/99/9999",dec:0},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A207TAT01_DATE_START=gx.fn.toDatetimeValue(a)},v2z:function(a){gx.O.Z207TAT01_DATE_START=gx.fn.toDatetimeValue(a)},v2c:function(a){gx.fn.setGridControlValue("TAT01_DATE_START",a||gx.fn.currentGridRowImpl(28),gx.O.A207TAT01_DATE_START,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A207TAT01_DATE_START=gx.fn.toDatetimeValue(this.val())},val:function(a){return gx.fn.getGridControlValue("TAT01_DATE_START",
a||gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};b[32]={lvl:2,type:"date",len:10,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TAT01_DATE_END",gxz:"Z208TAT01_DATE_END",gxold:"O208TAT01_DATE_END",gxvar:"A208TAT01_DATE_END",dp:{f:0,st:false,wn:false,mf:false,pic:"99/99/9999",dec:0},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A208TAT01_DATE_END=gx.fn.toDatetimeValue(a)},v2z:function(a){gx.O.Z208TAT01_DATE_END=
gx.fn.toDatetimeValue(a)},v2c:function(a){gx.fn.setGridControlValue("TAT01_DATE_END",a||gx.fn.currentGridRowImpl(28),gx.O.A208TAT01_DATE_END,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A208TAT01_DATE_END=gx.fn.toDatetimeValue(this.val())},val:function(a){return gx.fn.getGridControlValue("TAT01_DATE_END",a||gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};b[35]={fld:"TABLE4",grid:0};this.AV6cTAT01_DATE_START_FROM=gx.date.nullDate();this.ZV6cTAT01_DATE_START_FROM=
gx.date.nullDate();this.OV6cTAT01_DATE_START_FROM=gx.date.nullDate();this.AV7cTAT01_DATE_START_TO=gx.date.nullDate();this.ZV7cTAT01_DATE_START_TO=gx.date.nullDate();this.OV7cTAT01_DATE_START_TO=gx.date.nullDate();this.OV8LinkSelection=this.ZV8LinkSelection="";this.O11TAT01_INFO_NO=this.Z11TAT01_INFO_NO=0;this.Z207TAT01_DATE_START=gx.date.nullDate();this.O207TAT01_DATE_START=gx.date.nullDate();this.Z208TAT01_DATE_END=gx.date.nullDate();this.O208TAT01_DATE_END=gx.date.nullDate();this.AV6cTAT01_DATE_START_FROM=
gx.date.nullDate();this.AV7cTAT01_DATE_START_TO=gx.date.nullDate();this.AV9pTAT01_INFO_NO=0;this.AV8LinkSelection="";this.A11TAT01_INFO_NO=0;this.A207TAT01_DATE_START=gx.date.nullDate();this.A208TAT01_DATE_END=gx.date.nullDate();this.Events={e13282_client:["ENTER",true],e14281_client:["CANCEL",true]};this.setVCMap("AV9pTAT01_INFO_NO","vPTAT01_INFO_NO",0,"int");c.addRefreshingVar(this.GXValidFnc[17]);c.addRefreshingVar(this.GXValidFnc[21]);this.InitStandaloneVars()});gx.setParentObj(new tat01_sel);
