gx.evt.autoSkip=!1;
gx.define("tbw14_crf_sdt_work",!1,function(){this.ServerClass="tbw14_crf_sdt_work";this.PackageName="";this.setObjectType("trn");this.setOnAjaxSessionTimeout("Warn");this.hasEnterEvent=true;this.skipOnEnter=false;this.SetStandaloneVars=function(){this.Gx_mode=gx.fn.getControlValue("vMODE")};this.Valid_Tbw14_session_id=function(){try{var a=gx.util.balloon.getNew("TBW14_SESSION_ID");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Valid_Tbw14_disp_datetime=function(){try{var a=
gx.util.balloon.getNew("TBW14_DISP_DATETIME");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Valid_Tbw14_study_id=function(){try{var a=gx.util.balloon.getNew("TBW14_STUDY_ID");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Valid_Tbw14_subject_id=function(){try{var a=gx.util.balloon.getNew("TBW14_SUBJECT_ID");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Valid_Tbw14_crf_id=function(){try{var a=
gx.util.balloon.getNew("TBW14_CRF_ID");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Valid_Tbw14_crf_eda_no=function(){try{var a=gx.util.balloon.getNew("TBW14_CRF_EDA_NO");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Valid_Tbw14_crf_latest_version=function(){gx.ajax.validSrvEvt("dyncall","valid_Tbw14_crf_latest_version",["gx.O.A192TBW14_SESSION_ID","gx.O.A193TBW14_DISP_DATETIME","gx.O.A194TBW14_STUDY_ID","gx.O.A195TBW14_SUBJECT_ID",
"gx.O.A196TBW14_CRF_ID","gx.O.A940TBW14_CRF_EDA_NO","gx.O.A197TBW14_CRF_LATEST_VERSION","gx.O.A890TBW14_SDT_SAVE"],["A890TBW14_SDT_SAVE","Gx_mode","Z192TBW14_SESSION_ID","Z193TBW14_DISP_DATETIME","Z194TBW14_STUDY_ID","Z195TBW14_SUBJECT_ID","Z196TBW14_CRF_ID","Z940TBW14_CRF_EDA_NO","Z197TBW14_CRF_LATEST_VERSION","Z890TBW14_SDT_SAVE",["BTN_DELETE2","Enabled"],["BTN_ENTER2","Enabled"]]);return true};this.e111h60_client=function(){this.executeServerEvent("ENTER",true)};this.e121h60_client=function(){this.executeServerEvent("CANCEL",
true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,5,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,27,28,34,37,39,42,44,47,49,52,54,57,59,62,64,67,69,72,74];this.GXLastCtrlId=74;b[2]={fld:"TABLEMAIN",grid:0};b[5]={fld:"TABLETOOLBAR",grid:0};b[8]={fld:"SECTIONTOOLBAR",grid:0};b[9]={fld:"BTN_FIRST",grid:0};b[10]={fld:"BTN_FIRST_SEPARATOR",grid:0};b[11]={fld:"BTN_PREVIOUS",grid:0};b[12]={fld:"BTN_PREVIOUS_SEPARATOR",grid:0};b[13]={fld:"BTN_NEXT",grid:0};b[14]={fld:"BTN_NEXT_SEPARATOR",grid:0};b[15]=
{fld:"BTN_LAST",grid:0};b[16]={fld:"BTN_LAST_SEPARATOR",grid:0};b[17]={fld:"BTN_SELECT",grid:0};b[18]={fld:"BTN_SELECT_SEPARATOR",grid:0};b[19]={fld:"BTN_ENTER2",grid:0};b[20]={fld:"BTN_ENTER2_SEPARATOR",grid:0};b[21]={fld:"BTN_CANCEL2",grid:0};b[22]={fld:"BTN_CANCEL2_SEPARATOR",grid:0};b[23]={fld:"BTN_DELETE2",grid:0};b[24]={fld:"BTN_DELETE2_SEPARATOR",grid:0};b[27]={fld:"GROUPDATA",grid:0};b[28]={fld:"TABLE1",grid:0};b[34]={fld:"TABLE2",grid:0};b[37]={fld:"TEXTBLOCKTBW14_SESSION_ID",format:0,grid:0};
b[39]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Valid_Tbw14_session_id,isvalid:null,rgrid:[],fld:"TBW14_SESSION_ID",gxz:"Z192TBW14_SESSION_ID",gxold:"O192TBW14_SESSION_ID",gxvar:"A192TBW14_SESSION_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A192TBW14_SESSION_ID=a},v2z:function(a){gx.O.Z192TBW14_SESSION_ID=a},v2c:function(){gx.fn.setControlValue("TBW14_SESSION_ID",gx.O.A192TBW14_SESSION_ID,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},
c2v:function(){gx.O.A192TBW14_SESSION_ID=this.val()},val:function(){return gx.fn.getControlValue("TBW14_SESSION_ID")},nac:gx.falseFn};this.declareDomainHdlr(39,function(){});b[42]={fld:"TEXTBLOCKTBW14_DISP_DATETIME",format:0,grid:0};b[44]={lvl:0,type:"svchar",len:14,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Valid_Tbw14_disp_datetime,isvalid:null,rgrid:[],fld:"TBW14_DISP_DATETIME",gxz:"Z193TBW14_DISP_DATETIME",gxold:"O193TBW14_DISP_DATETIME",gxvar:"A193TBW14_DISP_DATETIME",ucs:[],op:[],ip:[],
nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A193TBW14_DISP_DATETIME=a},v2z:function(a){gx.O.Z193TBW14_DISP_DATETIME=a},v2c:function(){gx.fn.setControlValue("TBW14_DISP_DATETIME",gx.O.A193TBW14_DISP_DATETIME,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A193TBW14_DISP_DATETIME=this.val()},val:function(){return gx.fn.getControlValue("TBW14_DISP_DATETIME")},nac:gx.falseFn};this.declareDomainHdlr(44,function(){});b[47]={fld:"TEXTBLOCKTBW14_STUDY_ID",format:0,grid:0};
b[49]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Valid_Tbw14_study_id,isvalid:null,rgrid:[],fld:"TBW14_STUDY_ID",gxz:"Z194TBW14_STUDY_ID",gxold:"O194TBW14_STUDY_ID",gxvar:"A194TBW14_STUDY_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A194TBW14_STUDY_ID=gx.num.intval(a)},v2z:function(a){gx.O.Z194TBW14_STUDY_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("TBW14_STUDY_ID",gx.O.A194TBW14_STUDY_ID,0);typeof this.dom_hdl==
"function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A194TBW14_STUDY_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("TBW14_STUDY_ID",",")},nac:gx.falseFn};this.declareDomainHdlr(49,function(){});b[52]={fld:"TEXTBLOCKTBW14_SUBJECT_ID",format:0,grid:0};b[54]={lvl:0,type:"int",len:6,dec:0,sign:false,pic:"ZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Valid_Tbw14_subject_id,isvalid:null,rgrid:[],fld:"TBW14_SUBJECT_ID",gxz:"Z195TBW14_SUBJECT_ID",gxold:"O195TBW14_SUBJECT_ID",gxvar:"A195TBW14_SUBJECT_ID",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A195TBW14_SUBJECT_ID=gx.num.intval(a)},v2z:function(a){gx.O.Z195TBW14_SUBJECT_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("TBW14_SUBJECT_ID",gx.O.A195TBW14_SUBJECT_ID,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A195TBW14_SUBJECT_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("TBW14_SUBJECT_ID",",")},nac:gx.falseFn};this.declareDomainHdlr(54,function(){});
b[57]={fld:"TEXTBLOCKTBW14_CRF_ID",format:0,grid:0};b[59]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Valid_Tbw14_crf_id,isvalid:null,rgrid:[],fld:"TBW14_CRF_ID",gxz:"Z196TBW14_CRF_ID",gxold:"O196TBW14_CRF_ID",gxvar:"A196TBW14_CRF_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A196TBW14_CRF_ID=gx.num.intval(a)},v2z:function(a){gx.O.Z196TBW14_CRF_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("TBW14_CRF_ID",gx.O.A196TBW14_CRF_ID,
0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A196TBW14_CRF_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("TBW14_CRF_ID",",")},nac:gx.falseFn};this.declareDomainHdlr(59,function(){});b[62]={fld:"TEXTBLOCKTBW14_CRF_EDA_NO",format:0,grid:0};b[64]={lvl:0,type:"int",len:2,dec:0,sign:false,pic:"Z9",ro:0,grid:0,gxgrid:null,fnc:this.Valid_Tbw14_crf_eda_no,isvalid:null,rgrid:[],fld:"TBW14_CRF_EDA_NO",gxz:"Z940TBW14_CRF_EDA_NO",gxold:"O940TBW14_CRF_EDA_NO",
gxvar:"A940TBW14_CRF_EDA_NO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A940TBW14_CRF_EDA_NO=gx.num.intval(a)},v2z:function(a){gx.O.Z940TBW14_CRF_EDA_NO=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("TBW14_CRF_EDA_NO",gx.O.A940TBW14_CRF_EDA_NO,0)},c2v:function(){gx.O.A940TBW14_CRF_EDA_NO=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("TBW14_CRF_EDA_NO",",")},nac:gx.falseFn};b[67]={fld:"TEXTBLOCKTBW14_CRF_LATEST_VERSION",format:0,grid:0};b[69]=
{lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Valid_Tbw14_crf_latest_version,isvalid:null,rgrid:[],fld:"TBW14_CRF_LATEST_VERSION",gxz:"Z197TBW14_CRF_LATEST_VERSION",gxold:"O197TBW14_CRF_LATEST_VERSION",gxvar:"A197TBW14_CRF_LATEST_VERSION",ucs:[],op:[74],ip:[74,69,64,59,54,49,44,39],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A197TBW14_CRF_LATEST_VERSION=gx.num.intval(a)},v2z:function(a){gx.O.Z197TBW14_CRF_LATEST_VERSION=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("TBW14_CRF_LATEST_VERSION",
gx.O.A197TBW14_CRF_LATEST_VERSION,0);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A197TBW14_CRF_LATEST_VERSION=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("TBW14_CRF_LATEST_VERSION",",")},nac:gx.falseFn};this.declareDomainHdlr(69,function(){});b[72]={fld:"TEXTBLOCKTBW14_SDT_SAVE",format:0,grid:0};b[74]={lvl:0,type:"vchar",len:2097152,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"TBW14_SDT_SAVE",
gxz:"Z890TBW14_SDT_SAVE",gxold:"O890TBW14_SDT_SAVE",gxvar:"A890TBW14_SDT_SAVE",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A890TBW14_SDT_SAVE=a},v2z:function(a){gx.O.Z890TBW14_SDT_SAVE=a},v2c:function(){gx.fn.setControlValue("TBW14_SDT_SAVE",gx.O.A890TBW14_SDT_SAVE,0)},c2v:function(){gx.O.A890TBW14_SDT_SAVE=this.val()},val:function(){return gx.fn.getControlValue("TBW14_SDT_SAVE")},nac:gx.falseFn};this.O193TBW14_DISP_DATETIME=this.Z193TBW14_DISP_DATETIME=this.A193TBW14_DISP_DATETIME=
this.O192TBW14_SESSION_ID=this.Z192TBW14_SESSION_ID=this.A192TBW14_SESSION_ID="";this.O197TBW14_CRF_LATEST_VERSION=this.Z197TBW14_CRF_LATEST_VERSION=this.A197TBW14_CRF_LATEST_VERSION=this.O940TBW14_CRF_EDA_NO=this.Z940TBW14_CRF_EDA_NO=this.A940TBW14_CRF_EDA_NO=this.O196TBW14_CRF_ID=this.Z196TBW14_CRF_ID=this.A196TBW14_CRF_ID=this.O195TBW14_SUBJECT_ID=this.Z195TBW14_SUBJECT_ID=this.A195TBW14_SUBJECT_ID=this.O194TBW14_STUDY_ID=this.Z194TBW14_STUDY_ID=this.A194TBW14_STUDY_ID=0;this.A193TBW14_DISP_DATETIME=
this.A192TBW14_SESSION_ID=this.O890TBW14_SDT_SAVE=this.Z890TBW14_SDT_SAVE=this.A890TBW14_SDT_SAVE="";this.A197TBW14_CRF_LATEST_VERSION=this.A940TBW14_CRF_EDA_NO=this.A196TBW14_CRF_ID=this.A195TBW14_SUBJECT_ID=this.A194TBW14_STUDY_ID=0;this.A890TBW14_SDT_SAVE="";this.Events={e111h60_client:["ENTER",true],e121h60_client:["CANCEL",true]};this.EnterCtrl=["BTN_ENTER2","BTN_ENTER2_SEPARATOR","BTN_ENTER"];this.setVCMap("Gx_mode","vMODE",0,"char");this.InitStandaloneVars()});gx.setParentObj(new tbw14_crf_sdt_work);
